/**
 * RSS FEED DATA — 200 USA Market Feeds
 * Energy, Trucking & Specialized Transportation Industries
 * Categories: trucking, logistics, supply_chain, oil_gas, energy, chemical, refrigerated, bulk, hazmat, marine, government
 */

import type { RSSFeedSource } from "./rssService";

const T = "2025-01-01T00:00:00Z";
const f = (id: number, name: string, url: string, category: string): RSSFeedSource => ({
  id: `rss_${String(id).padStart(3, "0")}`, name, url, category, enabled: true, addedAt: T,
});

export const ALL_200_FEEDS: RSSFeedSource[] = [
  // ===== ALL NEWS / GENERAL TRUCKING (25) =====
  f(1,"FreightWaves","https://www.freightwaves.com/news/feed","trucking"),
  f(2,"Transport Topics","https://www.ttnews.com/rss.xml","trucking"),
  f(3,"Trucking Dive","https://www.truckingdive.com/feeds/news/","trucking"),
  f(4,"CDL Life","https://cdllife.com/feed","trucking"),
  f(5,"Overdrive Magazine","https://www.overdriveonline.com/feed","trucking"),
  f(6,"Commercial Carrier Journal","https://www.ccjdigital.com/feed","trucking"),
  f(7,"Truck News","https://www.trucknews.com/rss/","trucking"),
  f(8,"FleetOwner","https://www.fleetowner.com/rss.xml","trucking"),
  f(9,"Heavy Duty Trucking","https://www.truckinginfo.com/rss","trucking"),
  f(10,"American Trucking Associations","https://www.trucking.org/news/feed","trucking"),
  f(11,"Truckers News","https://www.truckersnews.com/feed","trucking"),
  f(12,"Land Line Magazine","https://landline.media/feed/","trucking"),
  f(13,"DAT Freight & Analytics","https://www.dat.com/blog/rss.xml","trucking"),
  f(14,"Truckload Carriers Association","https://www.truckload.org/feed","trucking"),
  f(15,"Women in Trucking","https://www.womenintrucking.org/blog/rss.xml","trucking"),
  f(16,"Smart Trucking","https://www.smart-trucking.com/feed","trucking"),
  f(17,"The Trucker","https://www.thetrucker.com/feed","trucking"),
  f(18,"Truck Parts & Service","https://www.truckpartsandservice.com/__rss/news.xml","trucking"),
  f(19,"10-4 Magazine","https://www.10-4mag.com/feed","trucking"),
  f(20,"Expedite Now","https://www.expeditenow.com/feed","trucking"),
  f(21,"Expediters Online","https://www.expeditersonline.com/rss","trucking"),
  f(22,"Owner Operator Direct","https://www.owneroperatordirect.com/blog/feed","trucking"),
  f(23,"Trucking Answers","https://truckinganswers.com/feed","trucking"),
  f(24,"Go Trucking","https://gotrucking.com/feed","trucking"),
  f(25,"Truck Driver News","https://truckdrivernews.com/feed","trucking"),

  // ===== LOGISTICS & SUPPLY CHAIN (30) =====
  f(26,"Logistics Management","https://feeds.feedburner.com/logisticsmgmt/latest","logistics"),
  f(27,"Supply Chain Dive","https://www.supplychaindive.com/feeds/news/","supply_chain"),
  f(28,"SupplyChainBrain","https://www.supplychainbrain.com/rss","supply_chain"),
  f(29,"Inbound Logistics","https://www.inboundlogistics.com/feed","logistics"),
  f(30,"Journal of Commerce","https://www.joc.com/rss/logistics","logistics"),
  f(31,"DC Velocity","https://www.dcvelocity.com/rss","logistics"),
  f(32,"Supply Chain 24/7","https://www.supplychain247.com/rss","supply_chain"),
  f(33,"Logistics Viewpoints","https://logisticsviewpoints.com/feed","logistics"),
  f(34,"Supply Chain Digital","https://supplychaindigital.com/feed","supply_chain"),
  f(35,"Supply Chain Mgmt Review","https://www.scmr.com/feed","supply_chain"),
  f(36,"Modern Materials Handling","https://www.mmh.com/rss","logistics"),
  f(37,"Material Handling & Logistics","https://www.mhlnews.com/rss","logistics"),
  f(38,"Penske Logistics Blog","https://www.gopenske.com/feeds/blog.rss","logistics"),
  f(39,"XPO Logistics Blog","https://www.xpo.com/blog/feed","logistics"),
  f(40,"Echo Global Logistics","https://www.echo.com/blog/feed","logistics"),
  f(41,"BlueGrace Logistics","https://www.mybluegrace.com/resources/feed","logistics"),
  f(42,"Trinity Logistics","https://www.trinitylogistics.com/insights/feed","logistics"),
  f(43,"GlobalTranz","https://www.globaltranz.com/resource-hub/feed","logistics"),
  f(44,"Odyssey Logistics","https://www.odysseylogistics.com/blog/feed","logistics"),
  f(45,"Ryder Blog","https://www.ryder.com/insights/feed","logistics"),
  f(46,"Landstar Blog","https://www.landstar.com/blog/feed","logistics"),
  f(47,"ArcBest Blog","https://www.arcb.com/blog/feed","logistics"),
  f(48,"Saia LTL","https://www.saia.com/news/feed","logistics"),
  f(49,"Old Dominion","https://www.odfl.com/news/feed","logistics"),
  f(50,"XPO LTL","https://www.xpo.com/news/feed","logistics"),
  f(51,"Estes Express","https://www.estes-express.com/news/feed","logistics"),
  f(52,"FedEx Newsroom","https://newsroom.fedex.com/rss","logistics"),
  f(53,"UPS Pressroom","https://pressroom.ups.com/rss","logistics"),
  f(54,"Freightos Blog","https://www.freightos.com/blog/feed","logistics"),
  f(55,"Flexport Blog","https://www.flexport.com/blog/feed","logistics"),

  // ===== OIL & GAS / ENERGY (35) =====
  f(56,"Oil & Gas Journal","https://www.ogj.com/rss","oil_gas"),
  f(57,"World Oil","https://www.worldoil.com/rss","oil_gas"),
  f(58,"Upstream Online","https://www.upstreamonline.com/rss","oil_gas"),
  f(59,"Rigzone","https://www.rigzone.com/news/rss/a_all.aspx","oil_gas"),
  f(60,"Oil Price","https://oilprice.com/rss/main","oil_gas"),
  f(61,"Energy Intelligence","https://www.energyintel.com/rss-feed","oil_gas"),
  f(62,"S&P Global Commodity Insights","https://www.spglobal.com/commodityinsights/rss","oil_gas"),
  f(63,"Hart Energy","https://www.hartenergy.com/rss","oil_gas"),
  f(64,"E&P Magazine","https://www.epmag.com/rss","oil_gas"),
  f(65,"Petroleum Economist","https://pemedianetwork.com/feed","oil_gas"),
  f(66,"Natural Gas Intelligence","https://www.naturalgasintel.com/rss","oil_gas"),
  f(67,"LNG Global","https://www.lngglobal.com/feed","oil_gas"),
  f(68,"Oil & Gas 360","https://www.oilandgas360.com/feed","oil_gas"),
  f(69,"Energy-Pedia","https://www.energy-pedia.com/newsfeeds.aspx","oil_gas"),
  f(70,"Oil & Gas IQ","https://www.oilandgasiq.com/rss","oil_gas"),
  f(71,"Pipeline & Gas Journal","https://pgjonline.com/feed","oil_gas"),
  f(72,"Midstream Business","https://www.midstreambusiness.com/rss","oil_gas"),
  f(73,"Shale Magazine","https://shalemag.com/feed","oil_gas"),
  f(74,"Energy Transfer News","https://ir.energytransfer.com/rss","oil_gas"),
  f(75,"Kinder Morgan News","https://ir.kindermorgan.com/rss","oil_gas"),
  f(76,"US EIA - Petroleum","https://www.eia.gov/rss/todayinenergy.xml","energy"),
  f(77,"US EIA - Natural Gas","https://www.eia.gov/naturalgas/weekly/rss.xml","energy"),
  f(78,"DOE Fossil Energy","https://www.energy.gov/fe/rss.xml","energy"),
  f(79,"API News","https://www.api.org/news/feed","oil_gas"),
  f(80,"OPEC News","https://www.opec.org/opec_web/en/rss.xml","oil_gas"),
  f(81,"Renewable Energy World","https://www.renewableenergyworld.com/feed","energy"),
  f(82,"Utility Dive","https://www.utilitydive.com/feeds/news/","energy"),
  f(83,"Power Magazine","https://www.powermag.com/feed","energy"),
  f(84,"Energy Central","https://energycentral.com/rss","energy"),
  f(85,"GreenTech Media","https://www.greentechmedia.com/feed","energy"),
  f(86,"CleanTechnica","https://cleantechnica.com/feed","energy"),
  f(87,"Solar Power World","https://www.solarpowerworldonline.com/feed","energy"),
  f(88,"Wind Power Monthly","https://www.windpowermonthly.com/rss","energy"),
  f(89,"Biofuels Digest","https://www.biofuelsdigest.com/bdigest/feed","energy"),
  f(90,"Hydrogen Fuel News","https://www.hydrogenfuelnews.com/feed","energy"),

  // ===== CHEMICAL INDUSTRY (20) =====
  f(91,"Chemical & Engineering News","https://feeds.feedburner.com/cen_latestnews","chemical"),
  f(92,"Chemistry World","https://www.chemistryworld.com/rss","chemical"),
  f(93,"Chemical Processing","https://www.chemicalprocessing.com/feed","chemical"),
  f(94,"ICIS Chemical News","https://www.icis.com/explore/rss","chemical"),
  f(95,"American Chemistry Council","https://www.americanchemistry.com/feed","chemical"),
  f(96,"ChemWeek","https://chemweek.com/feed","chemical"),
  f(97,"Green Chemicals Blog","https://greenchemicalsblog.com/feed","chemical"),
  f(98,"SOCMA Blog","https://www.socma.org/blog/feed","chemical"),
  f(99,"CSB News","https://www.csb.gov/feed","chemical"),
  f(100,"Chemical Watch","https://chemicalwatch.com/feed","chemical"),
  f(101,"Chemours News","https://www.chemours.com/news/feed","chemical"),
  f(102,"Dow News","https://corporate.dow.com/en-us/news/feed","chemical"),
  f(103,"BASF News","https://www.basf.com/us/en/media/news-releases.feed","chemical"),
  f(104,"DuPont News","https://www.dupont.com/news/feed","chemical"),
  f(105,"Eastman Chemical","https://www.eastman.com/Company/News_Center/feed","chemical"),
  f(106,"Huntsman News","https://www.huntsman.com/news/feed","chemical"),
  f(107,"Celanese News","https://www.celanese.com/news/feed","chemical"),
  f(108,"Olin Corporation","https://www.olin.com/news/feed","chemical"),
  f(109,"LyondellBasell","https://www.lyondellbasell.com/news/feed","chemical"),
  f(110,"Westlake Chemical","https://www.westlake.com/news/feed","chemical"),

  // ===== COLD CHAIN / REFRIGERATED (15) =====
  f(111,"RLS Logistics Blog","https://rlslogistics.com/feed","refrigerated"),
  f(112,"Cold Chain Federation","https://coldchainfederation.org.uk/feed","refrigerated"),
  f(113,"Refrigerated Transporter","https://www.refrigeratedtrans.com/rss","refrigerated"),
  f(114,"Tive Blog","https://www.tive.com/blog/feed","refrigerated"),
  f(115,"SpotSee Blog","https://spotsee.io/feed","refrigerated"),
  f(116,"Cooltrax Blog","https://cooltrax.com/feed","refrigerated"),
  f(117,"IARW News","https://www.iarw.org/news/feed","refrigerated"),
  f(118,"GCCA News","https://www.gcca.org/news/feed","refrigerated"),
  f(119,"Lineage Logistics","https://www.lineagelogistics.com/news/feed","refrigerated"),
  f(120,"Americold News","https://www.americold.com/news/feed","refrigerated"),
  f(121,"US Cold Storage","https://www.uscold.com/news/feed","refrigerated"),
  f(122,"Burris Logistics","https://www.burrislogistics.com/blog/feed","refrigerated"),
  f(123,"Preferred Freezer","https://www.preferredfreezer.com/news/feed","refrigerated"),
  f(124,"Carrier Transicold","https://www.carrier.com/truck-trailer/en/us/news/feed","refrigerated"),
  f(125,"Thermo King","https://www.thermoking.com/na/en/news/feed","refrigerated"),

  // ===== BULK TRANSPORTATION (20) =====
  f(126,"Bulk Transporter","https://www.bulktransporter.com/rss","bulk"),
  f(127,"Tank Transport Trader","https://tanktransport.com/feed","bulk"),
  f(128,"BulkLoads News","https://www.bulkloads.com/tools/news/feed","bulk"),
  f(129,"NTTC News","https://www.tanktruck.org/news/feed","bulk"),
  f(130,"Dry Bulk Magazine","https://www.drybulkmagazine.com/feed","bulk"),
  f(131,"Dry Cargo International","https://www.drycargomag.com/feed","bulk"),
  f(132,"Splash 24/7 Dry Cargo","https://splash247.com/category/sector/dry-cargo/feed","bulk"),
  f(133,"Pneumatic Conveying","https://www.powderbulk.com/feed","bulk"),
  f(134,"Bulk Handling Today","https://bulkhandlingtoday.co.za/feed","bulk"),
  f(135,"International Bulk Journal","https://bulkjournal.com/feed","bulk"),
  f(136,"Heil Trailer News","https://www.heiltrailer.com/news/feed","bulk"),
  f(137,"MAC Trailer News","https://www.mactrailer.com/news/feed","bulk"),
  f(138,"Tremcar News","https://www.tremcar.com/news/feed","bulk"),
  f(139,"Walker Tank News","https://www.walkertank.com/news/feed","bulk"),
  f(140,"Polar Tank News","https://www.polartank.com/news/feed","bulk"),
  f(141,"Brenner Tank","https://www.brennertank.com/news/feed","bulk"),
  f(142,"Dragon Products","https://www.dragonproductsltd.com/news/feed","bulk"),
  f(143,"Hoover Container","https://www.hoovercs.com/news/feed","bulk"),
  f(144,"Schneider Tanker","https://schneider.com/news/feed","bulk"),
  f(145,"Quality Distribution","https://www.qualitydistribution.com/news/feed","bulk"),

  // ===== HAZMAT TRANSPORTATION (15) =====
  f(146,"Hazmat Nation","https://hazmatnation.com/blog/feed","hazmat"),
  f(147,"ChemTrec Blog","https://www.chemtrec.com/resources/blog/feed","hazmat"),
  f(148,"Hazmat School","https://hazmatschool.com/feed","hazmat"),
  f(149,"Daniels Training","https://danielstraining.com/feed","hazmat"),
  f(150,"MLI Environmental","https://mlienvironmental.com/about-us/feed","hazmat"),
  f(151,"Tri-State Hazmat","https://tristatehazmat.com/feed","hazmat"),
  f(152,"PHMSA News","https://www.phmsa.dot.gov/rss","hazmat"),
  f(153,"DOT Hazmat","https://www.transportation.gov/hazmat/rss","hazmat"),
  f(154,"Labelmaster Blog","https://blog.labelmaster.com/feed","hazmat"),
  f(155,"ICC Compliance","https://www.icccompliance.us/blog/feed","hazmat"),
  f(156,"Hazmat Software","https://www.hazmatsoftware.com/blog/feed","hazmat"),
  f(157,"Clean Harbors News","https://www.cleanharbors.com/news/feed","hazmat"),
  f(158,"Stericycle News","https://www.stericycle.com/news/feed","hazmat"),
  f(159,"Veolia News","https://www.veolianorthamerica.com/news/feed","hazmat"),
  f(160,"US Ecology News","https://www.usecology.com/news/feed","hazmat"),

  // ===== MARINE / MARITIME (20) =====
  f(161,"gCaptain","https://gcaptain.com/feed","marine"),
  f(162,"Maritime Executive","https://maritime-executive.com/articles.rss","marine"),
  f(163,"Marine Link","https://www.marinelink.com/news/rss","marine"),
  f(164,"Splash 24/7","https://splash247.com/feed","marine"),
  f(165,"TradeWinds","https://www.tradewindsnews.com/rss","marine"),
  f(166,"Lloyd's List","https://lloydslist.maritimeintelligence.informa.com/rss","marine"),
  f(167,"Marine Log","https://www.marinelog.com/feed","marine"),
  f(168,"WorkBoat","https://www.workboat.com/rss","marine"),
  f(169,"Professional Mariner","https://www.professionalmariner.com/feed","marine"),
  f(170,"JOC Maritime","https://www.joc.com/maritime/rss","marine"),
  f(171,"American Shipper","https://www.freightwaves.com/american-shipper/feed","marine"),
  f(172,"Port Technology","https://www.porttechnology.org/feed","marine"),
  f(173,"AAPA Ports","https://www.aapa-ports.org/feed","marine"),
  f(174,"Port of LA News","https://www.portoflosangeles.org/news/feed","marine"),
  f(175,"Port of Houston","https://porthouston.com/news/feed","marine"),
  f(176,"MARAD News","https://www.maritime.dot.gov/rss","marine"),
  f(177,"US Coast Guard","https://www.news.uscg.mil/rss","marine"),
  f(178,"Cruise Law News","https://cruiselawnews.com/feed","marine"),
  f(179,"Tanker Shipping","https://www.tankershipping.com/feed","marine"),
  f(180,"Seatrade Maritime","https://www.seatrade-maritime.com/rss","marine"),

  // ===== GOVERNMENT & REGULATORY (20) =====
  f(181,"FMCSA News","https://www.fmcsa.dot.gov/newsroom/rss","government"),
  f(182,"DOT News","https://www.transportation.gov/rss","government"),
  f(183,"NHTSA News","https://www.nhtsa.gov/rss","government"),
  f(184,"NTSB News","https://www.ntsb.gov/Pages/RSS.aspx","government"),
  f(185,"EPA News","https://www.epa.gov/rss","government"),
  f(186,"OSHA News","https://www.osha.gov/rss","government"),
  f(187,"FRA News","https://railroads.dot.gov/rss","government"),
  f(188,"STB News","https://www.stb.gov/rss","government"),
  f(189,"FERC News","https://www.ferc.gov/rss","government"),
  f(190,"NRC News","https://www.nrc.gov/rss","government"),
  f(191,"GAO Reports","https://www.gao.gov/rss/reports.rss","government"),
  f(192,"CBO Reports","https://www.cbo.gov/rss","government"),
  f(193,"BLS Transportation","https://www.bls.gov/feed/ces_transportation.rss","government"),
  f(194,"Census Trade","https://www.census.gov/economic-indicators/rss","government"),
  f(195,"DOE News","https://www.energy.gov/rss","government"),
  f(196,"CARB News","https://ww2.arb.ca.gov/rss","government"),
  f(197,"Texas DMV","https://www.txdmv.gov/rss","government"),
  f(198,"CVSA News","https://www.cvsa.org/news/feed","government"),
  f(199,"ATRI Research","https://truckingresearch.org/feed","government"),
  f(200,"FHWA News","https://highways.dot.gov/rss","government"),
];
