import { ModuleDef } from "./types";
const M = "multiple_choice" as const, T = "true_false" as const;
const mc = (q:string,a:string[],c:number,e:string,r:string) => ({questionText:q,questionType:M,options:a.map((t,i)=>({id:"abcd"[i],text:t,isCorrect:i===c})),correctAnswer:"abcd"[c],explanation:e,difficulty:"medium" as const,regulationReference:r});
const tf = (q:string,v:boolean,e:string,r:string) => ({questionText:q,questionType:T,options:[{id:"a",text:"True",isCorrect:v},{id:"b",text:"False",isCorrect:!v}],correctAnswer:v?"a":"b",explanation:e,difficulty:"easy" as const,regulationReference:r});
const les = (t:string,h:string,i:number,d:number,rc:string) => ({title:t,contentHtml:h,orderIndex:i,lessonType:"reading" as const,estimatedDurationMinutes:d,keyRegulations:[{code:rc,title:t,jurisdiction:"International",summary:t}]});
const mod = (t:string,ds:string,oi:number,dur:number,ls:any[],qs:any[]):ModuleDef => ({title:t,description:ds,orderIndex:oi,contentType:"text",estimatedDurationMinutes:dur,lessons:ls,quiz:{title:t+" Quiz",description:"Assessment: "+ds,questions:qs}});

export function getMaritime4(): Record<string, ModuleDef[]> { return {
"marpol-environmental": [
  mod("MARPOL Annexes I-III","Oil, noxious liquids, and harmful substances",1,55,[
    les("Annex I: Oil Pollution","<h2>Oil Pollution Prevention</h2><p>MARPOL Annex I: prohibits discharge of oil except through approved equipment (OWS — Oil Water Separator, max 15 ppm). IOPP Certificate required. Oil Record Book (ORB) Part I (machinery) and Part II (cargo/ballast). SOPEP (Shipboard Oil Pollution Emergency Plan). Special Areas: Mediterranean, Baltic, Black Sea, Red Sea, Gulf, Antarctic, NW European Waters — stricter discharge limits.</p>",1,30,"MARPOL Annex I"),
    les("Annexes II & III","<h2>Noxious Liquids & Packaged Goods</h2><p>Annex II: NLS (Noxious Liquid Substances) in bulk — categories X, Y, Z, OS. Pre-wash requirements for certain categories. P&A Manual (Procedures and Arrangements). Annex III: harmful substances in packaged form — aligns with IMDG Code. Marine Pollutant marking required.</p>",2,25,"MARPOL Annexes II, III"),
  ],[mc("OWS discharge limit:",["5 ppm","15 ppm","25 ppm","100 ppm"],1,"15 parts per million.","MARPOL Annex I"),mc("ORB stands for:",["Oil Recovery Book","Oil Record Book","Operational Readiness Brief","Ocean Routing Bulletin"],1,"Oil Record Book.","MARPOL Annex I"),mc("NLS categories include:",["A, B, C, D","X, Y, Z, OS","1, 2, 3, 4","I, II, III"],1,"X (most hazardous) to OS (least).","MARPOL Annex II"),tf("Special Areas have stricter discharge limits.",true,"Enhanced protection zones.","MARPOL Annex I"),mc("SOPEP is:",["Speed optimization plan","Shipboard Oil Pollution Emergency Plan","Safety officer personnel exam","Signal operations protocol"],1,"Emergency oil spill plan.","MARPOL Annex I")]),
  mod("MARPOL Annexes IV-VI","Sewage, garbage, air pollution",2,55,[
    les("Annexes IV & V","<h2>Sewage & Garbage</h2><p>Annex IV: sewage discharge rules — treated sewage allowed >3nm, untreated >12nm (comminuted) with ship en route >4 kts. Annex V: garbage — virtually no discharge at sea allowed since 2013 amendments. Food waste only >12nm (3nm in Special Areas if comminuted). Garbage Management Plan and Garbage Record Book required.</p>",1,25,"MARPOL Annexes IV, V"),
    les("Annex VI: Air Pollution","<h2>Air Emissions</h2><p>Annex VI: SOx limit 0.50% globally (since 2020), 0.10% in ECA/SECA. NOx Tier I/II/III limits based on engine RPM and construction date. EEDI (Energy Efficiency Design Index) for new ships. SEEMP (Ship Energy Efficiency Management Plan). CII (Carbon Intensity Indicator) rating A-E. ODS (Ozone Depleting Substances) restrictions.</p>",2,30,"MARPOL Annex VI"),
  ],[mc("Global SOx limit since 2020:",["3.50%","1.00%","0.50%","0.10%"],2,"0.50% sulfur.","MARPOL Annex VI"),mc("ECA SOx limit:",["0.50%","0.10%","1.00%","0.01%"],1,"0.10% in ECAs.","MARPOL Annex VI"),mc("Garbage discharge at sea since 2013:",["Allowed freely","Virtually prohibited","Allowed >3nm","Allowed >25nm"],1,"Near-total ban.","MARPOL Annex V"),tf("SEEMP is required for all ships.",true,"Ship Energy Efficiency Management Plan.","MARPOL Annex VI"),mc("CII rates ships:",["1-10","A-E","Green/Red","Pass/Fail"],1,"A (best) to E (worst).","MARPOL Annex VI")]),
  mod("US Environmental Compliance","OPA 90 and US-specific requirements",3,50,[
    les("OPA 90","<h2>Oil Pollution Act 1990</h2><p>Post-Exxon Valdez: double hull requirements for tank vessels, VRP (Vessel Response Plan) for oil tankers >300 GT and non-tankers >400 GT, COFR (Certificate of Financial Responsibility) proving ability to pay for cleanup, unlimited liability for spills caused by negligence. USCG enforces in US waters.</p>",1,25,"OPA 90, 33 CFR 155"),
    les("VGP & Ballast Water","<h2>US Discharge Permits</h2><p>EPA VGP (Vessel General Permit) for incidental discharges. Ballast Water Management Convention (BWM 2004): D-1 (exchange) and D-2 (treatment) standards. US: USCG ballast water discharge standard stricter than IMO D-2. VIDA (Vessel Incidental Discharge Act) transitioning from VGP to USCG-administered standards.</p>",2,25,"BWM Convention, VIDA"),
  ],[mc("OPA 90 was passed after:",["Titanic","Exxon Valdez","Costa Concordia","Deepwater Horizon"],1,"1989 Exxon Valdez spill.","OPA 90"),mc("COFR proves:",["Crew competency","Financial ability to pay for cleanup","Flag state approval","Classification",""],1,"Certificate of Financial Responsibility.","OPA 90"),mc("BWM D-2 requires:",["Ballast exchange at sea","Ballast water treatment system","No ballast discharge","Ballast from port only"],1,"Treatment standard.","BWM Convention"),tf("US ballast standard is stricter than IMO D-2.",true,"USCG standard more stringent.","VIDA"),mc("VRP required for tankers over:",["100 GT","300 GT","500 GT","1000 GT"],1,"300 GT for tankers.","OPA 90")]),
],
"lifesaving-fire": [
  mod("Life-Saving Appliances","SOLAS Chapter III and LSA Code",1,55,[
    les("LSA Types","<h2>Life-Saving Appliances</h2><p>SOLAS Chapter III and LSA Code: lifeboats (totally enclosed, free-fall, open), liferafts (davit-launched, throw-overboard), rescue boats, lifejackets, immersion suits, thermal protective aids. Capacity: lifeboats for 100% of persons on each side. Liferafts for 100% total. Annual servicing required for inflatable equipment.</p>",1,30,"SOLAS III, LSA Code"),
    les("Lifeboat Operations","<h2>Lifeboat Drills</h2><p>SOLAS III/19: abandon ship drills monthly, lifeboat lowering at least every 3 months, each lifeboat launched with crew at least once every 3 months. Free-fall lifeboats: simulated launching every 3 months, actual free-fall at least once every 6 months (unless alternatives approved). Records in ship's log.</p>",2,25,"SOLAS III/19"),
  ],[mc("Lifeboat capacity per side:",["50%","75%","100%","150%"],2,"100% each side.","SOLAS III"),mc("Abandon ship drills frequency:",["Weekly","Monthly","Quarterly","Semi-annually"],1,"Monthly.","SOLAS III/19"),mc("Inflatable equipment serviced:",["Monthly","Annually","Every 5 years","When damaged only"],1,"Annual servicing.","LSA Code"),tf("Free-fall lifeboats need actual launch every 6 months.",true,"Unless approved alternatives.","SOLAS III/19"),mc("LSA Code is linked to:",["MARPOL","SOLAS Chapter III","STCW","ISPS"],1,"SOLAS III references.","SOLAS III")]),
  mod("Fire Detection & Fixed Systems","Fire safety systems per SOLAS II-2",2,55,[
    les("Fire Detection","<h2>Detection Systems</h2><p>SOLAS Chapter II-2: fire detection types — smoke, heat, flame, manual call points. Fire zones: structural fire protection divides ship into main vertical/horizontal zones. A-class and B-class divisions. Fire dampers, fire doors (self-closing), ventilation shutdown. Fire control plan posted at key locations.</p>",1,25,"SOLAS II-2"),
    les("Fixed Firefighting Systems","<h2>Fixed Systems</h2><p>CO2 systems (engine room, cargo holds — personnel alarm before release), foam systems (machinery spaces, tanker decks), water mist/sprinkler (accommodation), dry chemical (galley). Inert gas system (IG) for tankers — maintains tank atmosphere below flammable range. Fire main and hydrant system: minimum pressure requirements.</p>",2,30,"SOLAS II-2"),
  ],[mc("A-class divisions withstand fire for:",["15 min","30 min","60 min","120 min"],2,"60 minutes.","SOLAS II-2"),mc("CO2 release requires:",["No warning","Personnel alarm before release","Captain approval only","Port state permission"],1,"Alarm before release — deadly gas.","SOLAS II-2"),mc("IG system maintains atmosphere:",["Above flammable range","Below flammable range","At normal oxygen","At high pressure"],1,"Below flammable range.","SOLAS II-2"),tf("Fire control plan must be posted.",true,"At key locations on ship.","SOLAS II-2"),mc("Water mist systems typically protect:",["Cargo holds","Accommodation spaces","Tanker decks","Engine room only"],1,"Accommodation and service spaces.","SOLAS II-2")]),
  mod("Emergency Procedures","Fire emergency and evacuation procedures",3,50,[
    les("Fire Emergency Response","<h2>Fire Response</h2><p>Fire alarm: continuous ringing of ship's bell + general alarm. Muster at fire stations per muster list. Fire party: leader, nozzleman, backup, BA controller. Boundary cooling to contain fire. Ventilation control — shut down to affected area. Reflash watch after extinguishment. Investigation and reporting.</p>",1,25,"SOLAS II-2, ISM Code"),
    les("Evacuation Systems","<h2>Evacuation</h2><p>MES (Marine Evacuation Systems) for large passenger vessels. Evacuation analysis per MSC.1/Circ.1238. Assembly stations, embarkation stations, embarkation ladders. Helicopter evacuation arrangements on certain vessels. SAR (Search and Rescue) coordination per SOLAS Chapter V. GMDSS distress communications.</p>",2,25,"SOLAS III, V"),
  ],[mc("Fire alarm signal:",["7 short + 1 long","Continuous ringing + general alarm","3 long blasts","Single whistle"],1,"Continuous bell + general alarm.","SOLAS II-2"),mc("BA controller manages:",["Bridge operations","Breathing apparatus teams entry/exit","Ballast water","Bow anchor"],1,"Tracks firefighters in SCBA.","General safety"),mc("MES is for:",["Cargo vessels","Large passenger vessel evacuation","Tankers","Fishing vessels"],1,"Marine Evacuation Systems.","SOLAS III"),tf("Reflash watch is unnecessary after extinguishment.",false,"Must monitor for re-ignition.","General safety"),mc("GMDSS provides:",["Cargo tracking","Global maritime distress communications","Garbage management","Grade crossing signals"],1,"Distress and safety comms.","SOLAS IV")]),
],
};}
