import { ModuleDef } from "./types";
const M = "multiple_choice" as const, T = "true_false" as const;
const mc = (q:string,a:string[],c:number,e:string,r:string) => ({questionText:q,questionType:M,options:a.map((t,i)=>({id:"abcd"[i],text:t,isCorrect:i===c})),correctAnswer:"abcd"[c],explanation:e,difficulty:"medium" as const,regulationReference:r});
const tf = (q:string,v:boolean,e:string,r:string) => ({questionText:q,questionType:T,options:[{id:"a",text:"True",isCorrect:v},{id:"b",text:"False",isCorrect:!v}],correctAnswer:v?"a":"b",explanation:e,difficulty:"easy" as const,regulationReference:r});
const les = (t:string,h:string,i:number,d:number,rc:string,j?:string) => ({title:t,contentHtml:h,orderIndex:i,lessonType:"reading" as const,estimatedDurationMinutes:d,keyRegulations:[{code:rc,title:t,jurisdiction:j||"International",summary:t}]});
const mod = (t:string,ds:string,oi:number,dur:number,ls:any[],qs:any[]):ModuleDef => ({title:t,description:ds,orderIndex:oi,contentType:"text",estimatedDurationMinutes:dur,lessons:ls,quiz:{title:t+" Quiz",description:"Assessment: "+ds,questions:qs}});

export function getMaritime1(): Record<string, ModuleDef[]> { return {
"stcw-basic-safety": [
  mod("Personal Survival Techniques","STCW A-VI/1-1 survival training",1,50,[
    les("Sea Survival","<h2>Personal Survival</h2><p>STCW Code A-VI/1-1 covers: types of emergencies at sea (collision, grounding, fire, flooding), life-saving appliances (lifejackets, immersion suits, liferafts, lifeboats), survival techniques in water (HELP position, huddle), helicopter rescue procedures, and signaling for rescue (SART, EPIRB, pyrotechnics).</p>",1,25,"STCW A-VI/1-1"),
    les("Abandoning Ship","<h2>Abandon Ship Procedures</h2><p>Muster stations, muster lists, alarm signals (7 short + 1 long blast). Donning lifejackets and immersion suits within regulatory time limits. Lifeboat launching procedures. Survival craft equipment and supplies. SOLAS Chapter III requirements for life-saving appliances.</p>",2,25,"SOLAS Chapter III"),
  ],[mc("STCW basic safety is in:",["Chapter II","Chapter VI","Chapter IV","Chapter I"],1,"Chapter VI.","STCW Convention"),mc("Abandon ship alarm is:",["1 long blast","7 short + 1 long","3 short","Continuous"],1,"7 short + 1 long.","SOLAS III"),mc("HELP position is for:",["Swimming faster","Conserving body heat in water","Signaling rescue","Climbing into liferaft"],1,"Heat Escape Lessening Posture.","STCW A-VI/1-1"),tf("EPIRB is a distress beacon.",true,"Emergency Position Indicating Radio Beacon.","SOLAS"),mc("Immersion suits protect against:",["Fire","Hypothermia in cold water","Chemical exposure","Noise"],1,"Cold water protection.","STCW A-VI/1-1")]),
  mod("Fire Prevention & Firefighting","STCW A-VI/1-2 fire safety",2,50,[
    les("Fire Triangle & Classes","<h2>Fire Science</h2><p>STCW A-VI/1-2: Fire triangle (heat, fuel, oxygen). Fire classes: A (ordinary combustibles), B (flammable liquids), C (gases), D (metals), E/F (electrical/cooking oils). Shipboard fire risks: engine room, galley, accommodation, cargo spaces. Fixed systems: CO2, foam, water mist, dry chemical.</p>",1,25,"STCW A-VI/1-2"),
    les("Firefighting Equipment","<h2>Equipment & Procedures</h2><p>SCBA (Self-Contained Breathing Apparatus) use and limitations. Fire hoses and nozzles (jet vs spray). Portable extinguishers. Fire team organization. Ventilation control (boundary cooling). SOLAS Chapter II-2 fire protection requirements.</p>",2,25,"SOLAS Chapter II-2"),
  ],[mc("Fire triangle elements:",["Heat, water, fuel","Heat, fuel, oxygen","Fuel, oxygen, CO2","Heat, metal, oxygen"],1,"Heat + fuel + oxygen.","STCW A-VI/1-2"),mc("Class B fires involve:",["Wood/paper","Flammable liquids","Gases","Metals"],1,"Liquids.","STCW A-VI/1-2"),mc("CO2 fixed systems primarily for:",["Accommodation","Engine room and cargo spaces","Bridge","Galley only"],1,"Enclosed spaces.","SOLAS II-2"),tf("SCBA has unlimited air supply.",false,"Limited duration (typically 30 min).","STCW A-VI/1-2"),mc("Boundary cooling uses:",["CO2","Water spray on surrounding bulkheads","Foam","Dry chemical"],1,"Prevents fire spread.","SOLAS II-2")]),
  mod("Elementary First Aid","STCW A-VI/1-3 medical first aid",3,45,[
    les("First Aid at Sea","<h2>Maritime First Aid</h2><p>STCW A-VI/1-3: body structure, CPR and AED use, controlling bleeding (direct pressure, tourniquet), shock management, burns treatment, fracture immobilization. Ship's Medical Chest per flag state requirements. Radio medical advice (TMAS — Telemedical Maritime Assistance Service).</p>",1,25,"STCW A-VI/1-3"),
    les("Hypothermia & Drowning","<h2>Cold Water Emergencies</h2><p>Stages of hypothermia: mild (shivering), moderate (confusion), severe (unconsciousness). Treatment: remove wet clothing, rewarm gradually, warm fluids if conscious. Near-drowning: rescue breathing, CPR, position for drainage.</p>",2,20,"STCW A-VI/1-3"),
  ],[mc("TMAS provides:",["Navigation advice","Telemedical maritime assistance","Training certification","Terminal services"],1,"Remote medical guidance.","STCW A-VI/1-3"),mc("First step for severe bleeding:",["Tourniquet","Direct pressure","Elevation only","Ice"],1,"Direct pressure first.","STCW A-VI/1-3"),mc("Hypothermia treatment includes:",["Rapid rewarming in hot water","Gradual rewarming, warm fluids","Exercise to generate heat","Cold water immersion"],1,"Gradual rewarming.","STCW A-VI/1-3"),tf("AED use is part of STCW basic safety.",true,"CPR and AED in A-VI/1-3.","STCW A-VI/1-3"),mc("Ship's Medical Chest requirements set by:",["IMO directly","Flag state","Port state","Classification society"],1,"Flag state requirements.","MLC 2006")]),
  mod("Personal Safety & Social Responsibility","STCW A-VI/1-4 personal safety",4,40,[
    les("Shipboard Safety","<h2>Personal Safety</h2><p>STCW A-VI/1-4: enclosed space entry procedures (test atmosphere, ventilation, rescue plan), PPE requirements, fall prevention (harnesses, guardrails), working aloft/over side procedures, safe lifting techniques, drug and alcohol policies, anti-harassment and bullying prevention.</p>",1,25,"STCW A-VI/1-4"),
  ],[mc("Before enclosed space entry:",["Just enter quickly","Test atmosphere, ventilate, have rescue plan","Wear a dust mask","Get captain's verbal OK"],1,"Mandatory procedures.","STCW A-VI/1-4"),mc("Enclosed space risks include:",["Only oxygen deficiency","O2 deficiency, toxic gases, flammable vapors","Noise only","Cold only"],1,"Multiple hazards.","STCW A-VI/1-4"),tf("PPE is optional on vessels.",false,"Required per STCW and ISM Code.","STCW A-VI/1-4"),mc("Working aloft requires:",["Nothing special","Safety harness and spotter","Only good weather","Captain on bridge"],1,"Fall protection.","STCW A-VI/1-4"),mc("Drug/alcohol policies governed by:",["No regulations exist","Flag state, STCW, and company ISM","Local port rules only","Crew vote"],1,"Multiple regulatory layers.","STCW, ISM Code")]),
],
"maritime-hazmat-imdg": [
  mod("IMDG Code Classification","9 UN hazard classes for maritime",1,50,[
    les("IMDG Code Overview","<h2>IMDG Classification</h2><p>The International Maritime Dangerous Goods Code (mandatory under SOLAS Chapter VII) uses the same 9 UN hazard classes as DOT: 1-Explosives, 2-Gases, 3-Flammable Liquids, 4-Flammable Solids, 5-Oxidizers, 6-Toxic, 7-Radioactive, 8-Corrosive, 9-Miscellaneous. Key maritime additions: Marine Pollutant marking, EmS (Emergency Schedules) replacing ERG, Dangerous Goods List with stowage/segregation codes.</p>",1,25,"IMDG Code"),
    les("Marking, Labeling & Placarding","<h2>IMDG Marking</h2><p>UN number and proper shipping name on packages. Diamond-shaped hazard labels on packages, placards on CTUs (Cargo Transport Units). Marine Pollutant mark (fish and tree symbol) when applicable. Fumigation warning signs. Limited/excepted quantity marks.</p>",2,25,"IMDG Code Chapter 5"),
  ],[mc("IMDG Code is mandatory under:",["MARPOL","SOLAS Chapter VII","STCW","MLC"],1,"SOLAS VII.","SOLAS Chapter VII"),mc("Marine Pollutant mark shows:",["Skull and crossbones","Fish and tree symbol","Flame","Radiation symbol"],1,"Marine pollutant ID.","IMDG Code"),mc("EmS replaces:",["The ship's log","ERG for maritime","Cargo plan","Stowage manual"],1,"Maritime emergency guide.","IMDG Code"),tf("IMDG uses same 9 UN classes as DOT.",true,"Harmonized system.","IMDG Code"),mc("CTU stands for:",["Container Terminal Unit","Cargo Transport Unit","Customs Trade Update","Central Tracking Unit"],1,"Cargo Transport Unit.","IMDG Code")]),
  mod("Stowage & Segregation","IMDG stowage and segregation requirements",2,50,[
    les("Stowage Categories","<h2>Stowage Requirements</h2><p>IMDG Code assigns stowage categories: on deck only, under deck only, on deck or under deck. Stowage codes (SW) specify conditions. Segregation table governs proximity of incompatible DG classes — from 'away from' to 'separated by an intervening complete compartment'.</p>",1,25,"IMDG Code Chapter 7"),
    les("Container Packing","<h2>CTU Packing</h2><p>Container packing certificate (IMDG §5.4.2): shipper certifies DG properly classified, packed, marked, labeled, and in proper condition for transport. Packing must prevent shifting. Incompatible DG must not be packed in same CTU.</p>",2,25,"IMDG Code §5.4.2"),
  ],[mc("Segregation table governs:",["Fuel consumption","Proximity of incompatible DG classes","Crew berthing","Speed limits"],1,"DG compatibility.","IMDG Code Chapter 7"),mc("Container packing certificate certifies:",["Container is new","DG properly classified, packed, marked","Insurance paid","Customs cleared"],1,"Shipper certification.","IMDG Code §5.4.2"),mc("Strongest segregation level:",["Away from","Separated by intervening compartment","Separated from","No requirement"],1,"Maximum separation.","IMDG Code"),tf("Incompatible DG can share a CTU.",false,"Must be separated.","IMDG Code §5.4.2"),mc("Stowage codes are prefixed:",["ST","SW","SC","SG"],1,"SW codes.","IMDG Code Chapter 7")]),
  mod("Documentation & Emergency Response","DG documentation and incident response",3,45,[
    les("DG Documentation","<h2>Required Documents</h2><p>Dangerous Goods Transport Document (IMDG §5.4.1): proper shipping name, UN number, class, packing group, quantity, EmS number. Container/vehicle packing certificate. Dangerous Goods Manifest or stowage plan showing location of all DG aboard. Master must have access to Medical First Aid Guide (MFAG).</p>",1,25,"IMDG Code §5.4"),
    les("Maritime DG Emergencies","<h2>Emergency Response</h2><p>EmS (Emergency Schedules) provide fire and spillage response for each UN number. Fire schedule (F-*) and Spillage schedule (S-*). DG incidents: jettisoning DG only as last resort (SOLAS). Report to flag state and nearest coastal state. International reporting via IMO Circular.</p>",2,20,"IMDG Code, SOLAS"),
  ],[mc("DG Transport Document includes:",["Only UN number","UN number, class, packing group, EmS","Ship dimensions","Crew list"],1,"Comprehensive info.","IMDG Code §5.4.1"),mc("EmS schedules are coded:",["F-* (fire) and S-* (spillage)","E-1 through E-9","DG-A through DG-Z","IMO-01 through IMO-99"],0,"Fire and spillage.","IMDG Code"),mc("Jettisoning DG is:",["Standard procedure","Last resort only","Prohibited always","Captain's choice"],1,"SOLAS: last resort.","SOLAS"),tf("Master must have MFAG aboard.",true,"Medical First Aid Guide required.","IMDG Code"),mc("DG incidents reported to:",["IMO headquarters","Flag state and nearest coastal state","Shipper only","Insurance company"],1,"Regulatory reporting.","SOLAS, IMDG Code")]),
],
};}
