import { ModuleDef } from "./types";
const M = "multiple_choice" as const, T = "true_false" as const;
const mc = (q:string,a:string[],c:number,e:string,r:string) => ({questionText:q,questionType:M,options:a.map((t,i)=>({id:"abcd"[i],text:t,isCorrect:i===c})),correctAnswer:"abcd"[c],explanation:e,difficulty:"medium" as const,regulationReference:r});
const tf = (q:string,v:boolean,e:string,r:string) => ({questionText:q,questionType:T,options:[{id:"a",text:"True",isCorrect:v},{id:"b",text:"False",isCorrect:!v}],correctAnswer:v?"a":"b",explanation:e,difficulty:"easy" as const,regulationReference:r});
const les = (t:string,h:string,i:number,d:number,rc:string) => ({title:t,contentHtml:h,orderIndex:i,lessonType:"reading" as const,estimatedDurationMinutes:d,keyRegulations:[{code:rc,title:t,jurisdiction:"International",summary:t}]});
const mod = (t:string,ds:string,oi:number,dur:number,ls:any[],qs:any[]):ModuleDef => ({title:t,description:ds,orderIndex:oi,contentType:"text",estimatedDurationMinutes:dur,lessons:ls,quiz:{title:t+" Quiz",description:"Assessment: "+ds,questions:qs}});

export function getMaritime5(): Record<string, ModuleDef[]> { return {
"bridge-resource-mgmt": [
  mod("BRM Principles","Team coordination and situational awareness",1,50,[
    les("BRM Fundamentals","<h2>Bridge Resource Management</h2><p>IMO Model Course 1.22 and STCW A-II/1: BRM applies crew resource management (CRM) concepts from aviation to the bridge team. Core principles: assertive communication, shared mental model, task allocation, workload management, error trapping. The master sets the tone — but junior officers must speak up when they see a safety concern.</p>",1,25,"STCW A-II/1, IMO MC 1.22"),
    les("Situational Awareness","<h2>Maintaining SA</h2><p>Three levels of SA: Level 1 (perception — what is happening), Level 2 (comprehension — what it means), Level 3 (projection — what will happen next). SA killers: fatigue, distraction, tunnel vision, complacency, poor communication. Tools: radar, ECDIS, AIS, visual lookout — all must be cross-checked.</p>",2,25,"STCW A-II/1"),
  ],[mc("BRM adapted from:",["Railway operations","Aviation CRM","Military tactics","Automotive engineering"],1,"Crew Resource Management from aviation.","IMO MC 1.22"),mc("Situational awareness Level 3 is:",["Perception","Comprehension","Projection — what will happen next","Reaction"],2,"Predicting future state.","STCW A-II/1"),mc("Who must speak up about safety concerns?",["Only the master","Only the pilot","All bridge team members","Only the OOW"],2,"Everyone — assertive communication.","IMO MC 1.22"),tf("Complacency is a threat to situational awareness.",true,"SA killer.","STCW A-II/1"),mc("BRM is required under:",["MARPOL","STCW A-II/1","ISPS Code","MLC"],1,"STCW competency requirement.","STCW A-II/1")]),
  mod("Communication & Decision-Making","Effective bridge team communication",2,50,[
    les("Communication Models","<h2>Bridge Communication</h2><p>Closed-loop communication: sender → receiver → feedback confirmation. Standard maritime phrases (SMCP — IMO Standard Marine Communication Phrases). Challenge and response for critical actions. Pilot-master information exchange (IMO A.960). Language barriers — SMCP addresses this with standardized English phrases.</p>",1,25,"IMO SMCP, A.960"),
    les("Decision Making Under Pressure","<h2>Decision Making</h2><p>Recognition-Primed Decision making (RPD) model: experienced mariners pattern-match situations. PACE model: Primary, Alternate, Contingency, Emergency plans. Time pressure effects: narrowing of attention, reversion to trained behaviors. Debriefing after critical events to capture lessons learned.</p>",2,25,"IMO MC 1.22"),
  ],[mc("Closed-loop communication includes:",["Sender only","Sender, receiver, and feedback","Written reports only","Radio only"],1,"Confirmation loop.","IMO SMCP"),mc("SMCP provides:",["Ship maintenance checklists","Standardized maritime English phrases","Security protocols","Cargo stowage plans"],1,"Standard Marine Communication Phrases.","IMO SMCP"),mc("Pilot-master exchange governed by:",["IMO A.960","IMDG Code","MARPOL","ISPS"],0,"Resolution A.960.","IMO A.960"),tf("PACE model includes an Emergency plan.",true,"Primary, Alternate, Contingency, Emergency.","IMO MC 1.22"),mc("Under time pressure, people tend to:",["Consider all options","Revert to trained behaviors","Freeze completely","Make better decisions"],1,"Training-based responses.","IMO MC 1.22")]),
  mod("Error Management & Human Factors","Managing errors on the bridge",3,45,[
    les("Error Chain","<h2>Error Management</h2><p>James Reason's Swiss Cheese Model: accidents result from alignment of holes in multiple defensive layers. Types of errors: slips (wrong action, right intent), lapses (forgot), mistakes (wrong plan). Violations: routine (cutting corners) and exceptional. Bridge team must trap errors before they reach the hazard.</p>",1,25,"Human factors research"),
    les("Fatigue on the Bridge","<h2>Fatigue Management</h2><p>IMO Guidelines on Fatigue (MSC/Circ.1014): fatigue degrades all cognitive functions critical for watchkeeping — attention, decision-making, reaction time. Circadian low points (0200-0600). Rest period compliance per STCW and MLC. Fatigue risk management systems (FRMS) encouraged by IMO.</p>",2,20,"IMO MSC/Circ.1014"),
  ],[mc("Swiss Cheese Model by:",["Einstein","James Reason","Titanic inquiry","IMO directly"],1,"Error causation model.","Human factors"),mc("A 'slip' is:",["Deliberate violation","Wrong action with right intention","Forgetting to act","Wrong plan"],1,"Unintended action.","Human factors"),mc("Circadian low point:",["1000-1400","0200-0600","1800-2200","1200-1600"],1,"Lowest alertness.","IMO MSC/Circ.1014"),tf("Routine violations are acceptable.",false,"Cutting corners increases risk.","Human factors"),mc("FRMS stands for:",["Fire Risk Monitoring System","Fatigue Risk Management System","Fuel Reporting and Monitoring","Fleet Resource Management"],1,"Fatigue management.","IMO MSC/Circ.1014")]),
],
"maritime-hours-rest": [
  mod("STCW Rest Requirements","STCW Section A-VIII/1 hours of rest",1,50,[
    les("STCW Rest Periods","<h2>STCW Hours of Rest</h2><p>STCW Section A-VIII/1: minimum 10 hours rest in any 24-hour period (may be divided into no more than 2 periods, one of which must be at least 6 hours). Minimum 77 hours rest in any 7-day period. Exceptions only in emergencies (master's discretion, documented). Rest periods may not be divided into more than 2 periods.</p>",1,25,"STCW A-VIII/1"),
    les("Record Keeping","<h2>Rest Hour Records</h2><p>Records maintained in standardized format (IMO/ILO format). Available for inspection by PSC, flag state, and company. Records signed by both seafarer and master (or authorized officer). Non-compliance detected during PSC can lead to detention. Records retained on board and ashore.</p>",2,25,"STCW A-VIII/1"),
  ],[mc("Min rest in 24 hours:",["8 hrs","10 hrs","12 hrs","6 hrs"],1,"10 hours minimum.","STCW A-VIII/1"),mc("Max rest period divisions in 24 hrs:",["1","2","3","4"],1,"No more than 2 periods.","STCW A-VIII/1"),mc("One rest period must be at least:",["4 hrs","5 hrs","6 hrs","8 hrs"],2,"6 hours continuous.","STCW A-VIII/1"),tf("Exceptions allowed only in emergencies.",true,"Master's discretion, documented.","STCW A-VIII/1"),mc("Min rest in 7 days:",["56 hrs","70 hrs","77 hrs","84 hrs"],2,"77 hours per 7-day period.","STCW A-VIII/1")]),
  mod("MLC 2006 Work Hours","Maritime Labour Convention work/rest standards",2,50,[
    les("MLC Standard A2.3","<h2>MLC Work Hours</h2><p>MLC 2006 Standard A2.3: max 14 hours work in any 24-hour period, max 72 hours in any 7-day period. OR min 10 hours rest in 24 hours (divided max 2, one ≥6hrs), min 77 hours rest in 7 days. Flag state chooses work-hour or rest-hour basis. MLC also covers: leave entitlement, repatriation, wages, medical care, accommodation.</p>",1,25,"MLC 2006 A2.3"),
    les("Differences: STCW vs MLC","<h2>Comparing Frameworks</h2><p>STCW focuses on safety (watchkeeping fitness). MLC focuses on labor rights (working conditions). Both apply simultaneously — the stricter standard prevails. STCW enforced through PSC and flag state. MLC enforced through Maritime Labour Certificate (MLC Certificate) and DMLC (Declaration of Maritime Labour Compliance).</p>",2,25,"STCW, MLC 2006"),
  ],[mc("MLC max work in 24 hrs:",["12 hrs","14 hrs","16 hrs","No limit"],1,"14 hours maximum.","MLC 2006 A2.3"),mc("MLC max work in 7 days:",["56 hrs","72 hrs","84 hrs","100 hrs"],1,"72 hours.","MLC 2006 A2.3"),mc("When STCW and MLC conflict:",["STCW always wins","MLC always wins","Stricter standard prevails","Captain decides"],2,"More protective standard applies.","STCW, MLC"),tf("MLC Certificate required for international voyages.",true,"Mandatory compliance document.","MLC 2006"),mc("MLC 2006 covers:",["Navigation only","Seafarer labor rights and conditions","Cargo handling","Environmental protection"],1,"Comprehensive labor convention.","MLC 2006")]),
  mod("Fatigue Management at Sea","Maritime fatigue prevention",3,45,[
    les("Maritime Fatigue Factors","<h2>Fatigue at Sea</h2><p>Unique maritime fatigue factors: continuous 24/7 operations, limited crew (no relief driver), motion and vibration, social isolation, port turnaround pressure, watchkeeping patterns (4-on/8-off, 6-on/6-off). IMO Guidelines on Fatigue Mitigation (MSC.1/Circ.1598): voyage planning, watch schedules, sleep hygiene, napping strategies.</p>",1,25,"IMO MSC.1/Circ.1598"),
    les("Company & Flag State Obligations","<h2>Organizational Responsibility</h2><p>ISM Code requires companies to ensure safe manning. MLC requires adequate manning to avoid excessive work hours. Flag state sets minimum safe manning document. Company fatigue policies under ISM SMS. Fatigue as contributing factor investigated by MAIB, NTSB (Marine), TSB.</p>",2,20,"ISM Code, MLC"),
  ],[mc("Common watch pattern:",["8-on/16-off","4-on/8-off","12-on/12-off","Continuous"],1,"4 on, 8 off.","General"),mc("IMO fatigue guidelines:",["MSC.1/Circ.1598","MARPOL Annex VI","STCW Chapter IV","ISPS Part B"],0,"Fatigue mitigation circular.","IMO MSC.1/Circ.1598"),mc("Safe manning document issued by:",["Company","Flag state","Port state","IMO"],1,"Flag state responsibility.","SOLAS V/14"),tf("Motion and vibration contribute to maritime fatigue.",true,"Unique shipboard factors.","IMO MSC.1/Circ.1598"),mc("Fatigue accidents investigated by:",["Only the company","MAIB, NTSB Marine, TSB","Insurance companies","Classification societies"],1,"National investigation bodies.","General")]),
],
};}
