import { ModuleDef } from "./types";
const M = "multiple_choice" as const, T = "true_false" as const;
const mc = (q:string,a:string[],c:number,e:string,r:string) => ({questionText:q,questionType:M,options:a.map((t,i)=>({id:"abcd"[i],text:t,isCorrect:i===c})),correctAnswer:"abcd"[c],explanation:e,difficulty:"medium" as const,regulationReference:r});
const tf = (q:string,v:boolean,e:string,r:string) => ({questionText:q,questionType:T,options:[{id:"a",text:"True",isCorrect:v},{id:"b",text:"False",isCorrect:!v}],correctAnswer:v?"a":"b",explanation:e,difficulty:"easy" as const,regulationReference:r});
const les = (t:string,h:string,i:number,d:number,rc:string) => ({title:t,contentHtml:h,orderIndex:i,lessonType:"reading" as const,estimatedDurationMinutes:d,keyRegulations:[{code:rc,title:t,jurisdiction:"International",summary:t}]});
const mod = (t:string,ds:string,oi:number,dur:number,ls:any[],qs:any[]):ModuleDef => ({title:t,description:ds,orderIndex:oi,contentType:"text",estimatedDurationMinutes:dur,lessons:ls,quiz:{title:t+" Quiz",description:"Assessment: "+ds,questions:qs}});

export function getMaritime3(): Record<string, ModuleDef[]> { return {
"maritime-security-isps": [
  mod("ISPS Code Framework","International Ship and Port Facility Security",1,50,[
    les("ISPS Overview","<h2>ISPS Code</h2><p>ISPS Code (SOLAS Chapter XI-2) adopted after 9/11. Part A: mandatory requirements. Part B: guidance. Three security levels: Level 1 (normal), Level 2 (heightened), Level 3 (exceptional — specific threat). Key roles: CSO (Company Security Officer), SSO (Ship Security Officer), PFSO (Port Facility Security Officer). Ship Security Plan (SSP) approved by flag state or RSO.</p>",1,25,"ISPS Code, SOLAS XI-2"),
    les("Security Assessments","<h2>Ship Security Assessment</h2><p>SSA (Ship Security Assessment) identifies vulnerabilities: access points, restricted areas, cargo/stores handling, monitoring systems. Results feed into SSP. PFSA (Port Facility Security Assessment) similar for ports. Both must be reviewed and updated regularly. DoS (Declaration of Security) between ship and port when required.</p>",2,25,"ISPS Code Part A"),
  ],[mc("ISPS Code has how many security levels?",["2","3","4","5"],1,"Levels 1, 2, 3.","ISPS Code"),mc("SSO stands for:",["Ship Safety Officer","Ship Security Officer","Senior Staff Officer","Shore Security Operator"],1,"Ship Security Officer.","ISPS Code"),mc("ISPS was adopted after:",["Exxon Valdez","9/11 attacks","Titanic","Costa Concordia"],1,"Post-9/11 maritime security.","SOLAS XI-2"),tf("Part B of ISPS is mandatory.",false,"Part B is guidance; Part A is mandatory.","ISPS Code"),mc("DoS is between:",["Two ships","Ship and port facility","Flag states","Classification societies"],1,"Declaration of Security.","ISPS Code")]),
  mod("Security Drills & Equipment","Security training and equipment requirements",2,45,[
    les("Security Drills","<h2>Training & Drills</h2><p>ISPS Part A/13: drills at least every 3 months. Exercises at least once per calendar year (no more than 18 months apart). All crew must have security awareness training. SSO and CSO require specific STCW certification (Table A-VI/5 and A-VI/6). Records of training maintained for flag state and PSC inspection.</p>",1,25,"ISPS Part A/13"),
    les("Security Equipment","<h2>Security Systems</h2><p>SSAS (Ship Security Alert System): covert distress alert to flag state and company (not broadcast). LRIT (Long Range Identification and Tracking). AIS (can be switched off only with master's authority in security situations). CCTV, access control systems, intruder detection. 33 CFR 104/105 for US implementation.</p>",2,20,"33 CFR 104/105"),
  ],[mc("Security drills at least every:",["Month","3 months","6 months","Year"],1,"Quarterly minimum.","ISPS Part A/13"),mc("SSAS sends alert to:",["All nearby ships","Flag state and company covertly","USCG only","IMO headquarters"],1,"Covert alert.","SOLAS XI-2"),mc("US ISPS implementation in:",["46 CFR","33 CFR 104/105","49 CFR","29 CFR"],1,"33 CFR.","33 CFR 104/105"),tf("All crew need security awareness training.",true,"Per ISPS and STCW.","ISPS Part A"),mc("Exercises at least once per:",["Month","Quarter","Calendar year","5 years"],2,"Annual minimum (max 18 months).","ISPS Part A/13")]),
  mod("Cyber Security & Threats","Modern maritime security threats",3,45,[
    les("Maritime Cyber Security","<h2>Cyber Threats</h2><p>IMO MSC-FAL.1/Circ.3: cyber risk management in Safety Management Systems by 2021. Threats: GPS spoofing, ECDIS malware, ransomware on ship networks, AIS manipulation. ISM Code now requires cyber risk assessment. BIMCO guidelines for cyber security onboard ships.</p>",1,25,"IMO MSC-FAL.1/Circ.3"),
    les("Piracy & Armed Robbery","<h2>Physical Threats</h2><p>IMO MSC.1/Circ.1334: Best Management Practices for piracy (BMP5 for Indian Ocean). Citadel concept: safe room for crew. PCASP (Privately Contracted Armed Security Personnel). Reporting: IMO piracy reports, IMB Piracy Reporting Centre. High Risk Area (HRA) transit requirements.</p>",2,20,"IMO MSC.1/Circ.1334"),
  ],[mc("IMO required cyber risk management by:",["2019","2021","2025","No requirement"],1,"ISM Code incorporation.","IMO MSC-FAL.1/Circ.3"),mc("BMP5 covers:",["Cargo handling","Anti-piracy best practices","Bridge management","Environmental compliance"],1,"Best Management Practices.","BMP5"),mc("Citadel is:",["Navigation bridge","Safe room for crew during piracy attack","Engine room","Cargo hold"],1,"Protected retreat.","BMP5"),tf("GPS spoofing is a maritime cyber threat.",true,"Navigation system vulnerability.","IMO MSC-FAL.1/Circ.3"),mc("IMB stands for:",["International Maritime Bureau","International Maritime Board","Integrated Marine Bridge","Institute of Maritime Business"],0,"Piracy reporting center.","IMB")]),
],
"cargo-handling-stowage": [
  mod("Cargo Securing & CSS Code","Code of Safe Practice for Cargo Stowage and Securing",1,50,[
    les("CSS Code","<h2>Cargo Securing</h2><p>IMO CSS Code (MSC.1/Circ.1353/Rev.1): cargo securing arrangements must prevent shifting in all sea conditions. Cargo Securing Manual (CSM) required for all ships. Lashing calculations: forces from rolling, pitching, heaving. Timber deck cargo code. Grain code (SOLAS Chapter VI). Container lashing: automatic twist-locks, lashing rods, turnbuckles, stacking weights.</p>",1,25,"CSS Code"),
    les("Container Stowage","<h2>Container Operations</h2><p>Bay plan management. Stack weights and tier limits. Reefer container connections and monitoring. OOG (Out of Gauge) cargo: flat racks, open tops. Hatch cover strength ratings. SOLAS VGM (Verified Gross Mass) requirement — Method 1 (weigh packed container) or Method 2 (sum of contents + tare).</p>",2,25,"SOLAS VI"),
  ],[mc("CSM stands for:",["Cargo Stowage Manual","Cargo Securing Manual","Container Safety Manual","CSS Management"],1,"Required per CSS Code.","CSS Code"),mc("VGM verification methods:",["1 method","2 methods","3 methods","No standard"],1,"Method 1 (weigh) or Method 2 (calculate).","SOLAS"),mc("OOG cargo uses:",["Standard containers only","Flat racks and open tops","Tank containers","Reefer containers"],1,"Out of Gauge handling.","General"),tf("Lashing calculations consider ship motions.",true,"Rolling, pitching, heaving forces.","CSS Code"),mc("Grain cargo governed by:",["IMDG Code","SOLAS Chapter VI / Grain Code","STCW","MARPOL"],1,"International Grain Code.","SOLAS VI")]),
  mod("Stability & Load Planning","Vessel stability and cargo planning",2,50,[
    les("Stability Fundamentals","<h2>Cargo and Stability</h2><p>Loading computer mandatory for cargo vessels. Key concepts: GM (metacentric height), GZ (righting lever), free surface effect from liquid cargo/ballast. Stability criteria per SOLAS and classification society rules. Intact and damage stability calculations. Loadline Convention (ILLC 1966) sets maximum drafts for different zones and seasons.</p>",1,25,"SOLAS, ILLC 1966"),
    les("Loading/Discharge Planning","<h2>Load Planning</h2><p>Cargo plan optimization: stability, visibility, stress, port rotation. Ballast management during cargo operations. Trim optimization for fuel efficiency. Loading rate coordination with terminal. Draft surveys for cargo quantity determination.</p>",2,25,"SOLAS Chapter VI"),
  ],[mc("GM measures:",["Ship's speed","Metacentric height (stability indicator)","Cargo weight","Fuel consumption"],1,"Initial stability measure.","SOLAS"),mc("Free surface effect comes from:",["Wind","Liquid in partially filled tanks","Deck cargo","Container stacking"],1,"Reduces stability.","SOLAS"),mc("Loadline Convention sets:",["Speed limits","Maximum drafts by zone/season","Crew numbers","Cargo types"],1,"ILLC 1966.","ILLC 1966"),tf("Loading computers are optional.",false,"Mandatory for cargo vessels.","SOLAS"),mc("Draft survey determines:",["Ship's age","Cargo quantity loaded/discharged","Fuel quality","Container count"],1,"Weight by displacement.","General")]),
  mod("Bulk Cargo & Special Cargoes","Bulk carrier safety and special cargo requirements",3,45,[
    les("Bulk Cargo Hazards","<h2>Bulk Cargo Safety</h2><p>IMSBC Code (International Maritime Solid Bulk Cargoes Code): Group A cargoes (may liquefy — e.g., nickel ore, iron ore fines), Group B (chemical hazards), Group C (neither). Moisture content testing: TML (Transportable Moisture Limit) — cargo must not exceed TML. Bulk carrier structural risks: hold flooding, structural failure from improper loading sequences.</p>",1,25,"IMSBC Code"),
    les("Reefer & Livestock","<h2>Special Cargoes</h2><p>Reefer cargo: temperature control, atmosphere management (CA/MA), pre-trip inspections. Livestock: ventilation, feeding, watering, veterinary requirements. Project cargo: heavy lifts, engineering calculations, sea fastening design. Timber deck cargo: Code of Safe Practice for Ships Carrying Timber Deck Cargoes.</p>",2,20,"Various IMO codes"),
  ],[mc("Group A bulk cargo risk:",["Explosion","Liquefaction","Radiation","Corrosion"],1,"May liquefy and cause capsizing.","IMSBC Code"),mc("TML stands for:",["Total Mass Limit","Transportable Moisture Limit","Terminal Management Level","Tare Mass Loading"],1,"Maximum moisture for transport.","IMSBC Code"),mc("IMSBC Code covers:",["Liquid bulk","Solid bulk cargoes","Containers","Passengers"],1,"International Maritime Solid Bulk Cargoes.","IMSBC Code"),tf("Cargo exceeding TML must not be loaded.",true,"Liquefaction risk too high.","IMSBC Code"),mc("Pre-trip inspection is for:",["Navigation equipment","Reefer containers","Lifeboats","Mooring lines"],1,"Verify reefer function before loading.","General")]),
],
};}
