import { ModuleDef } from "./types";
const M = "multiple_choice" as const, T = "true_false" as const;
const mc = (q:string,a:string[],c:number,e:string,r:string) => ({questionText:q,questionType:M,options:a.map((t,i)=>({id:"abcd"[i],text:t,isCorrect:i===c})),correctAnswer:"abcd"[c],explanation:e,difficulty:"medium" as const,regulationReference:r});
const tf = (q:string,v:boolean,e:string,r:string) => ({questionText:q,questionType:T,options:[{id:"a",text:"True",isCorrect:v},{id:"b",text:"False",isCorrect:!v}],correctAnswer:v?"a":"b",explanation:e,difficulty:"easy" as const,regulationReference:r});
const les = (t:string,h:string,i:number,d:number,rc:string,j?:string) => ({title:t,contentHtml:h,orderIndex:i,lessonType:"reading" as const,estimatedDurationMinutes:d,keyRegulations:[{code:rc,title:t,jurisdiction:j||"US",summary:t}]});
const mod = (t:string,ds:string,oi:number,dur:number,ls:any[],qs:any[]):ModuleDef => ({title:t,description:ds,orderIndex:oi,contentType:"text",estimatedDurationMinutes:dur,lessons:ls,quiz:{title:t+" Quiz",description:"Assessment: "+ds,questions:qs}});

export function getMaritime6(): Record<string, ModuleDef[]> { return {
"customs-trade-compliance": [
  mod("CBP Entry Procedures","US Customs entry and classification",1,50,[
    les("Entry Process","<h2>CBP Entry</h2><p>19 CFR governs customs entry. Steps: entry filing (within 15 days of arrival), duty assessment based on HTS (Harmonized Tariff Schedule) classification, liquidation (final duty determination — up to 314 days). Entry types: formal (>$2,500), informal (<$2,500). Customs broker required for formal entries. Reasonable care standard — importer responsible for accurate classification and valuation.</p>",1,25,"19 CFR"),
    les("ISF 10+2","<h2>Importer Security Filing</h2><p>ISF (10+2): 10 data elements from importer + 2 from carrier, filed 24 hours before vessel loading at foreign port. Required for all ocean imports to US. Penalties for late/inaccurate filing: $5,000 per violation. Data: manufacturer, seller, buyer, ship-to party, HTS number, container stuffing location, consolidator, etc.</p>",2,25,"19 CFR Part 149"),
  ],[mc("Entry must be filed within:",["5 days","15 days","30 days","60 days"],1,"15 calendar days of arrival.","19 CFR"),mc("ISF filed how many hours before loading?",["12","24","48","72"],1,"24 hours before vessel loading.","19 CFR Part 149"),mc("ISF penalty per violation:",["$1,000","$5,000","$10,000","$25,000"],1,"$5,000 per violation.","19 CFR Part 149"),tf("Customs broker required for formal entries.",true,"Over $2,500 value.","19 CFR"),mc("HTS stands for:",["Harbor Transport Schedule","Harmonized Tariff Schedule","Hazmat Transport System","High-risk Trade Screening"],1,"Classification system.","19 CFR")]),
  mod("Trade Programs & Compliance","C-TPAT, FTZ, duty drawback",2,50,[
    les("C-TPAT & Trusted Trader","<h2>Trade Programs</h2><p>C-TPAT (Customs-Trade Partnership Against Terrorism): voluntary program — members get reduced inspections, priority processing, front of line. Tiers: Tier 1 (certified), Tier 2 (validated), Tier 3 (highest). FTZ (Foreign Trade Zones): designated areas where goods can be imported, stored, manufactured without formal customs entry until entering US commerce. Duty drawback: refund of duties on imported goods that are re-exported.</p>",1,25,"19 CFR"),
    les("USMCA Rules of Origin","<h2>USMCA Compliance</h2><p>USMCA (US-Mexico-Canada Agreement) replaced NAFTA 2020. Rules of origin determine if goods qualify for preferential duty rates. Regional Value Content (RVC) calculations. Certificate of Origin required. Auto rules: 75% RVC requirement, labor value content provisions. De minimis threshold: 10% for most goods.</p>",2,25,"USMCA, 19 CFR"),
  ],[mc("C-TPAT is:",["Mandatory for all importers","Voluntary trusted trader program","Criminal enforcement","Tax program"],1,"Voluntary partnership.","19 CFR"),mc("FTZ allows:",["Free shipping","Deferral of customs duties","Tax evasion","Unlimited imports"],1,"Duties deferred until entering commerce.","19 CFR"),mc("USMCA auto RVC requirement:",["50%","62.5%","75%","90%"],2,"75% regional value content.","USMCA"),tf("Duty drawback refunds duties on re-exported goods.",true,"Incentive for re-export.","19 CFR"),mc("USMCA replaced:",["WTO","NAFTA","TPP","CAFTA"],1,"Effective July 2020.","USMCA")]),
  mod("Enforcement & Penalties","Customs violations and penalties",3,45,[
    les("Customs Violations","<h2>Enforcement</h2><p>CBP enforcement: negligence penalties (2x lost revenue), gross negligence (4x), fraud (domestic value of goods). Prior disclosure: voluntary reporting reduces penalties. Focused Assessment: CBP audit of importer's internal controls. AD/CVD (Antidumping/Countervailing Duties): additional duties on unfairly priced imports. Forced labor: imports produced with forced labor prohibited under 19 USC §1307.</p>",1,25,"19 USC, 19 CFR"),
    les("Recordkeeping","<h2>Records Retention</h2><p>19 USC §1508: importers must keep records for 5 years from date of entry. Records include: entry documents, invoices, correspondence, financial records. (a)(1)(A) records: entry summary, classification, valuation. Failure to maintain records: penalties of $10,000-$100,000.</p>",2,20,"19 USC §1508"),
  ],[mc("Fraud penalty can be:",["2x lost revenue","4x lost revenue","Domestic value of goods","$10,000 flat"],2,"Full domestic value.","19 USC"),mc("Records retention period:",["1 year","3 years","5 years","7 years"],2,"5 years from entry.","19 USC §1508"),mc("Prior disclosure:",["Increases penalties","Reduces penalties via voluntary reporting","Eliminates all duties","Is mandatory"],1,"Voluntary = reduced penalty.","19 CFR"),tf("Forced labor imports are prohibited.",true,"19 USC §1307.","19 USC §1307"),mc("AD/CVD duties target:",["All imports","Unfairly priced imports","Re-exports","Transit cargo"],1,"Antidumping/countervailing.","19 USC")]),
],
"inland-waterway-ops": [
  mod("Inland Waterway Regulations","USCG regulations for inland operations",1,50,[
    les("Inland Navigation Rules","<h2>Inland Rules</h2><p>33 CFR Part 83 (Inland Navigation Rules): based on COLREGS but with key differences for rivers, lakes, ICW. Differences: inland uses whistle signals for intent (1 short = I intend to pass port-to-port), COLREGS uses signals for action taken. Western Rivers special rules. Towing vessel requirements: 46 CFR Subchapter M (inspection of towing vessels).</p>",1,25,"33 CFR Part 83"),
    les("Lock & Dam Operations","<h2>Locks & Dams</h2><p>USACE (US Army Corps of Engineers) operates 239 lock chambers on US inland waterways. Lock transit procedures: approach signals, vessel order priority, safety requirements during transit. River conditions: current, water level, debris, fog. USCG Captain of the Port (COTP) can close waterways for safety.</p>",2,25,"33 CFR, USACE"),
  ],[mc("Inland whistle for port-to-port:",["2 short","1 short","1 prolonged","3 short"],1,"1 short = port-to-port intent.","33 CFR Part 83"),mc("Towing vessel inspection under:",["46 CFR Subchapter M","49 CFR Part 232","SOLAS","MARPOL"],0,"Subchapter M.","46 CFR Subchapter M"),mc("US locks operated by:",["USCG","USACE","EPA","DOT"],1,"Army Corps of Engineers.","USACE"),tf("COTP can close waterways.",true,"Captain of the Port authority.","33 CFR"),mc("Number of US lock chambers:",["50","150","239","500"],2,"239 lock chambers.","USACE")]),
  mod("Towing & Barge Operations","Barge fleet management and safety",2,50,[
    les("Barge Types & Operations","<h2>Barge Operations</h2><p>Types: hopper barges (dry cargo), tank barges (liquid), deck barges (heavy/project cargo). Fleet makeup: multiple barges lashed together as a 'tow'. River tows can exceed 1,000 feet. Fleeting areas: where barges are assembled/stored. 46 CFR Subchapter M: safety management system, vessel inspections, crew training for towing vessels.</p>",1,25,"46 CFR Subchapter M"),
    les("Hazmat by Barge","<h2>Barge Hazmat</h2><p>Tank barges carry petroleum, chemicals, and other hazmat. 46 CFR Subchapter D and O: tank barge construction and inspection. Vapor recovery systems. Transfer operations: Declaration of Inspection (DOI) before every transfer. Oil spill response: barge response plan per OPA 90. USCG Certificate of Inspection (COI) required.</p>",2,25,"46 CFR, OPA 90"),
  ],[mc("River tows can exceed:",["100 ft","500 ft","1,000 ft","5,000 ft"],2,"Over 1,000 feet.","General"),mc("DOI required before:",["Every voyage","Every cargo transfer","Annual inspection","Crew change"],1,"Declaration of Inspection.","46 CFR"),mc("Fleeting areas are for:",["Fuel storage","Barge assembly and storage","Crew quarters","Lock operations"],1,"Staging barges.","General"),tf("Tank barges need COI from USCG.",true,"Certificate of Inspection.","46 CFR"),mc("Barge oil spill response per:",["MARPOL","OPA 90","STCW","ISPS"],1,"Oil Pollution Act.","OPA 90")]),
  mod("River Navigation & Pilotage","River piloting and navigation aids",3,50,[
    les("River Pilotage","<h2>River Navigation</h2><p>River pilotage: specialized knowledge of currents, shoals, bridge clearances, river stages. USCG licensing: Master/Pilot of Towing Vessels. River mile markers. USACE navigation charts. Current effects on handling: flanking maneuvers, backing maneuvers. Bridge clearance gauges. High water operations: increased current, debris, submerged hazards.</p>",1,25,"46 CFR, 33 CFR"),
    les("Aids to Navigation","<h2>ATON System</h2><p>USCG Aids to Navigation (ATON): buoys, daymarks, lights. Inland waterway system: red (right descending) — opposite of IALA-B for seaward. Mile boards. Regulatory markers: speed zones, restricted areas, danger areas. Electronic aids: AIS ATON, DGPS. Light lists published by USCG.</p>",2,25,"33 CFR Part 62"),
  ],[mc("River buoy system red marks:",["Right returning from sea","Right descending the river","Left descending","Channel center"],1,"Right descending.","33 CFR Part 62"),mc("Flanking maneuvers used for:",["Docking","Navigating river bends with current","Anchoring","Loading cargo"],1,"River current handling.","General"),mc("Bridge clearance info from:",["Gauges at bridges","GPS only","Radio only","Crew estimate"],0,"Physical gauges.","USACE"),tf("AIS is used on inland waterways.",true,"AIS ATON and vessel AIS.","33 CFR"),mc("ATON stands for:",["Automatic Train Operation Network","Aids to Navigation","Advanced Terminal Operations","Anchor Testing and Oversight"],1,"Aids to Navigation.","33 CFR Part 62")]),
  mod("Environmental & Safety Compliance","Inland waterway environmental rules",4,40,[
    les("Environmental Requirements","<h2>Inland Environmental</h2><p>Clean Water Act: no discharge of oil or hazardous substances. State-specific discharge permits. Ballast water management for Great Lakes vessels. EPA VGP requirements. Spill reporting: NRC (1-800-424-8802) for any oil sheen. USCG exercises enforcement on inland waters jointly with state agencies.</p>",1,25,"Clean Water Act, OPA 90"),
  ],[mc("Oil sheen reported to:",["EPA only","NRC 1-800-424-8802","State only","No reporting needed"],1,"National Response Center.","Clean Water Act"),mc("Great Lakes vessels must manage:",["Only fuel","Ballast water","Cargo only","Nothing special"],1,"BWM requirements.","EPA, USCG"),tf("State agencies also enforce on inland waters.",true,"Joint with USCG.","General"),mc("Any visible oil sheen is:",["Acceptable","A reportable discharge","Normal operations","Only reported monthly"],1,"Zero tolerance for sheens.","Clean Water Act"),mc("Inland water enforcement by:",["FRA","USCG and state agencies","TSA","OSHA only"],1,"Joint enforcement.","33 CFR")]),
],
};}
