import { ModuleDef } from "./types";
const M = "multiple_choice" as const, T = "true_false" as const;
const mc = (q:string,a:string[],c:number,e:string,r:string) => ({questionText:q,questionType:M,options:a.map((t,i)=>({id:"abcd"[i],text:t,isCorrect:i===c})),correctAnswer:"abcd"[c],explanation:e,difficulty:"medium" as const,regulationReference:r});
const tf = (q:string,v:boolean,e:string,r:string) => ({questionText:q,questionType:T,options:[{id:"a",text:"True",isCorrect:v},{id:"b",text:"False",isCorrect:!v}],correctAnswer:v?"a":"b",explanation:e,difficulty:"easy" as const,regulationReference:r});
const les = (t:string,h:string,i:number,d:number,rc:string) => ({title:t,contentHtml:h,orderIndex:i,lessonType:"reading" as const,estimatedDurationMinutes:d,keyRegulations:[{code:rc,title:t,jurisdiction:"International",summary:t}]});
const mod = (t:string,ds:string,oi:number,dur:number,ls:any[],qs:any[]):ModuleDef => ({title:t,description:ds,orderIndex:oi,contentType:"text",estimatedDurationMinutes:dur,lessons:ls,quiz:{title:t+" Quiz",description:"Assessment: "+ds,questions:qs}});

export function getMaritime2(): Record<string, ModuleDef[]> { return {
"vessel-navigation": [
  mod("COLREGS & Rules of the Road","International collision regulations",1,55,[
    les("COLREGS Overview","<h2>Rules of the Road</h2><p>COLREGS (Convention on International Regulations for Preventing Collisions at Sea, 1972): 41 rules plus 4 annexes. Key rules: Rule 5 (lookout), Rule 6 (safe speed), Rule 7 (risk of collision), Rule 8 (action to avoid collision), Rules 11-19 (steering and sailing rules), Rule 34 (maneuvering signals), Rule 35 (sound signals in restricted visibility).</p>",1,30,"COLREGS 1972"),
    les("Navigation Lights & Shapes","<h2>Lights & Day Shapes</h2><p>COLREGS Annex I: navigation lights visible at prescribed distances. Power-driven vessel: masthead, sidelights, sternlight. Vessel at anchor: all-round white. Vessel not under command: two red all-round. Towing: additional masthead lights. Day shapes: ball (anchor), diamond (towing), cylinder (constrained by draft).</p>",2,25,"COLREGS Annex I"),
  ],[mc("COLREGS Rule 5 requires:",["Speed limits","Proper lookout at all times","Port-side passage","Anchoring at night"],1,"Lookout by sight and hearing.","COLREGS Rule 5"),mc("Vessel not under command shows:",["Green lights","Two red all-round lights","Blue flashing","White strobe"],1,"Two red vertically.","COLREGS Rule 27"),mc("Risk of collision is Rule:",["5","6","7","8"],2,"Rule 7.","COLREGS"),tf("COLREGS applies only in international waters.",false,"Also adopted for inland waters (with modifications).","COLREGS"),mc("Day shape for vessel at anchor:",["Diamond","Ball","Cylinder","Cone"],1,"Black ball.","COLREGS Rule 30")]),
  mod("Electronic Navigation","ECDIS, radar, AIS systems",2,50,[
    les("ECDIS Requirements","<h2>Electronic Charts</h2><p>ECDIS (Electronic Chart Display and Information System) is now mandatory under SOLAS V/19.2. Uses ENC (Electronic Navigational Charts) from national hydrographic offices. Must maintain backup arrangements (second ECDIS or paper charts). Type-approved per IMO performance standards. Officers must complete ECDIS-specific training per STCW.</p>",1,25,"SOLAS V/19.2"),
    les("Radar & AIS","<h2>Radar and AIS</h2><p>ARPA/radar mandatory per SOLAS. AIS (Automatic Identification System) transmits vessel identity, position, course, speed. Class A mandatory for SOLAS vessels. AIS data aids collision avoidance and VTS (Vessel Traffic Services). LRIT (Long Range Identification and Tracking) for security.</p>",2,25,"SOLAS V/19"),
  ],[mc("ECDIS uses charts called:",["Paper charts","ENC","Raster scans","GPS maps"],1,"Electronic Navigational Charts.","SOLAS V/19.2"),mc("AIS transmits:",["Cargo manifest","Vessel ID, position, course, speed","Crew list","Weather data"],1,"Identification and tracking.","SOLAS V/19"),mc("ECDIS backup can be:",["Nothing needed","Second ECDIS or paper charts","GPS only","Radar only"],1,"Mandatory backup.","SOLAS V/19.2"),tf("ECDIS training is required under STCW.",true,"Officers must complete type-specific training.","STCW"),mc("LRIT is for:",["Load planning","Long Range Identification and Tracking","Liferaft testing","Logistics routing"],1,"Security tracking.","SOLAS V/19.1")]),
  mod("Passage Planning","Voyage planning requirements",3,50,[
    les("Passage Planning Process","<h2>Voyage Planning</h2><p>IMO Resolution A.893(21): four stages — appraisal (gather info), planning (plot route, identify hazards), execution (monitor progress), monitoring (continuous checking). Must account for weather routing, traffic separation schemes, ECA/SECA zones, UKC (Under Keel Clearance), tidal windows.</p>",1,25,"IMO A.893(21)"),
    les("Watchkeeping Standards","<h2>Bridge Watchkeeping</h2><p>STCW Chapter II: OOW (Officer of the Watch) requirements. Maintain proper lookout. Never leave bridge unattended. Handover procedures. Call the master when in doubt. Fitness for duty requirements.</p>",2,25,"STCW Chapter II"),
  ],[mc("Passage planning stages:",["2","3","4","5"],2,"Appraisal, planning, execution, monitoring.","IMO A.893(21)"),mc("UKC stands for:",["United Kingdom Channel","Under Keel Clearance","Universal Knot Calculation","Unified Knowledge Certificate"],1,"Clearance under hull.","Navigation"),mc("ECA zones restrict:",["Speed","Emissions (SOx/NOx)","Cargo type","Crew size"],1,"Emission Control Areas.","MARPOL Annex VI"),tf("OOW may leave bridge if autopilot is engaged.",false,"Bridge must never be unattended.","STCW Chapter II"),mc("When in doubt, OOW should:",["Wait and observe","Call the master","Increase speed","Ignore the concern"],1,"Call the master.","STCW Chapter II")]),
],
"port-operations-safety": [
  mod("Terminal Safety Regulations","OSHA longshoring and terminal standards",1,50,[
    les("Longshoring Standards","<h2>OSHA Maritime Standards</h2><p>29 CFR 1917 (Marine Terminals) and 1918 (Longshoring): cover cargo handling, container operations, Ro-Ro operations, crane operations, fall protection, confined space entry. MTSA (Maritime Transportation Security Act) adds security requirements. Key hazards: falling cargo, pinch points, vehicle traffic, hazardous atmospheres.</p>",1,25,"OSHA 29 CFR 1917/1918"),
    les("Container Terminal Operations","<h2>Container Ops</h2><p>STS (Ship-to-Shore) gantry cranes, RTG (Rubber Tired Gantry), straddle carriers, AGV (Automated Guided Vehicles). Twist-lock operations, lashing/unlashing. Wind speed limits for crane operations. Traffic management systems separating pedestrians from equipment.</p>",2,25,"OSHA 29 CFR 1917"),
  ],[mc("Marine terminal safety under:",["Part 232","OSHA 29 CFR 1917","Part 218","STCW"],1,"OSHA maritime standards.","OSHA 29 CFR 1917"),mc("STS crane stands for:",["Standard Transport System","Ship-to-Shore","Safety Testing Station","Stowage Tracking"],1,"Ship-to-Shore gantry.","OSHA 29 CFR 1917"),mc("Twist-locks secure:",["Hatch covers","Containers to each other/vessel","Mooring lines","Gangways"],1,"Container connections.","General"),tf("Pedestrians and equipment share terminal lanes.",false,"Must be separated.","OSHA 29 CFR 1917"),mc("MTSA adds:",["Cargo requirements","Security requirements","Speed limits","Environmental rules"],1,"Maritime security.","MTSA")]),
  mod("Port State Control","PSC inspections and detentions",2,45,[
    les("PSC Framework","<h2>Port State Control</h2><p>Paris MOU, Tokyo MOU, US Coast Guard PSC: inspect foreign-flag vessels for compliance with SOLAS, MARPOL, STCW, MLC. Deficiency categories: detainable (ship held) vs non-detainable (correct within timeframe). CIC (Concentrated Inspection Campaigns) target specific areas annually. Targeting: high-risk vessels inspected more frequently based on ship type, age, flag, classification society performance.</p>",1,25,"IMO Resolution A.1155(32)"),
    les("Detention & Penalties","<h2>Consequences</h2><p>Detention: vessel cannot sail until deficiencies corrected. Published in PSC database (THETIS for Paris MOU, USCG database for US). Repeated detentions can lead to banning from ports. Flag state notified. Financial impact: delay costs, port fees, reputation damage.</p>",2,20,"Paris MOU, USCG"),
  ],[mc("PSC inspects for compliance with:",["Only SOLAS","SOLAS, MARPOL, STCW, MLC","National regulations only","Classification rules only"],1,"Multiple conventions.","IMO A.1155(32)"),mc("CIC stands for:",["Container Inspection Code","Concentrated Inspection Campaign","Cargo Insurance Certificate","Crew Identification Check"],1,"Annual targeted inspections.","Paris MOU"),mc("Detention means:",["Vessel fined","Vessel cannot sail until deficiencies corrected","Crew arrested","Cargo seized"],1,"Ship held.","Paris MOU"),tf("Repeated detentions can lead to port banning.",true,"Serious consequence.","Paris MOU"),mc("US PSC conducted by:",["FRA","USCG","EPA","CBP"],1,"US Coast Guard.","USCG")]),
  mod("Vessel-Port Interface","Ship/shore operations safety",3,45,[
    les("Mooring & Gangway Safety","<h2>Ship-Shore Interface</h2><p>SOLAS requirements for means of access (gangway, accommodation ladder). Mooring operations: snap-back zones, PPE requirements, communication between ship and shore. ISGOTT for tanker operations. Ship-shore safety checklist (ISGOTT Appendix). Bunkering safety: fuel transfer procedures, scupper plugs, fire equipment ready.</p>",1,25,"SOLAS, ISGOTT"),
    les("Cargo Documentation","<h2>Port Documentation</h2><p>Bill of lading, cargo manifest, dangerous goods manifest, stowage plan, stability calculations. Notice of Readiness (NOR) for charter party. ISF 10+2 for US imports. Pre-arrival notification requirements vary by port state.</p>",2,20,"Various"),
  ],[mc("Snap-back zones are near:",["Cargo holds","Mooring lines under tension","Navigation equipment","Fuel tanks"],1,"Dangerous line recoil area.","General safety"),mc("ISGOTT covers:",["Container operations","Tanker operations safety","Passenger ships","Fishing vessels"],1,"International Safety Guide for Oil Tankers and Terminals.","ISGOTT"),mc("ISF 10+2 applies to:",["All global ports","US imports","EU exports","Canadian coastal"],1,"US import security filing.","19 CFR"),tf("Scupper plugs must be in place during bunkering.",true,"Prevent fuel spills overboard.","MARPOL"),mc("NOR stands for:",["National Operational Requirement","Notice of Readiness","Navigation Operations Report","No Outstanding Repairs"],1,"Charter party notice.","Maritime law")]),
],
};}
