import { ModuleDef } from "./types";
const M = "multiple_choice" as const, T = "true_false" as const;
const mc = (q:string,a:string[],c:number,e:string,r:string) => ({questionText:q,questionType:M,options:a.map((t,i)=>({id:"abcd"[i],text:t,isCorrect:i===c})),correctAnswer:"abcd"[c],explanation:e,difficulty:"medium" as const,regulationReference:r});
const tf = (q:string,v:boolean,e:string,r:string) => ({questionText:q,questionType:T,options:[{id:"a",text:"True",isCorrect:v},{id:"b",text:"False",isCorrect:!v}],correctAnswer:v?"a":"b",explanation:e,difficulty:"easy" as const,regulationReference:r});
const les = (t:string,h:string,i:number,d:number,rc:string) => ({title:t,contentHtml:h,orderIndex:i,lessonType:"reading" as const,estimatedDurationMinutes:d,keyRegulations:[{code:rc,title:t,jurisdiction:"US",summary:t}]});
const mod = (t:string,ds:string,oi:number,dur:number,ls:any[],qs:any[]):ModuleDef => ({title:t,description:ds,orderIndex:oi,contentType:"text",estimatedDurationMinutes:dur,lessons:ls,quiz:{title:t+" Quiz",description:"Assessment: "+ds,questions:qs}});

export function getRail4(): Record<string, ModuleDef[]> { return {
"air-brakes-rail": [
  mod("Air Brake Fundamentals","How railroad air brakes work",1,55,[
    les("Automatic Air Brakes","<h2>Fail-Safe Design</h2><p>Railroad air brakes: air loss = brakes APPLY (opposite of trucks). Brake pipe ~90 psi. Service: reduce pressure = proportional application. Emergency: rapid full release = max force. No spring brakes on most RR cars — the air system itself is fail-safe. Each car has a control valve managing its brake cylinder from auxiliary reservoir.</p>",1,30,"49 CFR Part 232"),
    les("Control Valves","<h2>Car Control Valves</h2><p>Each car's control valve senses brake pipe changes, charges auxiliary reservoir, controls brake cylinder pressure, provides gradual application, release, and emergency modes. Modern ABD/ABDW valves replaced the original Westinghouse triple valve.</p>",2,25,"49 CFR Part 232"),
  ],[mc("Fail-safe because:",["Electric backup","Air loss applies brakes","Spring brakes","Computer"],1,"Air loss = apply.","49 CFR Part 232"),mc("Brake pipe pressure:",["60 psi","~90 psi","120 psi","150 psi"],1,"Standard.","49 CFR Part 232"),mc("Service application by:",["Increasing pressure","Reducing pipe pressure","Pedal","Lever per car"],1,"Reduction = apply.","49 CFR Part 232"),tf("RR freight cars have spring brakes.",false,"Most do not.","49 CFR Part 232"),mc("Emergency involves:",["Gradual reduction","Rapid full pressure release","Loco brakes only","Engine off"],1,"Max force.","49 CFR Part 232")]),
  mod("Brake Testing & EOT","Class I-III tests and EOT devices",2,55,[
    les("Four Brake Test Classes","<h2>Tests</h2><p>Class I: walk train, verify each car apply/release, check piston travel. Class IA: within 24hrs same location. Class II: from loco via EOT, no walking. Class III: cars added/removed — verify new cars' brakes.</p>",1,30,"49 CFR Part 232 Subpart E"),
    les("EOT Devices","<h2>End-of-Train</h2><p>Monitor rear brake pipe pressure, transmit to loco Head-of-Train display. Some two-way EOTs can initiate emergency from rear. Replaced the caboose. Must be armed and tested before departure.</p>",2,25,"49 CFR Part 232"),
  ],[mc("Walk-the-train test:",["Class II","Class I","Class III","Class IA"],1,"Class I = full walk.","49 CFR Part 232"),mc("Class III triggered by:",["First assembly","Cars added/removed","24 hours","Final terminal"],1,"Consist changes.","49 CFR Part 232"),mc("EOT replaced:",["Locomotive","Caboose","Hand brakes","Dynamic brakes"],1,"Caboose replacement.","49 CFR Part 232"),tf("Class II needs no walking.",true,"From loco via EOT.","49 CFR Part 232"),mc("Some EOTs can:",["Steer","Initiate emergency from rear","Add cars","Control throttle"],1,"Two-way capability.","49 CFR Part 232")]),
  mod("Dynamic Braking & Grades","Dynamic braking and grade operations",3,50,[
    les("Dynamic Braking","<h2>Dynamic Brakes</h2><p>Traction motors become generators resisting wheel rotation. 100K+ lbs retarding force per loco. Advantages: reduces shoe wear, conserves air. Less effective at low speed. NOT a substitute for emergency air brakes.</p>",1,25,"General operating rules"),
    les("Grade Operations","<h2>Grades</h2><p>Descending: dynamic primary, air supplements. Never exhaust pipe air on long grades. Stall on grade = runaway risk. Proper train handling critical for crew and public safety.</p>",2,25,"General operating rules"),
  ],[mc("Motors become:",["Compressors","Generators resisting rotation","Pumps","Amplifiers"],1,"Generator mode.","General"),mc("Least effective at:",["High speed","Low speed","Medium","All equal"],1,"Drops at low speed.","General"),mc("Descending grade primary:",["Air only","Dynamic braking","Hand brakes","Engine off"],1,"Dynamic primary.","General"),tf("Dynamic substitutes for emergency brakes.",false,"Not in emergencies.","49 CFR Part 232"),mc("Retarding force per loco:",["1K lbs","10K lbs","100K+ lbs","500 lbs"],2,"Over 100,000 lbs.","General")]),
  mod("Brake Troubleshooting","Common defects and corrections",4,45,[
    les("Common Defects","<h2>Defects</h2><p>Stuck brakes: flat spots/thermal damage. Excessive piston travel: worn shoes/maladjusted rigging. Pipe leaks: reduced effectiveness. Defective valve: improper apply/release. Cars with inoperative brakes: set out or handle per Part 232 minimum operative brake percentage.</p>",1,25,"49 CFR Part 232"),
  ],[mc("Stuck brakes cause:",["Fuel savings","Flat spots/thermal damage","Better stopping","Nothing"],1,"Wheel damage.","49 CFR Part 232"),mc("Excessive piston travel:",["New shoes","Worn shoes/maladjusted","Over-pressure","Good"],1,"Wear indicator.","49 CFR Part 232"),mc("Inoperative brake cars:",["No restriction","Set out per Part 232","Head of train","Tow separately"],1,"Part 232 rules.","49 CFR Part 232"),tf("Pipe leaks have no effect.",false,"Reduces effectiveness.","49 CFR Part 232"),mc("Part 232 requires min:",["Operative brake %","New shoes","Dynamic locos","Hand brakes/car"],0,"Minimum %.","49 CFR Part 232")]),
],
"rail-hours-of-service": [
  mod("Train Employee HOS","12-hour rule and rest requirements",1,50,[
    les("The 12-Hour Rule","<h2>Train HOS</h2><p>49 CFR Part 228: max 12 consecutive hrs on duty. Then 10 hrs undisturbed rest. DIFFERS FROM TRUCKING: truck = 11 drive + 14 window; rail = 12 TOTAL, no split. No 34-hr restart. Monthly: 276 hrs max.</p>",1,25,"49 CFR Part 228"),
    les("Limbo Time","<h2>Limbo Time</h2><p>Unique to rail: time waiting for transportation after duty release. NOT on-duty, NOT rest. Can't begin 10-hr rest until reaching designated terminal. No trucking equivalent. Reform was part of RSIA 2008.</p>",2,25,"49 USC §21103"),
  ],[mc("Max on-duty train employees:",["10 hrs","12 hrs","14 hrs","11 hrs"],1,"12 total.","49 CFR Part 228"),mc("Required rest after 12:",["8 hrs","10 hrs","12 hrs","6 hrs"],1,"10 consecutive.","49 CFR Part 228"),mc("Monthly limit:",["240","276","300","No limit"],1,"276 hrs/month.","49 CFR Part 228"),tf("Rail has 34-hr restart like trucking.",false,"No restart.","49 CFR Part 228"),mc("Limbo time is:",["Driving","Wait for transport after release","Break","Overtime"],1,"Unique rail concept.","49 USC §21103")]),
  mod("Dispatcher & Signal HOS","HOS for other employee categories",2,45,[
    les("Dispatcher HOS","<h2>Dispatchers</h2><p>Part 228 Subpart B: 9 hrs max (2-shift locations) or 12 hrs (fewer shifts). Min 8 hrs off between shifts. Different from train crew absolute 12-hr limit.</p>",1,20,"49 CFR Part 228 Subpart B"),
    les("Signal Employee HOS","<h2>Signal Employees</h2><p>12 hrs max, 10 hrs rest — similar to train employees but with some emergency exceptions for threats to life/property.</p>",2,25,"49 CFR Part 228"),
  ],[mc("Dispatcher max (2 shifts):",["8 hrs","9 hrs","12 hrs","14 hrs"],1,"9 hours.","49 CFR Part 228 Subpart B"),mc("Min off between dispatcher shifts:",["6","8","10","12"],1,"8 consecutive.","49 CFR Part 228"),tf("Signal HOS identical to train.",false,"Similar but exceptions.","49 CFR Part 228"),mc("Dispatcher HOS varies by:",["Traffic","Shifts at location","Weather","Day"],1,"Staffing determines.","49 CFR Part 228 Subpart B"),mc("Signal max on-duty:",["10","12","14","No limit"],1,"12 hours.","49 CFR Part 228")]),
  mod("Fatigue & Enforcement","Fatigue management and penalties",3,45,[
    les("Fatigue Management","<h2>Fatigue</h2><p>Part 228 Subpart F: fatigue plans required. Circadian disruption, sleep debt, time-on-task. NTSB: fatigue factor in many rail accidents. Electronic recordkeeping replacing manual logs.</p>",1,25,"49 CFR Part 228 Subpart F"),
    les("Enforcement","<h2>Penalties</h2><p>FRA enforces via inspections/audits. Up to $27K/violation. Criminal penalties for willful violations. Federal whistleblower protections for reporters.</p>",2,20,"49 CFR Part 228"),
  ],[mc("NTSB on fatigue:",["Rarely factor","Factor in many accidents","Trucking only","Not relevant"],1,"Major factor.","NTSB"),tf("Fatigue plans required.",true,"Part 228 Subpart F.","49 CFR Part 228 Subpart F"),mc("Max penalty:",["$5K","$27K","$100K","$1K"],1,"$27,000/violation.","49 CFR Part 228"),tf("Whistleblower protections exist.",true,"Federal.","49 CFR Part 228"),mc("Enforced by:",["OSHA","FRA","TSA","State DOTs"],1,"FRA enforces.","49 CFR Part 228")]),
],
};}
