import { ModuleDef } from "./types";

export function getRailCoursesPart2(): Record<string, ModuleDef[]> {
  return {
    "conductor-certification": [
      {
        title: "Conductor Role and Responsibilities", description: "Core duties under 49 CFR Part 242", orderIndex: 1, contentType: "text", estimatedDurationMinutes: 50,
        lessons: [
          { title: "Conductor Authority and Duties", contentHtml: "<h2>The Conductor's Authority</h2><p>Under 49 CFR Part 242, the conductor is responsible for the safe movement and operation of the train. Key duties include:</p><ul><li>Ensuring proper train makeup and securement</li><li>Communicating with dispatchers for movement authority</li><li>Verifying air brake tests</li><li>Managing switching operations</li><li>Overseeing hazmat documentation and placarding</li></ul><p>Unlike trucking where one driver handles everything, rail uses a two-person crew model where conductor and engineer share safety responsibilities.</p>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 242", title: "Qualification and Certification of Conductors", jurisdiction: "US", summary: "Federal standards for conductor qualification and certification." }] },
          { title: "Certification Requirements", contentHtml: "<h2>Certification Standards</h2><p>Conductors must meet: vision/hearing standards (§242.117), pass knowledge examination (§242.119), pass skills performance test (§242.121), and be recertified every 36 months. Certification can be revoked for signal compliance failures, unauthorized movements, and switching violations.</p>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR §242.119", title: "Conductor knowledge examination", jurisdiction: "US", summary: "Knowledge requirements for conductor certification." }] },
        ],
        quiz: {
          title: "Conductor Role Quiz", description: "Test conductor duties and certification knowledge",
          questions: [
            { questionText: "The conductor has authority over crew members regarding:", questionType: "multiple_choice", options: [{ id: "a", text: "Pay and scheduling", isCorrect: false }, { id: "b", text: "Train movements", isCorrect: true }, { id: "c", text: "Equipment maintenance", isCorrect: false }, { id: "d", text: "Track inspection", isCorrect: false }], correctAnswer: "b", explanation: "The conductor has authority over all crew members with respect to train movements.", difficulty: "easy", regulationReference: "49 CFR Part 242" },
            { questionText: "Conductor recertification is required every:", questionType: "multiple_choice", options: [{ id: "a", text: "12 months", isCorrect: false }, { id: "b", text: "24 months", isCorrect: false }, { id: "c", text: "36 months", isCorrect: true }, { id: "d", text: "48 months", isCorrect: false }], correctAnswer: "c", explanation: "Part 242 requires recertification every 36 months.", difficulty: "easy", regulationReference: "49 CFR Part 242" },
            { questionText: "True or False: Conductors have different vision standards than engineers.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "Vision thresholds are the same for conductors (§242.117) and engineers (§240.121).", difficulty: "medium", regulationReference: "49 CFR §242.117" },
            { questionText: "Which is NOT a core conductor duty?", questionType: "multiple_choice", options: [{ id: "a", text: "Managing switching operations", isCorrect: false }, { id: "b", text: "Operating the locomotive throttle", isCorrect: true }, { id: "c", text: "Verifying air brake tests", isCorrect: false }, { id: "d", text: "Overseeing hazmat documentation", isCorrect: false }], correctAnswer: "b", explanation: "Operating the throttle is the engineer's duty.", difficulty: "easy", regulationReference: "49 CFR Part 242" },
            { questionText: "The conductor certification rule is in:", questionType: "multiple_choice", options: [{ id: "a", text: "49 CFR Part 240", isCorrect: false }, { id: "b", text: "49 CFR Part 242", isCorrect: true }, { id: "c", text: "49 CFR Part 232", isCorrect: false }, { id: "d", text: "49 CFR Part 228", isCorrect: false }], correctAnswer: "b", explanation: "Part 242 governs conductor certification; Part 240 is for engineers.", difficulty: "easy", regulationReference: "49 CFR Part 242" },
          ],
        },
      },
      {
        title: "Switching Operations Safety", description: "Safe switching practices and blue signal protection", orderIndex: 2, contentType: "text", estimatedDurationMinutes: 50,
        lessons: [
          { title: "Switching Procedures", contentHtml: "<h2>Safe Switching Practices</h2><p>Switching is one of the most hazardous railroad activities. 49 CFR Part 218 governs blue signal protection and safe clearance. Key requirements:</p><ul><li>Point protection — conductor must know location of all crew members</li><li>Shoving movements must be protected by a crew member at the leading end</li><li>Blue flag/light protection when workers are on, under, or between equipment</li></ul>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 218", title: "Railroad Operating Practices", jurisdiction: "US", summary: "Safety requirements for switching operations and blue signal protection." }] },
          { title: "Equipment Securement", contentHtml: "<h2>Securement Requirements</h2><p>After the Lac-Mégantic disaster (2013), securement rules were significantly strengthened under 49 CFR Part 232:</p><ul><li>Minimum hand brakes based on tonnage and grade</li><li>Securement testing (checking for roll-back)</li><li>Unattended train securement procedures</li><li>Communication of securement status between crews</li></ul>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 232", title: "Securement of equipment", jurisdiction: "US", summary: "Requirements for securing unattended rolling stock." }] },
        ],
        quiz: {
          title: "Switching Safety Quiz", description: "Test switching safety knowledge",
          questions: [
            { questionText: "Blue signal protection is required when workers are:", questionType: "multiple_choice", options: [{ id: "a", text: "In the dispatcher's office", isCorrect: false }, { id: "b", text: "On, under, or between equipment", isCorrect: true }, { id: "c", text: "In the locomotive cab", isCorrect: false }, { id: "d", text: "On the station platform", isCorrect: false }], correctAnswer: "b", explanation: "Blue flags/lights protect workers on, under, or between equipment per Part 218.", difficulty: "easy", regulationReference: "49 CFR Part 218" },
            { questionText: "Shoving movements must be protected by:", questionType: "multiple_choice", options: [{ id: "a", text: "PTC automatically", isCorrect: false }, { id: "b", text: "A crew member at the leading end", isCorrect: true }, { id: "c", text: "Dispatcher authorization alone", isCorrect: false }, { id: "d", text: "A derail device", isCorrect: false }], correctAnswer: "b", explanation: "A crew member must protect the leading end of shoving movements.", difficulty: "medium", regulationReference: "49 CFR Part 218" },
            { questionText: "The Lac-Mégantic disaster was primarily caused by:", questionType: "multiple_choice", options: [{ id: "a", text: "Signal failure", isCorrect: false }, { id: "b", text: "Inadequate equipment securement", isCorrect: true }, { id: "c", text: "Track defect", isCorrect: false }, { id: "d", text: "Dispatcher error", isCorrect: false }], correctAnswer: "b", explanation: "Caused by inadequate securement of an unattended train carrying crude oil.", difficulty: "medium", regulationReference: "49 CFR Part 232" },
            { questionText: "True or False: Hand brakes are the primary securement method.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: true }, { id: "b", text: "False", isCorrect: false }], correctAnswer: "a", explanation: "Hand brakes are primary; air brakes can leak off over time.", difficulty: "easy", regulationReference: "49 CFR Part 232" },
            { questionText: "Point protection means the conductor must:", questionType: "multiple_choice", options: [{ id: "a", text: "Stand at the switch point", isCorrect: false }, { id: "b", text: "Know the location of all crew members", isCorrect: true }, { id: "c", text: "Protect every grade crossing", isCorrect: false }, { id: "d", text: "Operate the locomotive", isCorrect: false }], correctAnswer: "b", explanation: "Point protection requires accounting for all crew member locations during switching.", difficulty: "medium", regulationReference: "49 CFR Part 218" },
          ],
        },
      },
      {
        title: "Air Brake Responsibilities", description: "Conductor's air brake duties", orderIndex: 3, contentType: "text", estimatedDurationMinutes: 50,
        lessons: [
          { title: "Air Brake Test Procedures", contentHtml: "<h2>Conductor's Role in Air Brake Testing</h2><p>Per 49 CFR Part 232:</p><ul><li><strong>Class I test</strong>: Train first assembled — conductor verifies each car's brakes apply and release</li><li><strong>Class IA test</strong>: When Class I was performed within 24 hours at same location</li><li><strong>Class II test</strong>: From locomotive; conductor verifies rear brake pipe pressure via EOT</li><li><strong>Class III test</strong>: Cars added/removed; conductor verifies new cars' brakes</li></ul>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 232", title: "Brake System Safety Standards", jurisdiction: "US", summary: "Air brake test requirements for freight trains." }] },
          { title: "Emergency Procedures", contentHtml: "<h2>Emergency Response Duties</h2><p>In an emergency, the conductor must: ensure protection of the train (flagging), report to dispatcher, account for all crew members, consult shipping papers and ERG if hazmat is involved, establish exclusion zones, and coordinate with first responders.</p>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 232", title: "Emergency brake procedures", jurisdiction: "US", summary: "Emergency braking and response procedures." }] },
        ],
        quiz: {
          title: "Air Brake Quiz", description: "Test air brake knowledge for conductors",
          questions: [
            { questionText: "A Class I brake test requires the conductor to:", questionType: "multiple_choice", options: [{ id: "a", text: "Only check the EOT reading", isCorrect: false }, { id: "b", text: "Verify each car's brakes apply and release", isCorrect: true }, { id: "c", text: "Only verify locomotive brakes", isCorrect: false }, { id: "d", text: "Check brake shoes visually only", isCorrect: false }], correctAnswer: "b", explanation: "Class I requires verification of each car's brakes.", difficulty: "medium", regulationReference: "49 CFR Part 232" },
            { questionText: "A Class III brake test is performed when:", questionType: "multiple_choice", options: [{ id: "a", text: "Train is first assembled", isCorrect: false }, { id: "b", text: "Cars are added or removed", isCorrect: true }, { id: "c", text: "Train crosses a state line", isCorrect: false }, { id: "d", text: "Engineer changes", isCorrect: false }], correctAnswer: "b", explanation: "Class III test is required when cars are added/removed from the train.", difficulty: "medium", regulationReference: "49 CFR Part 232" },
            { questionText: "In a hazmat emergency, the conductor should consult:", questionType: "multiple_choice", options: [{ id: "a", text: "The locomotive manual", isCorrect: false }, { id: "b", text: "Shipping papers and ERG", isCorrect: true }, { id: "c", text: "The train schedule", isCorrect: false }, { id: "d", text: "The track warrant", isCorrect: false }], correctAnswer: "b", explanation: "Shipping papers and ERG provide hazmat emergency response information.", difficulty: "easy", regulationReference: "49 CFR §172.600-604" },
            { questionText: "True or False: The conductor has no role in air brake testing.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "The conductor plays a critical role in all classes of air brake tests.", difficulty: "easy", regulationReference: "49 CFR Part 232" },
            { questionText: "Train protection (flagging) after an accident is the responsibility of:", questionType: "multiple_choice", options: [{ id: "a", text: "The dispatcher only", isCorrect: false }, { id: "b", text: "The conductor and crew", isCorrect: true }, { id: "c", text: "Local police only", isCorrect: false }, { id: "d", text: "The FRA", isCorrect: false }], correctAnswer: "b", explanation: "The conductor must ensure proper train protection after an accident.", difficulty: "easy", regulationReference: "49 CFR Part 218" },
          ],
        },
      },
      {
        title: "Hazmat and Radio Communication", description: "Conductor hazmat duties and FRA radio rules", orderIndex: 4, contentType: "text", estimatedDurationMinutes: 45,
        lessons: [
          { title: "Shipping Paper Verification", contentHtml: "<h2>Hazmat Shipping Papers</h2><p>The conductor must verify shipping papers per 49 CFR §172.202: proper shipping name, hazard class, UN/NA number, packing group, total quantity, and 24-hour emergency contact. The conductor must keep papers accessible and know hazmat car positions in the consist.</p>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "49 CFR §172.202", title: "Shipping paper requirements", jurisdiction: "US", summary: "Required information on hazmat shipping papers." }] },
          { title: "Radio Communication Rules", contentHtml: "<h2>FRA Radio Communication</h2><p>49 CFR Part 220 governs radio communication. Key rules:</p><ul><li>Standard phraseology for train movements</li><li>Repeat back mandatory directives (track warrants, Form D)</li><li>Personal electronic device prohibition (§220.313) — violations up to $27,000</li></ul>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 220", title: "Railroad Communications", jurisdiction: "US", summary: "Radio communication requirements for railroad operations." }] },
        ],
        quiz: {
          title: "Hazmat & Radio Quiz", description: "Test hazmat and radio knowledge",
          questions: [
            { questionText: "Shipping papers must include a 24-hour:", questionType: "multiple_choice", options: [{ id: "a", text: "GPS tracking number", isCorrect: false }, { id: "b", text: "Emergency contact number", isCorrect: true }, { id: "c", text: "Insurance policy number", isCorrect: false }, { id: "d", text: "Crew manifest", isCorrect: false }], correctAnswer: "b", explanation: "24-hour emergency response phone number required per §172.604.", difficulty: "easy", regulationReference: "49 CFR §172.604" },
            { questionText: "Mandatory directives received by radio must be:", questionType: "multiple_choice", options: [{ id: "a", text: "Acknowledged with a single click", isCorrect: false }, { id: "b", text: "Repeated back", isCorrect: true }, { id: "c", text: "Written down only", isCorrect: false }, { id: "d", text: "Forwarded to next crew", isCorrect: false }], correctAnswer: "b", explanation: "Mandatory directives must be repeated back for accuracy.", difficulty: "easy", regulationReference: "49 CFR Part 220" },
            { questionText: "Personal cell phone use by operating crew is:", questionType: "multiple_choice", options: [{ id: "a", text: "Allowed during station stops", isCorrect: false }, { id: "b", text: "Prohibited while on duty", isCorrect: true }, { id: "c", text: "Allowed if hands-free", isCorrect: false }, { id: "d", text: "At engineer's discretion", isCorrect: false }], correctAnswer: "b", explanation: "§220.313 prohibits personal electronic device use while on duty.", difficulty: "easy", regulationReference: "49 CFR §220.313" },
            { questionText: "True or False: The conductor must know hazmat car positions in the consist.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: true }, { id: "b", text: "False", isCorrect: false }], correctAnswer: "a", explanation: "The conductor must know hazmat car positions for emergency response.", difficulty: "easy", regulationReference: "49 CFR Part 174" },
            { questionText: "Maximum civil penalty per electronic device violation:", questionType: "multiple_choice", options: [{ id: "a", text: "$5,000", isCorrect: false }, { id: "b", text: "$16,000", isCorrect: false }, { id: "c", text: "$27,000", isCorrect: true }, { id: "d", text: "$50,000", isCorrect: false }], correctAnswer: "c", explanation: "Penalties for electronic device violations can reach $27,000 per violation.", difficulty: "hard", regulationReference: "49 CFR §220.313" },
          ],
        },
      },
      {
        title: "Passenger Train Conductor Duties", description: "Additional duties for passenger service", orderIndex: 5, contentType: "text", estimatedDurationMinutes: 40,
        lessons: [
          { title: "Passenger Safety Responsibilities", contentHtml: "<h2>Passenger Service Differences</h2><p>Passenger train conductors have additional responsibilities beyond freight operations:</p><ul><li>Passenger safety briefings and announcements</li><li>Door operation and station stop management</li><li>ADA compliance for passengers with disabilities</li><li>Emergency evacuation procedures specific to passenger equipment</li><li>Coordination with on-board service crew</li></ul>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "49 CFR Part 239", title: "Passenger Train Emergency Preparedness", jurisdiction: "US", summary: "Emergency preparedness requirements for passenger trains." }] },
        ],
        quiz: {
          title: "Passenger Conductor Quiz", description: "Test passenger service knowledge",
          questions: [
            { questionText: "Passenger conductors must manage:", questionType: "multiple_choice", options: [{ id: "a", text: "Car loading only", isCorrect: false }, { id: "b", text: "Door operation and station stops", isCorrect: true }, { id: "c", text: "Locomotive maintenance", isCorrect: false }, { id: "d", text: "Track inspection", isCorrect: false }], correctAnswer: "b", explanation: "Passenger conductors manage door operation and station stop procedures.", difficulty: "easy", regulationReference: "49 CFR Part 239" },
            { questionText: "ADA compliance is the responsibility of:", questionType: "multiple_choice", options: [{ id: "a", text: "The engineer only", isCorrect: false }, { id: "b", text: "The conductor", isCorrect: true }, { id: "c", text: "Station personnel only", isCorrect: false }, { id: "d", text: "The dispatcher", isCorrect: false }], correctAnswer: "b", explanation: "The conductor ensures ADA compliance for passengers with disabilities.", difficulty: "easy", regulationReference: "ADA, 49 CFR Part 239" },
            { questionText: "Emergency evacuation of passenger trains is governed by:", questionType: "multiple_choice", options: [{ id: "a", text: "49 CFR Part 232", isCorrect: false }, { id: "b", text: "49 CFR Part 239", isCorrect: true }, { id: "c", text: "49 CFR Part 228", isCorrect: false }, { id: "d", text: "49 CFR Part 213", isCorrect: false }], correctAnswer: "b", explanation: "Part 239 governs passenger train emergency preparedness.", difficulty: "medium", regulationReference: "49 CFR Part 239" },
            { questionText: "True or False: Freight and passenger conductor duties are identical.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "Passenger conductors have additional duties including door ops, safety briefings, and ADA compliance.", difficulty: "easy", regulationReference: "49 CFR Part 242" },
            { questionText: "On-board service crew coordination is:", questionType: "multiple_choice", options: [{ id: "a", text: "Not the conductor's concern", isCorrect: false }, { id: "b", text: "A conductor responsibility on passenger trains", isCorrect: true }, { id: "c", text: "The engineer's duty", isCorrect: false }, { id: "d", text: "Automated by PTC", isCorrect: false }], correctAnswer: "b", explanation: "The conductor coordinates with on-board service crew on passenger trains.", difficulty: "easy", regulationReference: "49 CFR Part 239" },
          ],
        },
      },
    ],

    "rail-hazmat-transport": [
      {
        title: "Rail Hazmat Classification", description: "DOT hazmat classification for rail", orderIndex: 1, contentType: "text", estimatedDurationMinutes: 45,
        lessons: [
          { title: "9 Hazard Classes", contentHtml: "<h2>DOT Hazard Classification</h2><p>49 CFR Parts 171-180 establish the 9 hazard classes: 1-Explosives, 2-Gases, 3-Flammable Liquids, 4-Flammable Solids, 5-Oxidizers, 6-Toxic, 7-Radioactive, 8-Corrosive, 9-Miscellaneous. Rail transport of PIH (poison-by-inhalation) like chlorine requires speed restrictions and key train provisions.</p>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Parts 171-180", title: "Hazardous Materials Regulations", jurisdiction: "US", summary: "Hazmat classification, packaging, placarding, and transport." }] },
          { title: "Rail-Specific Hazmat Rules", contentHtml: "<h2>Rail-Specific Requirements</h2><p>49 CFR Part 174 adds rail-specific rules:</p><ul><li><strong>Key trains/routes</strong>: Enhanced safety for certain hazmat quantities</li><li><strong>HHFT</strong>: Trains with 20+ tank cars of Class 3 flammable liquids — 50 mph max, 40 in urban areas</li><li><strong>DOT-117 tank cars</strong>: Required for crude oil and ethanol</li></ul>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "49 CFR Part 174", title: "Carriage by Rail", jurisdiction: "US", summary: "Rail-specific hazmat transport requirements." }] },
        ],
        quiz: {
          title: "Rail Hazmat Quiz", description: "Test rail hazmat classification knowledge",
          questions: [
            { questionText: "PIH materials in rail require:", questionType: "multiple_choice", options: [{ id: "a", text: "No special requirements", isCorrect: false }, { id: "b", text: "Speed restrictions and key train provisions", isCorrect: true }, { id: "c", text: "Only standard placarding", isCorrect: false }, { id: "d", text: "Escort vehicles only", isCorrect: false }], correctAnswer: "b", explanation: "PIH requires enhanced safety including speed restrictions.", difficulty: "medium", regulationReference: "49 CFR Part 174" },
            { questionText: "HHFT stands for:", questionType: "multiple_choice", options: [{ id: "a", text: "Heavy Haul Freight Train", isCorrect: false }, { id: "b", text: "High-Hazard Flammable Train", isCorrect: true }, { id: "c", text: "Hazmat Handling Fire Training", isCorrect: false }, { id: "d", text: "Highway-to-Highway Freight Transfer", isCorrect: false }], correctAnswer: "b", explanation: "HHFT = High-Hazard Flammable Train (20+ loaded tank cars of Class 3).", difficulty: "medium", regulationReference: "49 CFR Part 174" },
            { questionText: "Maximum HHFT speed:", questionType: "multiple_choice", options: [{ id: "a", text: "40 mph", isCorrect: false }, { id: "b", text: "50 mph", isCorrect: true }, { id: "c", text: "60 mph", isCorrect: false }, { id: "d", text: "70 mph", isCorrect: false }], correctAnswer: "b", explanation: "50 mph max, 40 mph in certain urban areas.", difficulty: "medium", regulationReference: "49 CFR Part 174" },
            { questionText: "DOT-117 cars are required for:", questionType: "multiple_choice", options: [{ id: "a", text: "All liquids", isCorrect: false }, { id: "b", text: "Crude oil and ethanol by rail", isCorrect: true }, { id: "c", text: "Radioactive materials only", isCorrect: false }, { id: "d", text: "All compressed gases", isCorrect: false }], correctAnswer: "b", explanation: "DOT-117 specification required for crude oil and ethanol rail transport.", difficulty: "hard", regulationReference: "49 CFR Part 179" },
            { questionText: "True or False: There are only 8 DOT hazard classes.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "There are 9 DOT hazard classes (1-9).", difficulty: "easy", regulationReference: "49 CFR Parts 171-180" },
          ],
        },
      },
      {
        title: "Hazmat Emergency Response", description: "Emergency procedures for rail hazmat incidents", orderIndex: 2, contentType: "text", estimatedDurationMinutes: 45,
        lessons: [
          { title: "Rail Hazmat Incident Response", contentHtml: "<h2>Emergency Response</h2><p>A single tank car holds 20,000-34,000 gallons vs ~9,000 for highway tankers. Response: stop train, protect against other movements, use shipping papers to identify materials, consult ERG, establish exclusion zones, contact CHEMTREC (1-800-424-9300) and NRC (1-800-424-8802).</p>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR §172.600-604", title: "Emergency Response Information", jurisdiction: "US", summary: "Hazmat emergency response information requirements." }] },
          { title: "Cross-Border Hazmat", contentHtml: "<h2>North American Hazmat</h2><p>US: 49 CFR 171-180; Canada: TDG Regulations; Mexico: NOM standards. The ERG is jointly published by all three countries. Cross-border shipping papers must be bilingual.</p>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "49 CFR Part 171", title: "Cross-border hazmat", jurisdiction: "US/CA/MX", summary: "Harmonized regulations for cross-border transport." }] },
        ],
        quiz: {
          title: "Hazmat Emergency Quiz", description: "Test hazmat emergency response",
          questions: [
            { questionText: "CHEMTREC's number is:", questionType: "multiple_choice", options: [{ id: "a", text: "1-800-424-8802", isCorrect: false }, { id: "b", text: "1-800-424-9300", isCorrect: true }, { id: "c", text: "911", isCorrect: false }, { id: "d", text: "1-800-535-0202", isCorrect: false }], correctAnswer: "b", explanation: "CHEMTREC: 1-800-424-9300.", difficulty: "medium", regulationReference: "Industry standard" },
            { questionText: "A single tank car can hold up to:", questionType: "multiple_choice", options: [{ id: "a", text: "9,000 gallons", isCorrect: false }, { id: "b", text: "15,000 gallons", isCorrect: false }, { id: "c", text: "34,000 gallons", isCorrect: true }, { id: "d", text: "50,000 gallons", isCorrect: false }], correctAnswer: "c", explanation: "Rail tank cars hold 20,000-34,000 gallons.", difficulty: "medium", regulationReference: "General railroad knowledge" },
            { questionText: "The ERG is published by:", questionType: "multiple_choice", options: [{ id: "a", text: "US only", isCorrect: false }, { id: "b", text: "US, Canada, and Mexico", isCorrect: true }, { id: "c", text: "United Nations", isCorrect: false }, { id: "d", text: "CHEMTREC", isCorrect: false }], correctAnswer: "b", explanation: "ERG is jointly published by DOT, Transport Canada, and SCT (Mexico).", difficulty: "easy", regulationReference: "ERG" },
            { questionText: "Canada's hazmat regulations are:", questionType: "multiple_choice", options: [{ id: "a", text: "DOT regulations", isCorrect: false }, { id: "b", text: "TDG regulations", isCorrect: true }, { id: "c", text: "IMDG Code", isCorrect: false }, { id: "d", text: "NOM standards", isCorrect: false }], correctAnswer: "b", explanation: "Canada uses Transportation of Dangerous Goods (TDG) Regulations.", difficulty: "easy", regulationReference: "TDG Act" },
            { questionText: "True or False: Cross-border shipping papers need only be in English.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "Must be in English AND the destination country's language.", difficulty: "easy", regulationReference: "49 CFR Part 171" },
          ],
        },
      },
      {
        title: "Placarding and Security", description: "Rail car placarding and hazmat security plans", orderIndex: 3, contentType: "text", estimatedDurationMinutes: 45,
        lessons: [
          { title: "Rail Car Placarding", contentHtml: "<h2>Placarding Requirements</h2><p>49 CFR Part 172 Subpart F: tank cars need 4 placards (both sides + both ends), residue placards on empty tank cars, PIH materials get additional POISON INHALATION HAZARD placards, fumigation placards on fumigated boxcars.</p>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "49 CFR Part 172 Subpart F", title: "Placarding", jurisdiction: "US", summary: "Hazmat placarding requirements." }] },
          { title: "Hazmat Security Plans", contentHtml: "<h2>Security Requirements</h2><p>49 CFR Part 172 Subpart I requires security plans addressing personnel security, unauthorized access, and en route security. Enhanced plans reviewed by TSA for PIH, select agents, and high-quantity explosives/radioactive materials.</p>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "49 CFR Part 172 Subpart I", title: "Safety and Security Plans", jurisdiction: "US", summary: "Hazmat security plan requirements." }] },
        ],
        quiz: {
          title: "Placarding & Security Quiz", description: "Test placarding and security knowledge",
          questions: [
            { questionText: "Tank cars require minimum:", questionType: "multiple_choice", options: [{ id: "a", text: "2 placards", isCorrect: false }, { id: "b", text: "4 placards", isCorrect: true }, { id: "c", text: "6 placards", isCorrect: false }, { id: "d", text: "1 placard", isCorrect: false }], correctAnswer: "b", explanation: "Both sides AND both ends = 4 minimum.", difficulty: "easy", regulationReference: "49 CFR Part 172 Subpart F" },
            { questionText: "Empty tank cars that contained hazmat require:", questionType: "multiple_choice", options: [{ id: "a", text: "No placards", isCorrect: false }, { id: "b", text: "EMPTY placards", isCorrect: false }, { id: "c", text: "Residue placards", isCorrect: true }, { id: "d", text: "Only end placards", isCorrect: false }], correctAnswer: "c", explanation: "Residue placards required even when empty.", difficulty: "medium", regulationReference: "49 CFR Part 172 Subpart F" },
            { questionText: "Enhanced security plans are reviewed by:", questionType: "multiple_choice", options: [{ id: "a", text: "FRA", isCorrect: false }, { id: "b", text: "TSA", isCorrect: true }, { id: "c", text: "OSHA", isCorrect: false }, { id: "d", text: "EPA", isCorrect: false }], correctAnswer: "b", explanation: "TSA reviews enhanced security plans for high-risk hazmat.", difficulty: "medium", regulationReference: "49 CFR Part 172 Subpart I" },
            { questionText: "True or False: All hazmat shipments require a security plan.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "Only certain quantities/types require security plans per Subpart I.", difficulty: "medium", regulationReference: "49 CFR Part 172 Subpart I" },
            { questionText: "PIH materials require which additional placard?", questionType: "multiple_choice", options: [{ id: "a", text: "DANGEROUS", isCorrect: false }, { id: "b", text: "POISON INHALATION HAZARD", isCorrect: true }, { id: "c", text: "OXIDIZER", isCorrect: false }, { id: "d", text: "FLAMMABLE", isCorrect: false }], correctAnswer: "b", explanation: "PIH gets POISON INHALATION HAZARD placard in addition to hazard class placard.", difficulty: "medium", regulationReference: "49 CFR Part 172 Subpart F" },
          ],
        },
      },
      {
        title: "Hazmat Incident Reporting", description: "Reporting requirements for rail hazmat incidents", orderIndex: 4, contentType: "text", estimatedDurationMinutes: 40,
        lessons: [
          { title: "Reporting Obligations", contentHtml: "<h2>Hazmat Incident Reporting</h2><p>Multiple reporting requirements apply:</p><ul><li><strong>Immediate phone report to NRC</strong> (1-800-424-8802): Any release of reportable quantity</li><li><strong>Written report (DOT Form 5800.1)</strong>: Within 30 days for releases, deaths, hospitalizations, damage >$50,000, or evacuations</li><li><strong>FRA report</strong>: Separate under 49 CFR Part 225</li></ul>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "49 CFR §171.15-16", title: "Hazmat incident reporting", jurisdiction: "US", summary: "Immediate and written reporting requirements." }] },
        ],
        quiz: {
          title: "Hazmat Reporting Quiz", description: "Test reporting knowledge",
          questions: [
            { questionText: "NRC number is:", questionType: "multiple_choice", options: [{ id: "a", text: "1-800-424-9300", isCorrect: false }, { id: "b", text: "1-800-424-8802", isCorrect: true }, { id: "c", text: "1-800-535-0202", isCorrect: false }, { id: "d", text: "911", isCorrect: false }], correctAnswer: "b", explanation: "NRC: 1-800-424-8802.", difficulty: "medium", regulationReference: "49 CFR §171.15" },
            { questionText: "Written reports are due within:", questionType: "multiple_choice", options: [{ id: "a", text: "7 days", isCorrect: false }, { id: "b", text: "15 days", isCorrect: false }, { id: "c", text: "30 days", isCorrect: true }, { id: "d", text: "60 days", isCorrect: false }], correctAnswer: "c", explanation: "DOT Form 5800.1 due within 30 days.", difficulty: "easy", regulationReference: "49 CFR §171.16" },
            { questionText: "Written reports are required for property damage over:", questionType: "multiple_choice", options: [{ id: "a", text: "$10,000", isCorrect: false }, { id: "b", text: "$25,000", isCorrect: false }, { id: "c", text: "$50,000", isCorrect: true }, { id: "d", text: "$100,000", isCorrect: false }], correctAnswer: "c", explanation: "Written reports required when property damage exceeds $50,000.", difficulty: "medium", regulationReference: "49 CFR §171.16" },
            { questionText: "True or False: FRA and hazmat reports are the same form.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "FRA accident reports (Part 225) and hazmat reports (§171.16) are separate.", difficulty: "medium", regulationReference: "49 CFR §171.15-16" },
            { questionText: "Immediate phone report to NRC is required for:", questionType: "multiple_choice", options: [{ id: "a", text: "Any hazmat shipment", isCorrect: false }, { id: "b", text: "Any release of a reportable quantity", isCorrect: true }, { id: "c", text: "Overdue deliveries", isCorrect: false }, { id: "d", text: "Placard discrepancies only", isCorrect: false }], correctAnswer: "b", explanation: "Immediate NRC notification required for releases of reportable quantities.", difficulty: "easy", regulationReference: "49 CFR §171.15" },
          ],
        },
      },
      {
        title: "IMDG vs DOT Comparison", description: "Comparing rail hazmat with maritime IMDG requirements", orderIndex: 5, contentType: "text", estimatedDurationMinutes: 40,
        lessons: [
          { title: "Rail vs Maritime Hazmat", contentHtml: "<h2>Key Differences</h2><p>While DOT and IMDG use the same 9 UN hazard classes, maritime has unique requirements:</p><ul><li>Marine Pollutant marking (required in maritime, not in trucking/rail)</li><li>EmS (Emergency Schedules) replace ERG in maritime</li><li>Container packing certificates required for maritime</li><li>IMDG Code supplements (with medical first aid guide) required aboard vessels</li></ul><p>For intermodal containers moving rail-to-vessel, both DOT AND IMDG requirements must be met.</p>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "IMDG Code", title: "International Maritime Dangerous Goods Code", jurisdiction: "International", summary: "Maritime hazmat transport standards." }] },
        ],
        quiz: {
          title: "Rail vs Maritime Hazmat Quiz", description: "Compare rail and maritime hazmat",
          questions: [
            { questionText: "Marine Pollutant marking is required in:", questionType: "multiple_choice", options: [{ id: "a", text: "Rail only", isCorrect: false }, { id: "b", text: "Maritime shipping", isCorrect: true }, { id: "c", text: "Trucking only", isCorrect: false }, { id: "d", text: "Air transport only", isCorrect: false }], correctAnswer: "b", explanation: "Marine Pollutant marking is a maritime-specific requirement.", difficulty: "medium", regulationReference: "IMDG Code" },
            { questionText: "EmS replaces ERG in:", questionType: "multiple_choice", options: [{ id: "a", text: "Rail transport", isCorrect: false }, { id: "b", text: "Maritime transport", isCorrect: true }, { id: "c", text: "Air transport", isCorrect: false }, { id: "d", text: "Pipeline transport", isCorrect: false }], correctAnswer: "b", explanation: "Emergency Schedules (EmS) are the maritime equivalent of the ERG.", difficulty: "medium", regulationReference: "IMDG Code" },
            { questionText: "Intermodal containers rail-to-vessel must meet:", questionType: "multiple_choice", options: [{ id: "a", text: "DOT requirements only", isCorrect: false }, { id: "b", text: "IMDG requirements only", isCorrect: false }, { id: "c", text: "Both DOT and IMDG requirements", isCorrect: true }, { id: "d", text: "Neither", isCorrect: false }], correctAnswer: "c", explanation: "Containers moving between modes must comply with both regulatory frameworks.", difficulty: "hard", regulationReference: "49 CFR Part 176, IMDG Code" },
            { questionText: "True or False: DOT and IMDG use different hazard class numbering.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "Both use the same 9 UN hazard classes.", difficulty: "easy", regulationReference: "49 CFR, IMDG Code" },
            { questionText: "Container packing certificates are required for:", questionType: "multiple_choice", options: [{ id: "a", text: "All rail shipments", isCorrect: false }, { id: "b", text: "Maritime hazmat containers", isCorrect: true }, { id: "c", text: "Trucking only", isCorrect: false }, { id: "d", text: "Empty containers", isCorrect: false }], correctAnswer: "b", explanation: "Container packing certificates are a maritime IMDG requirement.", difficulty: "medium", regulationReference: "IMDG Code" },
          ],
        },
      },
    ],

    "train-dispatching-ops": [
      {
        title: "Dispatching Fundamentals", description: "Train authority methods", orderIndex: 1, contentType: "text", estimatedDurationMinutes: 50,
        lessons: [
          { title: "Methods of Train Authority", contentHtml: "<h2>Train Movement Authority</h2><p>49 CFR Parts 236 and 241 govern dispatching methods:</p><ul><li><strong>CTC</strong>: Remote signal/switch control by dispatcher</li><li><strong>Track Warrant</strong>: Verbal/written authority with movement limits</li><li><strong>Direct Traffic Control</strong>: Named blocks assigned</li><li><strong>Timetable/Train Order</strong>: Historical, largely replaced</li></ul><p>Dispatchers must never authorize conflicting movements.</p>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 241", title: "US Locational Requirement for Dispatching", jurisdiction: "US", summary: "Train dispatching requirements." }] },
          { title: "Priority Management", contentHtml: "<h2>Train Priority</h2><p>Priority factors: passenger trains (highest), intermodal/time-sensitive, hazmat key trains, crew HOS limitations, maintenance windows. Dispatcher must balance service with safety and HOS compliance.</p>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 228", title: "Hours of Service impact on dispatching", jurisdiction: "US", summary: "HOS constraints dispatchers must account for." }] },
        ],
        quiz: {
          title: "Dispatching Fundamentals Quiz", description: "Test dispatching knowledge",
          questions: [
            { questionText: "CTC allows the dispatcher to control:", questionType: "multiple_choice", options: [{ id: "a", text: "Only signals", isCorrect: false }, { id: "b", text: "Signals and power switches remotely", isCorrect: true }, { id: "c", text: "Only switches", isCorrect: false }, { id: "d", text: "Train braking", isCorrect: false }], correctAnswer: "b", explanation: "CTC controls both signals and power switches.", difficulty: "easy", regulationReference: "49 CFR Part 236" },
            { questionText: "Maximum on-duty time for train employees:", questionType: "multiple_choice", options: [{ id: "a", text: "10 hours", isCorrect: false }, { id: "b", text: "12 hours", isCorrect: true }, { id: "c", text: "14 hours", isCorrect: false }, { id: "d", text: "16 hours", isCorrect: false }], correctAnswer: "b", explanation: "12-hour rule limits train employee on-duty time.", difficulty: "easy", regulationReference: "49 CFR Part 228" },
            { questionText: "True or False: Dispatchers can authorize conflicting movements under PTC.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "Never authorize conflicting movements regardless of PTC.", difficulty: "medium", regulationReference: "49 CFR Part 236" },
            { questionText: "Passenger trains generally receive:", questionType: "multiple_choice", options: [{ id: "a", text: "Lowest priority", isCorrect: false }, { id: "b", text: "Highest priority", isCorrect: true }, { id: "c", text: "Same as freight", isCorrect: false }, { id: "d", text: "Priority only in peak hours", isCorrect: false }], correctAnswer: "b", explanation: "Passenger trains generally get highest priority.", difficulty: "easy", regulationReference: "General railroad operations" },
            { questionText: "A track warrant provides:", questionType: "multiple_choice", options: [{ id: "a", text: "Track ownership", isCorrect: false }, { id: "b", text: "Authority specifying movement limits", isCorrect: true }, { id: "c", text: "Speed limit exemptions", isCorrect: false }, { id: "d", text: "Repair authority", isCorrect: false }], correctAnswer: "b", explanation: "A track warrant specifies the limits of a train's authorized movement.", difficulty: "easy", regulationReference: "49 CFR Part 236" },
          ],
        },
      },
      {
        title: "Dispatching Technology", description: "CAD systems and modern dispatching", orderIndex: 2, contentType: "text", estimatedDurationMinutes: 50,
        lessons: [
          { title: "Computer-Aided Dispatch", contentHtml: "<h2>Modern Dispatch Technology</h2><p>CAD systems provide: real-time train location on electronic track diagrams, signal/switch control interfaces, conflict detection, crew time management (HOS countdown), work authority tracking, PTC integration. Despite technology, the human dispatcher remains legally responsible.</p>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 236", title: "Signal and dispatch systems", jurisdiction: "US", summary: "Dispatch technology regulatory framework." }] },
          { title: "Record Keeping", contentHtml: "<h2>Dispatch Records</h2><p>All communications audio recorded, track warrants logged electronically, signal/switch operations timestamped, records retained minimum 1 year.</p>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 220", title: "Communication recording", jurisdiction: "US", summary: "Recording and retention requirements." }] },
        ],
        quiz: {
          title: "Dispatch Technology Quiz", description: "Test modern dispatching knowledge",
          questions: [
            { questionText: "CAD provides all EXCEPT:", questionType: "multiple_choice", options: [{ id: "a", text: "Real-time train location", isCorrect: false }, { id: "b", text: "Conflict detection", isCorrect: false }, { id: "c", text: "Automatic train braking", isCorrect: true }, { id: "d", text: "Crew time management", isCorrect: false }], correctAnswer: "c", explanation: "CAD provides info/control but doesn't brake trains — that's PTC.", difficulty: "medium", regulationReference: "49 CFR Part 236" },
            { questionText: "Dispatch radio communications must be:", questionType: "multiple_choice", options: [{ id: "a", text: "Encrypted only", isCorrect: false }, { id: "b", text: "Audio recorded and retained", isCorrect: true }, { id: "c", text: "Transcribed in real time", isCorrect: false }, { id: "d", text: "Broadcast publicly", isCorrect: false }], correctAnswer: "b", explanation: "All dispatcher radio communications are audio recorded.", difficulty: "easy", regulationReference: "49 CFR Part 220" },
            { questionText: "True or False: CAD eliminates the need for human dispatchers.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "Human dispatcher remains legally responsible.", difficulty: "easy", regulationReference: "49 CFR Part 241" },
            { questionText: "Minimum records retention is:", questionType: "multiple_choice", options: [{ id: "a", text: "30 days", isCorrect: false }, { id: "b", text: "6 months", isCorrect: false }, { id: "c", text: "1 year", isCorrect: true }, { id: "d", text: "5 years", isCorrect: false }], correctAnswer: "c", explanation: "Minimum 1 year retention.", difficulty: "medium", regulationReference: "49 CFR Part 220" },
            { questionText: "Track warrants are logged:", questionType: "multiple_choice", options: [{ id: "a", text: "On paper only", isCorrect: false }, { id: "b", text: "Electronically", isCorrect: true }, { id: "c", text: "Not at all", isCorrect: false }, { id: "d", text: "Weekly summaries", isCorrect: false }], correctAnswer: "b", explanation: "Modern systems log authorities electronically.", difficulty: "easy", regulationReference: "49 CFR Part 220" },
          ],
        },
      },
      {
        title: "Emergency and HOS Dispatching", description: "Emergencies and dispatcher HOS rules", orderIndex: 3, contentType: "text", estimatedDurationMinutes: 45,
        lessons: [
          { title: "Emergency Dispatching", contentHtml: "<h2>Emergency Protocols</h2><p>Dispatcher must: immediately stop all movements in affected area, notify officials, coordinate with emergency responders (access routes, hazmat info), protect scene, document all actions with timestamps.</p>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 241", title: "Emergency dispatching", jurisdiction: "US", summary: "Dispatcher emergency requirements." }] },
          { title: "Dispatcher HOS Rules", contentHtml: "<h2>Dispatcher Hours of Service</h2><p>49 CFR Part 228 Subpart B: 9 hours max in 24-hour period (2-shift locations), or 12 hours (fewer shifts); minimum 8 consecutive hours off between shifts. Unlike train crew's absolute 12-hour limit, dispatcher HOS varies by staffing.</p>", orderIndex: 2, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "49 CFR Part 228 Subpart B", title: "Dispatcher HOS", jurisdiction: "US", summary: "Dispatcher hours of service rules." }] },
        ],
        quiz: {
          title: "Emergency & HOS Quiz", description: "Test emergency dispatch and HOS knowledge",
          questions: [
            { questionText: "First action in a dispatch emergency:", questionType: "multiple_choice", options: [{ id: "a", text: "Call superintendent", isCorrect: false }, { id: "b", text: "Stop all movements in affected area", isCorrect: true }, { id: "c", text: "File FRA report", isCorrect: false }, { id: "d", text: "Wait for more info", isCorrect: false }], correctAnswer: "b", explanation: "Stop all movements first to prevent additional incidents.", difficulty: "easy", regulationReference: "49 CFR Part 241" },
            { questionText: "Dispatcher max duty with 2 shifts:", questionType: "multiple_choice", options: [{ id: "a", text: "8 hours", isCorrect: false }, { id: "b", text: "9 hours", isCorrect: true }, { id: "c", text: "12 hours", isCorrect: false }, { id: "d", text: "14 hours", isCorrect: false }], correctAnswer: "b", explanation: "9 hours max at 2-shift locations.", difficulty: "medium", regulationReference: "49 CFR Part 228 Subpart B" },
            { questionText: "True or False: HOS rules are suspended during emergencies.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "HOS rules still apply during disruptions.", difficulty: "medium", regulationReference: "49 CFR Part 228" },
            { questionText: "Minimum off-duty time between dispatcher shifts:", questionType: "multiple_choice", options: [{ id: "a", text: "6 hours", isCorrect: false }, { id: "b", text: "8 hours", isCorrect: true }, { id: "c", text: "10 hours", isCorrect: false }, { id: "d", text: "12 hours", isCorrect: false }], correctAnswer: "b", explanation: "Minimum 8 consecutive hours off between shifts.", difficulty: "easy", regulationReference: "49 CFR Part 228 Subpart B" },
            { questionText: "All dispatcher emergency actions must be:", questionType: "multiple_choice", options: [{ id: "a", text: "Verbal only", isCorrect: false }, { id: "b", text: "Documented with timestamps", isCorrect: true }, { id: "c", text: "Reported next shift", isCorrect: false }, { id: "d", text: "Kept confidential", isCorrect: false }], correctAnswer: "b", explanation: "All actions and communications must be documented with timestamps.", difficulty: "easy", regulationReference: "49 CFR Part 241" },
          ],
        },
      },
      {
        title: "Network Planning and Coordination", description: "Territory planning, meets/passes, and coordination", orderIndex: 4, contentType: "text", estimatedDurationMinutes: 45,
        lessons: [
          { title: "Meet-Pass Planning", contentHtml: "<h2>Managing Meets and Passes</h2><p>On single-track territory (which constitutes most US railroad mileage), dispatchers must plan meets (opposing trains) and passes (same-direction overtakes) at sidings. Key considerations:</p><ul><li>Siding lengths vs train lengths</li><li>Time-on-duty for each crew</li><li>Fuel and tonnage limitations on grades</li><li>Minimizing overall network delay</li></ul>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 25, keyRegulations: [{ code: "49 CFR Part 241", title: "Dispatching coordination", jurisdiction: "US", summary: "Requirements for dispatching coordination." }] },
        ],
        quiz: {
          title: "Network Planning Quiz", description: "Test network management knowledge",
          questions: [
            { questionText: "A 'meet' involves:", questionType: "multiple_choice", options: [{ id: "a", text: "Two trains going the same direction", isCorrect: false }, { id: "b", text: "Two opposing trains passing at a siding", isCorrect: true }, { id: "c", text: "A train stopping at a station", isCorrect: false }, { id: "d", text: "A crew change", isCorrect: false }], correctAnswer: "b", explanation: "A meet occurs when two opposing trains use a siding to pass each other.", difficulty: "easy", regulationReference: "General railroad operations" },
            { questionText: "Most US railroad mileage is:", questionType: "multiple_choice", options: [{ id: "a", text: "Double track", isCorrect: false }, { id: "b", text: "Single track", isCorrect: true }, { id: "c", text: "Triple track", isCorrect: false }, { id: "d", text: "Quad track", isCorrect: false }], correctAnswer: "b", explanation: "Most US railroad mileage is single track with passing sidings.", difficulty: "easy", regulationReference: "General railroad knowledge" },
            { questionText: "Siding length is critical because:", questionType: "multiple_choice", options: [{ id: "a", text: "Longer sidings cost more", isCorrect: false }, { id: "b", text: "Trains that don't fit can't use them for meets", isCorrect: true }, { id: "c", text: "Speed is limited in sidings", isCorrect: false }, { id: "d", text: "Sidings have no signals", isCorrect: false }], correctAnswer: "b", explanation: "If a train is longer than the siding, it cannot pull in for a meet.", difficulty: "medium", regulationReference: "General railroad operations" },
            { questionText: "True or False: A 'pass' involves two opposing trains.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "A pass involves one train overtaking another going the same direction.", difficulty: "easy", regulationReference: "General railroad operations" },
            { questionText: "Crew time-on-duty affects dispatching because:", questionType: "multiple_choice", options: [{ id: "a", text: "Crews get paid overtime", isCorrect: false }, { id: "b", text: "Trains must stop when crew reaches 12-hour limit", isCorrect: true }, { id: "c", text: "It changes the signal system", isCorrect: false }, { id: "d", text: "It has no effect", isCorrect: false }], correctAnswer: "b", explanation: "If a crew reaches their HOS limit, the train must stop until a relief crew arrives.", difficulty: "medium", regulationReference: "49 CFR Part 228" },
          ],
        },
      },
      {
        title: "Dispatcher Certification", description: "Training and qualification for dispatchers", orderIndex: 5, contentType: "text", estimatedDurationMinutes: 40,
        lessons: [
          { title: "Dispatcher Training Requirements", contentHtml: "<h2>Qualification</h2><p>While there is no separate FRA dispatcher certification rule like Parts 240/242, dispatchers must be trained and qualified per each railroad's operating rules program (Part 217) and Part 241 dispatching requirements. Training typically includes:</p><ul><li>Signal and train control systems</li><li>Operating rules applicable to the territory</li><li>Emergency response procedures</li><li>HOS regulations</li><li>CAD system operation</li><li>OJT (on-the-job training) with a qualified dispatcher</li></ul>", orderIndex: 1, lessonType: "reading", estimatedDurationMinutes: 20, keyRegulations: [{ code: "49 CFR Part 217", title: "Operating rules program for dispatchers", jurisdiction: "US", summary: "Training and testing requirements for dispatchers." }] },
        ],
        quiz: {
          title: "Dispatcher Certification Quiz", description: "Test dispatcher qualification knowledge",
          questions: [
            { questionText: "Dispatcher qualification is governed by:", questionType: "multiple_choice", options: [{ id: "a", text: "49 CFR Part 240 (like engineers)", isCorrect: false }, { id: "b", text: "Railroad's Part 217 program and Part 241", isCorrect: true }, { id: "c", text: "State licensing boards", isCorrect: false }, { id: "d", text: "No federal requirements exist", isCorrect: false }], correctAnswer: "b", explanation: "Dispatchers are qualified through railroad's operating rules program (Part 217) and Part 241.", difficulty: "medium", regulationReference: "49 CFR Parts 217, 241" },
            { questionText: "True or False: There is a separate FRA dispatcher certification rule.", questionType: "true_false", options: [{ id: "a", text: "True", isCorrect: false }, { id: "b", text: "False", isCorrect: true }], correctAnswer: "b", explanation: "Unlike engineers (Part 240) and conductors (Part 242), there is no separate dispatcher certification rule.", difficulty: "medium", regulationReference: "49 CFR Part 241" },
            { questionText: "OJT for dispatchers means:", questionType: "multiple_choice", options: [{ id: "a", text: "Online Job Training", isCorrect: false }, { id: "b", text: "On-the-Job Training with a qualified dispatcher", isCorrect: true }, { id: "c", text: "Operator Job Testing", isCorrect: false }, { id: "d", text: "Operating Junction Terminal", isCorrect: false }], correctAnswer: "b", explanation: "OJT = On-the-Job Training under supervision of a qualified dispatcher.", difficulty: "easy", regulationReference: "General railroad operations" },
            { questionText: "Dispatcher training includes all EXCEPT:", questionType: "multiple_choice", options: [{ id: "a", text: "Signal systems", isCorrect: false }, { id: "b", text: "Emergency procedures", isCorrect: false }, { id: "c", text: "Locomotive maintenance", isCorrect: true }, { id: "d", text: "CAD system operation", isCorrect: false }], correctAnswer: "c", explanation: "Locomotive maintenance is not part of dispatcher training.", difficulty: "easy", regulationReference: "49 CFR Part 217" },
            { questionText: "Dispatchers must be tested on operating rules per:", questionType: "multiple_choice", options: [{ id: "a", text: "Part 217", isCorrect: true }, { id: "b", text: "Part 240", isCorrect: false }, { id: "c", text: "Part 242", isCorrect: false }, { id: "d", text: "Part 225", isCorrect: false }], correctAnswer: "a", explanation: "Part 217 requires periodic testing of all employees on operating rules.", difficulty: "easy", regulationReference: "49 CFR Part 217" },
          ],
        },
      },
    ],
  };
}
