import { ModuleDef } from "./types";
const M = "multiple_choice" as const, T = "true_false" as const;
const mc = (q:string,a:string[],c:number,e:string,r:string) => ({questionText:q,questionType:M,options:a.map((t,i)=>({id:"abcd"[i],text:t,isCorrect:i===c})),correctAnswer:"abcd"[c],explanation:e,difficulty:"medium" as const,regulationReference:r});
const tf = (q:string,v:boolean,e:string,r:string) => ({questionText:q,questionType:T,options:[{id:"a",text:"True",isCorrect:v},{id:"b",text:"False",isCorrect:!v}],correctAnswer:v?"a":"b",explanation:e,difficulty:"easy" as const,regulationReference:r});
const les = (t:string,h:string,i:number,d:number,rc:string) => ({title:t,contentHtml:h,orderIndex:i,lessonType:"reading" as const,estimatedDurationMinutes:d,keyRegulations:[{code:rc,title:t,jurisdiction:"US",summary:t}]});
const mod = (t:string,ds:string,oi:number,dur:number,ls:any[],qs:any[]):ModuleDef => ({title:t,description:ds,orderIndex:oi,contentType:"text",estimatedDurationMinutes:dur,lessons:ls,quiz:{title:t+" Quiz",description:"Assessment: "+ds,questions:qs}});

export function getRail5(): Record<string, ModuleDef[]> { return {
"intermodal-operations": [
  mod("Intermodal Fundamentals","Basics of intermodal freight",1,50,[
    les("What is Intermodal","<h2>Intermodal Transport</h2><p>Standardized containers/trailers moving rail↔truck↔vessel without unpacking. Types: COFC (Container on Flat Car), TOFC (Trailer on Flat Car), double-stack container trains. Rail moves 1 ton 492 miles per gallon vs ~130 for trucks — significant fuel/emissions advantage.</p>",1,25,"General intermodal"),
    les("Equipment Types","<h2>Equipment</h2><p>ISO containers (20'/40'/45'/53'), well cars (double-stack), spine cars, chassis for road drayage. CSC (Container Safety Convention) plates required on all containers. Container standards set by ISO.</p>",2,25,"ISO standards"),
  ],[mc("COFC stands for:",["Container On Freight Car","Container On Flat Car","Cargo Only Full Container","Cross-border Operations"],1,"Flat Car.","General"),mc("Rail fuel efficiency per ton:",["130 mi/gal","492 mi/gal","250 mi/gal","50 mi/gal"],1,"492 mi/gal.","General"),mc("Double-stack uses:",["Flat cars","Well cars","Box cars","Tank cars"],1,"Well cars.","General"),tf("CSC plates required on containers.",true,"Container Safety Convention.","ISO"),mc("TOFC stands for:",["Trailer On Flat Car","Train Only Freight","Terminal Operations","Through-route"],0,"Trailer on Flat Car.","General")]),
  mod("Terminal Operations","Intermodal terminal procedures",2,45,[
    les("Lift Operations","<h2>Terminal Ops</h2><p>Gantry cranes, reach stackers, top picks, side loaders. Key metrics: lifts per hour, dwell time, train turn time. Major facilities operate 24/7.</p>",1,25,"OSHA 29 CFR 1917"),
    les("Drayage Operations","<h2>Drayage</h2><p>Short-haul trucking to/from intermodal terminals. Chassis management: pool vs proprietary. Appointment systems manage terminal congestion. FMCSA regulates drayage carriers.</p>",2,20,"FMCSA regulations"),
  ],[mc("Gantry cranes for:",["Track repair","Container lifting","Train assembly","Fueling"],1,"Container handling.","General"),mc("Drayage is:",["Long-haul","Short-haul to/from terminals","Rail switching","Vessel loading"],1,"Terminal delivery.","General"),mc("Key terminal metric:",["Revenue/car","Lifts per hour","Fuel cost","Employees"],1,"Throughput.","General"),tf("Major terminals operate 24/7.",true,"Around the clock.","General"),mc("Chassis management:",["FRA regulated","Pool vs proprietary","Not needed","State-run"],1,"Equipment mgmt.","General")]),
  mod("Cross-Border Intermodal","US-Canada-Mexico operations",3,45,[
    les("Cross-Border Requirements","<h2>Cross-Border</h2><p>CBP advance manifest: 24-hr rule ocean, 2-hr rail. USMCA (formerly NAFTA) trade provisions. C-TPAT trusted shipper program. FAST cards for drivers.</p>",1,25,"19 CFR"),
    les("Documentation","<h2>Required Docs</h2><p>Commercial invoice, packing list, bill of lading, customs declaration, USMCA certificate of origin, hazmat docs in applicable languages.</p>",2,20,"19 CFR, USMCA"),
  ],[mc("CBP advance manifest for rail:",["24 hrs","2 hrs before","48 hrs","No requirement"],1,"2-hour rule.","19 CFR"),mc("USMCA replaced:",["WTO","NAFTA","EU agreement","TPP"],1,"Formerly NAFTA.","USMCA"),mc("C-TPAT is:",["Customs tariff","Trusted shipper program","Trade penalty","Tax credit"],1,"CBP partnership.","19 CFR"),tf("FAST cards expedite crossing.",true,"Trusted drivers.","CBP"),mc("Proof of origin:",["Verbal","USMCA certification","Photo ID","Insurance"],1,"Certification.","USMCA")]),
  mod("Safety & Compliance","Intermodal safety regulations",4,40,[
    les("Safety Requirements","<h2>Safety</h2><p>FMCSA Intermodal Equipment Provider regs (49 CFR 390 Subpart F). Roadability inspections before drayage. VGM (Verified Gross Mass) per SOLAS for maritime containers. Rail securement per AAR Loading Rules. Over-the-road tie-downs per FMCSA.</p>",1,25,"49 CFR 390 Subpart F"),
  ],[mc("IEP regulations in:",["Part 232","Part 390 Subpart F","Part 213","Part 228"],1,"FMCSA intermodal.","49 CFR 390"),mc("VGM stands for:",["Vehicle Gross Mass","Verified Gross Mass","Visual Gauge Measurement","Volume Grade"],1,"SOLAS weight verification.","SOLAS"),mc("Rail container securement per:",["FMCSA","AAR Loading Rules","Part 213","Part 232"],1,"AAR rules.","AAR"),tf("Roadability inspections required before drayage.",true,"Pre-trip inspection.","49 CFR 390 Subpart F"),mc("SOLAS VGM requirement is for:",["All freight","Maritime containers","Rail only","Air cargo"],1,"Maritime containers.","SOLAS")]),
],
};}
