/**
 * All User Types Compliance Scenarios (100)
 */
import { Scenario } from '../../runners/ScenarioExecutor';

const c = (id: number, name: string, actor: string, steps: string[], vals: string[]): Scenario => ({
  id: `COMP-${String(id).padStart(3, '0')}`, category: 'USER_COMPLIANCE', name, actor, steps, expectedOutcome: name, validations: vals
});

export const ALL_USER_COMPLIANCE_SCENARIOS: Scenario[] = [
  // DRIVER (1-20)
  c(1, 'Driver CDL upload', 'DRIVER', ['Upload CDL', 'OCR extract', 'Verify'], ['upload_ok', 'verified']),
  c(2, 'Driver medical card', 'DRIVER', ['Upload medical', 'Track expiry'], ['uploaded', 'tracked']),
  c(3, 'Driver hazmat endorsement', 'DRIVER', ['Upload hazmat', 'TSA check'], ['hazmat_ok']),
  c(4, 'Driver TWIC card', 'DRIVER', ['Upload TWIC', 'Port access'], ['twic_ok']),
  c(5, 'Driver drug test', 'DRIVER', ['Upload test', 'Clearinghouse'], ['test_ok']),
  c(6, 'Driver background check', 'DRIVER', ['Request check', 'Results'], ['check_ok']),
  c(7, 'Driver MVR report', 'DRIVER', ['Upload MVR', 'Clean'], ['mvr_ok']),
  c(8, 'Driver W-9', 'DRIVER', ['Upload W-9', 'Verified'], ['w9_ok']),
  c(9, 'Driver compliance score', 'SYSTEM', ['Calculate', 'Display 85%'], ['score_ok']),
  c(10, 'Driver expiration alert', 'SYSTEM', ['30 day alert', 'Email'], ['alert_ok']),
  c(11, 'Driver expired blocks load', 'DRIVER', ['Try book', 'Blocked'], ['blocked']),
  c(12, 'Driver tanker endorsement', 'DRIVER', ['Upload tanker', 'Enabled'], ['tanker_ok']),
  c(13, 'Driver doubles endorsement', 'DRIVER', ['Upload doubles', 'LCV'], ['doubles_ok']),
  c(14, 'Driver passport', 'DRIVER', ['Upload passport', 'Cross-border'], ['passport_ok']),
  c(15, 'Driver FAST card', 'DRIVER', ['Upload FAST', 'Expedited'], ['fast_ok']),
  c(16, 'Driver road test cert', 'DRIVER', ['Upload test', 'Qualified'], ['test_ok']),
  c(17, 'Driver employment app', 'DRIVER', ['Submit app', 'DQ file'], ['app_ok']),
  c(18, 'Driver annual query', 'SYSTEM', ['Query due', 'Clear'], ['query_ok']),
  c(19, 'Driver pre-employment', 'CARRIER', ['Screen', 'Cleared'], ['cleared']),
  c(20, 'Driver dashboard', 'DRIVER', ['View docs', 'Score'], ['dashboard_ok']),
  // CARRIER (21-40)
  c(21, 'Carrier MC Authority', 'CARRIER', ['Upload MC', 'FMCSA verify'], ['mc_ok']),
  c(22, 'Carrier DOT number', 'CARRIER', ['Enter DOT', 'SAFER lookup'], ['dot_ok']),
  c(23, 'Carrier UCR registration', 'CARRIER', ['Upload UCR', 'Current'], ['ucr_ok']),
  c(24, 'Carrier IFTA license', 'CARRIER', ['Upload IFTA', 'Tax compliant'], ['ifta_ok']),
  c(25, 'Carrier IRP cab card', 'CARRIER', ['Upload IRP', 'States'], ['irp_ok']),
  c(26, 'Carrier BOC-3', 'CARRIER', ['Upload BOC-3', 'Agent'], ['boc3_ok']),
  c(27, 'Carrier liability $1M', 'CARRIER', ['Upload COI', '$1M verified'], ['liability_ok']),
  c(28, 'Carrier cargo $100K', 'CARRIER', ['Upload cargo', '$100K'], ['cargo_ok']),
  c(29, 'Carrier workers comp', 'CARRIER', ['Upload WC', 'Covered'], ['wc_ok']),
  c(30, 'Carrier auto liability', 'CARRIER', ['Upload auto', 'Fleet'], ['auto_ok']),
  c(31, 'Carrier safety rating', 'CARRIER', ['View rating', 'CSA'], ['rating_ok']),
  c(32, 'Carrier drug program', 'CARRIER', ['Upload D&A', 'DOT'], ['drug_ok']),
  c(33, 'Carrier W-9', 'CARRIER', ['Upload W-9', 'EIN'], ['w9_ok']),
  c(34, 'Carrier banking ACH', 'CARRIER', ['Enter bank', 'ACH'], ['bank_ok']),
  c(35, 'Carrier equipment list', 'CARRIER', ['Upload list', 'Fleet'], ['equip_ok']),
  c(36, 'Carrier driver roster', 'CARRIER', ['Upload roster', 'Linked'], ['roster_ok']),
  c(37, 'Carrier insurance alert', 'SYSTEM', ['14 day alert', 'Email'], ['alert_ok']),
  c(38, 'Carrier score 92%', 'CARRIER', ['View score', 'Categories'], ['score_ok']),
  c(39, 'Carrier hazmat cert', 'CARRIER', ['Upload hazmat', 'PHMSA'], ['hazmat_ok']),
  c(40, 'Carrier min rejected', 'SYSTEM', ['$500K COI', 'Rejected'], ['rejected']),
  // BROKER (41-60)
  c(41, 'Broker authority MC-B', 'BROKER', ['Upload MC-B', 'Active'], ['mc_ok']),
  c(42, 'Broker license', 'BROKER', ['Upload license', 'State'], ['license_ok']),
  c(43, 'Broker BOC-3', 'BROKER', ['Upload BOC-3', 'Agent'], ['boc3_ok']),
  c(44, 'Broker UCR', 'BROKER', ['Upload UCR', 'Current'], ['ucr_ok']),
  c(45, 'Broker surety bond $75K', 'BROKER', ['Upload bond', 'BMC-84'], ['bond_ok']),
  c(46, 'Broker trust fund alt', 'BROKER', ['Upload trust', 'BMC-85'], ['trust_ok']),
  c(47, 'Broker contingent cargo', 'BROKER', ['Upload cargo', 'Coverage'], ['cargo_ok']),
  c(48, 'Broker general liability', 'BROKER', ['Upload GL', '$1M'], ['gl_ok']),
  c(49, 'Broker E&O insurance', 'BROKER', ['Upload E&O', 'Prof liability'], ['eo_ok']),
  c(50, 'Broker cyber insurance', 'BROKER', ['Upload cyber', 'Data breach'], ['cyber_ok']),
  c(51, 'Broker W-9', 'BROKER', ['Upload W-9', 'EIN'], ['w9_ok']),
  c(52, 'Broker banking', 'BROKER', ['Enter bank', 'ACH'], ['bank_ok']),
  c(53, 'Broker carrier packet', 'BROKER', ['Upload packet', 'Template'], ['packet_ok']),
  c(54, 'Broker shipper agreement', 'BROKER', ['Upload agreement', 'Terms'], ['agree_ok']),
  c(55, 'Broker rate con template', 'BROKER', ['Upload template', 'Ready'], ['ratecon_ok']),
  c(56, 'Broker bond expiration', 'SYSTEM', ['30 day alert', 'Renewal'], ['alert_ok']),
  c(57, 'Broker score 95%', 'BROKER', ['View score', 'All verified'], ['score_ok']),
  c(58, 'Broker carrier vetting', 'BROKER', ['Vet carrier', 'SAFER'], ['vet_ok']),
  c(59, 'Broker credit report', 'BROKER', ['Upload credit', 'Business'], ['credit_ok']),
  c(60, 'Broker compliance dashboard', 'BROKER', ['View all docs', 'Status'], ['dashboard_ok']),
  // SHIPPER (61-80)
  c(61, 'Shipper business license', 'SHIPPER', ['Upload license', 'State'], ['license_ok']),
  c(62, 'Shipper EIN verification', 'SHIPPER', ['Upload EIN', 'IRS'], ['ein_ok']),
  c(63, 'Shipper articles incorp', 'SHIPPER', ['Upload articles', 'State'], ['articles_ok']),
  c(64, 'Shipper DUNS number', 'SHIPPER', ['Enter DUNS', 'D&B verify'], ['duns_ok']),
  c(65, 'Shipper credit application', 'SHIPPER', ['Submit app', 'Approved'], ['credit_ok']),
  c(66, 'Shipper trade references', 'SHIPPER', ['Submit 3 refs', 'Verified'], ['refs_ok']),
  c(67, 'Shipper bank reference', 'SHIPPER', ['Upload bank ref', 'Optional'], ['bank_ok']),
  c(68, 'Shipper financial stmt', 'SHIPPER', ['Upload financials', 'Review'], ['fin_ok']),
  c(69, 'Shipper cargo insurance', 'SHIPPER', ['Upload cargo', 'Optional'], ['cargo_ok']),
  c(70, 'Shipper general liability', 'SHIPPER', ['Upload GL', '$1M'], ['gl_ok']),
  c(71, 'Shipper product liability', 'SHIPPER', ['Upload product', 'Optional'], ['product_ok']),
  c(72, 'Shipper W-9', 'SHIPPER', ['Upload W-9', 'Tax'], ['w9_ok']),
  c(73, 'Shipper payment terms', 'SHIPPER', ['Agree terms', 'Net 30'], ['terms_ok']),
  c(74, 'Shipper ACH authorization', 'SHIPPER', ['Submit ACH', 'Verified'], ['ach_ok']),
  c(75, 'Shipper facility insurance', 'SHIPPER', ['Upload facility', 'Warehouse'], ['facility_ok']),
  c(76, 'Shipper food safety cert', 'SHIPPER', ['Upload food', 'If applicable'], ['food_ok']),
  c(77, 'Shipper hazmat permit', 'SHIPPER', ['Upload hazmat', 'Facility'], ['hazmat_ok']),
  c(78, 'Shipper credit limit set', 'SYSTEM', ['Set $50K', 'Approved'], ['limit_ok']),
  c(79, 'Shipper score 88%', 'SHIPPER', ['View score', 'Status'], ['score_ok']),
  c(80, 'Shipper compliance dashboard', 'SHIPPER', ['View docs', 'Credit'], ['dashboard_ok']),
  // OWNER-OPERATOR (81-100)
  c(81, 'O/O CDL upload', 'OWNER_OP', ['Upload CDL', 'Verified'], ['cdl_ok']),
  c(82, 'O/O medical card', 'OWNER_OP', ['Upload medical', 'Expiry'], ['medical_ok']),
  c(83, 'O/O MC authority', 'OWNER_OP', ['Upload MC', 'If own auth'], ['mc_ok']),
  c(84, 'O/O lease agreement', 'OWNER_OP', ['Upload lease', 'Carrier link'], ['lease_ok']),
  c(85, 'O/O liability insurance', 'OWNER_OP', ['Upload liability', 'Min $1M'], ['liability_ok']),
  c(86, 'O/O cargo insurance', 'OWNER_OP', ['Upload cargo', '$100K'], ['cargo_ok']),
  c(87, 'O/O occupational acc', 'OWNER_OP', ['Upload occ acc', 'Coverage'], ['occ_ok']),
  c(88, 'O/O W-9', 'OWNER_OP', ['Upload W-9', '1099'], ['w9_ok']),
  c(89, 'O/O vehicle registration', 'OWNER_OP', ['Upload reg', 'Current'], ['reg_ok']),
  c(90, 'O/O annual inspection', 'OWNER_OP', ['Upload inspection', 'DOT'], ['insp_ok']),
  c(91, 'O/O hazmat endorsement', 'OWNER_OP', ['Upload hazmat', 'If needed'], ['hazmat_ok']),
  c(92, 'O/O IFTA decal', 'OWNER_OP', ['Upload IFTA', 'Fuel tax'], ['ifta_ok']),
  c(93, 'O/O IRP registration', 'OWNER_OP', ['Upload IRP', 'States'], ['irp_ok']),
  c(94, 'O/O ELD certificate', 'OWNER_OP', ['Upload ELD cert', 'Registered'], ['eld_ok']),
  c(95, 'O/O drug consortium', 'OWNER_OP', ['Upload consortium', 'Random pool'], ['drug_ok']),
  c(96, 'O/O score 90%', 'OWNER_OP', ['View score', 'Combined'], ['score_ok']),
  c(97, 'O/O dual compliance', 'SYSTEM', ['Driver + carrier', 'Both tracked'], ['dual_ok']),
  c(98, 'O/O insurance expiry', 'SYSTEM', ['Alert sent', 'Renewal'], ['alert_ok']),
  c(99, 'O/O authority switch', 'OWNER_OP', ['Change carrier', 'Docs update'], ['switch_ok']),
  c(100, 'O/O compliance dashboard', 'OWNER_OP', ['View all', 'Driver+Carrier'], ['dashboard_ok']),
];

export default ALL_USER_COMPLIANCE_SCENARIOS;
