/**
 * EUSOTRIP SIMULATION - Document Compliance Scenarios (75)
 * CDL, Medical, Insurance, Hazmat, TWIC, BOL, Run Tickets
 */

import { Scenario } from '../../runners/ScenarioExecutor';

function createDocScenario(id: number, name: string, actor: string, steps: string[], validations: string[]): Scenario {
  return {
    id: `DOC-${String(id).padStart(3, '0')}`,
    category: 'DOCUMENTS',
    name,
    actor,
    steps,
    expectedOutcome: name,
    validations
  };
}

export const DOCUMENT_COMPLIANCE_SCENARIOS: Scenario[] = [
  // CDL Management (1-15)
  createDocScenario(1, 'Driver uploads CDL for verification', 'DRIVER_D003',
    ['Navigate to documents', 'Select CDL type', 'Upload CDL image', 'OCR extracts data', 'Submit for verification'],
    ['upload_success', 'ocr_works', 'pending_status']),
  createDocScenario(2, 'Admin verifies driver CDL', 'ADMIN_A001',
    ['View verification queue', 'Select CDL document', 'Review extracted data', 'Approve document', 'Driver notified'],
    ['verification_works', 'notification_sent']),
  createDocScenario(3, 'CDL expiration warning 30 days', 'SYSTEM',
    ['CDL expires in 30 days', 'System generates warning', 'Email sent', 'Dashboard alert shown'],
    ['warning_generated', 'email_sent', 'alert_shown']),
  createDocScenario(4, 'CDL expiration warning 7 days', 'SYSTEM',
    ['CDL expires in 7 days', 'Urgent warning generated', 'SMS sent', 'Load booking restricted'],
    ['urgent_warning', 'sms_sent', 'booking_restricted']),
  createDocScenario(5, 'Expired CDL blocks load booking', 'DRIVER_D001',
    ['CDL expired', 'Attempt to book load', 'Blocked with message', 'Redirect to documents'],
    ['booking_blocked', 'message_clear', 'redirect_works']),
  createDocScenario(6, 'CDL renewal process', 'DRIVER_D003',
    ['Upload renewed CDL', 'Old document archived', 'New expiration tracked', 'Compliance restored'],
    ['renewal_works', 'archive_works', 'compliance_updated']),
  createDocScenario(7, 'CDL with endorsements verification', 'DRIVER_D004',
    ['Upload CDL with hazmat endorsement', 'Endorsements extracted', 'Hazmat loads unlocked'],
    ['endorsements_extracted', 'permissions_updated']),
  createDocScenario(8, 'CDL rejection with reason', 'ADMIN_A001',
    ['Review unclear CDL', 'Reject with reason: image quality', 'Driver notified', 'Resubmission requested'],
    ['rejection_works', 'reason_provided', 'resubmit_option']),
  createDocScenario(9, 'CDL state license verification', 'SYSTEM',
    ['Check CDL against state database', 'Verify license active', 'No violations found'],
    ['state_check_works', 'status_verified']),
  createDocScenario(10, 'CDL class verification for equipment', 'SYSTEM',
    ['Class A CDL uploaded', 'Verify can drive tractor-trailer', 'Equipment permissions set'],
    ['class_verified', 'permissions_correct']),

  // Medical Card (16-25)
  createDocScenario(16, 'Driver uploads medical card', 'DRIVER_D003',
    ['Select medical card type', 'Upload document', 'Expiration date captured', 'Pending verification'],
    ['upload_works', 'expiration_captured']),
  createDocScenario(17, 'Medical card verified by admin', 'ADMIN_A001',
    ['Review medical card', 'Verify examiner credentials', 'Approve', 'Update compliance status'],
    ['verification_works', 'compliance_updated']),
  createDocScenario(18, 'Medical card expiration cascade', 'SYSTEM',
    ['Medical expires', 'CDL status affected', 'Driving privileges suspended', 'Urgent notification'],
    ['cascade_works', 'suspension_applied']),
  createDocScenario(19, 'Medical exemption handling', 'DRIVER_D019',
    ['Upload medical exemption', 'Exemption type recorded', 'Special conditions noted'],
    ['exemption_handled', 'conditions_recorded']),
  createDocScenario(20, 'DOT physical results integration', 'SYSTEM',
    ['Results from clinic', 'Auto-import via API', 'Document created', 'Expiration set'],
    ['integration_works', 'auto_import']),

  // Insurance Documents (26-35)
  createDocScenario(26, 'Carrier uploads liability insurance COI', 'CARRIER_C002',
    ['Upload COI', 'Coverage amounts extracted', 'Expiration tracked', 'Verified against requirements'],
    ['upload_works', 'coverage_extracted', 'requirements_checked']),
  createDocScenario(27, 'Insurance below minimum rejected', 'SYSTEM',
    ['COI shows $500k liability', 'Minimum is $1M', 'Rejection with reason', 'Upload corrected COI'],
    ['minimum_enforced', 'reason_shown']),
  createDocScenario(28, 'Cargo insurance verification', 'CARRIER_C001',
    ['Upload cargo insurance', 'Coverage: $100k', 'High-value loads restricted until upgrade'],
    ['cargo_verified', 'restrictions_applied']),
  createDocScenario(29, 'Insurance expiration auto-notification', 'SYSTEM',
    ['Insurance expires in 14 days', 'Auto-email to carrier', 'Broker notified', 'Renewal reminder'],
    ['auto_notification', 'broker_notified']),
  createDocScenario(30, 'Insurance certificate sharing with shipper', 'CARRIER_C002',
    ['Shipper requests COI', 'Share from documents', 'Access logged', 'Expiration visible'],
    ['sharing_works', 'access_logged']),

  // Hazmat & Specialty (36-45)
  createDocScenario(36, 'Hazmat endorsement verification', 'DRIVER_D004',
    ['Upload hazmat endorsement', 'TSA background verified', 'Hazmat loads enabled'],
    ['hazmat_verified', 'tsa_checked', 'loads_enabled']),
  createDocScenario(37, 'TWIC card for port access', 'DRIVER_D008',
    ['Upload TWIC card', 'Verify with TSA database', 'Port loads enabled'],
    ['twic_verified', 'port_access_enabled']),
  createDocScenario(38, 'Tanker endorsement verification', 'DRIVER_D008',
    ['Upload tanker endorsement', 'Verify on CDL', 'Tanker loads enabled'],
    ['tanker_verified', 'loads_enabled']),
  createDocScenario(39, 'Passport for cross-border', 'DRIVER_D003',
    ['Upload passport', 'Verify expiration', 'Mexico/Canada loads enabled'],
    ['passport_verified', 'cross_border_enabled']),
  createDocScenario(40, 'FAST card verification', 'DRIVER_D003',
    ['Upload FAST card', 'Expedited border crossing enabled'],
    ['fast_verified', 'expedited_enabled']),

  // BOL Management (46-60)
  createDocScenario(46, 'Generate BOL for new load', 'DRIVER_D003',
    ['Load assigned', 'Generate BOL', 'Shipper info populated', 'Consignee info populated'],
    ['bol_generated', 'info_correct']),
  createDocScenario(47, 'Sign BOL at pickup', 'DRIVER_D003',
    ['Arrive at pickup', 'Review BOL', 'Capture signature', 'BOL status: picked up'],
    ['signature_captured', 'status_updated']),
  createDocScenario(48, 'BOL with exception noted', 'DRIVER_D003',
    ['Damaged cargo noted', 'Exception on BOL', 'Photo attached', 'Shipper notified'],
    ['exception_noted', 'photo_attached', 'notification_sent']),
  createDocScenario(49, 'BOL signature at delivery', 'DRIVER_D003',
    ['Arrive at delivery', 'Receiver signs BOL', 'Delivery confirmed', 'BOL completed'],
    ['delivery_signature', 'bol_completed']),
  createDocScenario(50, 'BOL shortage documented', 'DRIVER_D005',
    ['Count mismatch', 'Document shortage on BOL', 'Both parties sign', 'Claim initiated'],
    ['shortage_documented', 'claim_initiated']),
  createDocScenario(51, 'BOL PDF generation', 'DRIVER_D003',
    ['Load complete', 'Generate BOL PDF', 'All signatures included', 'Download available'],
    ['pdf_generated', 'signatures_included']),
  createDocScenario(52, 'BOL sent to broker automatically', 'SYSTEM',
    ['BOL completed', 'Auto-send to broker', 'Delivery timestamp', 'Attached to load'],
    ['auto_send_works', 'attached_to_load']),
  createDocScenario(53, 'BOL search and retrieval', 'BROKER_B001',
    ['Search by load number', 'Find BOL', 'View details', 'Download PDF'],
    ['search_works', 'retrieval_works']),
  createDocScenario(54, 'BOL audit trail', 'ADMIN_A001',
    ['View BOL history', 'See all signatures', 'Timestamps verified', 'Chain of custody'],
    ['audit_trail_complete']),
  createDocScenario(55, 'Multi-stop BOL handling', 'DRIVER_D007',
    ['5-stop load', 'Partial BOL per stop', 'All stops documented', 'Master BOL complete'],
    ['multi_stop_works', 'master_complete']),

  // Run Tickets (61-75)
  createDocScenario(61, 'Create run ticket for load', 'DRIVER_D003',
    ['Load assigned', 'Create run ticket', 'Ticket number generated', 'Linked to load'],
    ['ticket_created', 'linked_to_load']),
  createDocScenario(62, 'Add fuel expense to run ticket', 'DRIVER_D003',
    ['Buy fuel', 'Add expense', 'Upload receipt', 'Amount recorded'],
    ['expense_added', 'receipt_uploaded']),
  createDocScenario(63, 'Add toll expense to run ticket', 'DRIVER_D003',
    ['Pass toll', 'Add toll expense', 'E-ZPass auto-import option'],
    ['toll_added', 'auto_import_option']),
  createDocScenario(64, 'Add lumper fee to run ticket', 'DRIVER_D003',
    ['Pay lumper', 'Document fee', 'Comcheck attached', 'Reimbursement requested'],
    ['lumper_documented', 'reimbursement_requested']),
  createDocScenario(65, 'Run ticket expense categories', 'DRIVER_D003',
    ['View expense categories', 'Fuel/toll/scale/parking/meal/repair', 'All types available'],
    ['categories_available']),
  createDocScenario(66, 'Complete run ticket', 'DRIVER_D003',
    ['All expenses logged', 'Mark complete', 'Total calculated', 'Submit for review'],
    ['ticket_completed', 'total_correct']),
  createDocScenario(67, 'Run ticket approval workflow', 'CARRIER_C002',
    ['Review driver ticket', 'Verify receipts', 'Approve expenses', 'Process reimbursement'],
    ['approval_works', 'reimbursement_processed']),
  createDocScenario(68, 'Run ticket expense dispute', 'CARRIER_C002',
    ['Question expense', 'Request documentation', 'Driver responds', 'Resolution'],
    ['dispute_works', 'resolution_achieved']),
  createDocScenario(69, 'Run ticket export to accounting', 'CARRIER_C002',
    ['Select date range', 'Export all tickets', 'CSV/PDF format', 'Integration with QuickBooks'],
    ['export_works', 'integration_works']),
  createDocScenario(70, 'Run ticket mileage tracking', 'DRIVER_D003',
    ['Start trip odometer', 'End trip odometer', 'Total miles calculated', 'Fuel efficiency computed'],
    ['mileage_tracked', 'efficiency_calculated']),
  createDocScenario(71, 'Run ticket scale ticket attachment', 'DRIVER_D003',
    ['Upload scale ticket', 'Weight recorded', 'Legal weight verified'],
    ['scale_uploaded', 'weight_verified']),
  createDocScenario(72, 'Run ticket detention documentation', 'DRIVER_D003',
    ['Detention occurs', 'Log start/end time', 'Calculate detention pay', 'Submit claim'],
    ['detention_logged', 'claim_submitted']),
  createDocScenario(73, 'Run ticket IFTA reporting', 'CARRIER_C002',
    ['Quarterly IFTA due', 'Aggregate fuel by state', 'Miles by state', 'Report generated'],
    ['ifta_aggregated', 'report_generated']),
  createDocScenario(74, 'Run ticket history by driver', 'CARRIER_C002',
    ['View driver history', 'All tickets listed', 'Performance metrics', 'Cost per mile'],
    ['history_available', 'metrics_calculated']),
  createDocScenario(75, 'Run ticket mobile entry', 'DRIVER_D003',
    ['On mobile app', 'Quick expense entry', 'Camera receipt capture', 'Offline sync'],
    ['mobile_works', 'offline_sync'])
];

export default DOCUMENT_COMPLIANCE_SCENARIOS;
