/**
 * EUSOTRIP SIMULATION - Gamification Scenarios (100)
 */

import { Scenario } from '../../runners/ScenarioExecutor';

function createGamificationScenario(id: number, name: string, actor: string, steps: string[], validations: string[]): Scenario {
  return {
    id: `GAME-${String(id).padStart(3, '0')}`,
    category: 'GAMIFICATION',
    name,
    actor,
    steps,
    expectedOutcome: name,
    validations
  };
}

export const GAMIFICATION_SCENARIOS: Scenario[] = [
  // XP & Leveling (1-25)
  createGamificationScenario(1, 'Driver earns XP for load completion', 'DRIVER_D003',
    ['Complete load', 'Receive 100 XP', 'XP bar updates', 'Total XP accurate'],
    ['xp_awarded', 'display_updated']),
  createGamificationScenario(2, 'Driver levels up', 'DRIVER_D003',
    ['Reach 1000 XP', 'Level up animation', 'New level badge', 'Rewards unlocked'],
    ['level_up_works', 'rewards_granted']),
  createGamificationScenario(3, 'XP multiplier for streak', 'DRIVER_D010',
    ['5-day streak', '1.5x XP multiplier active', 'Bonus XP on completion'],
    ['multiplier_applied', 'bonus_calculated']),
  createGamificationScenario(4, 'XP for on-time delivery bonus', 'DRIVER_D003',
    ['Deliver early', 'Bonus 50 XP for on-time', 'Total reflected'],
    ['bonus_xp_awarded']),
  createGamificationScenario(5, 'XP for 5-star rating received', 'DRIVER_D005',
    ['Receive 5-star review', 'Earn 25 XP', 'Notification shown'],
    ['review_xp_works']),
  createGamificationScenario(6, 'View XP history breakdown', 'DRIVER_D003',
    ['Open profile', 'View XP history', 'See sources', 'Filter by type'],
    ['history_available', 'filter_works']),
  createGamificationScenario(7, 'Level requirements increase progressively', 'DRIVER_D002',
    ['Level 1: 1000 XP', 'Level 2: 2500 XP', 'Level 3: 5000 XP', 'Curve visible'],
    ['progression_curve_correct']),
  createGamificationScenario(8, 'Maximum level cap', 'DRIVER_D002',
    ['Reach level 50', 'No more level ups', 'Prestige option available'],
    ['level_cap_works', 'prestige_available']),
  createGamificationScenario(9, 'Prestige system reset', 'DRIVER_D002',
    ['Prestige', 'Level resets to 1', 'Prestige badge earned', 'Permanent bonus'],
    ['prestige_works', 'bonus_applied']),
  createGamificationScenario(10, 'XP leaderboard position', 'DRIVER_D003',
    ['View leaderboard', 'See position', 'Filter by time period'],
    ['leaderboard_works', 'position_accurate']),

  // Achievements & Badges (26-50)
  createGamificationScenario(26, 'Unlock first load achievement', 'DRIVER_D016',
    ['Complete first load', 'Achievement unlocked', 'Badge displayed'],
    ['achievement_unlocked', 'badge_shown']),
  createGamificationScenario(27, 'Unlock 100 loads milestone', 'DRIVER_D003',
    ['Complete 100th load', 'Milestone achievement', 'Special reward'],
    ['milestone_unlocked', 'reward_granted']),
  createGamificationScenario(28, 'Unlock on-time streak achievement', 'DRIVER_D010',
    ['10 on-time deliveries in row', 'Streak achievement', 'XP bonus'],
    ['streak_achievement']),
  createGamificationScenario(29, 'Unlock hazmat specialist badge', 'DRIVER_D004',
    ['Complete 50 hazmat loads', 'Specialist badge', 'Profile highlight'],
    ['specialist_badge_earned']),
  createGamificationScenario(30, 'Unlock cross-country badge', 'DRIVER_D002',
    ['Deliver to all 48 states', 'Cross-country badge', 'Map completion shown'],
    ['cross_country_unlocked']),
  createGamificationScenario(31, 'View all available achievements', 'DRIVER_D001',
    ['Open achievements page', 'See all categories', 'Progress shown per achievement'],
    ['achievements_displayed', 'progress_shown']),
  createGamificationScenario(32, 'Hidden achievement discovery', 'DRIVER_D003',
    ['Trigger hidden condition', 'Secret achievement unlocked', 'Surprise notification'],
    ['hidden_achievement_works']),
  createGamificationScenario(33, 'Achievement sharing to social', 'DRIVER_D010',
    ['Unlock achievement', 'Share to social media', 'Formatted post created'],
    ['share_works']),
  createGamificationScenario(34, 'Achievement notification preferences', 'DRIVER_D003',
    ['Configure notifications', 'Only major achievements', 'Test notification'],
    ['preferences_saved']),
  createGamificationScenario(35, 'Tiered achievement system', 'DRIVER_D003',
    ['Bronze: 10 loads', 'Silver: 50 loads', 'Gold: 100 loads', 'Platinum: 500 loads'],
    ['tiers_work']),

  // Daily & Weekly Challenges (51-70)
  createGamificationScenario(51, 'Daily challenge: complete 2 loads', 'DRIVER_D003',
    ['View daily challenge', 'Complete 2 loads', 'Claim reward'],
    ['challenge_completed', 'reward_claimed']),
  createGamificationScenario(52, 'Weekly challenge: earn $5000', 'DRIVER_D010',
    ['View weekly challenge', 'Track progress', 'Complete by Sunday', 'Bonus XP'],
    ['weekly_tracked', 'bonus_awarded']),
  createGamificationScenario(53, 'Challenge expiration', 'DRIVER_D001',
    ['Daily challenge not completed', 'Expires at midnight', 'New challenge next day'],
    ['expiration_works', 'new_challenge_generated']),
  createGamificationScenario(54, 'Bonus challenge for premium users', 'DRIVER_D002',
    ['Premium subscription', 'Extra challenge available', 'Higher rewards'],
    ['premium_challenge_works']),
  createGamificationScenario(55, 'Challenge difficulty scaling', 'DRIVER_D003',
    ['New user: easier challenges', 'Veteran: harder challenges', 'Scaling based on history'],
    ['difficulty_scales']),
  createGamificationScenario(56, 'Team challenge completion', 'CARRIER_C002',
    ['Fleet challenge: 50 loads', 'All drivers contribute', 'Team reward'],
    ['team_challenge_works']),
  createGamificationScenario(57, 'Challenge progress notification', 'DRIVER_D003',
    ['50% progress on challenge', 'Notification sent', 'Encouragement message'],
    ['progress_notification']),
  createGamificationScenario(58, 'Skip challenge option', 'DRIVER_D005',
    ['Challenge too hard', 'Skip and get new one', 'One skip per day'],
    ['skip_works', 'limit_enforced']),
  createGamificationScenario(59, 'Challenge reward variety', 'DRIVER_D003',
    ['XP rewards', 'Wallet bonus', 'Badge rewards', 'All types work'],
    ['reward_variety']),
  createGamificationScenario(60, 'Challenge completion streak', 'DRIVER_D010',
    ['7-day challenge streak', 'Streak bonus', 'Streak broken penalty'],
    ['streak_bonus_works']),

  // Leaderboards & Competition (71-85)
  createGamificationScenario(71, 'Global leaderboard view', 'DRIVER_D003',
    ['View global leaderboard', 'Top 100 displayed', 'Own rank shown'],
    ['leaderboard_displays', 'rank_shown']),
  createGamificationScenario(72, 'Regional leaderboard filter', 'DRIVER_D003',
    ['Filter by Texas region', 'Regional rankings', 'Compete locally'],
    ['regional_filter_works']),
  createGamificationScenario(73, 'Weekly leaderboard reset', 'SYSTEM',
    ['Week ends', 'Leaderboard resets', 'Winners announced'],
    ['reset_works', 'winners_notified']),
  createGamificationScenario(74, 'Leaderboard prize distribution', 'ADMIN_A001',
    ['Week ends', 'Top 10 get prizes', 'Wallet credits added'],
    ['prizes_distributed']),
  createGamificationScenario(75, 'Carrier fleet leaderboard', 'CARRIER_C002',
    ['View fleet ranking', 'Compare against other carriers'],
    ['fleet_leaderboard_works']),
  createGamificationScenario(76, 'Friend leaderboard', 'DRIVER_D003',
    ['Add friends', 'View friend leaderboard', 'Compete with friends'],
    ['friend_leaderboard_works']),
  createGamificationScenario(77, 'Leaderboard anti-cheat', 'SYSTEM',
    ['Suspicious activity detected', 'Flagged for review', 'Invalid entries removed'],
    ['anti_cheat_works']),
  createGamificationScenario(78, 'Seasonal leaderboard event', 'SYSTEM',
    ['Holiday season event', 'Special leaderboard', 'Themed rewards'],
    ['seasonal_event_works']),

  // Rewards & Redemption (86-100)
  createGamificationScenario(86, 'Redeem points for wallet credit', 'DRIVER_D003',
    ['Earn 5000 points', 'Redeem for $50 credit', 'Wallet updated'],
    ['redemption_works', 'wallet_credited']),
  createGamificationScenario(87, 'Redeem points for fuel discount', 'DRIVER_D010',
    ['Redeem for 10% fuel discount', 'Discount code generated', 'Works at pump'],
    ['fuel_discount_works']),
  createGamificationScenario(88, 'Redeem points for merchandise', 'DRIVER_D003',
    ['Browse rewards catalog', 'Select item', 'Shipping address', 'Order placed'],
    ['merchandise_redemption_works']),
  createGamificationScenario(89, 'Points expiration warning', 'DRIVER_D005',
    ['Points expiring in 30 days', 'Warning notification', 'Reminder to redeem'],
    ['expiration_warning']),
  createGamificationScenario(90, 'Exclusive reward tiers', 'DRIVER_D002',
    ['Platinum tier unlocks exclusive rewards', 'Premium items available'],
    ['tier_exclusives_work']),
  createGamificationScenario(91, 'Reward shipping tracking', 'DRIVER_D003',
    ['Order merchandise', 'Track shipment', 'Delivery confirmed'],
    ['shipping_tracking_works']),
  createGamificationScenario(92, 'Digital reward instant delivery', 'DRIVER_D003',
    ['Redeem digital reward', 'Instant delivery', 'Code received'],
    ['digital_reward_works']),
  createGamificationScenario(93, 'Refer a friend bonus', 'DRIVER_D010',
    ['Refer new driver', 'Friend signs up', 'Both get bonus'],
    ['referral_works', 'both_rewarded']),
  createGamificationScenario(94, 'Reward catalog browsing', 'DRIVER_D001',
    ['Browse categories', 'Filter by points', 'Sort by popularity'],
    ['catalog_works']),
  createGamificationScenario(95, 'Insufficient points message', 'DRIVER_D016',
    ['Try to redeem expensive item', 'Insufficient points', 'Show how many needed'],
    ['insufficient_handled']),
  createGamificationScenario(96, 'Points transfer between users', 'DRIVER_D003',
    ['Transfer 1000 points to friend', 'Confirmation required', 'Points moved'],
    ['transfer_works']),
  createGamificationScenario(97, 'Gamification opt-out option', 'DRIVER_D020',
    ['Disable gamification', 'Points hidden', 'Challenges hidden'],
    ['opt_out_works']),
  createGamificationScenario(98, 'Gamification analytics for admin', 'ADMIN_A001',
    ['View engagement metrics', 'Redemption rates', 'Popular rewards'],
    ['analytics_available']),
  createGamificationScenario(99, 'A/B test reward values', 'ADMIN_A001',
    ['Set up A/B test', 'Different point values', 'Track conversion'],
    ['ab_test_works']),
  createGamificationScenario(100, 'Gamification API for partners', 'EXTERNAL_SYSTEM',
    ['Partner queries points', 'API returns data', 'Integration works'],
    ['api_works'])
];

export default GAMIFICATION_SCENARIOS;
