/**
 * EUSOTRIP SIMULATION - Terminal Operations Scenarios (60)
 */

import { Scenario } from '../../runners/ScenarioExecutor';

function createTerminalScenario(id: number, name: string, actor: string, steps: string[], validations: string[]): Scenario {
  return {
    id: `TERM-${String(id).padStart(3, '0')}`,
    category: 'TERMINAL',
    name,
    actor,
    steps,
    expectedOutcome: name,
    validations
  };
}

export const TERMINAL_SCENARIOS: Scenario[] = [
  // Check-In/Check-Out (1-15)
  createTerminalScenario(1, 'Driver check-in at terminal', 'DRIVER_D003',
    ['Arrive at terminal', 'Scan QR code', 'Verify load info', 'Check-in confirmed'],
    ['checkin_works', 'timestamp_logged']),
  createTerminalScenario(2, 'Automated gate check-in', 'SYSTEM',
    ['Truck approaches gate', 'License plate scanned', 'Auto-identified', 'Gate opens'],
    ['auto_checkin_works']),
  createTerminalScenario(3, 'Dock door assignment', 'TERMINAL_T001',
    ['Driver checked in', 'Dock assigned', 'Driver notified', 'Map to dock'],
    ['dock_assigned', 'directions_provided']),
  createTerminalScenario(4, 'Driver check-out after loading', 'DRIVER_D003',
    ['Loading complete', 'BOL signed', 'Check-out', 'Gate pass generated'],
    ['checkout_works', 'gate_pass_generated']),
  createTerminalScenario(5, 'Drop trailer check-in', 'DRIVER_D007',
    ['Arrive with drop trailer', 'Check-in trailer only', 'Assigned yard spot'],
    ['drop_trailer_works']),
  createTerminalScenario(6, 'Bobtail check-in for pickup', 'DRIVER_D003',
    ['Arrive bobtail', 'Trailer assigned', 'Pick up loaded trailer'],
    ['bobtail_pickup_works']),
  createTerminalScenario(7, 'Reschedule appointment at check-in', 'DRIVER_D005',
    ['Early arrival', 'Appointment conflict', 'Reschedule option', 'New time set'],
    ['reschedule_works']),
  createTerminalScenario(8, 'Express check-in for priority', 'DRIVER_D002',
    ['Priority driver', 'Express lane', 'Faster processing'],
    ['express_works']),
  createTerminalScenario(9, 'Check-in with missing paperwork', 'DRIVER_D001',
    ['Missing BOL', 'Issue flagged', 'Hold for resolution'],
    ['paperwork_validation_works']),
  createTerminalScenario(10, 'Multiple trailers check-in', 'DRIVER_D012',
    ['Team driver', 'Two trailers', 'Both processed'],
    ['multiple_trailers_work']),

  // Dock Management (16-30)
  createTerminalScenario(16, 'View dock status dashboard', 'TERMINAL_T001',
    ['Open dashboard', 'See all docks', 'Status: available/occupied/maintenance'],
    ['dashboard_works']),
  createTerminalScenario(17, 'Assign truck to dock', 'TERMINAL_T001',
    ['Select waiting truck', 'Assign to dock 5', 'Driver notified'],
    ['assignment_works']),
  createTerminalScenario(18, 'Mark dock under maintenance', 'TERMINAL_T001',
    ['Dock 3 needs repair', 'Mark maintenance', 'Removed from rotation'],
    ['maintenance_marking_works']),
  createTerminalScenario(19, 'Dock occupancy timing', 'SYSTEM',
    ['Truck at dock', 'Timer starts', 'Loading time tracked'],
    ['timing_works']),
  createTerminalScenario(20, 'Dock priority queue', 'SYSTEM',
    ['Multiple trucks waiting', 'Priority assigned', 'Queue managed'],
    ['queue_works']),
  createTerminalScenario(21, 'Dock capacity optimization', 'SYSTEM',
    ['Analyze dock usage', 'Suggest improvements', 'Reduce wait time'],
    ['optimization_works']),
  createTerminalScenario(22, 'Real-time dock availability', 'DRIVER_D003',
    ['Check terminal status', 'See available docks', 'Estimated wait time'],
    ['availability_shown']),
  createTerminalScenario(23, 'Dock equipment tracking', 'TERMINAL_T001',
    ['Track forklifts', 'Track pallet jacks', 'Equipment at each dock'],
    ['equipment_tracking_works']),
  createTerminalScenario(24, 'Dock alarm system', 'SYSTEM',
    ['Safety violation', 'Alarm triggered', 'Operations notified'],
    ['alarm_works']),
  createTerminalScenario(25, 'Dock throughput reporting', 'TERMINAL_T001',
    ['View daily throughput', 'Trucks processed', 'Average time'],
    ['reporting_works']),

  // Yard Management (31-45)
  createTerminalScenario(31, 'Yard map visualization', 'TERMINAL_T001',
    ['View yard map', 'Trailer locations', 'Available spots'],
    ['yard_map_works']),
  createTerminalScenario(32, 'Trailer location tracking', 'TERMINAL_T001',
    ['Search trailer number', 'Show location on map', 'Status displayed'],
    ['trailer_tracking_works']),
  createTerminalScenario(33, 'Yard spot assignment', 'TERMINAL_T001',
    ['Incoming trailer', 'Assign spot B-15', 'Driver directed'],
    ['spot_assignment_works']),
  createTerminalScenario(34, 'Trailer move request', 'TERMINAL_T001',
    ['Request trailer move', 'Yard jockey assigned', 'Move completed'],
    ['move_request_works']),
  createTerminalScenario(35, 'Yard inventory count', 'TERMINAL_T001',
    ['Initiate yard check', 'Verify all trailers', 'Discrepancies flagged'],
    ['inventory_works']),
  createTerminalScenario(36, 'Dwell time alert', 'SYSTEM',
    ['Trailer at yard 48+ hours', 'Alert generated', 'Action required'],
    ['dwell_alert_works']),
  createTerminalScenario(37, 'Yard capacity monitoring', 'TERMINAL_T001',
    ['Capacity 90%', 'Warning displayed', 'Overflow plan'],
    ['capacity_monitoring_works']),
  createTerminalScenario(38, 'Yard zone configuration', 'TERMINAL_T001',
    ['Configure zones', 'Reefer zone', 'Hazmat zone', 'Empty zone'],
    ['zone_config_works']),
  createTerminalScenario(39, 'Reefer monitoring in yard', 'SYSTEM',
    ['Reefer in yard', 'Temp monitored', 'Alert on deviation'],
    ['reefer_monitoring_works']),
  createTerminalScenario(40, 'Yard jockey dispatch', 'TERMINAL_T001',
    ['Move needed', 'Dispatch jockey', 'Track progress'],
    ['jockey_dispatch_works']),

  // Appointments & Scheduling (46-60)
  createTerminalScenario(46, 'Schedule delivery appointment', 'BROKER_B001',
    ['Select terminal', 'Choose date/time', 'Appointment confirmed'],
    ['appointment_works']),
  createTerminalScenario(47, 'View appointment calendar', 'TERMINAL_T001',
    ['Open calendar', 'See all appointments', 'Filter by type'],
    ['calendar_works']),
  createTerminalScenario(48, 'Appointment conflict detection', 'SYSTEM',
    ['Double-booking attempted', 'Conflict detected', 'Alternative suggested'],
    ['conflict_detection_works']),
  createTerminalScenario(49, 'Cancel appointment', 'BROKER_B001',
    ['Cancel appointment', 'Slot freed', 'All parties notified'],
    ['cancel_works']),
  createTerminalScenario(50, 'Appointment reminder', 'SYSTEM',
    ['24 hours before', 'Reminder sent', 'Driver confirms'],
    ['reminder_works']),
  createTerminalScenario(51, 'Late arrival handling', 'TERMINAL_T001',
    ['Driver 30 min late', 'Slot forfeited', 'Reschedule required'],
    ['late_handling_works']),
  createTerminalScenario(52, 'Walk-up handling', 'TERMINAL_T001',
    ['Unscheduled arrival', 'Fit into schedule', 'Extended wait time'],
    ['walkin_works']),
  createTerminalScenario(53, 'Peak hour slot pricing', 'SYSTEM',
    ['Premium time slot', 'Higher fee displayed', 'Off-peak discount'],
    ['pricing_works']),
  createTerminalScenario(54, 'Recurring appointment', 'SHIPPER_S002',
    ['Set weekly recurring', 'Auto-scheduled', 'Exceptions handled'],
    ['recurring_works']),
  createTerminalScenario(55, 'Appointment analytics', 'TERMINAL_T001',
    ['View no-show rate', 'Average wait time', 'Utilization rate'],
    ['analytics_works']),
  createTerminalScenario(56, 'Third-party appointment sync', 'SYSTEM',
    ['Sync with shipper system', 'Appointments imported', 'Updates synced'],
    ['third_party_sync_works']),
  createTerminalScenario(57, 'Emergency appointment override', 'TERMINAL_T001',
    ['Urgent shipment', 'Override normal schedule', 'Priority handling'],
    ['override_works']),
  createTerminalScenario(58, 'Appointment slot release', 'SYSTEM',
    ['Unused slot', 'Release to waitlist', 'Notify interested'],
    ['release_works']),
  createTerminalScenario(59, 'Multi-terminal coordination', 'BROKER_B002',
    ['Schedule at 3 terminals', 'Route optimization', 'Timing coordinated'],
    ['multi_terminal_works']),
  createTerminalScenario(60, 'Terminal closed day handling', 'SYSTEM',
    ['Holiday closure', 'Appointments blocked', 'Reschedule notification'],
    ['closure_handling_works'])
];

export default TERMINAL_SCENARIOS;
