/**
 * COMPLETE 12-ROLE PERMISSION MATRIX
 * Maps every EusoTrip role to its allowed permissions.
 * From EusoTrip_Security_Architecture.md Section 4.3
 */

import type { Permission, Action, Resource, Scope } from "./permissions";

type UserRole =
  | "DRIVER" | "ESCORT" | "CATALYST" | "SHIPPER" | "BROKER"
  | "DISPATCH" | "TERMINAL_MANAGER" | "COMPLIANCE_OFFICER"
  | "SAFETY_MANAGER" | "FACTORING" | "ADMIN" | "SUPER_ADMIN";

function p(action: Action, resource: Resource, scope: Scope): Permission {
  return { action, resource, scope };
}

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  // ─── TIER 2: FIELD OPERATORS ──────────────────────────────────────────────
  DRIVER: [
    // Load
    p("READ", "LOAD", "OWN"),
    p("UPDATE", "LOAD", "OWN"), // Status updates (at pickup, in transit, delivered)
    // GPS
    p("CREATE", "GPS_BREADCRUMB", "OWN"),
    p("CREATE", "GEOTAG", "OWN"),
    p("READ", "GEOTAG", "OWN"),
    p("READ", "ROUTE", "OWN"),
    // Documents
    p("CREATE", "DOCUMENT", "OWN"),
    p("READ", "DOCUMENT", "OWN"),
    p("CREATE", "BOL", "OWN"),
    p("READ", "BOL", "OWN"),
    p("CREATE", "POD", "OWN"),
    p("READ", "POD", "OWN"),
    // Financial
    p("READ", "WALLET", "OWN"),
    p("READ", "INVOICE", "OWN"),
    p("READ", "PAYMENT", "OWN"),
    // User
    p("READ", "USER", "OWN"),
    p("UPDATE", "USER", "OWN"),
    // Sensitive (own only)
    p("READ", "SSN", "OWN"),
    p("READ", "CDL_NUMBER", "OWN"),
    p("READ", "BANK_ACCOUNT", "OWN"),
    p("READ", "MEDICAL_CERT", "OWN"),
    // Communication
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
    // Compliance
    p("READ", "SAFETY_EVENT", "OWN"),
    p("CREATE", "INCIDENT_REPORT", "OWN"),
    p("READ", "INCIDENT_REPORT", "OWN"),
    // Gamification
    p("READ", "MISSION", "OWN"),
    p("READ", "ACHIEVEMENT", "OWN"),
    p("READ", "REWARD", "OWN"),
  ],

  ESCORT: [
    p("READ", "LOAD", "OWN"),
    p("CREATE", "GPS_BREADCRUMB", "OWN"),
    p("CREATE", "GEOTAG", "OWN"),
    p("READ", "GEOTAG", "OWN"),
    p("READ", "ROUTE", "OWN"),
    p("READ", "WALLET", "OWN"),
    p("READ", "INVOICE", "OWN"),
    p("READ", "PAYMENT", "OWN"),
    p("READ", "USER", "OWN"),
    p("UPDATE", "USER", "OWN"),
    p("READ", "SSN", "OWN"),
    p("READ", "BANK_ACCOUNT", "OWN"),
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
    p("CREATE", "DOCUMENT", "OWN"),
    p("READ", "DOCUMENT", "OWN"),
    p("READ", "SAFETY_EVENT", "OWN"),
    p("READ", "MISSION", "OWN"),
    p("READ", "ACHIEVEMENT", "OWN"),
  ],

  // ─── TIER 3: BUSINESS OPERATORS ───────────────────────────────────────────
  CATALYST: [
    // Loads (company fleet)
    p("CREATE", "LOAD", "COMPANY"),
    p("READ", "LOAD", "COMPANY"),
    p("UPDATE", "LOAD", "COMPANY"),
    p("DELETE", "LOAD", "COMPANY"),
    // Bids
    p("CREATE", "BID", "COMPANY"),
    p("READ", "BID", "COMPANY"),
    p("UPDATE", "BID", "COMPANY"),
    p("DELETE", "BID", "COMPANY"),
    // Fleet
    p("CREATE", "VEHICLE", "COMPANY"),
    p("READ", "VEHICLE", "COMPANY"),
    p("UPDATE", "VEHICLE", "COMPANY"),
    p("DELETE", "VEHICLE", "COMPANY"),
    p("CREATE", "EQUIPMENT", "COMPANY"),
    p("READ", "EQUIPMENT", "COMPANY"),
    p("UPDATE", "EQUIPMENT", "COMPANY"),
    p("DELETE", "EQUIPMENT", "COMPANY"),
    // Drivers
    p("CREATE", "DRIVER", "COMPANY"),
    p("READ", "DRIVER", "COMPANY"),
    p("UPDATE", "DRIVER", "COMPANY"),
    p("DELETE", "DRIVER", "COMPANY"),
    // GPS
    p("READ", "GPS_BREADCRUMB", "COMPANY"),
    p("READ", "GEOTAG", "COMPANY"),
    p("READ", "GEOFENCE", "COMPANY"),
    p("READ", "ROUTE", "COMPANY"),
    // Financial
    p("READ", "WALLET", "OWN"),
    p("CREATE", "INVOICE", "COMPANY"),
    p("READ", "INVOICE", "COMPANY"),
    p("UPDATE", "INVOICE", "COMPANY"),
    p("READ", "PAYMENT", "COMPANY"),
    // Documents
    p("CREATE", "DOCUMENT", "COMPANY"),
    p("READ", "DOCUMENT", "COMPANY"),
    p("UPDATE", "DOCUMENT", "COMPANY"),
    p("CREATE", "BOL", "COMPANY"),
    p("READ", "BOL", "COMPANY"),
    p("CREATE", "POD", "COMPANY"),
    p("READ", "POD", "COMPANY"),
    p("CREATE", "RATE_CONFIRMATION", "COMPANY"),
    p("READ", "RATE_CONFIRMATION", "COMPANY"),
    // User management (company)
    p("CREATE", "USER", "COMPANY"),
    p("READ", "USER", "COMPANY"),
    p("UPDATE", "USER", "COMPANY"),
    p("DELETE", "USER", "COMPANY"),
    // Sensitive (company scope)
    p("READ", "CDL_NUMBER", "COMPANY"),
    p("READ", "BANK_ACCOUNT", "COMPANY"),
    p("UPDATE", "BANK_ACCOUNT", "COMPANY"),
    // Compliance
    p("READ", "COMPLIANCE_RECORD", "COMPANY"),
    p("READ", "SAFETY_EVENT", "COMPANY"),
    p("READ", "AUDIT_LOG", "COMPANY"),
    // Communication
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
    // Agreements
    p("CREATE", "AGREEMENT", "COMPANY"),
    p("READ", "AGREEMENT", "COMPANY"),
    p("UPDATE", "AGREEMENT", "COMPANY"),
    // Gamification
    p("READ", "MISSION", "OWN"),
    p("READ", "ACHIEVEMENT", "OWN"),
    p("READ", "REWARD", "OWN"),
  ],

  SHIPPER: [
    p("CREATE", "LOAD", "COMPANY"),
    p("READ", "LOAD", "COMPANY"),
    p("UPDATE", "LOAD", "COMPANY"),
    p("DELETE", "LOAD", "COMPANY"),
    p("READ", "BID", "LINKED"),
    p("APPROVE", "BID", "COMPANY"),
    p("READ", "GPS_BREADCRUMB", "LINKED"),
    p("READ", "GEOTAG", "LINKED"),
    p("READ", "ROUTE", "LINKED"),
    p("READ", "WALLET", "OWN"),
    p("CREATE", "PAYMENT", "COMPANY"),
    p("READ", "PAYMENT", "COMPANY"),
    p("UPDATE", "PAYMENT", "COMPANY"),
    p("READ", "INVOICE", "LINKED"),
    p("CREATE", "DOCUMENT", "COMPANY"),
    p("READ", "DOCUMENT", "COMPANY"),
    p("CREATE", "BOL", "COMPANY"),
    p("READ", "BOL", "COMPANY"),
    p("READ", "POD", "LINKED"),
    p("CREATE", "RATE_CONFIRMATION", "COMPANY"),
    p("READ", "RATE_CONFIRMATION", "COMPANY"),
    p("CREATE", "USER", "COMPANY"),
    p("READ", "USER", "COMPANY"),
    p("UPDATE", "USER", "COMPANY"),
    p("DELETE", "USER", "COMPANY"),
    p("READ", "BANK_ACCOUNT", "COMPANY"),
    p("UPDATE", "BANK_ACCOUNT", "COMPANY"),
    p("READ", "COMPLIANCE_RECORD", "COMPANY"),
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
    p("CREATE", "AGREEMENT", "COMPANY"),
    p("READ", "AGREEMENT", "COMPANY"),
    p("UPDATE", "AGREEMENT", "COMPANY"),
    p("READ", "MISSION", "OWN"),
    p("READ", "ACHIEVEMENT", "OWN"),
    p("CREATE", "DETENTION_CHARGE", "COMPANY"),
    p("READ", "DETENTION_CHARGE", "COMPANY"),
    // Supply Chain — view own terminal partnerships
    p("READ", "TERMINAL_PARTNER", "LINKED"),
    p("READ", "SUPPLY_CHAIN_CONFIG", "OWN"),
    p("UPDATE", "SUPPLY_CHAIN_CONFIG", "OWN"),
  ],

  BROKER: [
    p("CREATE", "LOAD", "COMPANY"),
    p("READ", "LOAD", "COMPANY"),
    p("UPDATE", "LOAD", "COMPANY"),
    p("DELETE", "LOAD", "COMPANY"),
    p("CREATE", "BID", "COMPANY"),
    p("READ", "BID", "COMPANY"),
    p("UPDATE", "BID", "COMPANY"),
    p("DELETE", "BID", "COMPANY"),
    p("READ", "GPS_BREADCRUMB", "LINKED"),
    p("READ", "GEOTAG", "LINKED"),
    p("READ", "ROUTE", "LINKED"),
    p("READ", "WALLET", "OWN"),
    p("CREATE", "INVOICE", "COMPANY"),
    p("READ", "INVOICE", "COMPANY"),
    p("UPDATE", "INVOICE", "COMPANY"),
    p("CREATE", "PAYMENT", "COMPANY"),
    p("READ", "PAYMENT", "COMPANY"),
    p("CREATE", "DOCUMENT", "COMPANY"),
    p("READ", "DOCUMENT", "COMPANY"),
    p("CREATE", "RATE_CONFIRMATION", "COMPANY"),
    p("READ", "RATE_CONFIRMATION", "COMPANY"),
    p("CREATE", "USER", "COMPANY"),
    p("READ", "USER", "COMPANY"),
    p("UPDATE", "USER", "COMPANY"),
    p("READ", "BANK_ACCOUNT", "COMPANY"),
    p("UPDATE", "BANK_ACCOUNT", "COMPANY"),
    p("READ", "COMPLIANCE_RECORD", "COMPANY"),
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
    p("CREATE", "AGREEMENT", "COMPANY"),
    p("READ", "AGREEMENT", "COMPANY"),
    p("UPDATE", "AGREEMENT", "COMPANY"),
    p("READ", "AUDIT_LOG", "COMPANY"),
    p("READ", "MISSION", "OWN"),
    p("READ", "ACHIEVEMENT", "OWN"),
    // Supply Chain — view terminal partnerships
    p("READ", "TERMINAL_PARTNER", "LINKED"),
  ],

  DISPATCH: [
    p("READ", "LOAD", "COMPANY"),
    p("UPDATE", "LOAD", "COMPANY"),
    p("READ", "BID", "COMPANY"),
    p("READ", "DRIVER", "COMPANY"),
    p("READ", "VEHICLE", "COMPANY"),
    p("READ", "EQUIPMENT", "COMPANY"),
    p("READ", "GPS_BREADCRUMB", "COMPANY"),
    p("READ", "GEOTAG", "COMPANY"),
    p("CREATE", "GEOFENCE", "COMPANY"),
    p("READ", "GEOFENCE", "COMPANY"),
    p("READ", "ROUTE", "COMPANY"),
    p("READ", "WALLET", "OWN"),
    p("READ", "PAYMENT", "OWN"),
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
    p("READ", "DOCUMENT", "COMPANY"),
    p("READ", "COMPLIANCE_RECORD", "COMPANY"),
    p("READ", "USER", "COMPANY"),
    p("READ", "MISSION", "OWN"),
  ],

  FACTORING: [
    p("READ", "LOAD", "LINKED"),
    p("CREATE", "FACTORING_ADVANCE", "COMPANY"),
    p("READ", "FACTORING_ADVANCE", "COMPANY"),
    p("UPDATE", "FACTORING_ADVANCE", "COMPANY"),
    p("CREATE", "INVOICE", "LINKED"),
    p("READ", "INVOICE", "LINKED"),
    p("UPDATE", "INVOICE", "LINKED"),
    p("CREATE", "PAYMENT", "LINKED"),
    p("READ", "PAYMENT", "LINKED"),
    p("READ", "WALLET", "OWN"),
    p("READ", "GEOTAG", "LINKED"),
    p("READ", "BANK_ACCOUNT", "COMPANY"),
    p("UPDATE", "BANK_ACCOUNT", "COMPANY"),
    p("CREATE", "USER", "COMPANY"),
    p("READ", "USER", "COMPANY"),
    p("UPDATE", "USER", "COMPANY"),
    p("DELETE", "USER", "COMPANY"),
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
    p("CREATE", "DOCUMENT", "COMPANY"),
    p("READ", "DOCUMENT", "COMPANY"),
  ],

  // ─── TIER 4: COMPANY ADMIN ────────────────────────────────────────────────
  TERMINAL_MANAGER: [
    p("READ", "LOAD", "COMPANY"),
    p("UPDATE", "LOAD", "COMPANY"),
    p("READ", "DRIVER", "COMPANY"),
    p("READ", "CDL_NUMBER", "COMPANY"),
    p("READ", "GPS_BREADCRUMB", "COMPANY"),
    p("CREATE", "GEOTAG", "COMPANY"),
    p("READ", "GEOTAG", "COMPANY"),
    p("CREATE", "GEOFENCE", "COMPANY"),
    p("READ", "GEOFENCE", "COMPANY"),
    p("UPDATE", "GEOFENCE", "COMPANY"),
    p("DELETE", "GEOFENCE", "COMPANY"),
    p("READ", "WALLET", "OWN"),
    p("CREATE", "USER", "COMPANY"),
    p("READ", "USER", "COMPANY"),
    p("UPDATE", "USER", "COMPANY"),
    p("DELETE", "USER", "COMPANY"),
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
    p("CREATE", "DOCUMENT", "COMPANY"),
    p("READ", "DOCUMENT", "COMPANY"),
    p("READ", "COMPLIANCE_RECORD", "COMPANY"),
    p("READ", "SAFETY_EVENT", "COMPANY"),
    p("READ", "AUDIT_LOG", "COMPANY"),
    p("CREATE", "DETENTION_CHARGE", "COMPANY"),
    p("READ", "DETENTION_CHARGE", "COMPANY"),
    p("CREATE", "BOL", "COMPANY"),
    p("READ", "BOL", "COMPANY"),
    // Supply Chain — Terminal Partner management
    p("CREATE", "TERMINAL_PARTNER", "COMPANY"),
    p("READ", "TERMINAL_PARTNER", "COMPANY"),
    p("UPDATE", "TERMINAL_PARTNER", "COMPANY"),
    p("DELETE", "TERMINAL_PARTNER", "COMPANY"),
    p("READ", "SUPPLY_CHAIN_CONFIG", "COMPANY"),
    p("UPDATE", "SUPPLY_CHAIN_CONFIG", "COMPANY"),
  ],

  COMPLIANCE_OFFICER: [
    p("READ", "LOAD", "COMPANY"),
    p("READ", "DRIVER", "COMPANY"),
    p("READ", "VEHICLE", "COMPANY"),
    p("READ", "EQUIPMENT", "COMPANY"),
    p("READ", "CDL_NUMBER", "COMPANY"),
    p("READ", "SSN", "COMPANY"),
    p("READ", "MEDICAL_CERT", "COMPANY"),
    p("CREATE", "COMPLIANCE_RECORD", "COMPANY"),
    p("READ", "COMPLIANCE_RECORD", "COMPANY"),
    p("UPDATE", "COMPLIANCE_RECORD", "COMPANY"),
    p("READ", "SAFETY_EVENT", "COMPANY"),
    p("READ", "INCIDENT_REPORT", "COMPANY"),
    p("READ", "AUDIT_LOG", "COMPANY"),
    p("READ", "DOCUMENT", "COMPANY"),
    p("READ", "USER", "COMPANY"),
    p("READ", "WALLET", "OWN"),
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
    p("READ", "GPS_BREADCRUMB", "COMPANY"),
    p("READ", "GEOTAG", "COMPANY"),
    p("READ", "GEOFENCE", "COMPANY"),
  ],

  SAFETY_MANAGER: [
    p("READ", "LOAD", "COMPANY"),
    p("READ", "DRIVER", "COMPANY"),
    p("READ", "VEHICLE", "COMPANY"),
    p("READ", "CDL_NUMBER", "COMPANY"),
    p("READ", "MEDICAL_CERT", "COMPANY"),
    p("CREATE", "SAFETY_EVENT", "COMPANY"),
    p("READ", "SAFETY_EVENT", "COMPANY"),
    p("UPDATE", "SAFETY_EVENT", "COMPANY"),
    p("DELETE", "SAFETY_EVENT", "COMPANY"),
    p("CREATE", "INCIDENT_REPORT", "COMPANY"),
    p("READ", "INCIDENT_REPORT", "COMPANY"),
    p("UPDATE", "INCIDENT_REPORT", "COMPANY"),
    p("READ", "COMPLIANCE_RECORD", "COMPANY"),
    p("READ", "AUDIT_LOG", "COMPANY"),
    p("READ", "GPS_BREADCRUMB", "COMPANY"),
    p("READ", "GEOTAG", "COMPANY"),
    p("READ", "GEOFENCE", "COMPANY"),
    p("READ", "DOCUMENT", "COMPANY"),
    p("READ", "USER", "COMPANY"),
    p("READ", "WALLET", "OWN"),
    p("CREATE", "MESSAGE", "OWN"),
    p("READ", "MESSAGE", "OWN"),
    p("READ", "CONVERSATION", "OWN"),
    p("READ", "NOTIFICATION", "OWN"),
  ],

  // ─── TIER 5-6: PLATFORM ADMIN ─────────────────────────────────────────────
  ADMIN: [
    // CRUD all primary resources
    ...["LOAD", "BID", "RATE_CONFIRMATION", "BOL", "POD",
        "USER", "COMPANY", "DRIVER", "VEHICLE", "EQUIPMENT",
        "INVOICE", "PAYMENT", "REFUND", "DETENTION_CHARGE",
        "DOCUMENT", "AGREEMENT", "COMPLIANCE_RECORD",
        "SAFETY_EVENT", "INCIDENT_REPORT",
        "MESSAGE", "CONVERSATION", "NOTIFICATION",
        "MISSION", "ACHIEVEMENT", "REWARD",
        "GEOFENCE", "FACTORING_ADVANCE",
        "TERMINAL_PARTNER", "SUPPLY_CHAIN_CONFIG",
    ].flatMap(r => [
      p("CREATE", r as Resource, "PLATFORM"),
      p("READ", r as Resource, "PLATFORM"),
      p("UPDATE", r as Resource, "PLATFORM"),
      p("DELETE", r as Resource, "PLATFORM"),
    ]),
    // Read-only for sensitive
    p("READ", "WALLET", "PLATFORM"),
    p("READ", "SSN", "PLATFORM"),
    p("READ", "BANK_ACCOUNT", "PLATFORM"),
    p("READ", "CDL_NUMBER", "PLATFORM"),
    p("READ", "MEDICAL_CERT", "PLATFORM"),
    p("READ", "GPS_BREADCRUMB", "PLATFORM"),
    p("READ", "GEOTAG", "PLATFORM"),
    p("READ", "ROUTE", "PLATFORM"),
    p("READ", "AUDIT_LOG", "PLATFORM"),
    p("EXPORT", "AUDIT_LOG", "PLATFORM"),
    p("READ", "SYSTEM_CONFIG", "PLATFORM"),
    p("READ", "API_KEY", "PLATFORM"),
    p("UPDATE", "API_KEY", "PLATFORM"),
    p("READ", "PLATFORM_FEES", "PLATFORM"),
  ],

  SUPER_ADMIN: [
    // Everything ADMIN has, plus SYSTEM scope
    ...["LOAD", "BID", "RATE_CONFIRMATION", "BOL", "POD",
        "USER", "COMPANY", "DRIVER", "VEHICLE", "EQUIPMENT",
        "WALLET", "INVOICE", "PAYMENT", "REFUND", "DETENTION_CHARGE",
        "DOCUMENT", "AGREEMENT", "COMPLIANCE_RECORD",
        "SAFETY_EVENT", "INCIDENT_REPORT",
        "MESSAGE", "CONVERSATION", "NOTIFICATION",
        "MISSION", "ACHIEVEMENT", "REWARD",
        "GPS_BREADCRUMB", "GEOFENCE", "GEOTAG", "ROUTE",
        "FACTORING_ADVANCE",
        "TERMINAL_PARTNER", "SUPPLY_CHAIN_CONFIG",
    ].flatMap(r => [
      p("CREATE", r as Resource, "PLATFORM"),
      p("READ", r as Resource, "PLATFORM"),
      p("UPDATE", r as Resource, "PLATFORM"),
      p("DELETE", r as Resource, "PLATFORM"),
      p("EXPORT", r as Resource, "PLATFORM"),
    ]),
    // Sensitive data — full access
    p("READ", "SSN", "PLATFORM"),
    p("READ", "BANK_ACCOUNT", "PLATFORM"),
    p("CREATE", "BANK_ACCOUNT", "PLATFORM"),
    p("UPDATE", "BANK_ACCOUNT", "PLATFORM"),
    p("DELETE", "BANK_ACCOUNT", "PLATFORM"),
    p("READ", "CDL_NUMBER", "PLATFORM"),
    p("READ", "MEDICAL_CERT", "PLATFORM"),
    // System — full control
    p("CREATE", "SYSTEM_CONFIG", "SYSTEM"),
    p("READ", "SYSTEM_CONFIG", "SYSTEM"),
    p("UPDATE", "SYSTEM_CONFIG", "SYSTEM"),
    p("DELETE", "SYSTEM_CONFIG", "SYSTEM"),
    p("CREATE", "API_KEY", "SYSTEM"),
    p("READ", "API_KEY", "SYSTEM"),
    p("UPDATE", "API_KEY", "SYSTEM"),
    p("DELETE", "API_KEY", "SYSTEM"),
    p("CREATE", "ENCRYPTION_KEY", "SYSTEM"),
    p("READ", "ENCRYPTION_KEY", "SYSTEM"),
    p("UPDATE", "ENCRYPTION_KEY", "SYSTEM"),
    p("DELETE", "ENCRYPTION_KEY", "SYSTEM"),
    p("CREATE", "PLATFORM_FEES", "SYSTEM"),
    p("READ", "PLATFORM_FEES", "SYSTEM"),
    p("UPDATE", "PLATFORM_FEES", "SYSTEM"),
    p("DELETE", "PLATFORM_FEES", "SYSTEM"),
    // Audit
    p("READ", "AUDIT_LOG", "SYSTEM"),
    p("EXPORT", "AUDIT_LOG", "SYSTEM"),
    p("APPROVE", "USER", "PLATFORM"),
  ],
};

export type { UserRole };
