/**
 * TRAILER PRODUCT DATABASE
 * 50 most common products per non-hazmat trailer type + "Other" option
 * Used by LoadCreationWizard for product dropdown selection
 */

export interface TrailerProduct {
  id: string;
  name: string;
  category: string;
  nmfc?: string;
  freightClass?: string;
  notes?: string;
}

export const TRAILER_PRODUCTS: Record<string, TrailerProduct[]> = {
  dry_van: [
    { id: "dv_001", name: "Consumer Electronics", category: "Electronics", freightClass: "85", notes: "Fragile — requires padding/blanket wrap" },
    { id: "dv_002", name: "Household Furniture", category: "Furniture", freightClass: "100", notes: "Bulky — optimize cube utilization" },
    { id: "dv_003", name: "Clothing & Apparel", category: "Textiles", freightClass: "77.5" },
    { id: "dv_004", name: "Auto Parts (Boxed)", category: "Automotive", freightClass: "85", notes: "Heavy — check axle weights" },
    { id: "dv_005", name: "Canned Goods", category: "Food (Non-Perishable)", freightClass: "55", notes: "Heavy dense freight" },
    { id: "dv_006", name: "Paper Products (Boxed)", category: "Paper", freightClass: "55", notes: "Moisture-sensitive" },
    { id: "dv_007", name: "Bottled Water / Beverages", category: "Beverages", freightClass: "55", notes: "44,000 lb max typical" },
    { id: "dv_008", name: "Pet Food (Bagged/Boxed)", category: "Food (Non-Perishable)", freightClass: "60" },
    { id: "dv_009", name: "Cleaning Supplies", category: "Chemicals (Non-Hazmat)", freightClass: "65" },
    { id: "dv_010", name: "Cosmetics & Personal Care", category: "Consumer Goods", freightClass: "85" },
    { id: "dv_011", name: "Toys & Games", category: "Consumer Goods", freightClass: "150", notes: "Low density — high cube" },
    { id: "dv_012", name: "Books & Printed Materials", category: "Paper", freightClass: "55", notes: "Very heavy — pallet weight matters" },
    { id: "dv_013", name: "Pharmaceuticals (Non-Temp)", category: "Pharmaceutical", freightClass: "92.5", notes: "High-value — may require seal" },
    { id: "dv_014", name: "Medical Supplies & Devices", category: "Medical", freightClass: "85" },
    { id: "dv_015", name: "Sporting Goods", category: "Consumer Goods", freightClass: "110" },
    { id: "dv_016", name: "Mattresses", category: "Furniture", freightClass: "200", notes: "Extremely low density" },
    { id: "dv_017", name: "Appliances (Boxed)", category: "Appliances", freightClass: "92.5" },
    { id: "dv_018", name: "Office Supplies", category: "General", freightClass: "70" },
    { id: "dv_019", name: "Building Materials (Boxed)", category: "Construction", freightClass: "65" },
    { id: "dv_020", name: "Palletized Machinery Parts", category: "Industrial", freightClass: "85" },
    { id: "dv_021", name: "Retail Store Fixtures", category: "Retail", freightClass: "100" },
    { id: "dv_022", name: "Tile & Flooring (Boxed)", category: "Construction", freightClass: "55", notes: "Very heavy — 44k lb loads common" },
    { id: "dv_023", name: "Plumbing Fixtures", category: "Construction", freightClass: "85" },
    { id: "dv_024", name: "Electrical Supplies", category: "Industrial", freightClass: "77.5" },
    { id: "dv_025", name: "HVAC Components", category: "Industrial", freightClass: "85" },
    { id: "dv_026", name: "Paint & Coatings (Non-Hazmat)", category: "Chemicals (Non-Hazmat)", freightClass: "55" },
    { id: "dv_027", name: "Palletized Plastic Products", category: "Plastics", freightClass: "70" },
    { id: "dv_028", name: "Glass Products (Packaged)", category: "Glass", freightClass: "85", notes: "Fragile — requires careful loading" },
    { id: "dv_029", name: "Dry Pet Bedding / Hay", category: "Agriculture", freightClass: "77.5" },
    { id: "dv_030", name: "Wine (Boxed/Palletized)", category: "Beverages", freightClass: "70", notes: "Temperature-sensitive — monitor heat" },
    { id: "dv_031", name: "Coffee (Bagged/Boxed)", category: "Food (Non-Perishable)", freightClass: "60" },
    { id: "dv_032", name: "Snack Foods (Chips, Cookies)", category: "Food (Non-Perishable)", freightClass: "100", notes: "Lightweight — cube out quickly" },
    { id: "dv_033", name: "Diapers & Baby Products", category: "Consumer Goods", freightClass: "125" },
    { id: "dv_034", name: "Hardware & Fasteners", category: "Industrial", freightClass: "55", notes: "Dense — heavy pallets" },
    { id: "dv_035", name: "Textiles & Fabrics (Rolls)", category: "Textiles", freightClass: "77.5" },
    { id: "dv_036", name: "Shoes & Footwear", category: "Textiles", freightClass: "92.5" },
    { id: "dv_037", name: "Batteries (Non-Hazmat/Alkaline)", category: "Electronics", freightClass: "55" },
    { id: "dv_038", name: "Lawn & Garden Equipment", category: "Consumer Goods", freightClass: "85" },
    { id: "dv_039", name: "Bicycle Parts / Assembled", category: "Consumer Goods", freightClass: "100" },
    { id: "dv_040", name: "Automotive Tires", category: "Automotive", freightClass: "77.5" },
    { id: "dv_041", name: "Cased Beer / Spirits", category: "Beverages", freightClass: "55" },
    { id: "dv_042", name: "Frozen Food (Ambient Temp)", category: "Food (Non-Perishable)", freightClass: "65" },
    { id: "dv_043", name: "Candy & Confections", category: "Food (Non-Perishable)", freightClass: "70" },
    { id: "dv_044", name: "Palletized Chemicals (Non-Reg)", category: "Chemicals (Non-Hazmat)", freightClass: "65" },
    { id: "dv_045", name: "Rubber Products", category: "Industrial", freightClass: "65" },
    { id: "dv_046", name: "Musical Instruments", category: "Consumer Goods", freightClass: "150", notes: "Fragile — high-value" },
    { id: "dv_047", name: "Printer / Copier Equipment", category: "Electronics", freightClass: "92.5" },
    { id: "dv_048", name: "Computer Servers / IT Equip", category: "Electronics", freightClass: "92.5", notes: "High-value — may need white glove" },
    { id: "dv_049", name: "Paper (Rolls)", category: "Paper", freightClass: "55", notes: "Heavy — max axle weight concern" },
    { id: "dv_050", name: "Mixed Retail (LTL Partials)", category: "General", freightClass: "70" },
  ],

  reefer: [
    { id: "rf_001", name: "Fresh Produce (Mixed)", category: "Produce", notes: "32-36F typical" },
    { id: "rf_002", name: "Frozen Meat (Beef)", category: "Frozen Meat", notes: "0F or below" },
    { id: "rf_003", name: "Frozen Meat (Pork)", category: "Frozen Meat", notes: "0F or below" },
    { id: "rf_004", name: "Frozen Meat (Poultry)", category: "Frozen Poultry", notes: "0F or below" },
    { id: "rf_005", name: "Fresh Meat (Beef/Pork)", category: "Fresh Meat", notes: "28-32F" },
    { id: "rf_006", name: "Fresh Poultry", category: "Fresh Poultry", notes: "28-32F" },
    { id: "rf_007", name: "Seafood (Fresh)", category: "Seafood", notes: "30-34F" },
    { id: "rf_008", name: "Seafood (Frozen)", category: "Frozen Seafood", notes: "-10F to 0F" },
    { id: "rf_009", name: "Dairy Products (Milk)", category: "Dairy", notes: "33-38F — FSMA applies" },
    { id: "rf_010", name: "Dairy Products (Cheese)", category: "Dairy", notes: "35-40F" },
    { id: "rf_011", name: "Dairy Products (Yogurt)", category: "Dairy", notes: "33-38F" },
    { id: "rf_012", name: "Eggs (Shell/Liquid)", category: "Dairy", notes: "33-40F" },
    { id: "rf_013", name: "Ice Cream / Frozen Desserts", category: "Frozen Desserts", notes: "-20F to -10F" },
    { id: "rf_014", name: "Frozen Vegetables", category: "Frozen Produce", notes: "0F or below" },
    { id: "rf_015", name: "Frozen Fruit", category: "Frozen Produce", notes: "0F or below" },
    { id: "rf_016", name: "Fresh Fruit (Berries)", category: "Produce", notes: "32-34F — highly perishable" },
    { id: "rf_017", name: "Fresh Fruit (Citrus)", category: "Produce", notes: "38-48F" },
    { id: "rf_018", name: "Fresh Fruit (Tropical)", category: "Produce", notes: "45-55F — chill-sensitive" },
    { id: "rf_019", name: "Leafy Greens / Salads", category: "Produce", notes: "32-34F — FSMA applies" },
    { id: "rf_020", name: "Potatoes / Root Vegetables", category: "Produce", notes: "38-45F" },
    { id: "rf_021", name: "Tomatoes", category: "Produce", notes: "50-60F — never below 50F" },
    { id: "rf_022", name: "Frozen Pizza / Prepared Meals", category: "Frozen Prepared", notes: "0F or below" },
    { id: "rf_023", name: "Frozen Baked Goods", category: "Frozen Baked", notes: "0F or below" },
    { id: "rf_024", name: "Pharmaceuticals (Cold Chain)", category: "Pharmaceutical", notes: "36-46F (2-8C) — data logger required" },
    { id: "rf_025", name: "Vaccines / Biologics", category: "Pharmaceutical", notes: "35-46F strict — CDC cold chain" },
    { id: "rf_026", name: "Fresh Flowers / Floral", category: "Floral", notes: "33-36F" },
    { id: "rf_027", name: "Chocolate & Confections", category: "Food (Temp-Sensitive)", notes: "55-65F" },
    { id: "rf_028", name: "Deli Meats / Charcuterie", category: "Processed Meat", notes: "28-34F" },
    { id: "rf_029", name: "Fresh Juice (NFC)", category: "Beverages", notes: "33-38F" },
    { id: "rf_030", name: "Butter / Margarine", category: "Dairy", notes: "33-38F" },
    { id: "rf_031", name: "Fresh Pasta", category: "Food (Temp-Sensitive)", notes: "33-38F" },
    { id: "rf_032", name: "Sushi-Grade Fish", category: "Seafood", notes: "-4F flash frozen then 30-34F" },
    { id: "rf_033", name: "Frozen French Fries", category: "Frozen Prepared", notes: "0F or below" },
    { id: "rf_034", name: "Live Plants / Nursery Stock", category: "Horticulture", notes: "35-50F varies by species" },
    { id: "rf_035", name: "Craft Beer (Unpasteurized)", category: "Beverages", notes: "36-40F" },
    { id: "rf_036", name: "Clinical Trial Samples", category: "Medical", notes: "2-8C (36-46F) — validated" },
    { id: "rf_037", name: "Organ / Tissue Transport", category: "Medical", notes: "Strict protocol — time-critical" },
    { id: "rf_038", name: "Frozen Dough", category: "Frozen Baked", notes: "0F or below" },
    { id: "rf_039", name: "Fresh Herbs", category: "Produce", notes: "34-40F" },
    { id: "rf_040", name: "Mushrooms", category: "Produce", notes: "32-34F — high humidity" },
    { id: "rf_041", name: "Avocados", category: "Produce", notes: "40-55F — ethylene-sensitive" },
    { id: "rf_042", name: "Frozen Seafood (Lobster/Crab)", category: "Frozen Seafood", notes: "0F or below" },
    { id: "rf_043", name: "Meal Kits (Multi-Temp)", category: "Food (Temp-Sensitive)", notes: "32-40F" },
    { id: "rf_044", name: "Kombucha / Fermented Drinks", category: "Beverages", notes: "33-38F — live cultures" },
    { id: "rf_045", name: "Pet Food (Frozen Raw)", category: "Pet Food", notes: "0F or below" },
    { id: "rf_046", name: "Cosmetics (Temp-Sensitive)", category: "Consumer Goods", notes: "55-75F" },
    { id: "rf_047", name: "Candles / Wax Products", category: "Consumer Goods", notes: "55-70F — melt risk above 80F" },
    { id: "rf_048", name: "Wine (Temperature-Controlled)", category: "Beverages", notes: "55-60F" },
    { id: "rf_049", name: "Breast Milk / Blood Products", category: "Medical", notes: "Frozen: -4F / Refrigerated: 33-42F" },
    { id: "rf_050", name: "Frozen Smoothie Packs", category: "Frozen Produce", notes: "0F or below" },
  ],

  flatbed: [
    { id: "fb_001", name: "Steel Coils", category: "Steel", notes: "Coil racks required — 49 CFR 393.120" },
    { id: "fb_002", name: "Steel Beams / I-Beams", category: "Steel", notes: "Chained — 1 tiedown per 10ft" },
    { id: "fb_003", name: "Steel Pipe", category: "Steel", notes: "Bundled & chained — 49 CFR 393.118" },
    { id: "fb_004", name: "Steel Plate / Sheet", category: "Steel", notes: "Blocking & bracing — friction mats" },
    { id: "fb_005", name: "Lumber (Dimensional)", category: "Lumber", notes: "49 CFR 393.116 securement rules" },
    { id: "fb_006", name: "Plywood / OSB Sheets", category: "Lumber", notes: "Banded bundles — edge protectors" },
    { id: "fb_007", name: "Treated Lumber / Poles", category: "Lumber" },
    { id: "fb_008", name: "Logs (Sawlogs/Pulpwood)", category: "Timber", notes: "49 CFR 393.116" },
    { id: "fb_009", name: "Concrete Barriers / Jersey Walls", category: "Concrete", notes: "48,000 lb max typical" },
    { id: "fb_010", name: "Precast Concrete Panels", category: "Concrete", notes: "A-frame or tilt — may need oversize permit" },
    { id: "fb_011", name: "Concrete Pipe", category: "Concrete", notes: "Cradles required — 49 CFR 393.120" },
    { id: "fb_012", name: "Rebar Bundles", category: "Steel", notes: "Banded & chained" },
    { id: "fb_013", name: "Heavy Equipment (Excavator)", category: "Equipment", notes: "Oversize permit — 4-point chain" },
    { id: "fb_014", name: "Heavy Equipment (Bulldozer)", category: "Equipment", notes: "May need lowboy" },
    { id: "fb_015", name: "Heavy Equipment (Backhoe)", category: "Equipment" },
    { id: "fb_016", name: "Forklift / Skid Steer", category: "Equipment" },
    { id: "fb_017", name: "Construction Crane Components", category: "Equipment", notes: "Multi-load — oversize permits" },
    { id: "fb_018", name: "Generator Sets", category: "Equipment" },
    { id: "fb_019", name: "Transformers (De-Energized)", category: "Electrical" },
    { id: "fb_020", name: "Wind Turbine Blades", category: "Oversized", notes: "Superload permit — escort required" },
    { id: "fb_021", name: "Wind Turbine Tower Sections", category: "Oversized" },
    { id: "fb_022", name: "Solar Panels (Palletized)", category: "Energy", notes: "Fragile — no stacking" },
    { id: "fb_023", name: "Structural Steel (Fabricated)", category: "Steel" },
    { id: "fb_024", name: "Aluminum Extrusions", category: "Metals" },
    { id: "fb_025", name: "Copper Wire Spools", category: "Metals", notes: "High-value" },
    { id: "fb_026", name: "Roofing Materials (Shingles)", category: "Construction", notes: "Heavy palletized" },
    { id: "fb_027", name: "Drywall / Gypsum Board", category: "Construction", notes: "Tarped — moisture-sensitive" },
    { id: "fb_028", name: "Brick / Masonry Pallets", category: "Construction", notes: "Very heavy" },
    { id: "fb_029", name: "PVC / HDPE Pipe", category: "Plastics" },
    { id: "fb_030", name: "Utility Poles (Wood)", category: "Timber", notes: "Oversize length" },
    { id: "fb_031", name: "Railroad Ties", category: "Timber" },
    { id: "fb_032", name: "Boat / Yacht (On Cradle)", category: "Oversized", notes: "Wide load — permit required" },
    { id: "fb_033", name: "Prefab Building Modules", category: "Construction", notes: "Oversize — route survey" },
    { id: "fb_034", name: "HVAC Units (Rooftop)", category: "Equipment" },
    { id: "fb_035", name: "Water/Storage Tanks", category: "Equipment", notes: "Oversized diameter" },
    { id: "fb_036", name: "Agricultural Equipment", category: "Equipment", notes: "Wide loads" },
    { id: "fb_037", name: "Military Vehicles / Equipment", category: "Government" },
    { id: "fb_038", name: "Shipping Containers (Empty)", category: "Intermodal" },
    { id: "fb_039", name: "Steel Decking / Grating", category: "Steel" },
    { id: "fb_040", name: "Stone / Granite Slabs", category: "Stone", notes: "A-frame rack — fragile, heavy" },
    { id: "fb_041", name: "Insulation (Batt/Rigid)", category: "Construction", notes: "Tarped" },
    { id: "fb_042", name: "Fencing Materials / Posts", category: "Construction" },
    { id: "fb_043", name: "Oilfield Pipe (Drill/Casing)", category: "Oil & Gas", notes: "49 CFR 393.118" },
    { id: "fb_044", name: "Oilfield Equipment (BOP, Trees)", category: "Oil & Gas", notes: "Heavy — overweight permit" },
    { id: "fb_045", name: "Trusses / Roof Framing", category: "Construction", notes: "Oversize width/height" },
    { id: "fb_046", name: "Railroad Rail", category: "Steel", notes: "Extreme length" },
    { id: "fb_047", name: "Precast Concrete Stairs", category: "Concrete" },
    { id: "fb_048", name: "Road Plates / Trench Covers", category: "Steel", notes: "Very heavy per piece" },
    { id: "fb_049", name: "Scaffolding Components", category: "Construction" },
    { id: "fb_050", name: "Bridge Girders / Beams", category: "Concrete/Steel", notes: "Superload" },
  ],

  bulk_hopper: [
    { id: "bh_001", name: "Portland Cement", category: "Cement", notes: "Pneumatic unload, 48k lb loads" },
    { id: "bh_002", name: "Fly Ash", category: "Cement", notes: "Class C or F — pneumatic" },
    { id: "bh_003", name: "Calcium Carbonate (Limestone)", category: "Minerals" },
    { id: "bh_004", name: "Sand (Frac Sand)", category: "Mining", notes: "100 mesh, Northern White" },
    { id: "bh_005", name: "Sand (Silica / Industrial)", category: "Minerals", notes: "Silica dust precautions" },
    { id: "bh_006", name: "Flour (Wheat)", category: "Food Grade", notes: "FDA/FSMA — food-grade hopper" },
    { id: "bh_007", name: "Sugar (Granulated)", category: "Food Grade", notes: "Moisture-sensitive, sanitary" },
    { id: "bh_008", name: "Powdered Sugar", category: "Food Grade", notes: "Combustible dust awareness" },
    { id: "bh_009", name: "Salt (Road/Industrial)", category: "Minerals" },
    { id: "bh_010", name: "Salt (Food Grade)", category: "Food Grade", notes: "FDA compliant" },
    { id: "bh_011", name: "Plastic Pellets (Polyethylene)", category: "Plastics", notes: "PE resin — pneumatic unload" },
    { id: "bh_012", name: "Plastic Pellets (Polypropylene)", category: "Plastics", notes: "PP resin — keep dry" },
    { id: "bh_013", name: "Plastic Pellets (PVC Compound)", category: "Plastics" },
    { id: "bh_014", name: "Plastic Pellets (Nylon/PA)", category: "Plastics", notes: "Hygroscopic" },
    { id: "bh_015", name: "Soda Ash (Sodium Carbonate)", category: "Chemicals" },
    { id: "bh_016", name: "Potash (Potassium Chloride)", category: "Fertilizer" },
    { id: "bh_017", name: "Urea (Granular/Prilled)", category: "Fertilizer", notes: "Moisture-sensitive" },
    { id: "bh_018", name: "Ammonium Sulfate", category: "Fertilizer" },
    { id: "bh_019", name: "DAP / MAP Fertilizer", category: "Fertilizer" },
    { id: "bh_020", name: "Corn (Bulk Grain)", category: "Agriculture", notes: "USDA grade" },
    { id: "bh_021", name: "Soybeans (Bulk Grain)", category: "Agriculture" },
    { id: "bh_022", name: "Wheat (Bulk Grain)", category: "Agriculture" },
    { id: "bh_023", name: "Rice (Bulk)", category: "Agriculture" },
    { id: "bh_024", name: "Barley (Bulk Grain)", category: "Agriculture" },
    { id: "bh_025", name: "Oats (Bulk Grain)", category: "Agriculture" },
    { id: "bh_026", name: "Animal Feed (Pelleted)", category: "Agriculture" },
    { id: "bh_027", name: "Soybean Meal", category: "Agriculture", notes: "48% protein" },
    { id: "bh_028", name: "DDGS (Distillers Grains)", category: "Agriculture" },
    { id: "bh_029", name: "Bentonite Clay", category: "Minerals" },
    { id: "bh_030", name: "Kaolin Clay", category: "Minerals" },
    { id: "bh_031", name: "Barite", category: "Mining", notes: "Very heavy (4.2 SG)" },
    { id: "bh_032", name: "Calcium Chloride (Dry)", category: "Chemicals" },
    { id: "bh_033", name: "Sodium Bicarbonate", category: "Chemicals" },
    { id: "bh_034", name: "Titanium Dioxide", category: "Chemicals", notes: "High-value" },
    { id: "bh_035", name: "Carbon Black", category: "Chemicals", notes: "Static risk" },
    { id: "bh_036", name: "Alumina (Aluminum Oxide)", category: "Minerals" },
    { id: "bh_037", name: "Calcium Oxide (Quickite)", category: "Minerals", notes: "Reacts with water" },
    { id: "bh_038", name: "Hydrated Lime", category: "Minerals" },
    { id: "bh_039", name: "Diatomaceous Earth", category: "Minerals" },
    { id: "bh_040", name: "Talc (Industrial)", category: "Minerals" },
    { id: "bh_041", name: "Wood Pellets (Fuel)", category: "Biomass" },
    { id: "bh_042", name: "Wood Chips / Sawdust", category: "Biomass" },
    { id: "bh_043", name: "Perlite", category: "Minerals", notes: "Extremely lightweight" },
    { id: "bh_044", name: "Vermiculite", category: "Minerals" },
    { id: "bh_045", name: "Glass Cullet", category: "Recycling", notes: "Heavy, abrasive" },
    { id: "bh_046", name: "Calcium Sulfate (Gypsum)", category: "Minerals" },
    { id: "bh_047", name: "Starch (Corn/Potato)", category: "Food Grade", notes: "Combustible dust risk" },
    { id: "bh_048", name: "Maltodextrin", category: "Food Grade" },
    { id: "bh_049", name: "Protein Powder (Whey/Soy)", category: "Food Grade", notes: "Allergen controls" },
    { id: "bh_050", name: "Calcium Carbide", category: "Chemicals", notes: "Reacts with water — keep dry" },
  ],

  food_grade_tank: [
    { id: "fg_001", name: "Whole Milk (Grade A)", category: "Dairy", notes: "PMO regulated — 45F max, CIP wash" },
    { id: "fg_002", name: "Skim Milk", category: "Dairy", notes: "PMO regulated — 45F max" },
    { id: "fg_003", name: "Cream (Heavy/Light)", category: "Dairy", notes: "PMO regulated — 40F max" },
    { id: "fg_004", name: "Condensed Milk", category: "Dairy" },
    { id: "fg_005", name: "Liquid Sugar (67 Brix)", category: "Sweetener", notes: "Keep above 80F" },
    { id: "fg_006", name: "HFCS-55", category: "Sweetener", notes: "Keep 80-100F" },
    { id: "fg_007", name: "HFCS-42", category: "Sweetener", notes: "Keep 80-100F" },
    { id: "fg_008", name: "Corn Syrup (Regular)", category: "Sweetener", notes: "Keep 80-100F" },
    { id: "fg_009", name: "Molasses", category: "Sweetener", notes: "Keep 80-120F — very viscous" },
    { id: "fg_010", name: "Honey (Bulk)", category: "Sweetener", notes: "Keep 100-120F" },
    { id: "fg_011", name: "Soybean Oil (Refined)", category: "Edible Oil", notes: "Kosher tank required" },
    { id: "fg_012", name: "Canola Oil (Refined)", category: "Edible Oil" },
    { id: "fg_013", name: "Palm Oil (Refined)", category: "Edible Oil", notes: "Keep above 95F" },
    { id: "fg_014", name: "Coconut Oil (Refined)", category: "Edible Oil", notes: "Keep above 80F" },
    { id: "fg_015", name: "Corn Oil (Refined)", category: "Edible Oil" },
    { id: "fg_016", name: "Olive Oil (Bulk)", category: "Edible Oil" },
    { id: "fg_017", name: "Sunflower Oil", category: "Edible Oil" },
    { id: "fg_018", name: "Peanut Oil", category: "Edible Oil", notes: "Allergen — dedicated tank" },
    { id: "fg_019", name: "Orange Juice (NFC)", category: "Juice", notes: "33-36F, FSMA" },
    { id: "fg_020", name: "Orange Juice (Concentrate)", category: "Juice" },
    { id: "fg_021", name: "Apple Juice / Cider", category: "Juice", notes: "33-38F" },
    { id: "fg_022", name: "Grape Juice Concentrate", category: "Juice" },
    { id: "fg_023", name: "Tomato Paste / Puree", category: "Sauce" },
    { id: "fg_024", name: "Wine (Bulk)", category: "Beverage", notes: "SS tank — temp 55-65F" },
    { id: "fg_025", name: "Beer (Bulk)", category: "Beverage", notes: "34-38F, CO2 pressure" },
    { id: "fg_026", name: "Vinegar (Bulk)", category: "Condiment" },
    { id: "fg_027", name: "Soy Sauce (Bulk)", category: "Condiment" },
    { id: "fg_028", name: "Liquid Eggs (Pasteurized)", category: "Egg Products", notes: "USDA inspected — 33-40F" },
    { id: "fg_029", name: "Whey (Liquid)", category: "Dairy Byproduct", notes: "40F max" },
    { id: "fg_030", name: "Chocolate (Liquid)", category: "Confection", notes: "Keep 100-120F" },
    { id: "fg_031", name: "Glycerin (Food Grade/USP)", category: "Additive" },
    { id: "fg_032", name: "Ethanol (Food Grade/190 Proof)", category: "Alcohol", notes: "Bonded carrier" },
    { id: "fg_033", name: "Vegetable Shortening (Liquid)", category: "Edible Oil", notes: "Keep 110-130F" },
    { id: "fg_034", name: "Tallow (Edible Grade)", category: "Animal Fat", notes: "Keep above 120F" },
    { id: "fg_035", name: "Lard (Edible Grade)", category: "Animal Fat", notes: "Keep above 100F" },
    { id: "fg_036", name: "Fruit Puree (Aseptic)", category: "Fruit" },
    { id: "fg_037", name: "Maple Syrup (Bulk)", category: "Sweetener" },
    { id: "fg_038", name: "Phosphoric Acid (Food Grade)", category: "Additive" },
    { id: "fg_039", name: "Citric Acid Solution", category: "Additive" },
    { id: "fg_040", name: "Liquid Pectin", category: "Additive" },
    { id: "fg_041", name: "Vanilla Extract (Bulk)", category: "Flavoring", notes: "High-value" },
    { id: "fg_042", name: "Caramel Color", category: "Additive" },
    { id: "fg_043", name: "Sorbitol Solution (70%)", category: "Sweetener" },
    { id: "fg_044", name: "Propylene Glycol (Food Grade)", category: "Additive" },
    { id: "fg_045", name: "Coconut Cream / Milk", category: "Dairy Alternative" },
    { id: "fg_046", name: "Almond Milk (Bulk)", category: "Dairy Alternative" },
    { id: "fg_047", name: "Oat Milk (Bulk)", category: "Dairy Alternative" },
    { id: "fg_048", name: "Fish Oil (Food Grade)", category: "Edible Oil" },
    { id: "fg_049", name: "MCT Oil", category: "Edible Oil" },
    { id: "fg_050", name: "Agave Nectar (Bulk)", category: "Sweetener" },
  ],

  water_tank: [
    { id: "wt_001", name: "Potable Water (Municipal)", category: "Potable", notes: "NSF/ANSI 61 certified tank" },
    { id: "wt_002", name: "Potable Water (Emergency)", category: "Potable", notes: "FEMA/Red Cross standards" },
    { id: "wt_003", name: "Potable Water (Event Supply)", category: "Potable" },
    { id: "wt_004", name: "Potable Water (Construction)", category: "Potable" },
    { id: "wt_005", name: "Non-Potable (Dust Control)", category: "Non-Potable" },
    { id: "wt_006", name: "Non-Potable (Irrigation)", category: "Non-Potable" },
    { id: "wt_007", name: "Non-Potable (Landscaping)", category: "Non-Potable" },
    { id: "wt_008", name: "Non-Potable (Fire Suppression)", category: "Non-Potable" },
    { id: "wt_009", name: "Frac Water (Freshwater)", category: "Industrial" },
    { id: "wt_010", name: "Frac Water (Recycled)", category: "Industrial" },
    { id: "wt_011", name: "Produced Water", category: "Industrial", notes: "SWD well disposal" },
    { id: "wt_012", name: "Flowback Water", category: "Industrial", notes: "High TDS" },
    { id: "wt_013", name: "Saltwater (Brine)", category: "Industrial" },
    { id: "wt_014", name: "Industrial Process Water", category: "Industrial" },
    { id: "wt_015", name: "Boiler Feed Water", category: "Industrial" },
    { id: "wt_016", name: "Cooling Tower Makeup", category: "Industrial" },
    { id: "wt_017", name: "Deionized (DI) Water", category: "Industrial", notes: "Ultra-pure, dedicated tank" },
    { id: "wt_018", name: "Distilled Water", category: "Industrial" },
    { id: "wt_019", name: "RO Permeate", category: "Industrial" },
    { id: "wt_020", name: "Well Water (Residential Fill)", category: "Potable" },
    { id: "wt_021", name: "Pool / Spa Fill Water", category: "Non-Potable" },
    { id: "wt_022", name: "Hot Tub Water", category: "Non-Potable" },
    { id: "wt_023", name: "Aquarium / Fish Transport", category: "Specialty", notes: "Dechlorinated, aerated" },
    { id: "wt_024", name: "Livestock Water", category: "Agriculture" },
    { id: "wt_025", name: "Hydrostatic Test Water", category: "Industrial" },
    { id: "wt_026", name: "Concrete Batch Water", category: "Construction" },
    { id: "wt_027", name: "Drill Water", category: "Industrial" },
    { id: "wt_028", name: "Wastewater (Septic)", category: "Waste" },
    { id: "wt_029", name: "Wastewater (Industrial)", category: "Waste", notes: "EPA/state permits" },
    { id: "wt_030", name: "Wastewater (Car Wash)", category: "Waste" },
    { id: "wt_031", name: "Leachate (Landfill)", category: "Waste" },
    { id: "wt_032", name: "Greywater (Laundry/Sink)", category: "Waste" },
    { id: "wt_033", name: "Rainwater (Harvested)", category: "Non-Potable" },
    { id: "wt_034", name: "Spring Water (Bulk)", category: "Potable" },
    { id: "wt_035", name: "Mineral Water (Bulk)", category: "Potable" },
    { id: "wt_036", name: "Water Treatment Rinse", category: "Industrial" },
    { id: "wt_037", name: "Hydroseeding Slurry", category: "Agriculture" },
    { id: "wt_038", name: "Dust Suppression (Treated)", category: "Industrial" },
    { id: "wt_039", name: "Ice Rink Flood Water", category: "Specialty" },
    { id: "wt_040", name: "Aquaculture Water", category: "Agriculture" },
    { id: "wt_041", name: "Nursery / Greenhouse Water", category: "Agriculture" },
    { id: "wt_042", name: "Wine/Brewery Process Water", category: "Food Grade" },
    { id: "wt_043", name: "Food Plant Washdown Water", category: "Food Grade" },
    { id: "wt_044", name: "Hospital / Medical Facility", category: "Potable" },
    { id: "wt_045", name: "Military / Base Supply", category: "Potable" },
    { id: "wt_046", name: "Film / Movie Set Water", category: "Specialty" },
    { id: "wt_047", name: "Geothermal Loop Water", category: "Industrial" },
    { id: "wt_048", name: "Mine Dewatering", category: "Industrial" },
    { id: "wt_049", name: "Ballast Water", category: "Marine" },
    { id: "wt_050", name: "Reclaimed / Purple Pipe Water", category: "Non-Potable" },
  ],
};

export function getProductsForTrailer(trailerId: string): TrailerProduct[] {
  return TRAILER_PRODUCTS[trailerId] || [];
}

export function searchProducts(trailerId: string, query: string): TrailerProduct[] {
  const products = TRAILER_PRODUCTS[trailerId] || [];
  if (!query || query.length < 2) return products;
  const q = query.toLowerCase();
  return products.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    (p.notes && p.notes.toLowerCase().includes(q))
  );
}
