/**
 * EUSOTRIP SIMULATION - Telemetry Scenarios (80)
 */

import { Scenario } from '../../runners/ScenarioExecutor';

function createTelemetryScenario(id: number, name: string, actor: string, steps: string[], validations: string[]): Scenario {
  return {
    id: `TEL-${String(id).padStart(3, '0')}`,
    category: 'TELEMETRY',
    name,
    actor,
    steps,
    expectedOutcome: name,
    validations
  };
}

export const TELEMETRY_SCENARIOS: Scenario[] = [
  // GPS Tracking (1-20)
  createTelemetryScenario(1, 'Real-time GPS location tracking', 'DRIVER_D003',
    ['Driver on route', 'GPS updates every 30 sec', 'Location accurate', 'Map updates'],
    ['gps_accurate', 'updates_frequent']),
  createTelemetryScenario(2, 'GPS geofence trigger at pickup', 'SYSTEM',
    ['Driver enters pickup geofence', 'Status auto-updated', 'Timestamp logged'],
    ['geofence_works', 'auto_update']),
  createTelemetryScenario(3, 'GPS geofence trigger at delivery', 'SYSTEM',
    ['Driver enters delivery geofence', 'Arrival notification sent'],
    ['delivery_geofence_works']),
  createTelemetryScenario(4, 'GPS breadcrumb trail history', 'SHIPPER_S001',
    ['View load tracking', 'See route taken', 'Breadcrumb trail complete'],
    ['trail_displayed']),
  createTelemetryScenario(5, 'GPS signal loss handling', 'SYSTEM',
    ['Signal lost in tunnel', 'Last known shown', 'Alert generated'],
    ['signal_loss_handled']),
  createTelemetryScenario(6, 'GPS accuracy validation', 'SYSTEM',
    ['Compare to known location', 'Within 10 meters', 'Accurate'],
    ['accuracy_validated']),
  createTelemetryScenario(7, 'Multiple vehicle tracking', 'CATALYST_C002',
    ['Track 25 trucks', 'All on single map', 'Real-time updates'],
    ['multi_vehicle_works']),
  createTelemetryScenario(8, 'GPS data privacy controls', 'DRIVER_D003',
    ['GPS only shared during load', 'Off-duty location private'],
    ['privacy_enforced']),
  createTelemetryScenario(9, 'GPS-based mileage calculation', 'SYSTEM',
    ['Track route', 'Calculate actual miles', 'Compare to planned'],
    ['mileage_calculated']),
  createTelemetryScenario(10, 'GPS playback for disputes', 'BROKER_B001',
    ['Load disputed', 'Replay route taken', 'Timestamps shown'],
    ['playback_works']),

  // ELD Integration (21-40)
  createTelemetryScenario(21, 'ELD device connection', 'DRIVER_D003',
    ['Connect ELD device', 'Sync established', 'Data flowing'],
    ['eld_connected']),
  createTelemetryScenario(22, 'HOS status from ELD', 'DRIVER_D003',
    ['ELD reports driving', 'HOS clock updates', 'Time remaining accurate'],
    ['hos_from_eld']),
  createTelemetryScenario(23, 'ELD driving time alert', 'DRIVER_D003',
    ['30 min driving time left', 'Alert sent', 'Rest stop suggested'],
    ['driving_alert_works']),
  createTelemetryScenario(24, 'ELD 10-hour break tracking', 'DRIVER_D003',
    ['Start 10-hour break', 'Timer counts', 'Break complete notification'],
    ['break_tracking_works']),
  createTelemetryScenario(25, 'ELD 34-hour reset tracking', 'DRIVER_D003',
    ['Start 34-hour reset', 'Progress shown', 'Weekly hours restored'],
    ['reset_tracking_works']),
  createTelemetryScenario(26, 'ELD violation detection', 'SYSTEM',
    ['Driver exceeds 11 hours', 'Violation logged', 'Catalyst notified'],
    ['violation_detected']),
  createTelemetryScenario(27, 'ELD log export', 'DRIVER_D003',
    ['Export last 7 days', 'PDF generated', 'FMCSA compliant format'],
    ['export_works']),
  createTelemetryScenario(28, 'ELD roadside inspection mode', 'DRIVER_D003',
    ['Activate inspection mode', 'Logs displayed', 'Officer can view'],
    ['inspection_mode_works']),
  createTelemetryScenario(29, 'ELD malfunction handling', 'DRIVER_D003',
    ['ELD malfunctions', 'Paper log backup', 'Report to catalyst'],
    ['malfunction_handled']),
  createTelemetryScenario(30, 'ELD data sync across devices', 'DRIVER_D003',
    ['View on phone', 'Check on tablet', 'Data synced'],
    ['sync_works']),

  // Vehicle Diagnostics (41-55)
  createTelemetryScenario(41, 'Engine fault code detection', 'SYSTEM',
    ['Engine throws code', 'Alert to driver', 'Catalyst notified'],
    ['fault_detected']),
  createTelemetryScenario(42, 'Low fuel warning', 'SYSTEM',
    ['Fuel below 1/4', 'Alert sent', 'Nearby stations shown'],
    ['fuel_warning_works']),
  createTelemetryScenario(43, 'Tire pressure monitoring', 'SYSTEM',
    ['Low pressure detected', 'Alert generated', 'Safety warning'],
    ['tpms_works']),
  createTelemetryScenario(44, 'Reefer temperature monitoring', 'SYSTEM',
    ['Temp out of range', 'Alert to driver', 'Shipper notified'],
    ['reefer_monitoring_works']),
  createTelemetryScenario(45, 'Speed monitoring and alerts', 'CATALYST_C002',
    ['Driver exceeds 70mph', 'Speeding alert', 'Logged for review'],
    ['speed_monitoring_works']),
  createTelemetryScenario(46, 'Hard braking detection', 'SYSTEM',
    ['Hard brake event', 'Event logged', 'Safety score impacted'],
    ['hard_brake_detected']),
  createTelemetryScenario(47, 'Idle time tracking', 'CATALYST_C002',
    ['Excessive idle detected', 'Alert generated', 'Fuel waste calculated'],
    ['idle_tracking_works']),
  createTelemetryScenario(48, 'Maintenance reminder from telematics', 'SYSTEM',
    ['Oil change due', 'Reminder sent', 'Schedule service option'],
    ['maintenance_reminder_works']),

  // Driver Behavior (56-70)
  createTelemetryScenario(56, 'Safety score calculation', 'SYSTEM',
    ['Aggregate events', 'Calculate score', 'Display to driver'],
    ['score_calculated']),
  createTelemetryScenario(57, 'Safety score trending', 'DRIVER_D003',
    ['View score over time', 'Trend chart', 'Improvement suggestions'],
    ['trending_works']),
  createTelemetryScenario(58, 'Harsh acceleration detection', 'SYSTEM',
    ['Rapid acceleration', 'Event logged', 'Score impacted'],
    ['acceleration_detected']),
  createTelemetryScenario(59, 'Distracted driving detection', 'SYSTEM',
    ['Phone usage while driving', 'Alert generated', 'Coaching triggered'],
    ['distraction_detected']),
  createTelemetryScenario(60, 'Drowsiness detection', 'SYSTEM',
    ['Lane deviation pattern', 'Fatigue alert', 'Rest suggested'],
    ['drowsiness_detected']),
  createTelemetryScenario(61, 'Driver coaching based on telemetry', 'CATALYST_C002',
    ['Poor events identified', 'Coaching content assigned', 'Progress tracked'],
    ['coaching_works']),
  createTelemetryScenario(62, 'Gamified safety improvement', 'DRIVER_D003',
    ['Safe driving streak', 'Points earned', 'Leaderboard position'],
    ['gamification_works']),
  createTelemetryScenario(63, 'Fleet-wide safety dashboard', 'CATALYST_C002',
    ['View all drivers', 'Compare scores', 'Identify training needs'],
    ['fleet_dashboard_works']),

  // Reporting & Analytics (71-80)
  createTelemetryScenario(71, 'Telemetry data export', 'CATALYST_C002',
    ['Select date range', 'Export to CSV', 'All data included'],
    ['export_works']),
  createTelemetryScenario(72, 'Fuel efficiency report', 'CATALYST_C002',
    ['View MPG by driver', 'Fleet average', 'Cost analysis'],
    ['fuel_report_works']),
  createTelemetryScenario(73, 'Route efficiency analysis', 'CATALYST_C002',
    ['Compare planned vs actual', 'Deviation analysis', 'Cost impact'],
    ['route_analysis_works']),
  createTelemetryScenario(74, 'Compliance report generation', 'CATALYST_C002',
    ['Generate DOT report', 'HOS compliance', 'Violation summary'],
    ['compliance_report_works']),
  createTelemetryScenario(75, 'Real-time fleet dashboard', 'CATALYST_C002',
    ['View all metrics', 'Real-time updates', 'Drill-down capability'],
    ['dashboard_works']),
  createTelemetryScenario(76, 'Custom alert configuration', 'CATALYST_C002',
    ['Set custom thresholds', 'Configure notifications', 'Test alerts'],
    ['custom_alerts_work']),
  createTelemetryScenario(77, 'API access to telemetry data', 'EXTERNAL_SYSTEM',
    ['Query via API', 'Real-time data', 'Historical queries'],
    ['api_works']),
  createTelemetryScenario(78, 'Telemetry data retention', 'ADMIN_A001',
    ['Data stored 2 years', 'Archive accessible', 'Compliance met'],
    ['retention_works']),
  createTelemetryScenario(79, 'Telemetry during connectivity loss', 'DRIVER_D003',
    ['Connection lost', 'Data cached locally', 'Sync when restored'],
    ['offline_caching_works']),
  createTelemetryScenario(80, 'Third-party ELD integration', 'CATALYST_C002',
    ['Connect KeepTruckin', 'Data imported', 'Unified view'],
    ['third_party_works'])
];

export default TELEMETRY_SCENARIOS;
