/**
 * DOCUMENT CENTER — Complete Document Types Seed
 * 100+ document types covering CDL, DOT, Insurance, Tax, Hazmat,
 * Compliance, Vehicle, Safety, Employment, Legal, Operations, State-specific
 */

export const documentTypesSeed = [
  // CDL — Driver Licensing
  { id: 'CDL', category: 'CDL' as const, name: "Commercial Driver's License", shortName: 'CDL', description: 'State-issued commercial driver license with applicable endorsements', issuingAuthority: 'State DMV', regulatoryReference: '49 CFR 383', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license', hasExpiration: true, typicalValidityDays: 1460, expirationWarningDays: 90, verificationLevel: 'L3_EXTERNAL' as const, ocrEnabled: true, ocrFieldMappings: { licenseNumber: { pattern: 'DL|CDL|LICENSE.*?([A-Z0-9]+)', confidence: 0.85 }, expirationDate: { pattern: 'EXP.*?(\\d{2}/\\d{2}/\\d{4})', confidence: 0.9 }, state: { pattern: '(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC)', confidence: 0.95 }, endorsements: { pattern: 'ENDORSEMENTS?.*?([HNTPSX]+)', confidence: 0.8 } }, sortOrder: 1 },
  { id: 'MEDICAL_CERT', category: 'CDL' as const, name: "Medical Examiner's Certificate", shortName: 'Med Card', formNumber: 'MCSA-5876', description: 'DOT physical medical certificate (wallet card)', issuingAuthority: 'Certified Medical Examiner', regulatoryReference: '49 CFR 391.43', sourceUrl: 'https://www.fmcsa.dot.gov/regulations/medical/medical-examiners-certificate-commercial-driver-medical-certification', downloadUrl: 'https://www.fmcsa.dot.gov/forms/medical-examiners-certificate-mcsa-5876', hasExpiration: true, typicalValidityDays: 730, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, ocrEnabled: true, sortOrder: 2 },
  { id: 'MEDICAL_EXAM_LONG', category: 'CDL' as const, name: 'Medical Examination Report (Long Form)', shortName: 'DOT Physical', formNumber: 'MCSA-5875', description: 'Complete DOT physical examination report', issuingAuthority: 'Certified Medical Examiner', regulatoryReference: '49 CFR 391.43', sourceUrl: 'https://www.fmcsa.dot.gov/regulations/medical/medical-examination-report-form-commercial-driver-medical-certification', downloadUrl: 'https://www.fmcsa.dot.gov/forms/medical-examination-report-form-mcsa-5875', hasExpiration: true, typicalValidityDays: 730, verificationLevel: 'L2_STAFF' as const, sortOrder: 3 },
  { id: 'MVR', category: 'CDL' as const, name: 'Motor Vehicle Record', shortName: 'MVR', description: 'State driving history report showing violations and accidents', issuingAuthority: 'State DMV', regulatoryReference: '49 CFR 391.23', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license/states', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 4 },
  { id: 'PSP_REPORT', category: 'CDL' as const, name: 'Pre-Employment Screening Program Report', shortName: 'PSP', description: 'FMCSA crash and inspection history for past 5 years', issuingAuthority: 'FMCSA', regulatoryReference: '49 CFR 391.23', sourceUrl: 'https://www.psp.fmcsa.dot.gov/', downloadUrl: 'https://www.psp.fmcsa.dot.gov/psp/default.aspx', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 5 },
  { id: 'HAZMAT_ENDORSEMENT', category: 'CDL' as const, name: 'Hazardous Materials Endorsement', shortName: 'H Endorsement', description: 'CDL endorsement for transporting hazardous materials', issuingAuthority: 'TSA / State DMV', regulatoryReference: '49 CFR 383.93', sourceUrl: 'https://www.tsa.gov/for-industry/hazmat-endorsement', downloadUrl: 'https://universalenroll.dhs.gov/programs/hazmat', hasExpiration: true, typicalValidityDays: 1825, expirationWarningDays: 180, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 6 },
  { id: 'TWIC', category: 'CDL' as const, name: 'Transportation Worker Identification Credential', shortName: 'TWIC', description: 'Biometric credential for unescorted access to secure areas', issuingAuthority: 'TSA', regulatoryReference: '49 CFR 1572', sourceUrl: 'https://www.tsa.gov/twic', downloadUrl: 'https://universalenroll.dhs.gov/programs/twic', hasExpiration: true, typicalValidityDays: 1825, expirationWarningDays: 180, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 7 },
  { id: 'TANKER_ENDORSEMENT', category: 'CDL' as const, name: 'Tanker Endorsement', shortName: 'N Endorsement', description: 'CDL endorsement for tank vehicles', issuingAuthority: 'State DMV', regulatoryReference: '49 CFR 383.93', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license', hasExpiration: true, typicalValidityDays: 1460, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 8 },
  { id: 'DOUBLES_TRIPLES', category: 'CDL' as const, name: 'Doubles/Triples Endorsement', shortName: 'T Endorsement', description: 'CDL endorsement for pulling double or triple trailers', issuingAuthority: 'State DMV', regulatoryReference: '49 CFR 383.93', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license', hasExpiration: true, typicalValidityDays: 1460, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 9 },
  { id: 'PASSENGER_ENDORSEMENT', category: 'CDL' as const, name: 'Passenger Endorsement', shortName: 'P Endorsement', description: 'CDL endorsement for passenger vehicles', issuingAuthority: 'State DMV', regulatoryReference: '49 CFR 383.93', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license', hasExpiration: true, typicalValidityDays: 1460, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 10 },
  { id: 'SCHOOL_BUS', category: 'CDL' as const, name: 'School Bus Endorsement', shortName: 'S Endorsement', description: 'CDL endorsement for school bus operation', issuingAuthority: 'State DMV', regulatoryReference: '49 CFR 383.93', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license', hasExpiration: true, typicalValidityDays: 1460, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 11 },

  // DOT — Federal Motor Carrier
  { id: 'USDOT_NUMBER', category: 'DOT' as const, name: 'USDOT Number Registration', shortName: 'DOT#', description: 'Federal identification number for interstate commerce', issuingAuthority: 'FMCSA', regulatoryReference: '49 CFR 390.19', sourceUrl: 'https://www.fmcsa.dot.gov/registration/do-i-need-usdot-number', downloadUrl: 'https://li-public.fmcsa.dot.gov/LIVIEW/pkg_registration.prc_registration', hasExpiration: false, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 20 },
  { id: 'MC_AUTHORITY', category: 'DOT' as const, name: 'Motor Carrier Operating Authority', shortName: 'MC#', formNumber: 'OP-1', description: 'Authority to operate as a for-hire motor carrier', issuingAuthority: 'FMCSA', regulatoryReference: '49 CFR 365', sourceUrl: 'https://www.fmcsa.dot.gov/registration/get-mc-number-authority-operate', downloadUrl: 'https://www.fmcsa.dot.gov/registration/form-op-1-application-motor-property-carrier-and-broker-authority', hasExpiration: false, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 21 },
  { id: 'BROKER_AUTHORITY', category: 'DOT' as const, name: 'Broker Operating Authority', shortName: 'MC-B', formNumber: 'OP-1(B)', description: 'Authority to operate as a property broker', issuingAuthority: 'FMCSA', regulatoryReference: '49 CFR 365', sourceUrl: 'https://www.fmcsa.dot.gov/registration/broker-registration', downloadUrl: 'https://www.fmcsa.dot.gov/registration/form-op-1-application-motor-property-carrier-and-broker-authority', hasExpiration: false, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 22 },
  { id: 'MCS150', category: 'DOT' as const, name: 'Motor Carrier Identification Report', shortName: 'MCS-150', formNumber: 'MCS-150', description: 'Biennial update of company information', issuingAuthority: 'FMCSA', regulatoryReference: '49 CFR 390.19', sourceUrl: 'https://www.fmcsa.dot.gov/registration/updating-your-registration', downloadUrl: 'https://www.fmcsa.dot.gov/registration/form-mcs-150-motor-carrier-identification-report', hasExpiration: true, typicalValidityDays: 730, expirationWarningDays: 60, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 23 },
  { id: 'BOC3', category: 'DOT' as const, name: 'Designation of Process Agents', shortName: 'BOC-3', formNumber: 'BOC-3', description: 'Legal representative designation for each state', issuingAuthority: 'FMCSA', regulatoryReference: '49 CFR 366', sourceUrl: 'https://www.fmcsa.dot.gov/registration/form-boc-3-designation-agents-service-process', downloadUrl: 'https://www.fmcsa.dot.gov/registration/form-boc-3-designation-agents-service-process', hasExpiration: false, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 24 },
  { id: 'NEW_ENTRANT_AUDIT', category: 'DOT' as const, name: 'New Entrant Safety Audit', shortName: 'Safety Audit', description: 'Required audit within first 18 months of operation', issuingAuthority: 'FMCSA', regulatoryReference: '49 CFR 385.305', sourceUrl: 'https://www.fmcsa.dot.gov/safety/new-entrant-safety-assurance-program', downloadUrl: 'https://csa.fmcsa.dot.gov/safetyplanner/myfiles/SubSections.aspx?ch=23&sec=66&sub=161', hasExpiration: false, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 25 },
  { id: 'SAFETY_RATING', category: 'DOT' as const, name: 'FMCSA Safety Rating', shortName: 'Safety Rating', description: 'Official safety fitness determination', issuingAuthority: 'FMCSA', sourceUrl: 'https://ai.fmcsa.dot.gov/SMS/', downloadUrl: 'https://safer.fmcsa.dot.gov/CompanySnapshot.aspx', hasExpiration: false, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 26 },

  // INS — Insurance
  { id: 'AUTO_LIABILITY', category: 'INS' as const, name: 'Motor Carrier Auto Liability Insurance', shortName: 'Auto Liability', formNumber: 'BMC-91/91X', description: 'Primary liability insurance for motor carrier operations', issuingAuthority: 'Insurance Company', regulatoryReference: '49 CFR 387', sourceUrl: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements', downloadUrl: 'https://li-public.fmcsa.dot.gov/LIVIEW/pkg_carrquery.prc_carrlist', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 30 },
  { id: 'CARGO_INSURANCE', category: 'INS' as const, name: 'Cargo Insurance Certificate', shortName: 'Cargo', formNumber: 'BMC-32/34', description: 'Insurance covering cargo in transit', issuingAuthority: 'Insurance Company', sourceUrl: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L2_STAFF' as const, sortOrder: 31 },
  { id: 'GENERAL_LIABILITY', category: 'INS' as const, name: 'General Liability Insurance', shortName: 'Gen Liability', description: 'General business liability coverage', issuingAuthority: 'Insurance Company', sourceUrl: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L2_STAFF' as const, sortOrder: 32 },
  { id: 'WORKERS_COMP', category: 'INS' as const, name: 'Workers Compensation Insurance', shortName: 'Workers Comp', description: 'Coverage for employee workplace injuries', issuingAuthority: 'Insurance Company / State Fund', sourceUrl: 'https://www.dol.gov/general/topic/workcomp', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L2_STAFF' as const, sortOrder: 33 },
  { id: 'PHYSICAL_DAMAGE', category: 'INS' as const, name: 'Physical Damage Insurance', shortName: 'Physical Damage', description: 'Coverage for vehicle damage (collision, comprehensive)', issuingAuthority: 'Insurance Company', sourceUrl: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L2_STAFF' as const, sortOrder: 34 },
  { id: 'SURETY_BOND', category: 'INS' as const, name: 'Broker Surety Bond', shortName: 'Surety Bond', formNumber: 'BMC-84', description: '$75,000 surety bond for property brokers', issuingAuthority: 'Surety Company', regulatoryReference: '49 CFR 387.307', sourceUrl: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements', downloadUrl: 'https://www.fmcsa.dot.gov/registration/form-bmc-84-broker-surety-bond', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 35 },
  { id: 'TRUST_FUND', category: 'INS' as const, name: 'Broker Trust Fund Agreement', shortName: 'Trust Fund', formNumber: 'BMC-85', description: '$75,000 trust fund alternative to surety bond', issuingAuthority: 'Financial Institution', regulatoryReference: '49 CFR 387.307', sourceUrl: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements', downloadUrl: 'https://www.fmcsa.dot.gov/registration/form-bmc-85-broker-trust-fund-agreement', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 36 },
  { id: 'CONTINGENT_CARGO', category: 'INS' as const, name: 'Contingent Cargo Insurance', shortName: 'Contingent Cargo', description: 'Broker backup coverage for carrier cargo claims', issuingAuthority: 'Insurance Company', sourceUrl: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L2_STAFF' as const, sortOrder: 37 },
  { id: 'ERRORS_OMISSIONS', category: 'INS' as const, name: 'Errors & Omissions Insurance', shortName: 'E&O', description: 'Professional liability coverage', issuingAuthority: 'Insurance Company', sourceUrl: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L2_STAFF' as const, sortOrder: 38 },
  { id: 'UMBRELLA_LIABILITY', category: 'INS' as const, name: 'Umbrella/Excess Liability Insurance', shortName: 'Umbrella', description: 'Additional liability coverage above primary limits', issuingAuthority: 'Insurance Company', sourceUrl: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L2_STAFF' as const, sortOrder: 39 },

  // TAX — Tax Forms
  { id: 'W9', category: 'TAX' as const, name: 'Request for Taxpayer Identification Number', shortName: 'W-9', formNumber: 'W-9', description: 'Tax ID certification for independent contractors', issuingAuthority: 'IRS', sourceUrl: 'https://www.irs.gov/forms-pubs/about-form-w-9', downloadUrl: 'https://www.irs.gov/pub/irs-pdf/fw9.pdf', instructionsUrl: 'https://www.irs.gov/instructions/iw9', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 40 },
  { id: 'W4', category: 'TAX' as const, name: "Employee's Withholding Certificate", shortName: 'W-4', formNumber: 'W-4', description: 'Tax withholding elections for employees', issuingAuthority: 'IRS', sourceUrl: 'https://www.irs.gov/forms-pubs/about-form-w-4', downloadUrl: 'https://www.irs.gov/pub/irs-pdf/fw4.pdf', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 41 },
  { id: 'I9', category: 'TAX' as const, name: 'Employment Eligibility Verification', shortName: 'I-9', formNumber: 'I-9', description: 'Work authorization verification for all employees', issuingAuthority: 'USCIS', regulatoryReference: '8 CFR 274a', sourceUrl: 'https://www.uscis.gov/i-9', downloadUrl: 'https://www.uscis.gov/i-9', instructionsUrl: 'https://www.uscis.gov/i-9-central/form-i-9-resources/handbook-for-employers-m-274', hasExpiration: false, verificationLevel: 'L2_STAFF' as const, requiresSignature: true, sortOrder: 42 },
  { id: 'FORM_2290', category: 'TAX' as const, name: 'Heavy Highway Vehicle Use Tax Return', shortName: 'Form 2290', formNumber: '2290', description: 'Annual federal excise tax for vehicles 55,000+ lbs', issuingAuthority: 'IRS', sourceUrl: 'https://www.irs.gov/forms-pubs/about-form-2290', downloadUrl: 'https://www.irs.gov/pub/irs-pdf/f2290.pdf', instructionsUrl: 'https://www.irs.gov/pub/irs-pdf/i2290.pdf', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 43 },
  { id: 'EIN_VERIFICATION', category: 'TAX' as const, name: 'EIN Verification Letter', shortName: 'EIN Letter', formNumber: 'CP 575', description: 'IRS confirmation of Employer Identification Number', issuingAuthority: 'IRS', sourceUrl: 'https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 44 },
  { id: 'ACH_AUTH', category: 'TAX' as const, name: 'ACH Direct Deposit Authorization', shortName: 'Direct Deposit', description: 'Bank account authorization for electronic payments', issuingAuthority: 'EusoTrip', sourceUrl: 'https://eusotrip.com/settings/billing', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 45 },
  { id: 'VOIDED_CHECK', category: 'TAX' as const, name: 'Voided Check or Bank Letter', shortName: 'Bank Verification', description: 'Proof of bank account ownership', issuingAuthority: 'Bank', sourceUrl: 'https://eusotrip.com/settings/billing', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 46 },

  // HAZ — Hazmat
  { id: 'HAZMAT_REGISTRATION', category: 'HAZ' as const, name: 'Hazmat Registration Statement', shortName: 'Hazmat Reg', formNumber: 'DOT F 5800.2', description: 'Annual registration for hazmat transporters', issuingAuthority: 'PHMSA', regulatoryReference: '49 CFR 107.601', sourceUrl: 'https://www.phmsa.dot.gov/hazmat/registration', downloadUrl: 'https://www.phmsa.dot.gov/hazmat/registration/registration-and-fee-assessment-program', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, sortOrder: 50 },
  { id: 'HAZMAT_SECURITY_PLAN', category: 'HAZ' as const, name: 'Hazmat Security Plan', shortName: 'Security Plan', description: 'Written security plan for hazmat operations', issuingAuthority: 'Self-Prepared', regulatoryReference: '49 CFR 172.800', sourceUrl: 'https://www.phmsa.dot.gov/training/hazmat/hazmat-transportation-training-requirements', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L2_STAFF' as const, sortOrder: 51 },
  { id: 'HAZMAT_TRAINING_CERT', category: 'HAZ' as const, name: 'Hazmat Training Certificate', shortName: 'Hazmat Training', description: 'Certification of hazmat handling training', issuingAuthority: 'Training Provider', regulatoryReference: '49 CFR 172.704', sourceUrl: 'https://www.phmsa.dot.gov/training/hazmat/hazmat-transportation-training-requirements', hasExpiration: true, typicalValidityDays: 1095, expirationWarningDays: 90, verificationLevel: 'L2_STAFF' as const, sortOrder: 52 },
  { id: 'HAZMAT_SAFETY_PERMIT', category: 'HAZ' as const, name: 'Hazmat Safety Permit', shortName: 'Safety Permit', description: 'FMCSA safety permit for certain hazmat loads', issuingAuthority: 'FMCSA', regulatoryReference: '49 CFR 385.403', sourceUrl: 'https://www.fmcsa.dot.gov/regulations/hazardous-materials/hazardous-materials-safety-permit-program-hmsp', downloadUrl: 'https://li-public.fmcsa.dot.gov/LIVIEW/pkg_registration.prc_registration', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 53 },
  { id: 'EPA_ID', category: 'HAZ' as const, name: 'EPA Identification Number', shortName: 'EPA ID', description: 'EPA ID for hazardous waste transporters', issuingAuthority: 'EPA', regulatoryReference: '40 CFR 263', sourceUrl: 'https://rcrainfo.epa.gov/', downloadUrl: 'https://rcrapublic.epa.gov/rcrainfoweb/action/modules/br/handler/search', hasExpiration: false, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 54 },

  // COM — Compliance (IFTA, IRP, UCR)
  { id: 'IFTA_LICENSE', category: 'COM' as const, name: 'IFTA License', shortName: 'IFTA', description: 'International Fuel Tax Agreement license', issuingAuthority: 'Base State', sourceUrl: 'https://www.iftach.org/jurisdictions/', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, isStateSpecific: true, sortOrder: 60 },
  { id: 'IFTA_DECALS', category: 'COM' as const, name: 'IFTA Decals', shortName: 'IFTA Decals', description: 'Annual IFTA identification decals for each vehicle', issuingAuthority: 'Base State', sourceUrl: 'https://www.iftach.org/jurisdictions/', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 61 },
  { id: 'IRP_CAB_CARD', category: 'COM' as const, name: 'IRP Cab Card', shortName: 'Cab Card', description: 'International Registration Plan apportioned registration', issuingAuthority: 'Base State DMV', sourceUrl: 'https://www.irponline.org/page/JurisdictionInfo', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, isStateSpecific: true, sortOrder: 62 },
  { id: 'UCR', category: 'COM' as const, name: 'Unified Carrier Registration', shortName: 'UCR', description: 'Annual UCR registration for interstate carriers', issuingAuthority: 'UCR', sourceUrl: 'https://www.ucr.gov/', downloadUrl: 'https://www.ucr.gov/register/carrier', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 63 },

  // VEH — Vehicle
  { id: 'VEHICLE_REGISTRATION', category: 'VEH' as const, name: 'Vehicle Registration', shortName: 'Registration', description: 'State vehicle registration certificate', issuingAuthority: 'State DMV', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license/states', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L1_SYSTEM' as const, isStateSpecific: true, sortOrder: 70 },
  { id: 'VEHICLE_TITLE', category: 'VEH' as const, name: 'Vehicle Title', shortName: 'Title', description: 'Certificate of title showing ownership', issuingAuthority: 'State DMV', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license/states', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 71 },
  { id: 'LEASE_AGREEMENT', category: 'VEH' as const, name: 'Vehicle/Equipment Lease Agreement', shortName: 'Lease', description: 'Lease agreement for equipment under lease', issuingAuthority: 'Lessor', regulatoryReference: '49 CFR 376', sourceUrl: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-376', hasExpiration: true, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 72 },
  { id: 'ANNUAL_INSPECTION', category: 'VEH' as const, name: 'Annual Vehicle Inspection Report', shortName: 'Annual Inspection', description: 'DOT annual vehicle safety inspection', issuingAuthority: 'Certified Inspector', regulatoryReference: '49 CFR 396.17', sourceUrl: 'https://www.cvsa.org/inspections/', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L2_STAFF' as const, sortOrder: 73 },
  { id: 'TRAILER_REGISTRATION', category: 'VEH' as const, name: 'Trailer Registration', shortName: 'Trailer Reg', description: 'State registration for trailers', issuingAuthority: 'State DMV', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license/states', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 74 },

  // SAF — Safety & Training
  { id: 'DOT_DRUG_TEST', category: 'SAF' as const, name: 'DOT Drug Test Results', shortName: 'Drug Test', description: 'Pre-employment and random drug test results', issuingAuthority: 'MRO / Testing Lab', regulatoryReference: '49 CFR 382', sourceUrl: 'https://www.fmcsa.dot.gov/regulations/drug-alcohol-testing/overview-drug-and-alcohol-rules', hasExpiration: false, verificationLevel: 'L2_STAFF' as const, sortOrder: 80 },
  { id: 'DOT_ALCOHOL_TEST', category: 'SAF' as const, name: 'DOT Alcohol Test Results', shortName: 'Alcohol Test', description: 'Alcohol test results', issuingAuthority: 'Testing Provider', regulatoryReference: '49 CFR 382', sourceUrl: 'https://www.fmcsa.dot.gov/regulations/drug-alcohol-testing/overview-drug-and-alcohol-rules', hasExpiration: false, verificationLevel: 'L2_STAFF' as const, sortOrder: 81 },
  { id: 'CLEARINGHOUSE_QUERY', category: 'SAF' as const, name: 'Drug & Alcohol Clearinghouse Query', shortName: 'Clearinghouse', description: 'FMCSA Clearinghouse pre-employment query', issuingAuthority: 'FMCSA Clearinghouse', regulatoryReference: '49 CFR 382.701', sourceUrl: 'https://clearinghouse.fmcsa.dot.gov/', downloadUrl: 'https://clearinghouse.fmcsa.dot.gov/Login', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L3_EXTERNAL' as const, sortOrder: 82 },
  { id: 'DRUG_ALCOHOL_POLICY', category: 'SAF' as const, name: 'Drug & Alcohol Policy', shortName: 'D&A Policy', description: 'Company drug and alcohol testing policy', issuingAuthority: 'Carrier', regulatoryReference: '49 CFR 382.601', sourceUrl: 'https://www.fmcsa.dot.gov/regulations/drug-alcohol-testing/overview-drug-and-alcohol-rules', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 83 },
  { id: 'DRIVER_SAFETY_TRAINING', category: 'SAF' as const, name: 'Driver Safety Training Certificate', shortName: 'Safety Training', description: 'Completion of driver safety training', issuingAuthority: 'Training Provider', sourceUrl: 'https://www.fmcsa.dot.gov/driver-resources', hasExpiration: true, typicalValidityDays: 1095, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 84 },
  { id: 'DVIR_TRAINING', category: 'SAF' as const, name: 'DVIR Training Certificate', shortName: 'DVIR Training', description: 'Training on Driver Vehicle Inspection Reports', issuingAuthority: 'Training Provider / Carrier', regulatoryReference: '49 CFR 396.11', sourceUrl: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-396/subpart-A/section-396.11', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 85 },
  { id: 'ELD_TRAINING', category: 'SAF' as const, name: 'ELD Training Certificate', shortName: 'ELD Training', description: 'Training on Electronic Logging Device usage', issuingAuthority: 'Training Provider / Carrier', regulatoryReference: '49 CFR 395.22', sourceUrl: 'https://www.fmcsa.dot.gov/hours-service/elds/electronic-logging-devices', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 86 },
  { id: 'DEFENSIVE_DRIVING', category: 'SAF' as const, name: 'Defensive Driving Certificate', shortName: 'Defensive Driving', description: 'Defensive driving course completion', issuingAuthority: 'Training Provider', sourceUrl: 'https://www.fmcsa.dot.gov/driver-resources', hasExpiration: true, typicalValidityDays: 1095, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 87 },

  // EMP — Employment
  { id: 'DRIVER_APPLICATION', category: 'EMP' as const, name: 'Driver Employment Application', shortName: 'Application', description: 'FMCSA-compliant driver application form', issuingAuthority: 'Carrier', regulatoryReference: '49 CFR 391.21', sourceUrl: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-391/subpart-C/section-391.21', hasExpiration: false, verificationLevel: 'L2_STAFF' as const, requiresSignature: true, sortOrder: 90 },
  { id: 'EMPLOYMENT_HISTORY', category: 'EMP' as const, name: 'Employment History Verification', shortName: 'Work History', description: '10-year employment history verification', issuingAuthority: 'Previous Employers', regulatoryReference: '49 CFR 391.23', sourceUrl: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-391/subpart-C/section-391.23', hasExpiration: false, verificationLevel: 'L2_STAFF' as const, sortOrder: 91 },
  { id: 'ROAD_TEST_CERT', category: 'EMP' as const, name: 'Certificate of Road Test', shortName: 'Road Test', description: 'Certification of road test completion', issuingAuthority: 'Carrier', regulatoryReference: '49 CFR 391.31', sourceUrl: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-391/subpart-D/section-391.31', hasExpiration: false, verificationLevel: 'L2_STAFF' as const, sortOrder: 92 },
  { id: 'ANNUAL_MVR_REVIEW', category: 'EMP' as const, name: 'Annual Review of Driving Record', shortName: 'Annual Review', description: 'Annual review and certification of driver MVR', issuingAuthority: 'Carrier', regulatoryReference: '49 CFR 391.25', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license/states', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L2_STAFF' as const, sortOrder: 93 },
  { id: 'BACKGROUND_CHECK_AUTH', category: 'EMP' as const, name: 'Background Check Authorization', shortName: 'Background Auth', description: 'Consent for background screening', issuingAuthority: 'EusoTrip / Carrier', sourceUrl: 'https://eusotrip.com/documents', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 94 },
  { id: 'BACKGROUND_CHECK_RESULT', category: 'EMP' as const, name: 'Background Check Report', shortName: 'Background Report', description: 'Completed background check results', issuingAuthority: 'Background Check Provider', sourceUrl: 'https://eusotrip.com/documents', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L2_STAFF' as const, sortOrder: 95 },
  { id: 'EMERGENCY_CONTACT', category: 'EMP' as const, name: 'Emergency Contact Form', shortName: 'Emergency Contact', description: 'Emergency contact information', issuingAuthority: 'EusoTrip', sourceUrl: 'https://eusotrip.com/profile', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 96 },
  { id: 'EMPLOYMENT_AGREEMENT', category: 'EMP' as const, name: 'Employment Agreement', shortName: 'Employment Contract', description: 'Employment contract for W-2 employees', issuingAuthority: 'Employer', sourceUrl: 'https://eusotrip.com/agreements', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 97 },
  { id: 'HANDBOOK_ACK', category: 'EMP' as const, name: 'Employee Handbook Acknowledgment', shortName: 'Handbook Ack', description: 'Acknowledgment of employee handbook receipt', issuingAuthority: 'Employer', sourceUrl: 'https://eusotrip.com/documents', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 98 },

  // LEG — Legal Agreements
  { id: 'IC_AGREEMENT', category: 'LEG' as const, name: 'Independent Contractor Agreement', shortName: 'IC Agreement', description: 'Contract for independent contractor relationship', issuingAuthority: 'EusoTrip', sourceUrl: 'https://eusotrip.com/agreements', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 100 },
  { id: 'OO_LEASE_AGREEMENT', category: 'LEG' as const, name: 'Owner-Operator Lease Agreement', shortName: 'O/O Lease', description: 'Equipment lease agreement for owner-operators', issuingAuthority: 'Carrier', regulatoryReference: '49 CFR 376', sourceUrl: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-376', hasExpiration: true, verificationLevel: 'L2_STAFF' as const, requiresSignature: true, sortOrder: 101 },
  { id: 'BROKER_CARRIER_AGREEMENT', category: 'LEG' as const, name: 'Broker-Carrier Agreement', shortName: 'Broker Agreement', description: 'Contract between broker and carrier', issuingAuthority: 'Broker / EusoTrip', sourceUrl: 'https://eusotrip.com/agreements', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 102 },
  { id: 'SHIPPER_AGREEMENT', category: 'LEG' as const, name: 'Shipper Agreement', shortName: 'Shipper Terms', description: 'Terms and conditions for shippers', issuingAuthority: 'EusoTrip', sourceUrl: 'https://eusotrip.com/agreements', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 103 },
  { id: 'NDA', category: 'LEG' as const, name: 'Non-Disclosure Agreement', shortName: 'NDA', description: 'Confidentiality agreement', issuingAuthority: 'EusoTrip', sourceUrl: 'https://eusotrip.com/agreements', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, requiresSignature: true, sortOrder: 104 },
  { id: 'FACTORING_AGREEMENT', category: 'LEG' as const, name: 'Factoring Agreement', shortName: 'Factoring', description: 'Invoice factoring terms and conditions', issuingAuthority: 'Factoring Company', sourceUrl: 'https://eusotrip.com/agreements', hasExpiration: true, verificationLevel: 'L2_STAFF' as const, requiresSignature: true, sortOrder: 105 },
  { id: 'NOTICE_OF_ASSIGNMENT', category: 'LEG' as const, name: 'Notice of Assignment', shortName: 'NOA', description: 'Notice that receivables are assigned to factor', issuingAuthority: 'Factoring Company', sourceUrl: 'https://eusotrip.com/agreements', hasExpiration: false, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 106 },
  { id: 'TERMS_OF_SERVICE', category: 'LEG' as const, name: 'Platform Terms of Service', shortName: 'TOS', description: 'EusoTrip platform terms acceptance', issuingAuthority: 'EusoTrip', sourceUrl: 'https://eusotrip.com/terms-of-service', hasExpiration: false, verificationLevel: 'L0_SELF' as const, sortOrder: 107 },
  { id: 'PRIVACY_POLICY_ACK', category: 'LEG' as const, name: 'Privacy Policy Acknowledgment', shortName: 'Privacy Ack', description: 'Acknowledgment of privacy policy', issuingAuthority: 'EusoTrip', sourceUrl: 'https://eusotrip.com/privacy-policy', hasExpiration: false, verificationLevel: 'L0_SELF' as const, sortOrder: 108 },

  // OPS — Operations Templates
  { id: 'BOL_TEMPLATE', category: 'OPS' as const, name: 'Bill of Lading Template', shortName: 'BOL', description: 'Standard bill of lading form', issuingAuthority: 'Shipper', sourceUrl: 'https://eusotrip.com/documents/templates', hasExpiration: false, verificationLevel: 'L0_SELF' as const, sortOrder: 110 },
  { id: 'HAZMAT_BOL_TEMPLATE', category: 'OPS' as const, name: 'Hazmat Shipping Paper Template', shortName: 'Hazmat BOL', description: 'Hazmat shipping paper (49 CFR 172.200 compliant)', issuingAuthority: 'Shipper', regulatoryReference: '49 CFR 172.200', sourceUrl: 'https://www.phmsa.dot.gov/training/hazmat/hazmat-transportation-training-requirements', hasExpiration: false, verificationLevel: 'L0_SELF' as const, sortOrder: 111 },
  { id: 'RATE_CONFIRMATION', category: 'OPS' as const, name: 'Rate Confirmation Template', shortName: 'Rate Con', description: 'Load rate confirmation document', issuingAuthority: 'Broker / Shipper', sourceUrl: 'https://eusotrip.com/documents/templates', hasExpiration: false, verificationLevel: 'L0_SELF' as const, sortOrder: 112 },
  { id: 'CARRIER_PACKET', category: 'OPS' as const, name: 'Carrier Setup Packet', shortName: 'Carrier Packet', description: 'Carrier onboarding document package', issuingAuthority: 'Broker / Shipper', sourceUrl: 'https://eusotrip.com/documents/templates', hasExpiration: false, verificationLevel: 'L0_SELF' as const, sortOrder: 113 },
  { id: 'LUMPER_RECEIPT', category: 'OPS' as const, name: 'Lumper Receipt Template', shortName: 'Lumper Receipt', description: 'Receipt for lumper/loading services', issuingAuthority: 'Lumper', sourceUrl: 'https://eusotrip.com/documents/templates', hasExpiration: false, verificationLevel: 'L0_SELF' as const, sortOrder: 114 },
  { id: 'DETENTION_FORM', category: 'OPS' as const, name: 'Detention Time Record', shortName: 'Detention', description: 'Documentation of detention time', issuingAuthority: 'Driver / Carrier', sourceUrl: 'https://eusotrip.com/documents/templates', hasExpiration: false, verificationLevel: 'L0_SELF' as const, sortOrder: 115 },

  // TRL — Trailer-Type-Specific Documents
  { id: 'FOOD_SAFETY_CERT', category: 'COM' as const, name: 'Food Safety Certification', shortName: 'Food Safety', description: 'Certification for transporting food-grade products (reefer/temp-controlled)', issuingAuthority: 'FDA / State Dept of Agriculture', regulatoryReference: 'FSMA 21 CFR 1.908', sourceUrl: 'https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-sanitary-transportation-human-and-animal-food', downloadUrl: 'https://www.ecfr.gov/current/title-21/chapter-I/subchapter-A/part-1/subpart-O', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, sortOrder: 120 },
  { id: 'OVERSIZE_PERMIT', category: 'COM' as const, name: 'Oversize/Overweight Load Permit', shortName: 'OS/OW Permit', description: 'State-issued permit for oversized or overweight loads on flatbed trailers', issuingAuthority: 'State DOT', sourceUrl: 'https://ops.fhwa.dot.gov/freight/publications/sw_permit_report/', downloadUrl: 'https://ops.fhwa.dot.gov/freight/publications/sw_permit_report/', isStateSpecific: true, hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L2_STAFF' as const, sortOrder: 121 },

  // TANK — Cargo Tank Inspection & Maintenance
  { id: 'CARGO_TANK_TEST', category: 'VEH' as const, name: 'Cargo Tank Test & Inspection Certificate', shortName: 'Tank Test', description: 'Periodic cargo tank test certificate per 49 CFR 180.407 (pressure test, visual inspection, leak test)', issuingAuthority: 'DOT-Certified Inspector', regulatoryReference: '49 CFR 180.407', sourceUrl: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-180/subpart-E/section-180.407', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, sortOrder: 130 },
  { id: 'TANK_WASHOUT_CERT', category: 'VEH' as const, name: 'Tank Cleaning/Washout Certificate', shortName: 'Washout Cert', description: 'Proof of tank cleaning/sanitization between loads of different products', issuingAuthority: 'Tank Wash Facility', regulatoryReference: 'FSMA 21 CFR 1.908', sourceUrl: 'https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-sanitary-transportation-human-and-animal-food', hasExpiration: true, typicalValidityDays: 30, expirationWarningDays: 5, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 131 },
  { id: 'VAPOR_RECOVERY_CERT', category: 'VEH' as const, name: 'Vapor Recovery System Certification', shortName: 'Vapor Recovery', description: 'Certification that vapor recovery system meets state EPA / CARB requirements for petroleum tankers', issuingAuthority: 'State EPA / CARB', regulatoryReference: 'CARB CP-201', sourceUrl: 'https://ww2.arb.ca.gov/our-work/programs/vapor-recovery', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L2_STAFF' as const, isStateSpecific: true, sortOrder: 132 },
  { id: 'PRESSURE_RELIEF_TEST', category: 'VEH' as const, name: 'Pressure Relief Device Test Certificate', shortName: 'PRD Test', description: 'Certification of pressure relief device testing and recertification for pressurized/cryogenic tanks', issuingAuthority: 'DOT-Certified Inspector', regulatoryReference: '49 CFR 180.407', sourceUrl: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C/part-180/subpart-E/section-180.407', hasExpiration: true, typicalValidityDays: 1825, expirationWarningDays: 90, verificationLevel: 'L2_STAFF' as const, sortOrder: 133 },

  // CRYO — Cryogenic-Specific
  { id: 'CRYOGENIC_HANDLING_CERT', category: 'SAF' as const, name: 'Cryogenic Materials Handling Certificate', shortName: 'Cryo Training', description: 'Specialized training for LNG, LOX, LN2, LH2 handling including oxygen deficiency awareness and BLEVE response', issuingAuthority: 'Training Provider / CGA', regulatoryReference: 'CGA P-1 / OSHA 29 CFR 1910.101', sourceUrl: 'https://www.osha.gov/compressed-gas-equipment', hasExpiration: true, typicalValidityDays: 1095, expirationWarningDays: 90, verificationLevel: 'L2_STAFF' as const, sortOrder: 134 },

  // FLAT — Flatbed-Specific
  { id: 'LOAD_SECUREMENT_TRAINING', category: 'SAF' as const, name: 'Load Securement Training Certificate', shortName: 'Securement Training', description: 'Training on cargo securement per 49 CFR 393 Subpart I for flatbed and open-deck trailers', issuingAuthority: 'Training Provider / Carrier', regulatoryReference: '49 CFR 393 Subpart I', sourceUrl: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-393/subpart-I', hasExpiration: true, typicalValidityDays: 1095, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 135 },
  { id: 'ROUTE_SURVEY', category: 'OPS' as const, name: 'Oversize Load Route Survey', shortName: 'Route Survey', description: 'Pre-trip route survey documenting bridge clearances, utility lines, and turn restrictions for oversize loads', issuingAuthority: 'Carrier / Pilot Car', sourceUrl: 'https://ops.fhwa.dot.gov/freight/publications/sw_permit_report/', hasExpiration: true, typicalValidityDays: 30, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 136 },

  // BULK — Dry Bulk / Hopper-Specific
  { id: 'BULK_LOADING_CERT', category: 'SAF' as const, name: 'Pneumatic Loading/Unloading Training Certificate', shortName: 'Bulk Loading Cert', description: 'Training certification for pneumatic loading/unloading operations including pressure system safety and contamination prevention', issuingAuthority: 'Training Provider / Carrier', sourceUrl: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.302', hasExpiration: true, typicalValidityDays: 1095, verificationLevel: 'L1_SYSTEM' as const, sortOrder: 137 },
  { id: 'HOPPER_INSPECTION', category: 'VEH' as const, name: 'Pneumatic System Inspection Record', shortName: 'Hopper Inspection', description: 'Inspection record for pneumatic system integrity: blower, hoses, valves, seals, and pressure relief', issuingAuthority: 'Certified Inspector', sourceUrl: 'https://www.cvsa.org/inspections/', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L2_STAFF' as const, sortOrder: 138 },

  // FOOD — Food-Grade-Specific
  { id: 'KOSHER_CERT', category: 'COM' as const, name: 'Kosher Transportation Certification', shortName: 'Kosher Cert', description: 'Rabbinical certification for kosher product transportation', issuingAuthority: 'Kosher Certification Agency', sourceUrl: 'https://www.ok.org/about/what-is-kosher/', hasExpiration: true, typicalValidityDays: 365, verificationLevel: 'L2_STAFF' as const, sortOrder: 139 },
  { id: 'ORGANIC_CERT', category: 'COM' as const, name: 'USDA Organic Handler Certification', shortName: 'Organic Cert', description: 'USDA National Organic Program certification for organic product transportation', issuingAuthority: 'USDA-Accredited Certifier', regulatoryReference: '7 CFR 205', sourceUrl: 'https://www.ams.usda.gov/services/organic-certification', downloadUrl: 'https://organic.ams.usda.gov/integrity/', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, sortOrder: 140 },

  // WATER — Water Tank-Specific
  { id: 'POTABLE_WATER_CERT', category: 'COM' as const, name: 'Potable Water Tank Certification', shortName: 'Potable Cert', description: 'NSF/ANSI 61 compliance certification for potable water transport tanks', issuingAuthority: 'NSF International / State Health Dept', regulatoryReference: 'NSF/ANSI 61', sourceUrl: 'https://www.nsf.org/knowledge-library/nsf-ansi-61-702P', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, sortOrder: 141 },
  { id: 'WATER_QUALITY_TEST', category: 'COM' as const, name: 'Water Quality Test Results', shortName: 'Water Quality', description: 'Periodic water quality testing results (bacteria, chlorine, contaminants) for potable water hauling', issuingAuthority: 'Certified Lab / State Health Dept', sourceUrl: 'https://www.epa.gov/dwlabcert', hasExpiration: true, typicalValidityDays: 90, expirationWarningDays: 14, verificationLevel: 'L2_STAFF' as const, sortOrder: 142 },

  // PHARMA — Pharmaceutical Reefer-Specific
  { id: 'PHARMA_GDP_CERT', category: 'COM' as const, name: 'Good Distribution Practice Certificate', shortName: 'GDP Cert', description: 'Good Distribution Practice certification for pharmaceutical temperature-controlled shipments', issuingAuthority: 'Certification Body / WHO', regulatoryReference: 'EU GDP / WHO TRS 957', sourceUrl: 'https://www.who.int/publications/i/item/9789241209861', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, sortOrder: 143 },

  // FAC — Facility / Terminal Operations
  { id: 'SPCC_PLAN', category: 'COM' as const, name: 'Spill Prevention, Control & Countermeasure Plan', shortName: 'SPCC Plan', description: 'EPA-required plan for oil storage facilities to prevent discharges to navigable waters', issuingAuthority: 'Self-Prepared / PE Certified', regulatoryReference: '40 CFR 112', sourceUrl: 'https://www.epa.gov/oil-spills-prevention-and-preparedness-regulations/spill-prevention-control-and-countermeasure-spcc', downloadUrl: 'https://www.epa.gov/oil-spills-prevention-and-preparedness-regulations/spcc-plan', hasExpiration: true, typicalValidityDays: 1825, expirationWarningDays: 180, verificationLevel: 'L2_STAFF' as const, sortOrder: 150 },
  { id: 'STORMWATER_PERMIT', category: 'COM' as const, name: 'NPDES Stormwater Discharge Permit', shortName: 'Stormwater Permit', description: 'EPA National Pollutant Discharge Elimination System permit for stormwater runoff', issuingAuthority: 'State EPA / US EPA', regulatoryReference: 'CWA Section 402', sourceUrl: 'https://www.epa.gov/npdes/stormwater-discharges-industrial-activities', hasExpiration: true, typicalValidityDays: 1825, expirationWarningDays: 180, verificationLevel: 'L2_STAFF' as const, sortOrder: 151 },
  { id: 'EMERGENCY_RESPONSE_PLAN', category: 'SAF' as const, name: 'Facility Emergency Response Plan', shortName: 'FRP', description: 'Facility response plan for worst-case oil/hazmat discharge per 40 CFR 112.20', issuingAuthority: 'Self-Prepared / EPA Reviewed', regulatoryReference: '40 CFR 112.20', sourceUrl: 'https://www.epa.gov/oil-spills-prevention-and-preparedness-regulations/facility-response-plan-frp-overview', hasExpiration: true, typicalValidityDays: 1825, expirationWarningDays: 180, verificationLevel: 'L2_STAFF' as const, sortOrder: 152 },
  { id: 'AIR_QUALITY_PERMIT', category: 'COM' as const, name: 'Air Quality Operating Permit', shortName: 'Air Permit', description: 'State/federal permit for air emissions from terminal operations (VOCs, criteria pollutants)', issuingAuthority: 'State EPA / US EPA', regulatoryReference: 'CAA Title V', sourceUrl: 'https://www.epa.gov/title-v-operating-permits', hasExpiration: true, typicalValidityDays: 1825, expirationWarningDays: 180, verificationLevel: 'L2_STAFF' as const, isStateSpecific: true, sortOrder: 153 },
  { id: 'BUSINESS_LICENSE', category: 'LEG' as const, name: 'Business License / Operating Permit', shortName: 'Business License', description: 'State or local business operating license', issuingAuthority: 'State / Local Government', sourceUrl: 'https://www.sba.gov/business-guide/launch-your-business/apply-licenses-permits', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L1_SYSTEM' as const, isStateSpecific: true, sortOrder: 154 },
  { id: 'PROPERTY_INSURANCE', category: 'INS' as const, name: 'Commercial Property Insurance', shortName: 'Property Insurance', description: 'Insurance covering facility structures, equipment, and inventory', issuingAuthority: 'Insurance Company', sourceUrl: 'https://www.iii.org/article/what-covered-standard-commercial-property-policy', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L2_STAFF' as const, sortOrder: 155 },
  { id: 'ENVIRONMENTAL_LIABILITY', category: 'INS' as const, name: 'Environmental / Pollution Liability Insurance', shortName: 'Environmental Liability', description: 'Coverage for environmental contamination and cleanup costs', issuingAuthority: 'Insurance Company', sourceUrl: 'https://www.epa.gov/enforcement/financial-assurance', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 30, verificationLevel: 'L2_STAFF' as const, sortOrder: 156 },
  { id: 'FIRE_PREVENTION_PLAN', category: 'SAF' as const, name: 'Fire Prevention Plan', shortName: 'Fire Plan', description: 'OSHA-required fire prevention plan for facilities with flammable materials', issuingAuthority: 'Self-Prepared / Fire Marshal', regulatoryReference: 'OSHA 29 CFR 1910.39', sourceUrl: 'https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.39', hasExpiration: true, typicalValidityDays: 365, expirationWarningDays: 60, verificationLevel: 'L2_STAFF' as const, sortOrder: 157 },
  { id: 'TANK_INTEGRITY_TEST', category: 'VEH' as const, name: 'Above-Ground Storage Tank Integrity Test', shortName: 'AST Test', description: 'API 653 inspection for above-ground storage tanks at terminals', issuingAuthority: 'API-Certified Inspector', regulatoryReference: 'API 653', sourceUrl: 'https://www.api.org/products-and-services/standards/important-standards-702', hasExpiration: true, typicalValidityDays: 1825, expirationWarningDays: 180, verificationLevel: 'L2_STAFF' as const, sortOrder: 158 },

  // STATE — State-Specific Base Entries
  { id: 'STATE_CDL', category: 'STATE' as const, name: 'State CDL', description: 'State-issued CDL (linked to specific state)', issuingAuthority: 'State DMV', sourceUrl: 'https://www.fmcsa.dot.gov/registration/commercial-drivers-license/states', isStateSpecific: true, hasExpiration: true, typicalValidityDays: 1460, sortOrder: 200 },
  { id: 'STATE_IFTA', category: 'STATE' as const, name: 'State IFTA License', description: 'IFTA license from base state', issuingAuthority: 'State Revenue', sourceUrl: 'https://www.iftach.org/jurisdictions/', isStateSpecific: true, hasExpiration: true, typicalValidityDays: 365, sortOrder: 201 },
  { id: 'STATE_IRP', category: 'STATE' as const, name: 'State IRP Registration', description: 'IRP apportioned registration from base state', issuingAuthority: 'State DMV', sourceUrl: 'https://www.irponline.org/page/JurisdictionInfo', downloadUrl: 'https://www.irponline.org/page/JurisdictionInfo', isStateSpecific: true, hasExpiration: true, typicalValidityDays: 365, sortOrder: 202 },
  { id: 'STATE_WEIGHT_PERMIT', category: 'STATE' as const, name: 'State Weight/Permit', description: 'State-specific operating permit or weight distance tax', issuingAuthority: 'State DOT', sourceUrl: 'https://ops.fhwa.dot.gov/freight/publications/sw_permit_report/', isStateSpecific: true, hasExpiration: true, sortOrder: 203 },
  { id: 'STATE_FUEL_PERMIT', category: 'STATE' as const, name: 'State Fuel Permit', description: 'Single-state fuel permit (non-IFTA)', issuingAuthority: 'State Revenue', sourceUrl: 'https://www.iftach.org/jurisdictions/', isStateSpecific: true, hasExpiration: true, sortOrder: 204 },
  { id: 'CARB_COMPLIANCE', category: 'STATE' as const, name: 'CARB Truck & Bus Compliance', description: 'California Air Resources Board compliance certificate', issuingAuthority: 'CARB', sourceUrl: 'https://ww2.arb.ca.gov/our-work/programs/truck-and-bus-regulation', isStateSpecific: true, applicableStates: ['CA'], hasExpiration: true, typicalValidityDays: 365, sortOrder: 205 },
  { id: 'CA_MCP', category: 'STATE' as const, name: 'California Motor Carrier Permit', description: 'California intrastate motor carrier permit', issuingAuthority: 'CA DMV', sourceUrl: 'https://www.dmv.ca.gov/portal/vehicle-industry-services/motor-carrier-services-mcs/motor-carrier-permits/', isStateSpecific: true, applicableStates: ['CA'], hasExpiration: true, typicalValidityDays: 365, sortOrder: 206 },
];
