-- Document Center Migration
-- Creates all tables for the smart document management system

CREATE TABLE IF NOT EXISTS `document_types` (
  `id` varchar(50) NOT NULL,
  `category` enum('CDL','DOT','HAZ','INS','TAX','EMP','VEH','SAF','OPS','AUT','COM','LEG','STATE') NOT NULL,
  `subcategory` varchar(50),
  `name` varchar(200) NOT NULL,
  `shortName` varchar(50),
  `description` text,
  `formNumber` varchar(50),
  `issuingAuthority` varchar(200),
  `regulatoryReference` varchar(200),
  `sourceUrl` text,
  `downloadUrl` text,
  `instructionsUrl` text,
  `hasExpiration` boolean DEFAULT false,
  `typicalValidityDays` int,
  `expirationWarningDays` int DEFAULT 30,
  `verificationLevel` enum('L0_SELF','L1_SYSTEM','L2_STAFF','L3_EXTERNAL') DEFAULT 'L1_SYSTEM',
  `requiresSignature` boolean DEFAULT false,
  `requiresNotarization` boolean DEFAULT false,
  `requiresWitness` boolean DEFAULT false,
  `acceptedFileTypes` varchar(100) DEFAULT 'pdf,jpg,jpeg,png',
  `maxFileSizeMb` int DEFAULT 10,
  `minResolutionDpi` int DEFAULT 150,
  `ocrEnabled` boolean DEFAULT true,
  `ocrFieldMappings` json,
  `isStateSpecific` boolean DEFAULT false,
  `applicableStates` json,
  `sortOrder` int DEFAULT 100,
  `isActive` boolean DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_doc_types_category` (`category`),
  INDEX `idx_doc_types_active` (`isActive`)
);

CREATE TABLE IF NOT EXISTS `document_requirements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `documentTypeId` varchar(50) NOT NULL,
  `requiredForRole` enum('DRIVER','OWNER_OPERATOR','CARRIER','FLEET_MANAGER','DISPATCHER','SHIPPER','BROKER','COMPLIANCE_OFFICER','SAFETY_MANAGER','LUMPER','FACTORING_COMPANY','ADMIN','SUPER_ADMIN') NOT NULL,
  `requiredForEmploymentType` enum('W2_EMPLOYEE','1099_CONTRACTOR','OWNER_OPERATOR','COMPANY_OWNER'),
  `isRequired` boolean DEFAULT true,
  `isBlocking` boolean DEFAULT true,
  `priority` int DEFAULT 1,
  `conditionType` varchar(50),
  `conditionOperator` varchar(20),
  `conditionValue` json,
  `requiredInStates` json,
  `exemptInStates` json,
  `requiredAtOnboarding` boolean DEFAULT true,
  `gracePeriodDays` int DEFAULT 0,
  `renewalReminderDays` json DEFAULT ('[90,60,30,14,7,3,1]'),
  `uploadInstructions` text,
  `acceptanceCriteria` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_doc_req_role` (`requiredForRole`),
  INDEX `idx_doc_req_doctype` (`documentTypeId`)
);

CREATE TABLE IF NOT EXISTS `user_documents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `companyId` int,
  `documentTypeId` varchar(50) NOT NULL,
  `blobUrl` text NOT NULL,
  `blobPath` varchar(500),
  `fileName` varchar(500) NOT NULL,
  `fileSize` int,
  `mimeType` varchar(100),
  `fileHash` varchar(64),
  `documentNumber` text,
  `documentNumberLast4` varchar(4),
  `issuedBy` varchar(200),
  `issuedByState` varchar(2),
  `issuedDate` varchar(10),
  `effectiveDate` varchar(10),
  `expiresAt` varchar(10),
  `docStatus` enum('NOT_UPLOADED','UPLOADING','PENDING_REVIEW','VERIFIED','REJECTED','EXPIRED','EXPIRING_SOON','SUPERSEDED','NOT_APPLICABLE','WAIVED') NOT NULL DEFAULT 'PENDING_REVIEW',
  `statusChangedAt` timestamp DEFAULT CURRENT_TIMESTAMP,
  `statusChangedBy` int,
  `docVerifLevel` enum('L0_SELF','L1_SYSTEM','L2_STAFF','L3_EXTERNAL'),
  `verifiedAt` timestamp NULL,
  `verifiedBy` int,
  `verificationNotes` text,
  `rejectionReason` text,
  `rejectionCode` varchar(50),
  `ocrProcessed` boolean DEFAULT false,
  `ocrProcessedAt` timestamp NULL,
  `ocrExtractedData` json,
  `ocrConfidenceScore` decimal(5,2),
  `ocrErrors` json,
  `externalVerified` boolean DEFAULT false,
  `externalVerifiedAt` timestamp NULL,
  `externalVerificationSource` varchar(100),
  `externalVerificationData` json,
  `version` int DEFAULT 1,
  `previousVersionId` int,
  `supersededAt` timestamp NULL,
  `supersededBy` int,
  `uploadedBy` int NOT NULL,
  `uploadedAt` timestamp DEFAULT CURRENT_TIMESTAMP,
  `uploadIpAddress` varchar(45),
  `uploadUserAgent` text,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` timestamp NULL,
  `deletedBy` int,
  `deletionReason` text,
  PRIMARY KEY (`id`),
  INDEX `idx_user_docs_user` (`userId`),
  INDEX `idx_user_docs_company` (`companyId`),
  INDEX `idx_user_docs_type` (`documentTypeId`),
  INDEX `idx_user_docs_status` (`docStatus`),
  INDEX `idx_user_docs_expires` (`expiresAt`),
  INDEX `idx_user_docs_user_type` (`userId`, `documentTypeId`)
);

CREATE TABLE IF NOT EXISTS `user_document_requirements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `documentTypeId` varchar(50) NOT NULL,
  `documentRequirementId` int,
  `isRequired` boolean DEFAULT true,
  `isBlocking` boolean DEFAULT true,
  `priority` int DEFAULT 1,
  `udrStatus` enum('NOT_UPLOADED','UPLOADING','PENDING_REVIEW','VERIFIED','REJECTED','EXPIRED','EXPIRING_SOON','SUPERSEDED','NOT_APPLICABLE','WAIVED') NOT NULL DEFAULT 'NOT_UPLOADED',
  `currentDocumentId` int,
  `udrExpiresAt` varchar(10),
  `daysUntilExpiry` int,
  `isExpired` boolean DEFAULT false,
  `isExpiringSoon` boolean DEFAULT false,
  `complianceWeight` int DEFAULT 10,
  `requirementReason` text,
  `requirementSource` varchar(100),
  `calculatedAt` timestamp DEFAULT CURRENT_TIMESTAMP,
  `lastNotifiedAt` timestamp NULL,
  `nextNotificationAt` timestamp NULL,
  `gracePeriodEndsAt` timestamp NULL,
  `isInGracePeriod` boolean DEFAULT false,
  PRIMARY KEY (`id`),
  INDEX `idx_udr_user` (`userId`),
  INDEX `idx_udr_status` (`udrStatus`),
  INDEX `idx_udr_expires` (`udrExpiresAt`),
  UNIQUE KEY `idx_udr_unique` (`userId`, `documentTypeId`)
);

CREATE TABLE IF NOT EXISTS `doc_compliance_status` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int,
  `companyId` int,
  `overallStatus` varchar(20) NOT NULL,
  `complianceScore` int,
  `canOperate` boolean DEFAULT false,
  `totalRequired` int DEFAULT 0,
  `totalUploaded` int DEFAULT 0,
  `totalVerified` int DEFAULT 0,
  `totalMissing` int DEFAULT 0,
  `totalExpired` int DEFAULT 0,
  `totalExpiringSoon` int DEFAULT 0,
  `totalPendingReview` int DEFAULT 0,
  `totalRejected` int DEFAULT 0,
  `hasBlockingIssues` boolean DEFAULT false,
  `blockingDocuments` json,
  `missingDocuments` json,
  `expiredDocuments` json,
  `expiringDocuments` json,
  `pendingDocuments` json,
  `rejectedDocuments` json,
  `nextExpirationDate` varchar(10),
  `nextExpiringDocument` varchar(50),
  `calculatedAt` timestamp DEFAULT CURRENT_TIMESTAMP,
  `validUntil` timestamp NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_doc_compliance_user` (`userId`),
  INDEX `idx_doc_compliance_company` (`companyId`)
);

CREATE TABLE IF NOT EXISTS `state_doc_requirements` (
  `id` int NOT NULL AUTO_INCREMENT,
  `stateCode` varchar(2) NOT NULL,
  `stateName` varchar(100) NOT NULL,
  `documentTypeId` varchar(50) NOT NULL,
  `stateFormNumber` varchar(50),
  `stateFormName` varchar(200),
  `stateIssuingAgency` varchar(200),
  `statePortalUrl` text,
  `stateFormUrl` text,
  `stateInstructionsUrl` text,
  `isRequired` boolean DEFAULT true,
  `requiredForRoles` json,
  `conditions` json,
  `filingFee` decimal(10,2),
  `renewalFee` decimal(10,2),
  `lateFee` decimal(10,2),
  `validityPeriod` varchar(50),
  `renewalWindow` varchar(100),
  `notes` text,
  `lastVerified` varchar(10),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_state_doc_req_state` (`stateCode`),
  INDEX `idx_state_doc_req_doctype` (`documentTypeId`),
  UNIQUE KEY `idx_state_doc_req_unique` (`stateCode`, `documentTypeId`)
);

CREATE TABLE IF NOT EXISTS `user_operating_states` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `stateCode` varchar(2) NOT NULL,
  `isHomeState` boolean DEFAULT false,
  `isRegisteredState` boolean DEFAULT false,
  `isOperatingState` boolean DEFAULT true,
  `hasStatePermit` boolean DEFAULT false,
  `permitNumber` varchar(100),
  `permitExpiresAt` varchar(10),
  `hasWeightDistanceTax` boolean DEFAULT false,
  `weightDistanceAccountNumber` varchar(100),
  `addedAt` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_user_op_states_user` (`userId`),
  UNIQUE KEY `idx_user_op_states_unique` (`userId`, `stateCode`)
);

CREATE TABLE IF NOT EXISTS `document_templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `documentTypeId` varchar(50) NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text,
  `version` varchar(20) NOT NULL,
  `templateUrl` text NOT NULL,
  `thumbnailUrl` text,
  `isFillable` boolean DEFAULT false,
  `formFields` json,
  `sourceUrl` text,
  `lastOfficialUpdate` varchar(10),
  `stateCode` varchar(2),
  `isActive` boolean DEFAULT true,
  `effectiveDate` varchar(10),
  `supersededById` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_templates_doctype` (`documentTypeId`),
  INDEX `idx_templates_state` (`stateCode`)
);

CREATE TABLE IF NOT EXISTS `document_notifications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `documentTypeId` varchar(50) NOT NULL,
  `userDocumentId` int,
  `notificationType` varchar(50) NOT NULL,
  `scheduledFor` timestamp NOT NULL,
  `sentAt` timestamp NULL,
  `isSent` boolean DEFAULT false,
  `channels` json,
  `channelResults` json,
  `subject` text,
  `message` text,
  `actionUrl` text,
  `readAt` timestamp NULL,
  `clickedAt` timestamp NULL,
  `dismissedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_doc_notif_user` (`userId`),
  INDEX `idx_doc_notif_scheduled` (`scheduledFor`),
  INDEX `idx_doc_notif_pending` (`isSent`, `scheduledFor`)
);
