/**
 * Create all 19 missing tables in production DB
 * Usage: DATABASE_URL=<url> npx tsx server/migrations/run_missing_tables.ts
 */
import mysql2 from "mysql2/promise";

async function run() {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) { console.error("DATABASE_URL required"); process.exit(1); }

  const conn = await mysql2.createConnection(dbUrl);
  console.log("Connected to database\n");

  const tables: [string, string][] = [
    ["catalyst_risk_scores", `CREATE TABLE IF NOT EXISTS catalyst_risk_scores (
      id INT AUTO_INCREMENT PRIMARY KEY,
      companyId INT NOT NULL,
      overallScore INT NOT NULL,
      riskTier ENUM('low','moderate','elevated','high','critical') NOT NULL,
      safetyScore INT,
      insuranceScore INT,
      complianceScore INT,
      financialScore INT,
      claimsHistory JSON,
      csaBasicScores JSON,
      outOfServiceRate DECIMAL(5,2),
      crashRate DECIMAL(5,4),
      factors JSON DEFAULT ('[]'),
      recommendations JSON DEFAULT ('[]'),
      calculatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      validUntil TIMESTAMP NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY risk_score_company_idx (companyId),
      INDEX risk_score_tier_idx (riskTier)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["fmcsa_catalyst_cache", `CREATE TABLE IF NOT EXISTS fmcsa_catalyst_cache (
      id INT AUTO_INCREMENT PRIMARY KEY,
      dotNumber VARCHAR(8) NOT NULL,
      mcNumber VARCHAR(12),
      legalName VARCHAR(255),
      dbaName VARCHAR(255),
      entityType VARCHAR(50),
      operatingStatus VARCHAR(50),
      safetyRating VARCHAR(50),
      outOfServiceDate TIMESTAMP NULL,
      address TEXT,
      phone VARCHAR(20),
      powerUnits INT,
      drivers INT,
      carrierOperation VARCHAR(100),
      cargoCarried JSON,
      hazmatPermit TINYINT(1) DEFAULT 0,
      insuranceOnFile TINYINT(1) DEFAULT 0,
      bipdInsurance DECIMAL(14,2),
      cargoInsurance DECIMAL(14,2),
      bondSurety DECIMAL(14,2),
      basicsData JSON,
      rawResponse JSON,
      fetchedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      expiresAt TIMESTAMP NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY fmcsa_dot_unique (dotNumber),
      INDEX fmcsa_mc_idx (mcNumber),
      INDEX fmcsa_status_idx (operatingStatus)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["detention_claims", `CREATE TABLE IF NOT EXISTS detention_claims (
      id INT AUTO_INCREMENT PRIMARY KEY,
      loadId INT NOT NULL,
      claimantUserId INT NOT NULL,
      claimantCompanyId INT,
      facilityType ENUM('pickup','delivery') NOT NULL,
      arrivalAt TIMESTAMP NOT NULL,
      departureAt TIMESTAMP NULL,
      freeTimeMinutes INT NOT NULL DEFAULT 120,
      billableMinutes INT DEFAULT 0,
      hourlyRate DECIMAL(10,2) NOT NULL DEFAULT 75.00,
      totalAmount DECIMAL(10,2) DEFAULT 0,
      status ENUM('accruing','submitted','approved','denied','paid') NOT NULL DEFAULT 'accruing',
      evidence JSON,
      approvedBy INT,
      approvedAt TIMESTAMP NULL,
      notes TEXT,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX det_claim_load_idx (loadId),
      INDEX det_claim_status_idx (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["factoring_invoices", `CREATE TABLE IF NOT EXISTS factoring_invoices (
      id INT AUTO_INCREMENT PRIMARY KEY,
      loadId INT NOT NULL,
      invoiceNumber VARCHAR(50) NOT NULL,
      catalystUserId INT NOT NULL,
      catalystCompanyId INT,
      factoringCompanyId INT,
      invoiceAmount DECIMAL(12,2) NOT NULL,
      advanceRate DECIMAL(5,2) DEFAULT 90.00,
      advanceAmount DECIMAL(12,2),
      feeAmount DECIMAL(10,2),
      netAmount DECIMAL(12,2),
      status ENUM('draft','submitted','approved','funded','collected','disputed') NOT NULL DEFAULT 'draft',
      shipperPaymentDue TIMESTAMP NULL,
      fundedAt TIMESTAMP NULL,
      collectedAt TIMESTAMP NULL,
      documents JSON,
      notes TEXT,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY factoring_invoice_num (invoiceNumber),
      INDEX factoring_load_idx (loadId),
      INDEX factoring_catalyst_idx (catalystUserId),
      INDEX factoring_status_idx (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["dtc_codes", `CREATE TABLE IF NOT EXISTS dtc_codes (
      id INT AUTO_INCREMENT PRIMARY KEY,
      code VARCHAR(20) NOT NULL,
      system ENUM('engine','transmission','abs','emissions','body','chassis','network') NOT NULL,
      severity ENUM('info','warning','critical') NOT NULL DEFAULT 'warning',
      shortDescription VARCHAR(255) NOT NULL,
      longDescription TEXT,
      commonCauses TEXT,
      suggestedFixes TEXT,
      estimatedCostMin DECIMAL(8,2),
      estimatedCostMax DECIMAL(8,2),
      canDriveWith TINYINT(1) DEFAULT 1,
      outOfServiceRisk TINYINT(1) DEFAULT 0,
      make VARCHAR(50),
      model VARCHAR(50),
      yearRange VARCHAR(20),
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE KEY dtc_code_unique (code, make, model),
      INDEX dtc_system_idx (system),
      INDEX dtc_severity_idx (severity)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["lease_agreements", `CREATE TABLE IF NOT EXISTS lease_agreements (
      id INT AUTO_INCREMENT PRIMARY KEY,
      leaseNumber VARCHAR(50) NOT NULL,
      leaseType ENUM('full_lease_on','trip_lease','interline','seasonal') NOT NULL,
      lessorCompanyId INT NOT NULL,
      lessorUserId INT NOT NULL,
      lesseeCompanyId INT NOT NULL,
      lesseeUserId INT NOT NULL,
      dotNumber VARCHAR(20),
      mcNumber VARCHAR(20),
      vehicleIds JSON,
      driverIds JSON,
      effectiveDate TIMESTAMP NOT NULL,
      expirationDate TIMESTAMP NULL,
      autoRenew TINYINT(1) DEFAULT 0,
      insuranceRequirements JSON,
      compensationType ENUM('percentage','flat_per_mile','flat_per_load','hourly') NOT NULL,
      compensationRate DECIMAL(10,4) NOT NULL,
      deductions JSON,
      escrowRequired DECIMAL(10,2),
      status ENUM('draft','pending','active','suspended','terminated','expired') NOT NULL DEFAULT 'draft',
      terminationReason TEXT,
      terminatedAt TIMESTAMP NULL,
      terminatedBy INT,
      documentUrl TEXT,
      signedByLessor TINYINT(1) DEFAULT 0,
      signedByLessee TINYINT(1) DEFAULT 0,
      lessorSignedAt TIMESTAMP NULL,
      lesseeSignedAt TIMESTAMP NULL,
      notes TEXT,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY lease_number_unique (leaseNumber),
      INDEX lease_lessor_idx (lessorCompanyId),
      INDEX lease_lessee_idx (lesseeCompanyId),
      INDEX lease_status_idx (status),
      INDEX lease_type_idx (leaseType)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["run_tickets", `CREATE TABLE IF NOT EXISTS run_tickets (
      id INT AUTO_INCREMENT PRIMARY KEY,
      ticketNumber VARCHAR(50) NOT NULL,
      loadId INT,
      driverId INT NOT NULL,
      companyId INT NOT NULL,
      startDate TIMESTAMP NOT NULL,
      endDate TIMESTAMP NULL,
      startOdometer DECIMAL(10,1),
      endOdometer DECIMAL(10,1),
      totalMiles DECIMAL(10,1),
      fuelGallons DECIMAL(8,2),
      fuelCost DECIMAL(10,2),
      tollCost DECIMAL(8,2),
      otherExpenses DECIMAL(10,2),
      status ENUM('open','submitted','approved','rejected','paid') NOT NULL DEFAULT 'open',
      notes TEXT,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX rt_load_idx (loadId),
      INDEX rt_driver_idx (driverId),
      INDEX rt_company_idx (companyId)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["run_ticket_expenses", `CREATE TABLE IF NOT EXISTS run_ticket_expenses (
      id INT AUTO_INCREMENT PRIMARY KEY,
      ticketId INT NOT NULL,
      type ENUM('fuel','toll','meal','lodging','repair','scale','parking','other') NOT NULL,
      amount DECIMAL(10,2) NOT NULL,
      description VARCHAR(255),
      receiptUrl TEXT,
      location VARCHAR(255),
      expenseDate TIMESTAMP NOT NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX rte_ticket_idx (ticketId)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["reefer_readings", `CREATE TABLE IF NOT EXISTS reefer_readings (
      id INT AUTO_INCREMENT PRIMARY KEY,
      loadId INT,
      vehicleId INT,
      driverId INT,
      companyId INT,
      setpointF DECIMAL(5,1),
      actualTempF DECIMAL(5,1) NOT NULL,
      returnAirF DECIMAL(5,1),
      ambientTempF DECIMAL(5,1),
      humidity DECIMAL(4,1),
      mode ENUM('continuous','start_stop','defrost','off') DEFAULT 'continuous',
      fuelLevelPct INT,
      doorStatus ENUM('closed','open') DEFAULT 'closed',
      alarmActive TINYINT(1) DEFAULT 0,
      latitude DECIMAL(9,6),
      longitude DECIMAL(10,6),
      recordedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX rr_load_idx (loadId),
      INDEX rr_vehicle_idx (vehicleId),
      INDEX rr_recorded_idx (recordedAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["reefer_alerts", `CREATE TABLE IF NOT EXISTS reefer_alerts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      loadId INT,
      vehicleId INT,
      readingId INT,
      alertType ENUM('temp_high','temp_low','door_open','fuel_low','unit_off','defrost_long','sensor_fail') NOT NULL,
      severity ENUM('warning','critical') NOT NULL DEFAULT 'warning',
      message TEXT,
      tempAtAlert DECIMAL(5,1),
      thresholdValue DECIMAL(5,1),
      acknowledged TINYINT(1) DEFAULT 0,
      acknowledgedBy INT,
      acknowledgedAt TIMESTAMP NULL,
      resolvedAt TIMESTAMP NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX ra_load_idx (loadId),
      INDEX ra_vehicle_idx (vehicleId),
      INDEX ra_type_idx (alertType),
      INDEX ra_severity_idx (severity)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["per_load_insurance_policies", `CREATE TABLE IF NOT EXISTS per_load_insurance_policies (
      id INT AUTO_INCREMENT PRIMARY KEY,
      policyNumber VARCHAR(50) NOT NULL,
      loadId INT NOT NULL,
      catalystCompanyId INT NOT NULL,
      provider VARCHAR(100) NOT NULL DEFAULT 'Loadsure',
      coverageType ENUM('cargo','liability','combined') NOT NULL DEFAULT 'cargo',
      cargoValue DECIMAL(12,2),
      premiumAmount DECIMAL(10,2) NOT NULL,
      deductible DECIMAL(10,2),
      coverageLimit DECIMAL(12,2),
      commodityType VARCHAR(100),
      hazmatClass VARCHAR(10),
      originState VARCHAR(2),
      destState VARCHAR(2),
      quoteId VARCHAR(100),
      quoteData JSON,
      status ENUM('quoted','bound','active','expired','claimed','cancelled') NOT NULL DEFAULT 'quoted',
      effectiveFrom TIMESTAMP NULL,
      effectiveTo TIMESTAMP NULL,
      purchasedAt TIMESTAMP NULL,
      purchasedBy INT,
      claimId VARCHAR(100),
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY pli_policy_unique (policyNumber),
      INDEX pli_load_idx (loadId),
      INDEX pli_company_idx (catalystCompanyId),
      INDEX pli_status_idx (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["irp_registrations", `CREATE TABLE IF NOT EXISTS irp_registrations (
      id INT AUTO_INCREMENT PRIMARY KEY,
      companyId INT NOT NULL,
      vehicleId INT,
      irpAccountNumber VARCHAR(50),
      baseJurisdiction VARCHAR(2) NOT NULL,
      registeredStates JSON,
      registeredWeight INT,
      effectiveDate TIMESTAMP NOT NULL,
      expirationDate TIMESTAMP NOT NULL,
      cabCardUrl TEXT,
      status ENUM('active','expired','suspended','pending') NOT NULL DEFAULT 'active',
      renewalDate TIMESTAMP NULL,
      annualFee DECIMAL(10,2),
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX irp_company_idx (companyId),
      INDEX irp_vehicle_idx (vehicleId),
      INDEX irp_status_idx (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["debtors", `CREATE TABLE IF NOT EXISTS debtors (
      id INT AUTO_INCREMENT PRIMARY KEY,
      companyId INT,
      userId INT,
      name VARCHAR(255) NOT NULL,
      contactEmail VARCHAR(320),
      contactPhone VARCHAR(20),
      creditLimit DECIMAL(12,2),
      currentBalance DECIMAL(12,2) DEFAULT 0,
      paymentTermDays INT DEFAULT 30,
      avgPayDays DECIMAL(5,1),
      onTimePaymentPct DECIMAL(5,2),
      creditScore INT,
      creditRating ENUM('excellent','good','fair','poor','unknown') DEFAULT 'unknown',
      lastPaymentAt TIMESTAMP NULL,
      lastCreditCheckAt TIMESTAMP NULL,
      status ENUM('active','suspended','delinquent','collections','closed') NOT NULL DEFAULT 'active',
      notes TEXT,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX debtor_company_idx (companyId),
      INDEX debtor_user_idx (userId),
      INDEX debtor_status_idx (status),
      INDEX debtor_rating_idx (creditRating)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["credit_checks", `CREATE TABLE IF NOT EXISTS credit_checks (
      id INT AUTO_INCREMENT PRIMARY KEY,
      requestedBy INT NOT NULL,
      debtorId INT,
      targetCompanyId INT,
      targetName VARCHAR(255),
      checkType ENUM('full','quick','monitoring') NOT NULL DEFAULT 'quick',
      provider VARCHAR(100),
      score INT,
      rating ENUM('excellent','good','fair','poor','unknown'),
      reportData JSON,
      riskLevel ENUM('low','medium','high','critical'),
      recommendedCreditLimit DECIMAL(12,2),
      paymentHistory JSON,
      status ENUM('pending','completed','failed','expired') NOT NULL DEFAULT 'pending',
      completedAt TIMESTAMP NULL,
      expiresAt TIMESTAMP NULL,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX cc_requestor_idx (requestedBy),
      INDEX cc_debtor_idx (debtorId),
      INDEX cc_target_idx (targetCompanyId),
      INDEX cc_status_idx (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["location_breadcrumbs", `CREATE TABLE IF NOT EXISTS location_breadcrumbs (
      id INT AUTO_INCREMENT PRIMARY KEY,
      loadId INT,
      driverId INT,
      vehicleId INT,
      latitude DECIMAL(9,6) NOT NULL,
      longitude DECIMAL(10,6) NOT NULL,
      altitude DECIMAL(7,1),
      speed DECIMAL(5,1),
      heading DECIMAL(5,1),
      accuracy DECIMAL(5,1),
      source ENUM('gps','network','manual','geofence') NOT NULL DEFAULT 'gps',
      eventType ENUM('periodic','stop','start','geofence_enter','geofence_exit','sos','milestone') DEFAULT 'periodic',
      address VARCHAR(500),
      city VARCHAR(128),
      state VARCHAR(2),
      isMoving TINYINT(1) DEFAULT 1,
      batteryPct INT,
      signalStrength INT,
      metadata JSON,
      recordedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX lb_load_idx (loadId),
      INDEX lb_driver_idx (driverId),
      INDEX lb_vehicle_idx (vehicleId),
      INDEX lb_recorded_idx (recordedAt),
      INDEX lb_coords_idx (latitude, longitude)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["geotags", `CREATE TABLE IF NOT EXISTS geotags (
      id INT AUTO_INCREMENT PRIMARY KEY,
      loadId INT,
      driverId INT,
      userId INT,
      tagType ENUM('pickup_arrival','pickup_departure','delivery_arrival','delivery_departure','checkpoint','photo','signature','incident','custom') NOT NULL,
      latitude DECIMAL(9,6) NOT NULL,
      longitude DECIMAL(10,6) NOT NULL,
      accuracy DECIMAL(5,1),
      address VARCHAR(500),
      city VARCHAR(128),
      state VARCHAR(2),
      note TEXT,
      photoUrl TEXT,
      signatureUrl TEXT,
      documentId INT,
      verificationStatus ENUM('auto_verified','manual_verified','disputed','pending') DEFAULT 'pending',
      verifiedBy INT,
      verifiedAt TIMESTAMP NULL,
      metadata JSON,
      taggedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX gt_load_idx (loadId),
      INDEX gt_driver_idx (driverId),
      INDEX gt_type_idx (tagType),
      INDEX gt_tagged_idx (taggedAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["load_routes", `CREATE TABLE IF NOT EXISTS load_routes (
      id INT AUTO_INCREMENT PRIMARY KEY,
      loadId INT NOT NULL,
      routeType ENUM('planned','actual','optimized','hazmat_compliant') NOT NULL DEFAULT 'planned',
      originLat DECIMAL(9,6) NOT NULL,
      originLng DECIMAL(10,6) NOT NULL,
      destLat DECIMAL(9,6) NOT NULL,
      destLng DECIMAL(10,6) NOT NULL,
      distanceMiles DECIMAL(8,2),
      durationMinutes INT,
      polyline TEXT,
      waypoints JSON,
      hazmatRestrictions JSON,
      tunnelRestrictions JSON,
      weightRestrictions JSON,
      hosStops JSON,
      fuelStops JSON,
      weighStations JSON,
      stateCrossings JSON,
      tollCost DECIMAL(8,2),
      fuelCostEstimate DECIMAL(8,2),
      riskScore INT,
      isActive TINYINT(1) DEFAULT 1,
      calculatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX lr_load_idx (loadId),
      INDEX lr_type_idx (routeType),
      INDEX lr_active_idx (isActive)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["detention_records", `CREATE TABLE IF NOT EXISTS detention_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      loadId INT NOT NULL,
      driverId INT,
      facilityType ENUM('pickup','delivery') NOT NULL,
      facilityName VARCHAR(255),
      facilityAddress VARCHAR(500),
      arrivedAt TIMESTAMP NOT NULL,
      loadingStartedAt TIMESTAMP NULL,
      departedAt TIMESTAMP NULL,
      freeTimeMinutes INT NOT NULL DEFAULT 120,
      totalDwellMinutes INT,
      detentionMinutes INT DEFAULT 0,
      hourlyRate DECIMAL(10,2) DEFAULT 75.00,
      detentionCharge DECIMAL(10,2) DEFAULT 0,
      status ENUM('waiting','loading_unloading','completed','billed','paid','waived') NOT NULL DEFAULT 'waiting',
      waivedBy INT,
      waivedReason TEXT,
      evidence JSON,
      notes TEXT,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX dr_load_idx (loadId),
      INDEX dr_driver_idx (driverId),
      INDEX dr_status_idx (status),
      INDEX dr_arrived_idx (arrivedAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],

    ["state_crossings", `CREATE TABLE IF NOT EXISTS state_crossings (
      id INT AUTO_INCREMENT PRIMARY KEY,
      loadId INT NOT NULL,
      driverId INT,
      vehicleId INT,
      fromState VARCHAR(2) NOT NULL,
      toState VARCHAR(2) NOT NULL,
      crossingLat DECIMAL(9,6),
      crossingLng DECIMAL(10,6),
      crossedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      odometerReading DECIMAL(10,1),
      fuelGallons DECIMAL(8,2),
      isHazmat TINYINT(1) DEFAULT 0,
      hazmatClass VARCHAR(10),
      permitRequired TINYINT(1) DEFAULT 0,
      permitNumber VARCHAR(50),
      notes TEXT,
      createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX sc_load_idx (loadId),
      INDEX sc_driver_idx (driverId),
      INDEX sc_states_idx (fromState, toState),
      INDEX sc_crossed_idx (crossedAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`],
  ];

  let ok = 0, skip = 0, err = 0;
  for (const [name, sql] of tables) {
    try {
      await conn.query(sql);
      console.log(`  [CREATE] ${name}`);
      ok++;
    } catch (e: any) {
      if (e.code === "ER_TABLE_EXISTS_ERROR") {
        console.log(`  [EXISTS] ${name}`);
        skip++;
      } else {
        console.error(`  [ERROR]  ${name}: ${e.message?.slice(0, 200)}`);
        err++;
      }
    }
  }

  await conn.end();
  console.log(`\nDone: ${ok} created, ${skip} existed, ${err} errors`);
}

run().catch((e) => {
  console.error("Migration failed:", e);
  process.exit(1);
});
