-- EPA Enhanced: Clean Air Markets Emissions + RCRA Hazardous Waste Handlers

CREATE TABLE IF NOT EXISTS `hz_emissions` (
  `id` varchar(36) NOT NULL,
  `facility_id` varchar(20) NOT NULL,
  `facility_name` varchar(255) NOT NULL,
  `state_code` char(2) NOT NULL,
  `county_name` varchar(100),
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `fuel_types` json,
  `unit_types` json,
  `so2_tons` decimal(12,2),
  `nox_tons` decimal(12,2),
  `co2_tons` decimal(15,2),
  `hg_lbs` decimal(10,4),
  `gross_load_mwh` decimal(15,2),
  `heat_input_mmbtu` decimal(15,2),
  `operating_hours` int,
  `program_codes` json,
  `reporting_year` int NOT NULL,
  `reporting_quarter` int,
  `source_category` varchar(100),
  `fetched_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_hz_emissions_state` (`state_code`),
  INDEX `idx_hz_emissions_facility` (`facility_id`),
  INDEX `idx_hz_emissions_year` (`reporting_year`),
  INDEX `idx_hz_emissions_location` (`latitude`, `longitude`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hz_rcra_handlers` (
  `handler_id` varchar(20) NOT NULL,
  `handler_name` varchar(255) NOT NULL,
  `state_code` char(2) NOT NULL,
  `city` varchar(100),
  `county` varchar(100),
  `zip_code` varchar(10),
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `handler_type` enum('Generator','Transporter','TSDF','Mixed') DEFAULT 'Generator',
  `generator_status` varchar(10),
  `waste_activity_codes` json,
  `waste_codes` json,
  `land_type` varchar(50),
  `compliance_status` enum('In Compliance','Violation','Unknown') DEFAULT 'Unknown',
  `evaluations_count` int DEFAULT 0,
  `violations_count` int DEFAULT 0,
  `enforcement_actions_count` int DEFAULT 0,
  `penalties_total` decimal(15,2),
  `last_evaluation_date` date,
  `naics_code` varchar(10),
  `industry_sector` varchar(100),
  `fetched_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`handler_id`),
  INDEX `idx_hz_rcra_state` (`state_code`),
  INDEX `idx_hz_rcra_type` (`handler_type`),
  INDEX `idx_hz_rcra_compliance` (`compliance_status`),
  INDEX `idx_hz_rcra_location` (`latitude`, `longitude`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
