-- 0027_emanifest_tables.sql
-- Phase 2: ACE/ACI eManifest tables

-- ─── ACE eManifests (US-bound via CBP) ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS `ace_manifests` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `manifest_id` varchar(64) NOT NULL UNIQUE,
  `trip_number` varchar(32) NOT NULL,
  `scac_code` varchar(8) NOT NULL,
  `port_of_entry` varchar(8) NOT NULL,
  `estimated_arrival` datetime NOT NULL,
  `status` enum('draft','submitted','accepted','hold','refused','do_not_load','cancelled') NOT NULL DEFAULT 'draft',
  `carrier_name` varchar(255) NOT NULL,
  `dot_number` varchar(16) NOT NULL,
  `bond_number` varchar(32) NULL,
  `vehicle_type` enum('truck','rail','vessel','air') NOT NULL DEFAULT 'truck',
  `truck_license` varchar(16) NOT NULL,
  `truck_state` varchar(4) NOT NULL,
  `trailer_license` varchar(16) NULL,
  `trailer_state` varchar(4) NULL,
  `seal_numbers` json NOT NULL DEFAULT ('[]'),
  `driver_first_name` varchar(128) NOT NULL,
  `driver_last_name` varchar(128) NOT NULL,
  `driver_license_number` varchar(32) NOT NULL,
  `driver_license_state` varchar(4) NOT NULL,
  `driver_citizenship` varchar(4) NOT NULL,
  `fast_card_number` varchar(32) NULL,
  `shipments` json NOT NULL,
  `load_id` int NULL,
  `submitted_at` datetime NULL,
  `accepted_at` datetime NULL,
  `response_message` text NULL,
  `cbp_disposition` varchar(64) NULL,
  `created_by` int NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_ace_trip` (`trip_number`),
  INDEX `idx_ace_status` (`status`),
  INDEX `idx_ace_load` (`load_id`),
  INDEX `idx_ace_port` (`port_of_entry`),
  INDEX `idx_ace_scac` (`scac_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── ACI eManifests (Canada-bound via CBSA) ─────────────────────────────────

CREATE TABLE IF NOT EXISTS `aci_manifests` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `manifest_id` varchar(64) NOT NULL UNIQUE,
  `cargo_control_number` varchar(32) NOT NULL,
  `carrier_code` varchar(8) NOT NULL,
  `port_of_entry` varchar(8) NOT NULL,
  `estimated_arrival` datetime NOT NULL,
  `status` enum('draft','submitted','matched','not_matched','referred','released','cancelled') NOT NULL DEFAULT 'draft',
  `carrier_name` varchar(255) NOT NULL,
  `conveyance_type` enum('highway','rail','marine','air') NOT NULL DEFAULT 'highway',
  `truck_license` varchar(16) NOT NULL,
  `truck_jurisdiction` varchar(4) NOT NULL,
  `trailer_license` varchar(16) NULL,
  `trailer_jurisdiction` varchar(4) NULL,
  `seal_numbers` json NOT NULL DEFAULT ('[]'),
  `container_numbers` json NOT NULL DEFAULT ('[]'),
  `driver_first_name` varchar(128) NOT NULL,
  `driver_last_name` varchar(128) NOT NULL,
  `driver_date_of_birth` date NOT NULL,
  `driver_citizenship` varchar(4) NOT NULL,
  `driver_document_type` enum('passport','fast_card','nexus','cdl') NOT NULL,
  `driver_document_number` varchar(32) NOT NULL,
  `shipments` json NOT NULL,
  `pars_number` varchar(16) NULL,
  `load_id` int NULL,
  `submitted_at` datetime NULL,
  `matched_at` datetime NULL,
  `response_message` text NULL,
  `created_by` int NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_aci_ccn` (`cargo_control_number`),
  INDEX `idx_aci_status` (`status`),
  INDEX `idx_aci_load` (`load_id`),
  INDEX `idx_aci_port` (`port_of_entry`),
  INDEX `idx_aci_pars` (`pars_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
