-- 0028_fda_usda_enforcement.sql
-- V12: MX→US Enforcement — FDA Prior Notice + USDA APHIS Hold Tracking

-- ─── FDA Prior Notices (21 CFR Part 1, Subpart I) ─────────────────────────────
CREATE TABLE IF NOT EXISTS `fda_prior_notices` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `confirmation_number` varchar(32) NOT NULL UNIQUE,
  `load_id` int NULL,
  `ace_manifest_id` int NULL,
  `status` enum('draft','submitted','confirmed','review','hold','refused','cancelled') NOT NULL DEFAULT 'draft',
  `submitter_id` int NOT NULL,
  `importer_name` varchar(255) NOT NULL,
  `importer_fei_number` varchar(16) NULL,
  `importer_duns_number` varchar(16) NULL,
  `product_description` varchar(500) NOT NULL,
  `product_code` varchar(16) NULL,
  `product_fda_code` varchar(16) NULL,
  `country_of_origin` varchar(4) NOT NULL,
  `country_of_shipment` varchar(4) NOT NULL,
  `manufacturer_name` varchar(255) NULL,
  `manufacturer_fei_number` varchar(16) NULL,
  `shipper_name` varchar(255) NOT NULL,
  `grower_id` varchar(32) NULL,
  `quantity` decimal(12,2) NOT NULL,
  `quantity_unit` varchar(16) NOT NULL,
  `estimated_value_usd` decimal(12,2) NULL,
  `port_of_entry` varchar(8) NOT NULL,
  `anticipated_arrival` datetime NOT NULL,
  `mode_of_transport` enum('truck','rail','vessel','air') NOT NULL DEFAULT 'truck',
  `consignee_name` varchar(255) NOT NULL,
  `consignee_address` varchar(500) NULL,
  `consignee_fei_number` varchar(16) NULL,
  `submitted_at` datetime NULL,
  `confirmed_at` datetime NULL,
  `response_message` text NULL,
  `hold_reason` text NULL,
  `filing_deadline` datetime NULL,
  `is_late` boolean NOT NULL DEFAULT false,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fda_pn_load_idx` (`load_id`),
  INDEX `fda_pn_status_idx` (`status`),
  INDEX `fda_pn_port_idx` (`port_of_entry`),
  INDEX `fda_pn_arrival_idx` (`anticipated_arrival`),
  INDEX `fda_pn_confirm_idx` (`confirmation_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ─── USDA APHIS Holds & Inspections ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `usda_holds` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `hold_number` varchar(32) NOT NULL UNIQUE,
  `load_id` int NULL,
  `ace_manifest_id` int NULL,
  `fda_prior_notice_id` int NULL,
  `status` enum('pending_inspection','inspecting','sampled','passed','conditional_release','hold','refused','released') NOT NULL DEFAULT 'pending_inspection',
  `agency` enum('APHIS','FSIS','AMS','GIPSA') NOT NULL DEFAULT 'APHIS',
  `inspection_type` enum('phytosanitary','veterinary','food_safety','grain_inspection','fumigation','lab_sample') NOT NULL,
  `commodity_description` varchar(500) NOT NULL,
  `commodity_hts_code` varchar(16) NULL,
  `country_of_origin` varchar(4) NOT NULL,
  `quantity` decimal(12,2) NULL,
  `quantity_unit` varchar(16) NULL,
  `port_of_entry` varchar(8) NOT NULL,
  `inspection_facility` varchar(255) NULL,
  `hold_reason` text NULL,
  `hold_issued_at` datetime NULL,
  `hold_issued_by` varchar(128) NULL,
  `inspector_name` varchar(128) NULL,
  `inspection_started_at` datetime NULL,
  `inspection_completed_at` datetime NULL,
  `inspection_notes` text NULL,
  `samples_taken` boolean NOT NULL DEFAULT false,
  `lab_results` json NULL,
  `release_type` enum('unconditional','conditional','refused') NULL,
  `release_conditions` text NULL,
  `released_at` datetime NULL,
  `refusal_reason` text NULL,
  `inspection_fee_usd` decimal(10,2) NULL,
  `storage_fee_usd` decimal(10,2) NULL,
  `created_by` int NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `usda_hold_load_idx` (`load_id`),
  INDEX `usda_hold_status_idx` (`status`),
  INDEX `usda_hold_agency_idx` (`agency`),
  INDEX `usda_hold_port_idx` (`port_of_entry`),
  INDEX `usda_hold_num_idx` (`hold_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
