const {updateCourse} = require('./update_helper.cjs');
updateCourse('accident-reporting-post-crash', {
1: {
1: `<h2>Immediate Post-Accident Response</h2><p>When a CMV crash occurs, the driver's first priority is <strong>scene protection and life safety</strong>. Under 49 CFR §392.40, drivers must render reasonable assistance to injured persons.</p><h3>Critical First 15 Minutes</h3><ol><li><strong>Secure the scene:</strong> Activate hazard flashers, set reflective triangles (49 CFR §392.22) at 10, 100, and 200 feet behind the vehicle</li><li><strong>Check for injuries:</strong> Do NOT move injured persons unless there is immediate danger (fire, hazmat leak)</li><li><strong>Call 911:</strong> Report location, number of vehicles, injuries, hazmat presence</li><li><strong>Protect evidence:</strong> Do NOT move vehicles unless required for safety or by law enforcement</li></ol><h3>Hazmat Crashes</h3><p>Consult the Emergency Response Guidebook (ERG) immediately. Call CHEMTREC at 1-800-424-9300. Establish isolation zones per the ERG orange-bordered pages. Under 49 CFR §171.15, telephonic reports to the National Response Center are required within 12 hours for incidents involving death, hospitalization, evacuation, or road closure.</p><h3>Required Equipment — §393.95</h3><p>Every CMV must carry: three reflective triangles, a fire extinguisher rated 5 B:C minimum, and spare fuses if applicable. Place triangles within 10 minutes of stopping. On divided highways: 10, 100, 200 feet behind. On undivided two-lane roads: one 100 feet ahead, one 100 feet behind.</p>`,
2: `<h2>Immediate Response — Practical Scenarios</h2><h3>Scenario 1: Interstate Rear-End</h3><p>You strike the vehicle ahead on I-80 when traffic stops. Your truck is drivable; the other driver has neck pain.</p><p><strong>Actions:</strong></p><ul><li>DOT-recordable crash (bodily injury requiring medical treatment)</li><li>Set triangles at 10, 100, 200 feet</li><li>Exchange info — do NOT admit fault</li><li>Contact dispatch within 15 minutes</li><li>Post-crash inspection per §396.9 before moving</li></ul><h3>Scenario 2: Single-Vehicle Jackknife</h3><p>You jackknife on a wet ramp. No other vehicles, no injuries, but your vehicle needs towing.</p><p><strong>Analysis:</strong> This IS DOT-recordable (tow-away). Report on accident register (49 CFR §390.15); maintain record 3 years.</p><h3>Scenario 3: Parking Lot Clip</h3><p>You clip a light pole backing into a truck stop. Minor bumper damage, no injuries, pole bent.</p><p><strong>Analysis:</strong> NOT typically DOT-recordable — no tow, no injury, no fatality. But always report to dispatch per company policy.</p>`
},
2: {
1: `<h2>DOT Reportable Crash Criteria</h2><h3>FMCSA Definition — 49 CFR §390.5</h3><p>A crash is DOT-reportable if it involves a CMV and results in ANY of:</p><ol><li><strong>Fatality:</strong> Any person dies as a result</li><li><strong>Bodily injury:</strong> Any person transported for immediate medical treatment away from the scene</li><li><strong>Tow-away:</strong> Any vehicle towed due to disabling damage</li></ol><h3>Important Distinctions</h3><ul><li>"Immediate medical treatment away from scene" = transported by ambulance/vehicle to medical facility. Someone who refuses treatment at the scene but later seeks care does NOT typically trigger this criterion</li><li>"Disabling damage" = vehicle cannot be driven from scene. Towed for convenience (flat tire, out of fuel) does NOT qualify</li><li>The CMV does NOT need to be at fault — if your parked CMV is struck and criteria are met, it's still reportable for your carrier</li></ul><h3>State Reporting</h3><p>Most states have lower thresholds — typically property damage exceeding $1,000-$2,500. State reports feed into FMCSA's MCMIS database and affect Crash Indicator BASIC scores.</p>`,
2: `<h2>Reportable Crashes — Decision Flowchart</h2><h3>At-Scene Quick Check</h3><ol><li>Did anyone die? → <strong>YES = Reportable</strong></li><li>Was anyone transported for medical treatment? → <strong>YES = Reportable</strong></li><li>Was any vehicle towed due to damage? → <strong>YES = Reportable</strong></li></ol><p>All NO → Not DOT-reportable (may still require state/company reporting).</p><h3>Gray Areas</h3><p><strong>A:</strong> Other driver says "I'm fine" but goes to ER next day. At the time, criterion #2 not met. Best practice: record it if carrier later learns of the visit.</p><p><strong>B:</strong> Your CMV has crash-caused flat. Service truck changes tire on scene — you drive away. NOT tow-away. But if a wrecker lifts the vehicle, some jurisdictions consider it a tow.</p><p><strong>C:</strong> Pedestrian trips near your parked CMV — no contact with vehicle. NOT a CMV crash.</p><h3>Crash Register — §390.15</h3><p>For each reportable crash record: date, location, driver name, injuries, fatalities, hazmat release status. Maintain 3 years. Keep copies of all accident reports.</p>`
},
3: {
1: `<h2>Post-Accident Drug & Alcohol Testing — 49 CFR Part 382</h2><h3>When Testing Is Required</h3><table><tr><th>Outcome</th><th>Citation to CMV Driver?</th><th>Test Required?</th></tr><tr><td>Fatality</td><td>Not relevant</td><td><strong>YES — always</strong></td></tr><tr><td>Injury + transport</td><td>YES</td><td><strong>YES</strong></td></tr><tr><td>Injury + transport</td><td>NO</td><td>NO</td></tr><tr><td>Tow-away</td><td>YES</td><td><strong>YES</strong></td></tr><tr><td>Tow-away</td><td>NO</td><td>NO</td></tr></table><h3>Timing Requirements</h3><ul><li><strong>Alcohol:</strong> Within 8 hours. If impossible, document reason, cease attempts after 8 hours</li><li><strong>Drugs:</strong> Within 32 hours. If impossible, document, cease after 32 hours</li><li>Driver must remain available — leaving without being tested = refusal</li></ul><h3>No-Alcohol Rule — §392.5</h3><p>After any crash, do not consume alcohol for 8 hours or until tested, whichever comes first. Violation = treated as refusal to test.</p>`,
2: `<h2>Post-Accident Testing — Scenarios</h2><h3>Scenario 1: Fatal Crash at 2 AM</h3><p>Other driver fatally injured. Nearest collection site opens 8 AM.</p><ul><li>Alcohol test by 10 AM (8-hour window). 6-hour wait is acceptable if documented</li><li>Drug test by 10 AM next day (32 hours)</li><li>NO alcohol from 2 AM until tested</li><li>Document every step and timestamp</li></ul><h3>Scenario 2: Injury, No Citation</h3><p>Other driver injured and transported, but officer determines they ran a red light — you are NOT cited.</p><p><strong>Result:</strong> Post-accident testing NOT required (no citation). Carrier may still conduct reasonable-suspicion or company-policy test.</p><h3>Refusal Consequences</h3><ul><li>Same as positive result</li><li>Immediate removal from safety-sensitive duties</li><li>Referral to Substance Abuse Professional (SAP)</li><li>Reported to FMCSA Clearinghouse</li><li>Full return-to-duty process required</li></ul><h3>Employer Documentation</h3><p>Carrier must document each test decision — including decisions NOT to test and why. Incomplete documentation is a top audit finding.</p>`
},
4: {
1: `<h2>Documentation & Reporting Requirements</h2><h3>Carrier Accident Register — §390.15</h3><p>Record: date, location, driver name, injuries, fatalities, hazmat release. Retain 3 years with copies of all reports.</p><h3>Hazmat Incident Reports</h3><ul><li><strong>Telephonic (§171.15):</strong> Call NRC 800-424-8802 within 12 hours for death, hospitalization, evacuation, road closure >1 hour, marine pollutant >450L</li><li><strong>Written (§171.16):</strong> DOT Form 5800.1 within 30 days for any incident meeting telephonic criteria OR involving fire, breakage, spillage, contamination</li></ul><h3>Insurance — Part 387</h3><p>Minimums: $750K general freight, $1M hazmat, $5M high-risk hazmat. Notify insurer immediately — most policies require 24-72 hour notice. Late notice can jeopardize coverage.</p><h3>State Reports</h3><p>Police reports feed into FMCSA MCMIS affecting your Crash Indicator BASIC. Thresholds vary by state ($1,000-$2,500 property damage).</p>`,
2: `<h2>Documentation — Practical Checklists</h2><h3>At-Scene Checklist</h3><ol><li>Photos: all vehicles (4+ angles), scene overview, skid marks, signage, your DVIR</li><li>Other party: name, license, insurance, plate, VIN</li><li>Officer: name, badge, agency, report number</li><li>Witnesses: names, phones, what they observed</li><li>Weather, road conditions, GPS coordinates</li><li>Dashcam footage — preserve immediately</li></ol><h3>Reporting Timeline</h3><table><tr><th>Report</th><th>Deadline</th></tr><tr><td>Dispatch notification</td><td>Immediately</td></tr><tr><td>Alcohol test</td><td>8 hours</td></tr><tr><td>NRC hazmat telephonic</td><td>12 hours</td></tr><tr><td>Drug test</td><td>32 hours</td></tr><tr><td>Insurance notification</td><td>24-72 hours</td></tr><tr><td>DOT 5800.1 written</td><td>30 days</td></tr><tr><td>DataQs preventability</td><td>12 months</td></tr></table><h3>Litigation Protection</h3><p>Be factual and objective. Do NOT speculate about causes or admit fault. Preserve all electronic data (ELD, dashcam, GPS). Follow your carrier's attorney communication protocol. Everything written at the scene is discoverable in court.</p>`
}
}).then(()=>process.exit(0));
