const {updateCourse} = require('./update_helper.cjs');
updateCourse('fmcsa-safety-audit-preparation', {
1: {
1: `<h2>Understanding Safety Audits & Reviews</h2><p>The FMCSA conducts safety audits to evaluate carriers' safety management. Understanding triggers and methodology is key.</p><h3>Types of Reviews</h3><ul><li><strong>New Entrant Safety Audit:</strong> Within 18 months of new authority. Failure = revocation</li><li><strong>Compliance Review:</strong> Comprehensive on-site investigation. Results in safety rating</li><li><strong>Focused Investigation:</strong> Targets a specific BASIC area</li><li><strong>Off-Site Investigation:</strong> Remote document review</li></ul><h3>Triggers</h3><ol><li>CSA BASICs above intervention thresholds</li><li>Fatal or serious crashes</li><li>Complaints filed against the carrier</li><li>High out-of-service rates</li></ol><h3>Safety Rating Outcomes</h3><table><tr><th>Rating</th><th>Result</th></tr><tr><td>Satisfactory</td><td>Adequate safety controls</td></tr><tr><td>Conditional</td><td>Deficiencies — corrective action needed</td></tr><tr><td>Unsatisfactory</td><td>45 days to correct or shutdown</td></tr></table>`,
2: `<h2>Audit Preparation — Strategy</h2><h3>Investigator Methodology</h3><ol><li>Sample 5-10 driver files for complete review</li><li>Compare records against regulatory requirements point by point</li><li>Look for systemic problems, not just individual errors</li><li>Interview drivers privately to verify records</li></ol><h3>Quarterly Self-Audit</h3><ul><li>Pull 5 random DQ files — complete?</li><li>Check 5 drug test files — all tests conducted?</li><li>Review 5 vehicle maintenance files — current?</li><li>Examine recent HOS records — violations addressed?</li></ul><h3>Top 5 Audit Findings</h3><ol><li>Incomplete driver qualification files</li><li>Drug/alcohol testing deficiencies</li><li>Vehicle maintenance records incomplete</li><li>HOS violations not addressed</li><li>Insurance documentation gaps</li></ol><p>These account for ~80% of findings. Fix proactively to address most audit risk.</p>`
},
2: {
1: `<h2>Driver Qualification Files — 49 CFR Part 391</h2><p>The DQ file is the most commonly audited element. Required contents:</p><ol><li><strong>Employment application (391.21):</strong> Previous 3 years, gaps explained</li><li><strong>MVR (391.23):</strong> From each state driver held a license. Annual renewal</li><li><strong>Road test certificate (391.31):</strong> Or CDL with proper endorsements</li><li><strong>Medical certificate (391.43):</strong> Current DOT physical, max 2-year renewal</li><li><strong>Previous employer inquiry (391.23(d)):</strong> Safety history from all DOT employers, past 3 years. Within 30 days of hire</li><li><strong>Annual driving record review (391.25):</strong> Review MVR yearly, document</li><li><strong>Annual violations list (391.27):</strong> Driver provides list of all traffic violations, even if "none"</li></ol><h3>Clearinghouse Integration</h3><p>Since January 2020, pre-employment full Clearinghouse queries are required IN ADDITION to previous employer inquiries. Both needed.</p>`,
2: `<h2>DQ Files — Common Violations</h2><table><tr><th>Violation</th><th>Fix</th></tr><tr><td>Missing/expired medical certificate</td><td>Calendar reminders 60 days before expiry</td></tr><tr><td>No annual MVR review</td><td>Schedule on hire anniversary</td></tr><tr><td>No previous employer responses</td><td>Send day 1; follow up 15, 30 days</td></tr><tr><td>No annual violations list</td><td>Include in annual review</td></tr><tr><td>Employment gaps unexplained</td><td>Require explanation on application</td></tr></table><h3>Previous Employer Inquiries</h3><p>Send to ALL DOT employers within 30 days of hire. If no response: document attempts with dates. If employer is defunct: document that too. Investigator checks inquiry dates vs hire dates.</p><h3>Practical Tips</h3><ul><li>Use a DQ file checklist — laminated, in every file folder</li><li>Color-code tabs for expiring documents</li><li>Designate one person responsible for DQ file maintenance</li><li>Never allow a driver to operate without a complete file</li></ul>`
},
3: {
1: `<h2>Vehicle Maintenance Records — 49 CFR Part 396</h2><h3>Required Program — 396.3</h3><p>Written systematic inspection, repair, and maintenance program including:</p><ul><li>Inspection intervals and scope</li><li>Records of all inspections, repairs, maintenance</li><li>Person performing each action identified</li></ul><h3>Annual Inspection — 396.17</h3><p>Every CMV inspected annually per Appendix G by a qualified inspector. Document: inspector name/qualifications, date, location, vehicle ID, components checked, pass/fail determination.</p><h3>DVIRs — 396.11</h3><p>Drivers complete written DVIR at end of each day. List defects affecting safety. Even "no defects" must be documented. Carrier must repair defects before dispatching vehicle. Signature chain: driver reports, mechanic repairs, driver verifies.</p>`,
2: `<h2>Maintenance — Audit Readiness</h2><h3>Investigator Checklist</h3><ol><li>Annual inspection current for every vehicle?</li><li>DVIRs completed daily (including "no defects")?</li><li>Defects repaired timely with documentation?</li><li>Carrier following its own stated program?</li></ol><h3>Common Findings</h3><ul><li>Expired annual inspections</li><li>DVIRs skipped on no-defect days</li><li>Defects reported but no repair documented</li><li>No written maintenance program</li></ul><h3>Best Practices</h3><ul><li>Fleet management software for due dates</li><li>Daily DVIR review process</li><li>Work orders tied to DVIRs</li><li>Annual inspection certs in vehicle AND office</li><li>Mid-year maintenance reviews</li></ul>`
},
4: {
1: `<h2>Drug & Alcohol Program Audit — Part 382</h2><h3>Investigator Reviews</h3><ol><li>Written policy — complete and distributed to all drivers?</li><li>Testing records — pre-employment, random, post-accident, reasonable suspicion, RTD, follow-up</li><li>Random rates met — 50% drug, 10% alcohol annually?</li><li>SAMHSA-certified labs and qualified collectors?</li><li>Clearinghouse queries — pre-employment and annual?</li><li>Supervisor training — 60 min alcohol + 60 min drugs?</li></ol><h3>Record Retention</h3><table><tr><th>Record</th><th>Keep For</th></tr><tr><td>Positive results</td><td>5 years</td></tr><tr><td>Negative results</td><td>1 year</td></tr><tr><td>Refusals</td><td>5 years</td></tr><tr><td>SAP reports</td><td>5 years</td></tr></table>`,
2: `<h2>D&A Audit — Top Deficiencies</h2><ol><li><strong>Missing pre-employment tests:</strong> #1 D&A violation</li><li><strong>Random testing shortfall:</strong> Turnover causes drivers to leave before selection</li><li><strong>No Clearinghouse queries</strong></li><li><strong>Untrained supervisors</strong> making reasonable suspicion decisions</li><li><strong>Incomplete chain of custody forms</strong></li></ol><h3>C/TPA Users</h3><p>Even with a third-party administrator, the carrier is legally responsible. Verify your C/TPA uses certified labs, meets random rates, and provides record copies.</p><h3>Quick Check</h3><p>Pull last 12 months: every hire has pre-employment test? Random pool meets rates? Post-accident decisions documented? Clearinghouse queries on file?</p>`
},
5: {
1: `<h2>Insurance & Financial Responsibility — Part 387</h2><h3>Minimum Coverage</h3><table><tr><th>Commodity</th><th>Minimum</th></tr><tr><td>General freight</td><td>$750,000</td></tr><tr><td>Hazmat (most)</td><td>$1,000,000</td></tr><tr><td>High-risk hazmat</td><td>$5,000,000</td></tr></table><h3>FMCSA Filing</h3><p>Insurance filed via Form BMC-91 (surety bond) or BMC-91X (policy filing). Lapse = operating authority suspension within days.</p><h3>BOC-3 Process Agents</h3><p>Designate legal representatives in each state of operation via Form BOC-3. Required for operating authority.</p>`,
2: `<h2>Insurance — Audit Preparation</h2><h3>What Investigators Check</h3><ul><li>Is BMC-91/91X on file and current with FMCSA?</li><li>Does coverage meet minimums for the commodities hauled?</li><li>Is BOC-3 on file?</li><li>Are certificates of insurance available for review?</li></ul><h3>Common Issues</h3><ul><li>Coverage amount doesn't match commodities (hauling hazmat with only $750K coverage)</li><li>Policy lapsed and was reinstated but FMCSA filing wasn't updated</li><li>BOC-3 never filed or outdated</li></ul><h3>Audit Day Checklist</h3><ol><li>Have current insurance certificate readily available</li><li>Know your policy number, agent contact, and coverage limits</li><li>Verify BMC-91X is showing "Active" on FMCSA SAFER website</li><li>Keep copies of all correspondence with insurance provider</li></ol><p><strong>Pro tip:</strong> Check your own FMCSA SAFER profile quarterly. If your insurance filing shows inactive, your authority can be suspended — sometimes without your knowledge until a roadside inspection.</p>`
}
}).then(()=>process.exit(0));
