const {updateCourse} = require('./update_helper.cjs');
updateCourse('canadian-hos-eld-rules', {
1: {
1: `<h2>Canadian Hours of Service — Regulatory Framework</h2><p>Canadian HOS rules are governed by <strong>SOR/2005-313</strong> under the Motor Vehicle Transport Act.</p><h3>Key Differences from U.S. HOS</h3><table><tr><th>Rule</th><th>USA</th><th>Canada</th></tr><tr><td>Daily driving</td><td>11 hours</td><td>13 hours</td></tr><tr><td>On-duty limit</td><td>14-hr window (continuous)</td><td>14 hrs cumulative</td></tr><tr><td>Off-duty</td><td>10 consecutive hrs</td><td>8 consecutive + 2 accumulated</td></tr><tr><td>Cycles</td><td>60/7 or 70/8</td><td>Cycle 1: 70/7 · Cycle 2: 120/14</td></tr><tr><td>Rest break</td><td>30-min after 8 hrs driving</td><td>No federal equivalent</td></tr></table><h3>The 14-Hour Rule — Critical Distinction</h3><p>In Canada the 14-hour on-duty limit is <strong>cumulative</strong>. Off-duty time pauses the clock. A 2-hour break mid-shift extends available work time — fundamentally different from the U.S. window which runs continuously.</p><h3>The 8 + 2 Off-Duty Rule</h3><p>Drivers must take ≥ 10 hours off per day: 8 consecutive + 2 in blocks of ≥ 30 min. More flexible than the U.S. 10-consecutive-hour rule.</p>`,
2: `<h2>Canadian HOS — Practical Calculations</h2><h3>Scenario: Full-Day Schedule</h3><p>Start 06:00. Drive 06:00–11:00 (5 hrs). Off-duty lunch 11:00–12:00 (1 hr). Drive 12:00–17:00 (5 hrs, 10 total). Off-duty 17:00–18:00 (1 hr). On-duty work 18:00–20:00 (2 hrs, 12 on-duty total). Off-duty 20:00.</p><p><strong>Result:</strong> 10 hrs driving (under 13). 12 hrs on-duty (under 14 cumulative). Off-duty: 1+1+8 = 10 hrs (8 consecutive from 20:00–04:00). ✅ Compliant.</p><h3>Cycle 1 vs Cycle 2</h3><p><strong>Cycle 1 (70/7):</strong> 70 on-duty hours rolling 7 days. Reset: 36 consecutive hours off.</p><p><strong>Cycle 2 (120/14):</strong> 120 hours rolling 14 days. Must take ≥ 24 consecutive hours off before exceeding 70. Reset: 72 consecutive hours off.</p><h3>Switching</h3><p>Cycle 1→2: anytime. Cycle 2→1: requires 36 consecutive hours off.</p>`
},
2: {
1: `<h2>Daily & Cycle Limits — Detailed</h2><h3>13-Hour Driving</h3><p>Cumulative driving time. Stops and on-duty-not-driving don't count. Canada has NO adverse-conditions extension (unlike the U.S. 2-hour extension).</p><h3>14-Hour On-Duty (Cumulative)</h3><p>Total on-duty including driving. Off-duty pauses the clock. Work 6 hrs, off 3 hrs, work 6 hrs = 12 cumulative on-duty with 2 remaining.</p><h3>16-Hour Outer Limit</h3><p>Before the 16th hour after first coming on duty, the driver must have taken ≥ 8 consecutive hours off. Prevents excessively long shifts even with breaks.</p><h3>Cycle 1: 70/7 Details</h3><p>Rolling 7 days of on-duty time. Each new day, the oldest drops off. Or take 36 consecutive hours off to fully reset.</p><h3>Cycle 2: 120/14 Details</h3><p>Rolling 14 days. Before exceeding 70 total hours, must have had ≥ 24 consecutive off. Max 120 in 14 days. Full reset: 72 consecutive hours.</p>`,
2: `<h2>Cycle Calculations — Practice</h2><h3>Problem 1: Cycle 1</h3><p>Past 6 days: 12+14+10+13+11+8 = 68 hrs. Today (Day 7): 70−68 = <strong>2 hours available</strong>. Tomorrow Day 1's 12 hrs drop off → 56 + today's hours remain.</p><h3>Problem 2: Cycle 2 Rest Gate</h3><p>Driver on Cycle 2, 65 hours in 10 days. Can work to 70 without 24-hr rest. After 70, MUST have had ≥ 24 consecutive hours off to continue (up to 120).</p><h3>Problem 3: Day Boundaries</h3><p>A Canadian HOS "day" starts when the driver begins on-duty/driving after ≥ 8 consecutive hours off. NOT midnight-to-midnight. Accurate calculation requires knowing exactly when each day starts.</p><h3>Common Mistakes</h3><ul><li>Forgetting ALL on-duty time counts (not just driving)</li><li>Missing the 24-hour rest gate in Cycle 2</li><li>Miscounting the rolling 7/14 day window</li><li>Not accounting for 36-hour reset when switching Cycle 2→1</li></ul>`
},
3: {
1: `<h2>Off-Duty & Sleeper Berth</h2><h3>8+2 Rule Details</h3><ul><li><strong>8 consecutive hours</strong> — primary rest, cannot be split</li><li><strong>2 additional hours</strong> — blocks of ≥ 30 min throughout the day</li></ul><p>The 2 hours don't need to be adjacent to the 8-hour block. Options: 1×2hr, 2×1hr, or 4×30min.</p><h3>Sleeper Berth Split</h3><ul><li>The 8-consecutive-hour rest MAY be split when using a sleeper berth</li><li>Two periods totaling ≥ 10 hours; neither less than 2 hours</li><li>At least one period ≥ 7 hours in the sleeper</li><li>Neither period counts against the 14-hour on-duty limit when paired</li></ul><h3>Qualifying Sleeper Berth</h3><p>Minimum 1.9 m × 0.6 m × 0.6 m. Adequate ventilation, weather protection, mattress or equivalent.</p><h3>Off-Duty Deferral</h3><p>A driver may defer up to 2 hours of daily off-duty to the next day if the 2-day total is ≥ 20 hours off-duty. The deferred hours must be added to the 8-consecutive-hour block (making it 10).</p>`,
2: `<h2>Off-Duty — Practical Scenarios</h2><h3>Scenario 1: 8+2 Split</h3><p>On-duty 06:00–10:00. Off 10:00–10:30 (30 min). On-duty 10:30–13:00. Off lunch 13:00–14:00 (1 hr). On-duty 14:00–18:00. Off 18:00–19:00 (1 hr). Off 19:00–03:00 (8 consecutive).</p><p>On-duty: 10.5 hrs. Off-duty: 0.5+1+1+8 = 10.5 hrs with 8 consecutive. ✅</p><h3>Scenario 2: Sleeper Split</h3><p>Drive 06:00–13:00 (7 hrs). Sleeper 13:00–20:00 (7 hrs). Drive 20:00–01:00 (5 hrs). Sleeper 01:00–04:00 (3 hrs). Paired: 7+3 = 10 hrs. 12 hrs driving. ✅</p><h3>Scenario 3: Deferral</h3><p>Day 1: Only 8 hrs off (defer 2). Day 2: Must take 12 hrs off (10 consecutive). Two-day total: 8+12 = 20. ✅</p><h3>Common Mistakes</h3><ul><li>Breaking the 8-hour block with even 5 minutes of work restarts it</li><li>Blocks under 30 min don't count toward the 2 additional hours</li><li>Sleeper berth requires the vehicle's actual sleeper compartment, not just any rest location</li></ul>`
},
4: {
1: `<h2>Canadian ELD Technical Standard</h2><p>Full mandate effective <strong>January 1, 2023</strong>. All federally regulated CMVs must use certified ELDs.</p><h3>Third-Party Certification</h3><p>Unlike U.S. self-certification, Canada requires <strong>independent third-party testing</strong>. Only devices on Transport Canada's certified registry are legal.</p><h3>Technical Requirements</h3><ul><li><strong>ECM connection:</strong> J1939/J1708 data port, auto-records driving when vehicle exceeds speed threshold</li><li><strong>GPS:</strong> Position at each status change + 60-min intervals while driving</li><li><strong>Tamper detection:</strong> Logs disconnect attempts and data alteration</li><li><strong>Display:</strong> Current day + 14 previous days</li><li><strong>Transfer:</strong> Bluetooth, email, AND USB to enforcement</li></ul><h3>Exemptions</h3><ul><li>Vehicles manufactured before model year 2000</li><li>Short-term rentals (≤ 30 days)</li><li>Provincial/territorial government permit vehicles</li><li>160-km radius exemption (return to home terminal daily)</li></ul>`,
2: `<h2>ELD — Daily Operations & Compliance</h2><h3>Daily Workflow</h3><ol><li>Login with driver ID, verify vehicle info</li><li>Select duty status: Off, Sleeper, Driving, On-Duty Not Driving</li><li>Driving auto-engages above ~8 km/h</li><li>Add annotations for unusual events</li><li>Certify log at end of day</li></ol><h3>Malfunction</h3><p>Notify carrier within 24 hours. Begin paper logs. Repair/replace within <strong>14 days</strong> (U.S.: 8 days).</p><h3>Roadside Inspection</h3><p>Display current + 14 days. Transfer via officer's preferred method. If on paper logs due to malfunction, present both paper and malfunction documentation.</p><h3>Cross-Border Comparison</h3><table><tr><th>Feature</th><th>U.S.</th><th>Canada</th></tr><tr><td>Certification</td><td>Self-certified</td><td>Third-party</td></tr><tr><td>History</td><td>Current + 7 days</td><td>Current + 14 days</td></tr><tr><td>Malfunction window</td><td>8 days</td><td>14 days</td></tr></table><p>For cross-border ops, use a device certified in both countries and update jurisdiction setting at the border.</p>`
},
5: {
1: `<h2>Provincial Variations & Enforcement</h2><h3>Jurisdiction Rules</h3><ul><li><strong>Extra-provincial</strong> (crosses borders) → Federal rules always</li><li><strong>Intra-provincial</strong> → Provincial rules within that province</li><li><strong>One-time cross-border</strong> → Federal for that trip</li></ul><h3>Key Provinces</h3><p><strong>Ontario:</strong> Mirrors federal. 160-km local cartage exemption. MTO enforcement.</p><p><strong>British Columbia:</strong> Mountain driving provisions. Chain-up Oct 1–Mar 31.</p><p><strong>Alberta:</strong> Oilfield exemption (160 km radius). Agricultural harvest provisions.</p><p><strong>Quebec:</strong> Fatigue management emphasis. Montreal metro urban delivery rules.</p><p><strong>Saskatchewan:</strong> Farm vehicle exemptions during seeding/harvest.</p><h3>CCMTA National Safety Code</h3><p>Standard 9 covers HOS. Provides baseline most provinces adopt. Provincial officers enforce both provincial and federal rules.</p>`,
2: `<h2>Enforcement — Penalties & Practice</h2><h3>Fines by Province</h3><table><tr><th>Province</th><th>Range</th></tr><tr><td>Ontario</td><td>$200–$20,000</td></tr><tr><td>Alberta</td><td>$100–$25,000</td></tr><tr><td>British Columbia</td><td>$100–$15,000</td></tr><tr><td>Quebec</td><td>$350–$10,500</td></tr><tr><td>Federal</td><td>$25,000 first / $50,000 repeat</td></tr></table><h3>Scenario: Highway 401 Inspection</h3><p>MTO reviews ELD — you drove 14 hrs yesterday (1 over limit). Result: out-of-service, $315–$500 fine, CVSA record, potential carrier audit.</p><h3>False Logs</h3><p>Up to $25,000 first offense. Officers check ELD vs fuel receipts, tolls, GPS trails.</p><h3>Self-Protection</h3><ul><li>Log accurately — penalties dwarf any delivery bonus</li><li>Document any pressure to exceed hours</li><li>Keep paper backup supplies</li><li>Certify logs daily</li></ul>`
}
}).then(()=>process.exit(0));
