const {updateCourse} = require('./update_helper.cjs');
updateCourse('environmental-compliance-trucking', {
1: {
1: `<h2>EPA SmartWay Program</h2><p>SmartWay is a voluntary EPA partnership helping freight carriers improve fuel efficiency and reduce emissions. Over 3,000 carriers participate.</p><h3>Why It Matters</h3><ul><li>Major shippers (Walmart, Target, Amazon) increasingly require SmartWay-certified carriers</li><li>5-15% fuel savings from SmartWay technologies</li><li>Public listing on EPA website demonstrates environmental responsibility</li></ul><h3>Key Technologies</h3><table><tr><th>Technology</th><th>Fuel Savings</th></tr><tr><td>Trailer skirts/boat tails</td><td>5-7%</td></tr><tr><td>Low-rolling-resistance tires</td><td>3-5%</td></tr><tr><td>Auto tire inflation</td><td>1-2%</td></tr><tr><td>Idle reduction (APU)</td><td>5-10%</td></tr><tr><td>Speed limiters (65 vs 70 mph)</td><td>7-8%</td></tr></table><h3>Becoming a Partner</h3><ol><li>Register on SmartWay website</li><li>Input fleet data (miles, fuel, vehicle specs)</li><li>Submit annual data updates</li><li>EPA calculates your efficiency score and ranks you against peers</li></ol>`,
2: `<h2>SmartWay — Practical Implementation</h2><h3>Quick Wins for Any Fleet</h3><ul><li><strong>Tire pressure:</strong> Every 10 PSI under-inflation costs 1% fuel economy. Check tires weekly. Auto-inflation systems pay back in 12-18 months</li><li><strong>Speed management:</strong> Reducing governed speed from 70 to 65 mph saves ~7%. At $4/gal and 120K miles/year = ~$4,800/truck annually</li><li><strong>Idle reduction:</strong> Diesel idles at 0.8-1.0 gal/hr. Over 2,400 idle hrs/year = $7,200-$9,600 in wasted fuel</li><li><strong>Progressive shifting:</strong> Upshift at 1,200-1,400 RPM instead of higher = 5-10% savings</li></ul><h3>ROI: Trailer Aerodynamics</h3><p>Side skirts cost $2,000-$3,000 installed. Fuel savings: $3,600-$5,000/year. Payback: 6-10 months. Boat tail adds 1-3% more savings for ~$1,500.</p><h3>Driver Behavior</h3><p>The single largest variable in fuel economy. Difference between a fuel-efficient driver and average: 25-30% on the same route with the same truck. Driver training is the highest-ROI fuel saving measure available.</p>`
},
2: {
1: `<h2>Emissions Standards & DEF</h2><h3>EPA Emissions Timeline</h3><ul><li><strong>Pre-2007:</strong> Minimal aftertreatment requirements</li><li><strong>2007-2009:</strong> Diesel Particulate Filter (DPF) required — 90% PM reduction</li><li><strong>2010+:</strong> Selective Catalytic Reduction (SCR) with DEF required — 90% NOx reduction</li><li><strong>EPA 2027:</strong> GHG Phase 3 standards — ~50% CO2 reduction from 2010 levels</li></ul><h3>Diesel Exhaust Fluid (DEF)</h3><p>DEF is a 32.5% urea solution injected into the exhaust to convert NOx to harmless nitrogen and water.</p><ul><li><strong>Consumption:</strong> 2-3% of diesel use (2-3 gal per 100 gal diesel)</li><li><strong>Freezing:</strong> DEF freezes at 12°F (-11°C). Heated tanks and lines prevent issues</li><li><strong>Shelf life:</strong> 12 months at 77°F. Degrades faster in heat</li><li><strong>Quality:</strong> Must meet ISO 22241. Use only certified DEF — contaminated DEF destroys SCR catalysts ($3,000-$8,000 replacement)</li></ul><h3>DPF Maintenance</h3><p>The DPF traps soot and periodically burns it off (regeneration). Active regen requires high exhaust temp — don't shut down during active regen. Forced regen at a shop if filter becomes overloaded. Replacement cost: $2,000-$5,000.</p>`,
2: `<h2>Emissions — Practical Compliance</h2><h3>DEF System Warnings</h3><p>Modern trucks display DEF warnings in stages:</p><ol><li><strong>Low DEF level:</strong> Refill soon (typically at 10% remaining)</li><li><strong>Very low:</strong> Performance derate warning — fill immediately</li><li><strong>Empty DEF:</strong> Engine power reduced to 5 mph (limp mode). Cannot be overridden</li></ol><p><strong>NEVER run out of DEF.</strong> The 5-mph derate creates a safety hazard on highways. Carry a spare 2.5-gallon jug.</p><h3>Tampering — Federal Crime</h3><p>Deleting or tampering with emissions systems (DPF delete, SCR bypass, EGR delete) violates the Clean Air Act:</p><ul><li>Individual: up to $5,000 per violation</li><li>Business: up to $500,000 per violation</li><li>Shops performing deletes: federal prosecution</li></ul><p>EPA has increased enforcement — undercover purchases and social media mining identify violators.</p><h3>Maintenance Best Practices</h3><ul><li>Use only ULSD (ultra-low sulfur diesel, 15 ppm max)</li><li>Use correct engine oil spec (CK-4 or FA-4)</li><li>Don't ignore emissions-related check engine lights</li><li>Track DPF regen frequency — increasing frequency signals a developing problem</li></ul>`
},
3: {
1: `<h2>Idle Reduction Technologies</h2><h3>The Cost of Idling</h3><p>A long-haul truck idles 1,800-2,400 hours/year. At 0.8-1.0 gal/hr = $5,000-$10,000 in fuel alone plus engine wear, emissions, and noise.</p><h3>Solutions</h3><ul><li><strong>Auxiliary Power Units (APU):</strong> Small diesel or electric generators for cab HVAC and hotel power. 0.1-0.3 gal/hr vs 0.8-1.0 for main engine. Cost: $8,000-$12,000. Payback: 12-24 months</li><li><strong>Battery-electric HVAC:</strong> Store energy, provide 8-10 hrs climate control. No fuel during use. Cost: $6,000-$10,000</li><li><strong>Shore power:</strong> Plug in at equipped truck stops. $1-$3/hour</li><li><strong>Auto Start-Stop:</strong> Engine starts only when cab temp exceeds thresholds. Reduces idle fuel 50-70%</li></ul><h3>Anti-Idling Laws</h3><p>Many jurisdictions restrict idling: California (5 min), NYC (3 min), New Jersey (3 min), plus Pennsylvania, Connecticut, and others. Fines: $100-$25,000. Apply even during rest periods.</p>`,
2: `<h2>Idle Reduction — Decision Guide</h2><h3>Which Technology?</h3><table><tr><th>Operation Type</th><th>Best Solution</th></tr><tr><td>Long-haul, 300+ nights/year</td><td>Diesel APU (fastest payback)</td></tr><tr><td>Regional, 100-200 nights/year</td><td>Battery HVAC or auto start-stop</td></tr><tr><td>Routes with shore power</td><td>Shore power + battery backup</td></tr><tr><td>Extreme climate (AZ summer, MN winter)</td><td>Diesel APU (most reliable)</td></tr></table><h3>Tax Incentives</h3><p>Idle reduction equipment may qualify for: SmartWay designation (helps secure shipper contracts), state tax credits or grants (check your state DEQ), and federal excise tax exemption for qualifying APUs.</p><h3>Safety Connection</h3><p>Drivers who are uncomfortable don't sleep well. Poor sleep = fatigue = crashes. Idle reduction technology is a <strong>safety investment</strong>, not just environmental. A well-rested driver in a climate-controlled sleeper is significantly safer than one who idled all night in a hot or cold cab with engine noise and vibration.</p>`
},
4: {
1: `<h2>CARB California Regulations</h2><p>CARB enforces the nation's strictest trucking emissions rules. <strong>Any truck entering California — regardless of registration state — must comply.</strong></p><h3>Key CARB Programs</h3><ul><li><strong>Truck and Bus Rule:</strong> ALL trucks in CA must have 2010+ engines (phase-in complete)</li><li><strong>TRU Rule:</strong> Transport refrigeration units must meet PM standards — older TRUs need DPF retrofit or replacement</li><li><strong>Drayage Truck Rule:</strong> Trucks servicing CA ports/rail yards must have 2010+ engines</li><li><strong>Advanced Clean Fleets (ACF):</strong> 2024-2036 phased requirement for zero-emission vehicle purchases. Applies to drayage, public fleets, and large employers</li></ul><h3>TRUCRS Registration</h3><p>ALL trucks in California must register with CARB's TRUCRS system (trucrs.arb.ca.gov). Free but mandatory. Operating without registration = violation even if your truck meets emission standards.</p>`,
2: `<h2>CARB — Practical Compliance</h2><h3>Before Entering California</h3><ol><li>Verify engine meets 2010+ standards (check engine plate)</li><li>Register in TRUCRS if not already</li><li>Ensure DPF is functioning (no warning lights)</li><li>DEF tank full</li><li>TRU compliant if hauling refrigerated loads</li></ol><h3>Penalties</h3><ul><li>Non-compliant truck: up to $1,000/day</li><li>No TRUCRS registration: $1,000-$10,000</li><li>TRU violations: $1,000/day</li></ul><h3>Out-of-State Carriers</h3><p>CARB rules apply to ALL trucks entering California, even for a single trip. A Texas-registered truck entering CA for one delivery must be CARB compliant and TRUCRS registered. CARB inspectors are at border stations, ports, and distribution centers.</p><h3>Zero-Emission Future</h3><p>Under ACF, large fleets must begin purchasing ZEV trucks starting 2024 (drayage first, then large employers, all sales by 2036). This will reshape California trucking over the next decade. Carriers operating in CA should plan electrification strategy now.</p>`
},
5: {
1: `<h2>Spill Prevention & Environmental Response</h2><h3>Regulatory Framework</h3><ul><li><strong>EPA:</strong> Clean Water Act, CERCLA/Superfund, RCRA for hazardous waste</li><li><strong>DOT/PHMSA:</strong> Hazmat spill reporting under 49 CFR 171.15-171.16</li><li><strong>State agencies:</strong> State-specific environmental reporting requirements (often more stringent)</li></ul><h3>CMV Spill Sources</h3><ul><li>Fuel: saddle tank ruptures, overfills at fuel islands</li><li>Cargo: hazmat releases from damaged containers or crashes</li><li>Fluids: engine oil, coolant, hydraulic fluid from mechanical failures</li><li>Reefer: diesel spills from transport refrigeration units</li></ul><h3>Reporting Triggers</h3><p>Report immediately if a spill: reaches or may reach navigable water, exceeds reportable quantity (RQ) for the substance, or endangers public health. NRC: 800-424-8802 (federal). State hotlines vary by jurisdiction.</p>`,
2: `<h2>Spill Response — Practical Guide</h2><h3>Immediate Response</h3><ol><li><strong>Safety first:</strong> Move away if health risk. Stay upwind, uphill</li><li><strong>Stop the source:</strong> If safe, close valves or tighten fittings</li><li><strong>Contain:</strong> Use absorbent pads/booms from your spill kit to prevent spread toward drains, waterways, or soil</li><li><strong>Report:</strong> Call 911 if hazardous. Notify your carrier immediately. NRC if reportable quantity</li><li><strong>Do NOT wash it away:</strong> Flushing a spill into a storm drain turns a cleanup into an environmental crime</li></ol><h3>Spill Kit Essentials</h3><p>Every CMV should carry: absorbent pads (universal type), absorbent socks/booms for containment, nitrile gloves, plastic bags for contaminated absorbent, emergency contact numbers posted visibly.</p><h3>Fuel Spill at a Truck Stop</h3><p>You overfill your saddle tank — 5 gallons of diesel on the ground.</p><ul><li>Stop fueling immediately</li><li>Apply absorbent pads/material from the fuel island spill kit</li><li>Notify truck stop management</li><li>Do NOT drive over the spill (spreads contamination)</li><li>Small diesel spills on pavement rarely meet federal reporting thresholds but always comply with the facility's procedures and state requirements</li></ul><h3>Liability</h3><p>Under CERCLA, the transporter of a released hazardous substance can be held liable for cleanup costs — even if the spill wasn't your fault. Cleanup costs for soil and groundwater contamination can reach hundreds of thousands of dollars. This is why proper containment training and spill kits are essential.</p>`
}
}).then(()=>process.exit(0));
