const mysql = require('mysql2/promise');

async function run() {
  const conn = await mysql.createConnection({
    host: 'eusotrip-mysql.mysql.database.azure.com',
    user: 'eusotripadmin',
    password: 'EusoTrip2026Prod!',
    database: 'eusotrip',
    port: 3306,
    ssl: { rejectUnauthorized: true },
  });
  console.log('Connected');

  const courses = [
    {
      slug: 'hos-compliance-mastery',
      title: 'HOS Compliance Mastery',
      description: 'Master Hours of Service regulations under 49 CFR Part 395. Learn driving limits, sleeper berth provisions, and exemptions.',
      longDescription: 'Comprehensive training on FMCSA Hours of Service regulations covering the 11-hour driving limit, 14-hour on-duty window, 60/70-hour limits, 34-hour restart provisions, sleeper berth split options, short-haul exemptions, and adverse driving conditions. Includes real-world scenarios and violation prevention strategies.',
      category: 'compliance',
      countryScope: '["US"]',
      provinceScope: null,
      difficultyLevel: 'intermediate',
      estimatedDurationMinutes: 480,
      moduleCount: 6,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER","DISPATCH"]',
      renewalIntervalMonths: 12,
      regulatoryReference: '49 CFR Part 395',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["HOS","FMCSA","driving hours","ELD"]',
      keywords: '["hours of service","driving limits","sleeper berth","34-hour restart"]',
    },
    {
      slug: 'fmcsa-safety-audit-preparation',
      title: 'FMCSA Safety Audit Preparation',
      description: 'Prepare for FMCSA new entrant safety audits and compliance reviews covering all regulatory areas.',
      longDescription: 'Complete guide to passing FMCSA safety audits including documentation requirements, driver qualification files, vehicle maintenance records, drug & alcohol testing compliance, HOS records review, and insurance/financial responsibility verification.',
      category: 'compliance',
      countryScope: '["US"]',
      provinceScope: null,
      difficultyLevel: 'advanced',
      estimatedDurationMinutes: 360,
      moduleCount: 5,
      isMandatory: true,
      mandatoryForRoles: '["DISPATCH","COMPLIANCE_OFFICER","SAFETY_MANAGER"]',
      renewalIntervalMonths: 24,
      regulatoryReference: '49 CFR Parts 385, 390-397',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 85,
      tags: '["safety audit","FMCSA","compliance review","new entrant"]',
      keywords: '["safety audit","compliance review","new entrant","DOT audit"]',
    },
    {
      slug: 'hazmat-transportation-certification',
      title: 'Hazmat Transportation Certification',
      description: 'DOT/PHMSA hazardous materials transportation training covering 49 CFR Parts 171-180.',
      longDescription: 'Complete hazmat certification covering hazard classification, shipping papers, marking, labeling, placarding, packaging requirements, emergency response (ERG), security plans, loading/unloading procedures, and incident reporting under PHMSA regulations.',
      category: 'hazmat',
      countryScope: '["US"]',
      provinceScope: null,
      difficultyLevel: 'advanced',
      estimatedDurationMinutes: 720,
      moduleCount: 8,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER"]',
      renewalIntervalMonths: 36,
      regulatoryReference: '49 CFR Parts 171-180',
      hazmatSpecific: true,
      crossBorder: false,
      passingScore: 80,
      tags: '["hazmat","PHMSA","dangerous goods","placarding","ERG"]',
      keywords: '["hazardous materials","shipping papers","placards","emergency response"]',
    },
    {
      slug: 'eld-compliance-operation',
      title: 'ELD Compliance & Operation',
      description: 'Electronic Logging Device mandate compliance, operation, malfunction procedures, and data transfer.',
      longDescription: 'Training on ELD mandate requirements including device operation, RODS editing, malfunction and diagnostic procedures, unassigned driving time management, data transfer methods, roadside inspection procedures, and exemptions from the ELD mandate.',
      category: 'equipment',
      countryScope: '["US"]',
      provinceScope: null,
      difficultyLevel: 'beginner',
      estimatedDurationMinutes: 240,
      moduleCount: 4,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER"]',
      renewalIntervalMonths: 12,
      regulatoryReference: '49 CFR Part 395 Subpart B',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["ELD","electronic logging","RODS","mandate"]',
      keywords: '["ELD mandate","electronic logging device","RODS","data transfer"]',
    },
    {
      slug: 'driver-wellness-fatigue-management',
      title: 'Driver Wellness & Fatigue Management',
      description: 'Health management, fatigue detection, sleep hygiene, nutrition, and wellness strategies for commercial drivers.',
      longDescription: 'Comprehensive wellness program covering fatigue warning signs, circadian rhythm management, sleep apnea awareness, nutrition for long-haul drivers, exercise routines, mental health resources, substance abuse prevention, and ergonomic driving practices.',
      category: 'wellness',
      countryScope: '["US","CA","MX"]',
      provinceScope: null,
      difficultyLevel: 'beginner',
      estimatedDurationMinutes: 180,
      moduleCount: 4,
      isMandatory: false,
      mandatoryForRoles: '["DRIVER"]',
      renewalIntervalMonths: 24,
      regulatoryReference: null,
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 70,
      tags: '["wellness","fatigue","health","sleep"]',
      keywords: '["fatigue management","sleep apnea","driver wellness","nutrition"]',
    },
    {
      slug: 'defensive-driving-cmv',
      title: 'Defensive Driving for CMV Operators',
      description: 'Advanced defensive driving techniques specific to commercial motor vehicles across all road conditions.',
      longDescription: 'Master defensive driving principles including space management, speed adaptation, hazard perception, mirror usage, blind spot awareness, intersection navigation, highway merging, mountain driving, night driving, and emergency maneuvers for commercial vehicles.',
      category: 'safety',
      countryScope: '["US","CA","MX"]',
      provinceScope: null,
      difficultyLevel: 'intermediate',
      estimatedDurationMinutes: 300,
      moduleCount: 5,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER"]',
      renewalIntervalMonths: 24,
      regulatoryReference: null,
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["defensive driving","safety","CMV","accident prevention"]',
      keywords: '["defensive driving","space management","hazard perception","emergency maneuvers"]',
    },
    {
      slug: 'cargo-securement-standards',
      title: 'Cargo Securement Standards',
      description: 'FMCSA cargo securement rules under 49 CFR Part 393 including tiedown requirements and commodity-specific rules.',
      longDescription: 'Training on FMCSA cargo securement standards covering general requirements, working load limits, tiedown assemblies, aggregate working load limits, commodity-specific rules for logs, metal coils, paper rolls, concrete pipe, intermodal containers, automobiles, and heavy equipment.',
      category: 'safety',
      countryScope: '["US"]',
      provinceScope: null,
      difficultyLevel: 'intermediate',
      estimatedDurationMinutes: 300,
      moduleCount: 5,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER"]',
      renewalIntervalMonths: 24,
      regulatoryReference: '49 CFR Part 393 Subparts I',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["cargo securement","tiedowns","load securement","FMCSA"]',
      keywords: '["cargo securement","tiedowns","working load limit","blocking and bracing"]',
    },
    {
      slug: 'pre-trip-post-trip-inspection',
      title: 'Pre-Trip & Post-Trip Inspection Mastery',
      description: 'Systematic vehicle inspection procedures meeting FMCSA DVIR requirements and roadside inspection standards.',
      longDescription: 'Step-by-step training on performing thorough pre-trip and post-trip inspections covering engine compartment, cab interior, exterior walkabout, coupling devices, wheels/tires, brake systems, lights/reflectors, and DVIR documentation requirements.',
      category: 'equipment',
      countryScope: '["US","CA","MX"]',
      provinceScope: null,
      difficultyLevel: 'beginner',
      estimatedDurationMinutes: 240,
      moduleCount: 4,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER"]',
      renewalIntervalMonths: 12,
      regulatoryReference: '49 CFR Parts 392.7, 396.11, 396.13',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["inspection","DVIR","pre-trip","post-trip"]',
      keywords: '["pre-trip inspection","DVIR","vehicle inspection","brake check"]',
    },
    {
      slug: 'drug-alcohol-compliance',
      title: 'Drug & Alcohol Compliance',
      description: 'FMCSA drug and alcohol testing regulations, clearinghouse requirements, and return-to-duty procedures.',
      longDescription: 'Complete training on 49 CFR Part 40 and Part 382 covering pre-employment testing, random testing pools, post-accident testing triggers, reasonable suspicion training, FMCSA Clearinghouse reporting requirements, SAP evaluations, and return-to-duty procedures.',
      category: 'compliance',
      countryScope: '["US"]',
      provinceScope: null,
      difficultyLevel: 'intermediate',
      estimatedDurationMinutes: 300,
      moduleCount: 5,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER","DISPATCH","SAFETY_MANAGER"]',
      renewalIntervalMonths: 12,
      regulatoryReference: '49 CFR Parts 40, 382',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 85,
      tags: '["drug testing","alcohol","clearinghouse","DOT"]',
      keywords: '["drug testing","alcohol testing","clearinghouse","return to duty"]',
    },
    {
      slug: 'csa-score-management',
      title: 'CSA Score Management',
      description: 'Understanding and managing CSA BASICs scores, DataQs challenges, and intervention thresholds.',
      longDescription: 'Training on the FMCSA CSA SMS methodology covering all seven BASICs categories, how scores are calculated, time and severity weighting, intervention thresholds, DataQs challenge process, improving scores through compliance, and using CSA data for fleet management decisions.',
      category: 'regulatory',
      countryScope: '["US"]',
      provinceScope: null,
      difficultyLevel: 'advanced',
      estimatedDurationMinutes: 360,
      moduleCount: 5,
      isMandatory: false,
      mandatoryForRoles: '["DISPATCH","COMPLIANCE_OFFICER","SAFETY_MANAGER"]',
      renewalIntervalMonths: 12,
      regulatoryReference: 'FMCSA SMS Methodology',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["CSA","BASICs","SMS","DataQs"]',
      keywords: '["CSA scores","BASICs","safety measurement system","DataQs"]',
    },
    {
      slug: 'canadian-tdg-certification',
      title: 'Canadian TDG Certification',
      description: 'Transport Canada Transportation of Dangerous Goods certification for drivers and handlers.',
      longDescription: 'Comprehensive TDG training covering classification of dangerous goods, documentation (shipping documents), safety marks (labels, placards, UN numbers), means of containment, emergency response assistance plans (ERAPs), reporting requirements, and provincial variations.',
      category: 'hazmat',
      countryScope: '["CA"]',
      provinceScope: null,
      difficultyLevel: 'advanced',
      estimatedDurationMinutes: 600,
      moduleCount: 7,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER"]',
      renewalIntervalMonths: 36,
      regulatoryReference: 'Transportation of Dangerous Goods Act (TDG)',
      hazmatSpecific: true,
      crossBorder: false,
      passingScore: 80,
      tags: '["TDG","Canada","dangerous goods","Transport Canada"]',
      keywords: '["TDG certification","dangerous goods Canada","ERAP","Transport Canada"]',
    },
    {
      slug: 'canadian-hos-eld-rules',
      title: 'Canadian HOS & ELD Rules',
      description: 'Canadian federal and provincial hours of service and ELD regulations under SOR/2005-313.',
      longDescription: 'Training on Canadian Commercial Vehicle Drivers Hours of Service Regulations including daily driving limits (13hrs), daily on-duty limits (14hrs), mandatory off-duty time, cycle options (7-day and 14-day), sleeper berth provisions, ELD technical standards, and provincial variations in Alberta, Ontario, and Quebec.',
      category: 'compliance',
      countryScope: '["CA"]',
      provinceScope: null,
      difficultyLevel: 'intermediate',
      estimatedDurationMinutes: 420,
      moduleCount: 5,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER","DISPATCH"]',
      renewalIntervalMonths: 12,
      regulatoryReference: 'SOR/2005-313, CAN/CSA-ELD',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["HOS Canada","ELD Canada","SOR/2005-313"]',
      keywords: '["Canadian HOS","hours of service Canada","ELD Canada","cycle 1 cycle 2"]',
    },
    {
      slug: 'normas-oficiales-mexicanas-transporte',
      title: 'Normas Oficiales Mexicanas (NOM) para Transporte',
      description: 'Mexican transport regulations including NOM-012-SCT, NOM-002-SCT, and federal licensing requirements.',
      longDescription: 'Training on Mexican transportation regulations covering maximum weight and dimensions (NOM-012-SCT-2-2017), hazardous materials transport (NOM-002-SCT/2011), federal driver licensing (Licencia Federal de Conductor), vehicle safety standards, insurance requirements, and SCT compliance inspections.',
      category: 'regulatory',
      countryScope: '["MX"]',
      provinceScope: null,
      difficultyLevel: 'intermediate',
      estimatedDurationMinutes: 360,
      moduleCount: 5,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER","DISPATCH"]',
      renewalIntervalMonths: 12,
      regulatoryReference: 'NOM-012-SCT-2-2017, NOM-002-SCT/2011',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["NOM","SCT","Mexico","transporte"]',
      keywords: '["NOM Mexico","SCT regulations","licencia federal","autotransporte"]',
    },
    {
      slug: 'cross-border-us-canada',
      title: 'Cross-Border US-Canada Operations',
      description: 'Regulations, documentation, and procedures for cross-border trucking between the US and Canada.',
      longDescription: 'Comprehensive guide to US-Canada cross-border operations including FAST card/CBSA requirements, customs documentation, cabotage rules, insurance requirements, ACE/ACI manifests, hours of service reconciliation between jurisdictions, IFTA/IRP requirements, and hazmat cross-border protocols.',
      category: 'specialized',
      countryScope: '["US","CA"]',
      provinceScope: null,
      difficultyLevel: 'advanced',
      estimatedDurationMinutes: 480,
      moduleCount: 6,
      isMandatory: false,
      mandatoryForRoles: '["DRIVER","DISPATCH"]',
      renewalIntervalMonths: 24,
      regulatoryReference: 'FAST, CBSA, ACE, ACI',
      hazmatSpecific: false,
      crossBorder: true,
      passingScore: 80,
      tags: '["cross-border","US-Canada","FAST","customs"]',
      keywords: '["cross-border","US Canada","FAST card","cabotage","customs"]',
    },
    {
      slug: 'cross-border-us-mexico',
      title: 'Cross-Border US-Mexico Operations',
      description: 'Regulations, documentation, and procedures for cross-border trucking between the US and Mexico.',
      longDescription: 'Complete training on US-Mexico cross-border operations covering C-TPAT requirements, customs broker coordination, Mexican vehicle permits, insurance requirements, FAST South procedures, maquiladora operations, border crossing procedures at key ports of entry, and safety requirements for Mexican carriers operating in the US.',
      category: 'specialized',
      countryScope: '["US","MX"]',
      provinceScope: null,
      difficultyLevel: 'advanced',
      estimatedDurationMinutes: 480,
      moduleCount: 6,
      isMandatory: false,
      mandatoryForRoles: '["DRIVER","DISPATCH"]',
      renewalIntervalMonths: 24,
      regulatoryReference: 'C-TPAT, SCT permits, CBP regulations',
      hazmatSpecific: false,
      crossBorder: true,
      passingScore: 80,
      tags: '["cross-border","US-Mexico","C-TPAT","customs"]',
      keywords: '["cross-border","US Mexico","C-TPAT","maquiladora","border crossing"]',
    },
    {
      slug: 'winter-driving-extreme-weather',
      title: 'Winter Driving & Extreme Weather',
      description: 'Safe driving techniques for winter conditions, extreme heat, fog, high winds, and flooding.',
      longDescription: 'Training on extreme weather driving covering snow and ice techniques, chain installation, black ice recognition, whiteout procedures, mountain passes in winter, extreme heat tire management, fog driving protocols, high wind procedures for high-profile vehicles, and flood/standing water avoidance.',
      category: 'safety',
      countryScope: '["US","CA"]',
      provinceScope: null,
      difficultyLevel: 'intermediate',
      estimatedDurationMinutes: 300,
      moduleCount: 5,
      isMandatory: false,
      mandatoryForRoles: '["DRIVER"]',
      renewalIntervalMonths: 12,
      regulatoryReference: null,
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["winter driving","extreme weather","chains","ice"]',
      keywords: '["winter driving","chains","black ice","mountain driving","fog"]',
    },
    {
      slug: 'tanker-vehicle-operations',
      title: 'Tanker Vehicle Operations',
      description: 'Specialized training for tanker/MC-series vehicle operations including liquid surge, rollover prevention, and loading.',
      longDescription: 'Tanker endorsement training covering liquid surge dynamics, center of gravity management, rollover prevention, baffled vs. unbaffled tanks, loading/unloading procedures, vapor recovery systems, tank pressure monitoring, tanker inspection requirements, and emergency procedures for tank ruptures.',
      category: 'equipment',
      countryScope: '["US","CA","MX"]',
      provinceScope: null,
      difficultyLevel: 'advanced',
      estimatedDurationMinutes: 420,
      moduleCount: 6,
      isMandatory: false,
      mandatoryForRoles: '["DRIVER"]',
      renewalIntervalMonths: 24,
      regulatoryReference: '49 CFR Part 173, MC-306/DOT-406',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["tanker","liquid surge","rollover","loading"]',
      keywords: '["tanker operations","liquid surge","MC-306","DOT-406","vapor recovery"]',
    },
    {
      slug: 'oversize-overweight-load-compliance',
      title: 'Oversize/Overweight Load Compliance',
      description: 'Permit requirements, escort procedures, route planning, and safety for oversize/overweight loads.',
      longDescription: 'Training on oversize and overweight load operations covering federal bridge formula, state permit processes, escort/pilot car requirements, route surveys, flag and sign requirements, night and weekend restrictions, utility coordination, and load measurement techniques.',
      category: 'specialized',
      countryScope: '["US"]',
      provinceScope: null,
      difficultyLevel: 'advanced',
      estimatedDurationMinutes: 360,
      moduleCount: 5,
      isMandatory: false,
      mandatoryForRoles: '["DRIVER","DISPATCH","ESCORT"]',
      renewalIntervalMonths: 24,
      regulatoryReference: '23 CFR Part 658, State permit programs',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["oversize","overweight","permits","escort"]',
      keywords: '["oversize load","overweight permit","escort vehicle","bridge formula"]',
    },
    {
      slug: 'accident-reporting-post-crash',
      title: 'Accident Reporting & Post-Crash Procedures',
      description: 'Step-by-step procedures for accident response, documentation, reporting requirements, and post-crash testing.',
      longDescription: 'Training on post-accident procedures covering immediate safety actions, scene documentation, DOT reportable crash criteria, post-accident drug/alcohol testing requirements, insurance notification, FMCSA crash reporting, evidence preservation, driver statement guidelines, and working with law enforcement.',
      category: 'safety',
      countryScope: '["US","CA","MX"]',
      provinceScope: null,
      difficultyLevel: 'intermediate',
      estimatedDurationMinutes: 240,
      moduleCount: 4,
      isMandatory: true,
      mandatoryForRoles: '["DRIVER","DISPATCH","SAFETY_MANAGER"]',
      renewalIntervalMonths: 24,
      regulatoryReference: '49 CFR Part 390.5, Part 382.303',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 80,
      tags: '["accident","post-crash","reporting","testing"]',
      keywords: '["accident reporting","post-crash testing","DOT reportable","scene documentation"]',
    },
    {
      slug: 'environmental-compliance-trucking',
      title: 'Environmental Compliance for Trucking',
      description: 'EPA SmartWay, emissions standards, idle reduction, spill prevention, and environmental responsibility.',
      longDescription: 'Training on environmental compliance covering EPA SmartWay program participation, greenhouse gas emissions standards, diesel exhaust fluid (DEF) requirements, idle reduction technologies, fuel spill prevention and cleanup, CARB regulations for California operations, and sustainability reporting for carriers.',
      category: 'regulatory',
      countryScope: '["US","CA"]',
      provinceScope: null,
      difficultyLevel: 'intermediate',
      estimatedDurationMinutes: 300,
      moduleCount: 5,
      isMandatory: false,
      mandatoryForRoles: '["DISPATCH","COMPLIANCE_OFFICER"]',
      renewalIntervalMonths: 24,
      regulatoryReference: 'EPA SmartWay, CARB, Clean Air Act',
      hazmatSpecific: false,
      crossBorder: false,
      passingScore: 75,
      tags: '["environmental","EPA","SmartWay","emissions","CARB"]',
      keywords: '["EPA SmartWay","emissions","idle reduction","CARB","DEF"]',
    },
  ];

  console.log('Inserting', courses.length, 'courses...');

  for (const c of courses) {
    try {
      await conn.execute(
        `INSERT IGNORE INTO training_courses (slug, title, description, longDescription, category, countryScope, provinceScope, difficultyLevel, estimatedDurationMinutes, moduleCount, isMandatory, mandatoryForRoles, renewalIntervalMonths, regulatoryReference, hazmatSpecific, crossBorder, status, passingScore, tags, keywords, publishedAt)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, ?, ?, NOW())`,
        [c.slug, c.title, c.description, c.longDescription, c.category, c.countryScope, c.provinceScope, c.difficultyLevel, c.estimatedDurationMinutes, c.moduleCount, c.isMandatory, c.mandatoryForRoles, c.renewalIntervalMonths, c.regulatoryReference, c.hazmatSpecific, c.crossBorder, c.passingScore, c.tags, c.keywords]
      );
      console.log('  OK:', c.slug);
    } catch (e) {
      console.log('  ERR:', c.slug, e.message.substring(0, 100));
    }
  }

  const [count] = await conn.execute('SELECT COUNT(*) as c FROM training_courses');
  console.log('Total courses in DB:', count[0].c);
  await conn.end();
  console.log('DONE');
}

run().catch(e => { console.error('FATAL:', e.message); process.exit(1); });
