-- Seed 3 countries
INSERT IGNORE INTO `countries` (`code`, `name`, `label`, `regulatoryBody`, `regulatoryFramework`, `isActive`, `metadata`) VALUES
('US', 'United States', 'United States of America', 'FMCSA / DOT / PHMSA', '49 CFR Parts 100-199', TRUE, '{"currencyCode":"USD","languageCodes":["en"],"hazmatRegulator":"PHMSA","driverLicenseFormat":"CDL"}'),
('CA', 'Canada', 'Canada', 'Transport Canada / TDG', 'Transportation of Dangerous Goods Act', TRUE, '{"currencyCode":"CAD","languageCodes":["en","fr"],"hazmatRegulator":"Transport Canada TDG","driverLicenseFormat":"Provincial CDL"}'),
('MX', 'Mexico', 'México', 'SCT / SEMARNAT', 'NOM-002-SCT/2011', TRUE, '{"currencyCode":"MXN","languageCodes":["es"],"hazmatRegulator":"SCT/SEMARNAT","driverLicenseFormat":"Licencia Federal"}');

-- Seed US states (51: 50 states + DC)
INSERT IGNORE INTO `provinces` (`countryId`, `code`, `name`, `abbreviation`, `regionType`, `isActive`) VALUES
((SELECT id FROM countries WHERE code='US'), 'AL', 'Alabama', 'AL', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'AK', 'Alaska', 'AK', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'AZ', 'Arizona', 'AZ', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'AR', 'Arkansas', 'AR', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'CA', 'California', 'CA', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'CO', 'Colorado', 'CO', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'CT', 'Connecticut', 'CT', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'DE', 'Delaware', 'DE', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'DC', 'District of Columbia', 'DC', 'territory', TRUE),
((SELECT id FROM countries WHERE code='US'), 'FL', 'Florida', 'FL', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'GA', 'Georgia', 'GA', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'HI', 'Hawaii', 'HI', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'ID', 'Idaho', 'ID', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'IL', 'Illinois', 'IL', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'IN', 'Indiana', 'IN', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'IA', 'Iowa', 'IA', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'KS', 'Kansas', 'KS', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'KY', 'Kentucky', 'KY', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'LA', 'Louisiana', 'LA', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'ME', 'Maine', 'ME', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'MD', 'Maryland', 'MD', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'MA', 'Massachusetts', 'MA', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'MI', 'Michigan', 'MI', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'MN', 'Minnesota', 'MN', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'MS', 'Mississippi', 'MS', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'MO', 'Missouri', 'MO', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'MT', 'Montana', 'MT', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'NE', 'Nebraska', 'NE', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'NV', 'Nevada', 'NV', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'NH', 'New Hampshire', 'NH', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'NJ', 'New Jersey', 'NJ', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'NM', 'New Mexico', 'NM', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'NY', 'New York', 'NY', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'NC', 'North Carolina', 'NC', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'ND', 'North Dakota', 'ND', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'OH', 'Ohio', 'OH', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'OK', 'Oklahoma', 'OK', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'OR', 'Oregon', 'OR', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'PA', 'Pennsylvania', 'PA', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'RI', 'Rhode Island', 'RI', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'SC', 'South Carolina', 'SC', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'SD', 'South Dakota', 'SD', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'TN', 'Tennessee', 'TN', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'TX', 'Texas', 'TX', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'UT', 'Utah', 'UT', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'VT', 'Vermont', 'VT', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'VA', 'Virginia', 'VA', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'WA', 'Washington', 'WA', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'WV', 'West Virginia', 'WV', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'WI', 'Wisconsin', 'WI', 'state', TRUE),
((SELECT id FROM countries WHERE code='US'), 'WY', 'Wyoming', 'WY', 'state', TRUE);

-- Seed Canadian provinces/territories (13)
INSERT IGNORE INTO `provinces` (`countryId`, `code`, `name`, `abbreviation`, `regionType`, `isActive`) VALUES
((SELECT id FROM countries WHERE code='CA'), 'AB', 'Alberta', 'AB', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'BC', 'British Columbia', 'BC', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'MB', 'Manitoba', 'MB', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'NB', 'New Brunswick', 'NB', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'NL', 'Newfoundland and Labrador', 'NL', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'NS', 'Nova Scotia', 'NS', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'NT', 'Northwest Territories', 'NT', 'territory', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'NU', 'Nunavut', 'NU', 'territory', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'ON', 'Ontario', 'ON', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'PE', 'Prince Edward Island', 'PE', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'QC', 'Quebec', 'QC', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'SK', 'Saskatchewan', 'SK', 'province', TRUE),
((SELECT id FROM countries WHERE code='CA'), 'YT', 'Yukon', 'YT', 'territory', TRUE);

-- Seed Mexican states (32)
INSERT IGNORE INTO `provinces` (`countryId`, `code`, `name`, `abbreviation`, `regionType`, `isActive`) VALUES
((SELECT id FROM countries WHERE code='MX'), 'AGU', 'Aguascalientes', 'Ags.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'BCN', 'Baja California', 'B.C.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'BCS', 'Baja California Sur', 'B.C.S.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'CAM', 'Campeche', 'Camp.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'CHP', 'Chiapas', 'Chis.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'CHH', 'Chihuahua', 'Chih.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'COA', 'Coahuila', 'Coah.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'COL', 'Colima', 'Col.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'CMX', 'Ciudad de México', 'CDMX', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'DUR', 'Durango', 'Dgo.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'GUA', 'Guanajuato', 'Gto.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'GRO', 'Guerrero', 'Gro.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'HID', 'Hidalgo', 'Hgo.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'JAL', 'Jalisco', 'Jal.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'MEX', 'Estado de México', 'Méx.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'MIC', 'Michoacán', 'Mich.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'MOR', 'Morelos', 'Mor.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'NAY', 'Nayarit', 'Nay.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'NLE', 'Nuevo León', 'N.L.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'OAX', 'Oaxaca', 'Oax.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'PUE', 'Puebla', 'Pue.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'QUE', 'Querétaro', 'Qro.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'ROO', 'Quintana Roo', 'Q.Roo', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'SLP', 'San Luis Potosí', 'S.L.P.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'SIN', 'Sinaloa', 'Sin.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'SON', 'Sonora', 'Son.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'TAB', 'Tabasco', 'Tab.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'TAM', 'Tamaulipas', 'Tamps.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'TLA', 'Tlaxcala', 'Tlax.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'VER', 'Veracruz', 'Ver.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'YUC', 'Yucatán', 'Yuc.', 'federal_entity', TRUE),
((SELECT id FROM countries WHERE code='MX'), 'ZAC', 'Zacatecas', 'Zac.', 'federal_entity', TRUE);
