/**
 * EUSOCONNECT INTEGRATION PROVIDERS SEED DATA
 * 30+ providers across all categories
 */

import { getDb } from "../../server/db";
import { integrationProviders } from "../schema";

export const INTEGRATION_PROVIDERS_SEED = [
  // ═══════════════════════════════════════════════════════════════════════════
  // INSURANCE PROVIDERS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Canopy Connect",
    slug: "canopy_connect",
    displayName: "Canopy Connect",
    description: "Instantly import all your insurance policies, COIs, and claims. Connect once to share your insurance data digitally.",
    logoUrl: "/integrations/canopy-connect.png",
    websiteUrl: "https://usecanopy.com",
    category: "insurance" as const,
    subcategory: "aggregator",
    authType: "oauth2" as const,
    oauthAuthorizeUrl: "https://connect.usecanopy.com/authorize",
    oauthTokenUrl: "https://api.usecanopy.com/v1/oauth/token",
    oauthScopes: ["policies", "certificates", "claims"],
    requiresExternalId: false,
    apiBaseUrl: "https://api.usecanopy.com/v1",
    supportsWebhooks: true,
    webhookEvents: ["policy.created", "policy.updated", "policy.cancelled", "certificate.requested"],
    dataTypesAvailable: ["policies", "certificates", "claims", "documents"],
    syncFrequencyMinutes: 60,
    supportsRealtime: true,
    status: "active" as const,
    isPremium: false,
    availableForRoles: ["CATALYST", "SHIPPER", "BROKER", "OWNER_OPERATOR"],
    setupInstructions: "Click Connect to securely link your insurance accounts through Canopy Connect.",
  },
  {
    name: "Progressive Commercial",
    slug: "progressive_commercial",
    displayName: "Progressive Commercial",
    description: "Direct integration with Progressive Commercial for policy management and claims.",
    logoUrl: "/integrations/progressive.png",
    websiteUrl: "https://www.progressivecommercial.com",
    category: "insurance" as const,
    subcategory: "insurer_direct",
    authType: "api_key" as const,
    apiBaseUrl: "https://api.progressive.com/commercial/v1",
    requiresExternalId: true,
    externalIdLabel: "Policy Number",
    dataTypesAvailable: ["policies", "claims", "billing"],
    syncFrequencyMinutes: 120,
    status: "active" as const,
    availableForRoles: ["CATALYST", "OWNER_OPERATOR"],
  },
  {
    name: "Great West Casualty",
    slug: "great_west_casualty",
    displayName: "Great West Casualty",
    description: "Connect your Great West trucking insurance for automatic policy tracking.",
    logoUrl: "/integrations/great-west.png",
    websiteUrl: "https://www.gwccnet.com",
    category: "insurance" as const,
    subcategory: "insurer_direct",
    authType: "api_key_secret" as const,
    apiBaseUrl: "https://api.gwccnet.com/v1",
    requiresExternalId: true,
    externalIdLabel: "Account Number",
    dataTypesAvailable: ["policies", "cois", "claims", "loss_runs"],
    syncFrequencyMinutes: 120,
    status: "active" as const,
    availableForRoles: ["CATALYST", "OWNER_OPERATOR"],
  },
  {
    name: "Northland Insurance",
    slug: "northland_insurance",
    displayName: "Northland Insurance",
    description: "Sync policies and filings from Northland Insurance.",
    logoUrl: "/integrations/northland.png",
    websiteUrl: "https://www.northlandins.com",
    category: "insurance" as const,
    subcategory: "insurer_direct",
    authType: "api_key" as const,
    dataTypesAvailable: ["policies", "filings"],
    syncFrequencyMinutes: 240,
    status: "active" as const,
    availableForRoles: ["CATALYST", "OWNER_OPERATOR"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // COMPLIANCE NETWORKS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "ISNetworld",
    slug: "isnetworld",
    displayName: "ISNetworld",
    description: "Import your ISNetworld contractor safety grades, certifications, and compliance records.",
    logoUrl: "/integrations/isnetworld.png",
    websiteUrl: "https://www.isnetworld.com",
    category: "compliance" as const,
    subcategory: "contractor_management",
    authType: "oauth2_with_id" as const,
    oauthAuthorizeUrl: "https://api.isnetworld.com/oauth/authorize",
    oauthTokenUrl: "https://api.isnetworld.com/oauth/token",
    requiresExternalId: true,
    externalIdLabel: "ISNetworld Company ID",
    externalIdFormat: "XXXXXXXXXX",
    apiBaseUrl: "https://api.isnetworld.com/v2",
    supportsWebhooks: true,
    webhookEvents: ["grade.updated", "certification.expiring", "requirement.updated"],
    dataTypesAvailable: ["grades", "certifications", "safety_records", "training", "insurance_verification"],
    syncFrequencyMinutes: 240,
    status: "active" as const,
    availableForRoles: ["CATALYST", "SHIPPER", "BROKER", "OWNER_OPERATOR"],
    setupInstructions: "Enter your ISNetworld Company ID (found in your ISN dashboard) and authorize access.",
  },
  {
    name: "Veriforce",
    slug: "veriforce",
    displayName: "Veriforce",
    description: "Sync OQ records, drug tests, and training certifications from Veriforce.",
    logoUrl: "/integrations/veriforce.png",
    websiteUrl: "https://veriforce.com",
    category: "compliance" as const,
    subcategory: "contractor_management",
    authType: "api_key_secret" as const,
    apiBaseUrl: "https://api.veriforce.com/v1",
    requiresExternalId: true,
    externalIdLabel: "Veriforce Company ID",
    dataTypesAvailable: ["oq_records", "drug_tests", "training", "certifications", "safety_data"],
    syncFrequencyMinutes: 240,
    status: "active" as const,
    availableForRoles: ["CATALYST", "OWNER_OPERATOR", "DRIVER"],
    setupInstructions: "Enter your Veriforce API credentials from your Veriforce admin portal.",
  },
  {
    name: "Avetta",
    slug: "avetta",
    displayName: "Avetta",
    description: "Import supply chain prequalification data, audits, and insurance verification from Avetta.",
    logoUrl: "/integrations/avetta.png",
    websiteUrl: "https://www.avetta.com",
    category: "compliance" as const,
    subcategory: "supply_chain_risk",
    authType: "oauth2_with_id" as const,
    oauthAuthorizeUrl: "https://api.avetta.com/oauth/authorize",
    oauthTokenUrl: "https://api.avetta.com/oauth/token",
    requiresExternalId: true,
    externalIdLabel: "Avetta Supplier ID",
    apiBaseUrl: "https://api.avetta.com/v2",
    supportsWebhooks: true,
    dataTypesAvailable: ["prequalification", "insurance_verification", "audits", "corrective_actions"],
    syncFrequencyMinutes: 360,
    status: "active" as const,
    availableForRoles: ["CATALYST", "SHIPPER", "BROKER"],
    setupInstructions: "Enter your Avetta Supplier ID and authorize EusoTrip to access your profile.",
  },
  {
    name: "PEC Safety",
    slug: "pec_safety",
    displayName: "PEC Safety",
    description: "Import PEC Premier safety training and certification records.",
    logoUrl: "/integrations/pec-safety.png",
    websiteUrl: "https://www.pecsafety.com",
    category: "compliance" as const,
    subcategory: "safety_training",
    authType: "api_key" as const,
    apiBaseUrl: "https://api.pecsafety.com/v1",
    requiresExternalId: true,
    externalIdLabel: "PEC Company ID",
    dataTypesAvailable: ["training_records", "certifications", "safeland", "safeGulf"],
    syncFrequencyMinutes: 480,
    status: "active" as const,
    availableForRoles: ["CATALYST", "DRIVER"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TERMINAL MANAGEMENT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Dearman Systems",
    slug: "dearman",
    displayName: "Dearman Systems",
    description: "Import terminal schedules, rack assignments, BOLs, and inventory from Dearman terminal automation.",
    logoUrl: "/integrations/dearman.png",
    websiteUrl: "https://www.dearmansystems.com",
    category: "terminal" as const,
    subcategory: "terminal_automation",
    authType: "api_key_secret" as const,
    apiBaseUrl: "https://api.dearmansystems.com/v1",
    requiresExternalId: true,
    externalIdLabel: "Terminal Code",
    supportsWebhooks: true,
    webhookEvents: ["schedule.created", "schedule.updated", "bol.generated", "inventory.updated"],
    dataTypesAvailable: ["schedules", "rack_assignments", "bols", "inventory", "transactions"],
    syncFrequencyMinutes: 15,
    supportsRealtime: true,
    status: "active" as const,
    availableForRoles: ["TERMINAL_MANAGER", "CATALYST", "SHIPPER"],
    setupInstructions: "Enter your Dearman API credentials and terminal code(s) to sync scheduling data.",
  },
  {
    name: "PDI Technologies",
    slug: "pdi",
    displayName: "PDI Technologies",
    description: "Integrate with PDI for enterprise fuel management, rack pricing, and terminal operations.",
    logoUrl: "/integrations/pdi.png",
    websiteUrl: "https://www.pdisoftware.com",
    category: "terminal" as const,
    subcategory: "enterprise_management",
    authType: "oauth2" as const,
    oauthAuthorizeUrl: "https://auth.pdisoftware.com/oauth/authorize",
    oauthTokenUrl: "https://auth.pdisoftware.com/oauth/token",
    apiBaseUrl: "https://api.pdisoftware.com/v2",
    supportsWebhooks: true,
    dataTypesAvailable: ["transactions", "rack_pricing", "inventory", "scheduling", "settlements"],
    syncFrequencyMinutes: 30,
    supportsRealtime: true,
    status: "active" as const,
    availableForRoles: ["TERMINAL_MANAGER", "CATALYST", "SHIPPER"],
  },
  {
    name: "Titan Cloud Software",
    slug: "titan_cloud",
    displayName: "Titan Cloud",
    description: "Connect Titan Cloud for environmental compliance, tank monitoring, and fuel management.",
    logoUrl: "/integrations/titan-cloud.png",
    websiteUrl: "https://www.titancloud.com",
    category: "terminal" as const,
    subcategory: "environmental_compliance",
    authType: "api_key" as const,
    apiBaseUrl: "https://api.titancloud.com/v1",
    dataTypesAvailable: ["tank_data", "compliance_records", "atg_readings", "leak_detection", "deliveries"],
    syncFrequencyMinutes: 60,
    status: "active" as const,
    availableForRoles: ["TERMINAL_MANAGER"],
  },
  {
    name: "KloudGin",
    slug: "kloudgin",
    displayName: "KloudGin",
    description: "Integrate KloudGin work order and field service management.",
    logoUrl: "/integrations/kloudgin.png",
    websiteUrl: "https://www.kloudgin.com",
    category: "terminal" as const,
    subcategory: "field_service",
    authType: "oauth2" as const,
    dataTypesAvailable: ["work_orders", "scheduling", "assets", "inspections"],
    syncFrequencyMinutes: 30,
    status: "active" as const,
    availableForRoles: ["TERMINAL_MANAGER"],
  },
  {
    name: "Manage Petro",
    slug: "manage_petro",
    displayName: "Manage Petro",
    description: "Connect Manage Petro for mobile delivery tracking and inventory management.",
    logoUrl: "/integrations/manage-petro.png",
    category: "terminal" as const,
    subcategory: "mobile_delivery",
    authType: "api_key" as const,
    dataTypesAvailable: ["deliveries", "inventory", "customers", "routes"],
    syncFrequencyMinutes: 30,
    status: "active" as const,
    availableForRoles: ["CATALYST", "TERMINAL_MANAGER"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FUEL MANAGEMENT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "FuelCloud",
    slug: "fuelcloud",
    displayName: "FuelCloud",
    description: "Sync fuel transactions, tank inventory, and consumption data from FuelCloud.",
    logoUrl: "/integrations/fuelcloud.png",
    websiteUrl: "https://www.fuelcloud.com",
    category: "fuel" as const,
    subcategory: "fuel_management",
    authType: "api_key" as const,
    apiBaseUrl: "https://api.fuelcloud.com/v1",
    dataTypesAvailable: ["transactions", "inventory", "consumption", "tanks", "users"],
    syncFrequencyMinutes: 30,
    status: "active" as const,
    availableForRoles: ["CATALYST", "TERMINAL_MANAGER"],
  },
  {
    name: "FuelPlus",
    slug: "fuelplus",
    displayName: "FuelPlus",
    description: "Import fuel inventory and consumption tracking from FuelPlus.",
    logoUrl: "/integrations/fuelplus.png",
    category: "fuel" as const,
    subcategory: "fuel_management",
    authType: "api_key" as const,
    dataTypesAvailable: ["inventory", "consumption", "deliveries"],
    syncFrequencyMinutes: 60,
    status: "active" as const,
    availableForRoles: ["CATALYST", "TERMINAL_MANAGER"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ELD & TELEMATICS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Samsara",
    slug: "samsara",
    displayName: "Samsara",
    description: "Full integration with Samsara for ELD, GPS tracking, DVIR, safety events, and more.",
    logoUrl: "/integrations/samsara.png",
    websiteUrl: "https://www.samsara.com",
    category: "eld" as const,
    subcategory: "fleet_telematics",
    authType: "oauth2" as const,
    oauthAuthorizeUrl: "https://api.samsara.com/oauth2/authorize",
    oauthTokenUrl: "https://api.samsara.com/oauth2/token",
    oauthScopes: ["vehicles:read", "drivers:read", "hos:read", "safety:read"],
    apiBaseUrl: "https://api.samsara.com",
    supportsWebhooks: true,
    webhookEvents: ["vehicle.location", "driver.hos", "safety.event", "dvir.submitted"],
    dataTypesAvailable: ["vehicles", "drivers", "hos_logs", "gps_locations", "safety_events", "dvirs", "fuel", "ifta"],
    syncFrequencyMinutes: 5,
    supportsRealtime: true,
    status: "active" as const,
    availableForRoles: ["CATALYST", "DRIVER", "SAFETY_MANAGER", "COMPLIANCE_OFFICER"],
    setupInstructions: "Connect your Samsara account to automatically import HOS, GPS, safety events, and DVIRs.",
  },
  {
    name: "Motive",
    slug: "motive",
    displayName: "Motive",
    description: "Connect Motive (formerly KeepTruckin) for ELD compliance, GPS, and fleet management.",
    logoUrl: "/integrations/motive.png",
    websiteUrl: "https://gomotive.com",
    category: "eld" as const,
    subcategory: "fleet_telematics",
    authType: "oauth2" as const,
    oauthAuthorizeUrl: "https://api.gomotive.com/oauth/authorize",
    oauthTokenUrl: "https://api.gomotive.com/oauth/token",
    apiBaseUrl: "https://api.gomotive.com/v1",
    supportsWebhooks: true,
    dataTypesAvailable: ["vehicles", "drivers", "hos_logs", "locations", "fuel", "ifta", "safety"],
    syncFrequencyMinutes: 5,
    supportsRealtime: true,
    status: "active" as const,
    availableForRoles: ["CATALYST", "DRIVER", "SAFETY_MANAGER"],
  },
  {
    name: "Omnitracs",
    slug: "omnitracs",
    displayName: "Omnitracs",
    description: "Integrate Omnitracs fleet management, ELD, and routing solutions.",
    logoUrl: "/integrations/omnitracs.png",
    websiteUrl: "https://www.omnitracs.com",
    category: "eld" as const,
    subcategory: "fleet_management",
    authType: "api_key_secret" as const,
    apiBaseUrl: "https://api.omnitracs.com/v1",
    dataTypesAvailable: ["vehicles", "drivers", "hos_logs", "routing", "messaging", "fuel"],
    syncFrequencyMinutes: 15,
    status: "active" as const,
    availableForRoles: ["CATALYST", "DRIVER"],
  },
  {
    name: "Geotab",
    slug: "geotab",
    displayName: "Geotab",
    description: "Connect Geotab for telematics, vehicle diagnostics, and driver behavior data.",
    logoUrl: "/integrations/geotab.png",
    websiteUrl: "https://www.geotab.com",
    category: "eld" as const,
    subcategory: "telematics",
    authType: "credentials" as const,
    apiBaseUrl: "https://my.geotab.com/apiv1",
    dataTypesAvailable: ["vehicles", "trips", "fuel", "diagnostics", "driver_behavior", "zones"],
    syncFrequencyMinutes: 15,
    status: "active" as const,
    availableForRoles: ["CATALYST", "SAFETY_MANAGER"],
  },
  {
    name: "ELD Rider",
    slug: "eld_rider",
    displayName: "ELD Rider",
    description: "Import HOS logs from ELD Rider devices.",
    logoUrl: "/integrations/eld-rider.png",
    category: "eld" as const,
    subcategory: "eld_compliance",
    authType: "api_key" as const,
    dataTypesAvailable: ["hos_logs", "drivers"],
    syncFrequencyMinutes: 30,
    status: "active" as const,
    availableForRoles: ["CATALYST", "DRIVER"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BANKING & PAYMENTS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Stripe",
    slug: "stripe",
    displayName: "Stripe",
    description: "Connect Stripe for payment processing and payouts to your bank account.",
    logoUrl: "/integrations/stripe.png",
    websiteUrl: "https://stripe.com",
    category: "banking" as const,
    subcategory: "payments",
    authType: "oauth2" as const,
    oauthAuthorizeUrl: "https://connect.stripe.com/oauth/authorize",
    oauthTokenUrl: "https://connect.stripe.com/oauth/token",
    apiBaseUrl: "https://api.stripe.com/v1",
    dataTypesAvailable: ["account_status", "payouts", "transactions", "balance"],
    syncFrequencyMinutes: 60,
    status: "active" as const,
    availableForRoles: ["CATALYST", "SHIPPER", "BROKER", "OWNER_OPERATOR"],
  },
  {
    name: "Plaid",
    slug: "plaid",
    displayName: "Plaid",
    description: "Securely connect your bank account for instant verification and ACH transfers.",
    logoUrl: "/integrations/plaid.png",
    websiteUrl: "https://plaid.com",
    category: "banking" as const,
    subcategory: "banking",
    authType: "oauth2" as const,
    dataTypesAvailable: ["accounts", "balances", "transactions"],
    syncFrequencyMinutes: 1440,
    status: "active" as const,
    availableForRoles: ["CATALYST", "SHIPPER", "BROKER", "OWNER_OPERATOR"],
  },
  {
    name: "Relay Payments",
    slug: "relay_payments",
    displayName: "Relay Payments",
    description: "Connect Relay for trucking-specific payment processing.",
    logoUrl: "/integrations/relay.png",
    websiteUrl: "https://relaypayments.com",
    category: "banking" as const,
    subcategory: "trucking_payments",
    authType: "api_key" as const,
    dataTypesAvailable: ["payments", "fuel_advances", "settlements"],
    syncFrequencyMinutes: 60,
    status: "beta" as const,
    availableForRoles: ["CATALYST", "BROKER"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GOVERNMENT / REGULATORY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "FMCSA SAFER",
    slug: "fmcsa_safer",
    displayName: "FMCSA SAFER",
    description: "Automatically verify catalyst authority, safety ratings, and insurance filings with FMCSA.",
    logoUrl: "/integrations/fmcsa.png",
    websiteUrl: "https://safer.fmcsa.dot.gov",
    category: "government" as const,
    subcategory: "regulatory",
    authType: "api_key" as const,
    apiBaseUrl: "https://mobile.fmcsa.dot.gov/qc/services",
    requiresExternalId: true,
    externalIdLabel: "USDOT Number",
    dataTypesAvailable: ["authority", "safety_rating", "insurance_filings", "inspections", "crashes"],
    syncFrequencyMinutes: 1440,
    status: "active" as const,
    availableForRoles: ["CATALYST", "SHIPPER", "BROKER", "COMPLIANCE_OFFICER", "SAFETY_MANAGER"],
    setupInstructions: "Enter your FMCSA Web Services API key and USDOT number.",
  },
  {
    name: "FMCSA Clearinghouse",
    slug: "fmcsa_clearinghouse",
    displayName: "FMCSA Clearinghouse",
    description: "Query and report drug/alcohol violations per FMCSA Clearinghouse requirements.",
    logoUrl: "/integrations/clearinghouse.png",
    websiteUrl: "https://clearinghouse.fmcsa.dot.gov",
    category: "government" as const,
    subcategory: "regulatory",
    authType: "oauth2_with_id" as const,
    requiresExternalId: true,
    externalIdLabel: "Employer Clearinghouse ID",
    dataTypesAvailable: ["queries", "violations", "return_to_duty"],
    syncFrequencyMinutes: 1440,
    status: "active" as const,
    availableForRoles: ["CATALYST", "COMPLIANCE_OFFICER", "SAFETY_MANAGER"],
    setupInstructions: "Connect with your FMCSA Clearinghouse employer account.",
  },
  {
    name: "IFTA/IRP",
    slug: "ifta_irp",
    displayName: "IFTA/IRP",
    description: "Import fuel tax and registration data for IFTA/IRP compliance.",
    logoUrl: "/integrations/ifta.png",
    category: "government" as const,
    subcategory: "tax_compliance",
    authType: "api_key" as const,
    dataTypesAvailable: ["fuel_purchases", "mileage", "tax_reports", "registrations"],
    syncFrequencyMinutes: 1440,
    status: "coming_soon" as const,
    availableForRoles: ["CATALYST", "COMPLIANCE_OFFICER"],
  },
];

export async function seedIntegrationProviders() {
  const db = getDb();
  
  console.log("[Seed] Starting integration providers seed...");
  
  for (const provider of INTEGRATION_PROVIDERS_SEED) {
    try {
      await db.insert(integrationProviders).values(provider).onDuplicateKeyUpdate({
        set: {
          displayName: provider.displayName,
          description: provider.description,
          category: provider.category,
          authType: provider.authType,
          dataTypesAvailable: provider.dataTypesAvailable,
          status: provider.status,
          availableForRoles: provider.availableForRoles,
        },
      });
      console.log(`[Seed] Upserted provider: ${provider.name}`);
    } catch (error) {
      console.error(`[Seed] Failed to upsert provider ${provider.name}:`, error);
    }
  }
  
  console.log(`[Seed] Completed seeding ${INTEGRATION_PROVIDERS_SEED.length} integration providers.`);
}
